-- Task 12A production authorization snapshot query.
-- Captured target: xmlkxfjeagycwttklxjw / kptu-shared-checklists.
-- Captured latest production migration before change: 20260925032810.
-- This file is read-only. Save its result before applying the paired migration.

-- CAPTURED PRODUCTION STATE (2026-09-25, before Task 12A)
-- app_ai_conversations: rls=true force=false
-- policy app_ai_conversations_self_delete | DELETE | roles=["public"] | using="(owner_id = auth.uid())" | check=null
-- policy app_ai_conversations_self_insert | INSERT | roles=["public"] | using=null | check="((owner_id = auth.uid()) AND private.app_is_workspace_member(workspace_id))"
-- policy app_ai_conversations_self_select | SELECT | roles=["public"] | using="(owner_id = auth.uid())" | check=null
-- policy app_ai_conversations_self_update | UPDATE | roles=["public"] | using="(owner_id = auth.uid())" | check="(owner_id = auth.uid())"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_ai_daily_usage: rls=true force=false
-- policy app_ai_usage_self_select | SELECT | roles=["public"] | using="(user_id = auth.uid())" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_ai_messages: rls=true force=false
-- policy app_ai_messages_self_delete | DELETE | roles=["public"] | using="(owner_id = auth.uid())" | check=null
-- policy app_ai_messages_self_insert | INSERT | roles=["public"] | using=null | check="((owner_id = auth.uid()) AND (EXISTS ( SELECT 1\n   FROM app_ai_conversations c\n  WHERE ((c.id = app_ai_messages.conversation_id) AND (c.owner_id = auth.uid())))))"
-- policy app_ai_messages_self_select | SELECT | roles=["public"] | using="(owner_id = auth.uid())" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_ai_workspace_settings: rls=true force=false
-- policy app_ai_settings_admin_update | UPDATE | roles=["public"] | using="private.app_is_workspace_admin(workspace_id)" | check="private.app_is_workspace_admin(workspace_id)"
-- policy app_ai_settings_member_read | SELECT | roles=["public"] | using="private.app_is_workspace_member(workspace_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_direct_messages: rls=true force=false
-- policy app_direct_messages_insert | INSERT | roles=["authenticated"] | using=null | check="((sender_id = ( SELECT auth.uid() AS uid)) AND private.app_is_workspace_member(workspace_id) AND (EXISTS ( SELECT 1\n   FROM app_workspace_members wm\n  WHERE ((wm.workspace_id = app_direct_messages.workspace_id) AND (wm.user_id = app_direct_messages.recipient_id)))))"
-- policy app_direct_messages_read | SELECT | roles=["authenticated"] | using="(private.app_is_workspace_member(workspace_id) AND ((sender_id = ( SELECT auth.uid() AS uid)) OR (recipient_id = ( SELECT auth.uid() AS uid))))" | check=null
-- policy app_direct_messages_read_update | UPDATE | roles=["authenticated"] | using="(recipient_id = ( SELECT auth.uid() AS uid))" | check="(recipient_id = ( SELECT auth.uid() AS uid))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_document_ai_index: rls=true force=false
-- policy app_document_ai_index_read | SELECT | roles=["authenticated"] | using="private.app_can_view_document(document_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_document_chunks: rls=true force=false
-- policy app_document_chunks_read | SELECT | roles=["authenticated"] | using="private.app_can_view_document(document_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_documents: rls=true force=false
-- policy app_documents_scoped_delete | DELETE | roles=["authenticated"] | using="(((project_id IS NULL) AND ((uploaded_by = auth.uid()) OR private.app_is_workspace_admin(workspace_id))) OR ((project_id IS NOT NULL) AND ((uploaded_by = auth.uid()) OR private.app_can_manage_space(project_id))))" | check=null
-- policy app_documents_scoped_insert | INSERT | roles=["authenticated"] | using=null | check="((uploaded_by = auth.uid()) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20) AND ((project_id IS NULL) OR private.app_can_edit_space(project_id)))"
-- policy app_documents_scoped_read | SELECT | roles=["authenticated"] | using="private.app_can_view_document(id)" | check=null
-- policy app_documents_scoped_update | UPDATE | roles=["authenticated"] | using="(((project_id IS NULL) AND ((uploaded_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 30))) OR ((project_id IS NOT NULL) AND ((uploaded_by = auth.uid()) OR private.app_can_edit_space(project_id))))" | check="(((project_id IS NULL) AND ((uploaded_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 30))) OR ((project_id IS NOT NULL) AND ((uploaded_by = auth.uid()) OR private.app_can_edit_space(project_id))))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_event_attendees: rls=true force=false
-- policy app_event_attendees_delete | DELETE | roles=["public"] | using="((user_id = auth.uid()) OR (EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_attendees.event_id) AND ((e.created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(e.workspace_id)) >= 30))))))" | check=null
-- policy app_event_attendees_insert | INSERT | roles=["public"] | using=null | check="(EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_attendees.event_id) AND ((e.created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(e.workspace_id)) >= 30)))))"
-- policy app_event_attendees_scoped_read | SELECT | roles=["authenticated"] | using="private.app_can_view_event(event_id)" | check=null
-- policy app_event_attendees_update | UPDATE | roles=["public"] | using="((user_id = auth.uid()) OR (EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_attendees.event_id) AND ((e.created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(e.workspace_id)) >= 30))))))" | check="((user_id = auth.uid()) OR (EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_attendees.event_id) AND ((e.created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(e.workspace_id)) >= 30))))))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_event_comments: rls=true force=false
-- policy app_event_comments_delete | DELETE | roles=["public"] | using="((author_id = auth.uid()) OR (EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_comments.event_id) AND private.app_is_workspace_admin(e.workspace_id)))))" | check=null
-- policy app_event_comments_scoped_insert | INSERT | roles=["authenticated"] | using=null | check="((author_id = auth.uid()) AND private.app_can_view_event(event_id))"
-- policy app_event_comments_scoped_read | SELECT | roles=["authenticated"] | using="private.app_can_view_event(event_id)" | check=null
-- policy app_event_comments_update | UPDATE | roles=["public"] | using="(author_id = auth.uid())" | check="(author_id = auth.uid())"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_event_photos: rls=true force=false
-- policy app_event_photos_scoped_delete | DELETE | roles=["authenticated"] | using="((uploaded_by = auth.uid()) AND private.app_can_view_event(event_id))" | check=null
-- policy app_event_photos_scoped_insert | INSERT | roles=["authenticated"] | using=null | check="((uploaded_by = auth.uid()) AND private.app_can_view_event(event_id))"
-- policy app_event_photos_scoped_read | SELECT | roles=["authenticated"] | using="private.app_can_view_event(event_id)" | check=null
-- policy app_event_photos_scoped_update | UPDATE | roles=["authenticated"] | using="((uploaded_by = auth.uid()) AND private.app_can_view_event(event_id))" | check="((uploaded_by = auth.uid()) AND private.app_can_view_event(event_id))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_event_suborganizations: rls=true force=false
-- policy app_event_suborganizations_delete | DELETE | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_suborganizations.event_id) AND ((e.created_by = ( SELECT auth.uid() AS uid)) OR private.app_is_workspace_admin(e.workspace_id) OR ((e.project_id IS NOT NULL) AND private.app_can_edit_space(e.project_id))))))" | check=null
-- policy app_event_suborganizations_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM (app_events e\n     JOIN app_suborganizations o ON ((o.workspace_id = e.workspace_id)))\n  WHERE ((e.id = app_event_suborganizations.event_id) AND (o.id = app_event_suborganizations.organization_id) AND ((e.created_by = ( SELECT auth.uid() AS uid)) OR private.app_is_workspace_admin(e.workspace_id) OR ((e.project_id IS NOT NULL) AND private.app_can_edit_space(e.project_id)))))))"
-- policy app_event_suborganizations_read | SELECT | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_events e\n  WHERE ((e.id = app_event_suborganizations.event_id) AND private.app_is_workspace_member(e.workspace_id) AND ((e.calendar_scope = 'team'::text) OR (e.created_by = ( SELECT auth.uid() AS uid))) AND ((e.project_id IS NULL) OR private.app_can_view_space(e.project_id)))))" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_events: rls=true force=false
-- policy app_events_scoped_delete | DELETE | roles=["authenticated"] | using="(((calendar_scope = 'personal'::text) AND (created_by = auth.uid())) OR ((calendar_scope = 'team'::text) AND (((project_id IS NULL) AND ((created_by = auth.uid()) OR private.app_is_workspace_admin(workspace_id))) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR private.app_can_manage_space(project_id))))))" | check=null
-- policy app_events_scoped_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = auth.uid()) AND private.app_is_workspace_member(workspace_id) AND ((calendar_scope = 'personal'::text) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20)) AND ((project_id IS NULL) OR private.app_can_edit_space(project_id)))"
-- policy app_events_scoped_read | SELECT | roles=["authenticated"] | using="(private.app_is_workspace_member(workspace_id) AND ((calendar_scope = 'team'::text) OR ((calendar_scope = 'personal'::text) AND (created_by = auth.uid()))) AND ((project_id IS NULL) OR private.app_can_view_space(project_id)))" | check=null
-- policy app_events_scoped_update | UPDATE | roles=["authenticated"] | using="(((calendar_scope = 'personal'::text) AND (created_by = auth.uid())) OR ((calendar_scope = 'team'::text) AND (((project_id IS NULL) AND ((created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 30))) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR private.app_can_edit_space(project_id))))))" | check="(((calendar_scope = 'personal'::text) AND (created_by = auth.uid())) OR ((calendar_scope = 'team'::text) AND (((project_id IS NULL) AND ((created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 30))) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR private.app_can_edit_space(project_id))))))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_invites: rls=true force=false
-- policy app_invites_admin_read | SELECT | roles=["authenticated"] | using="private.app_is_workspace_admin(workspace_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_meetings: rls=true force=false
-- policy app_meetings_scoped_delete | DELETE | roles=["authenticated"] | using="(((project_id IS NULL) AND ((created_by = auth.uid()) OR private.app_is_workspace_admin(workspace_id))) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR private.app_can_manage_space(project_id))))" | check=null
-- policy app_meetings_scoped_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = auth.uid()) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20) AND ((project_id IS NULL) OR private.app_can_edit_space(project_id)))"
-- policy app_meetings_scoped_read | SELECT | roles=["authenticated"] | using="(private.app_is_workspace_member(workspace_id) AND ((project_id IS NULL) OR private.app_can_view_space(project_id)))" | check=null
-- policy app_meetings_scoped_update | UPDATE | roles=["authenticated"] | using="(((project_id IS NULL) AND ((created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 30))) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR private.app_can_edit_space(project_id))))" | check="(((project_id IS NULL) AND ((created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 30))) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR private.app_can_edit_space(project_id))))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_org_affiliation_tags: rls=true force=false
-- policy app_org_affiliation_tags_delete | DELETE | roles=["authenticated"] | using="((created_by = auth.uid()) OR private.app_is_workspace_admin(workspace_id))" | check=null
-- policy app_org_affiliation_tags_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = auth.uid()) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20))"
-- policy app_org_affiliation_tags_read | SELECT | roles=["authenticated"] | using="private.app_is_workspace_member(workspace_id)" | check=null
-- policy app_org_affiliation_tags_update | UPDATE | roles=["authenticated"] | using="((created_by = auth.uid()) OR private.app_is_workspace_admin(workspace_id))" | check="((created_by = auth.uid()) OR private.app_is_workspace_admin(workspace_id))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_pages: rls=true force=false
-- policy app_pages_create_guard | INSERT | roles=["authenticated"] | using=null | check="((owner_id = ( SELECT auth.uid() AS uid)) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20) AND ((space_id IS NULL) OR (EXISTS ( SELECT 1\n   FROM app_spaces s\n  WHERE ((s.id = app_pages.space_id) AND (s.workspace_id = app_pages.workspace_id) AND private.app_can_edit_space(s.id))))) AND ((workstream_id IS NULL) OR (EXISTS ( SELECT 1\n   FROM (app_project_workstreams w\n     JOIN app_spaces s ON ((s.id = w.project_id)))\n  WHERE ((w.id = app_pages.workstream_id) AND (w.project_id = app_pages.space_id) AND (s.workspace_id = app_pages.workspace_id) AND private.app_can_edit_space(s.id))))))"
-- policy app_pages_delete | DELETE | roles=["authenticated"] | using="private.app_can_manage_page(id)" | check=null
-- policy app_pages_member_read | SELECT | roles=["authenticated"] | using="private.app_can_view_page(id)" | check=null
-- policy app_pages_update | UPDATE | roles=["authenticated"] | using="private.app_can_edit_page(id)" | check="(private.app_can_edit_page(id) AND ((space_id IS NULL) OR (EXISTS ( SELECT 1\n   FROM app_spaces s\n  WHERE ((s.id = app_pages.space_id) AND (s.workspace_id = app_pages.workspace_id) AND private.app_can_edit_space(s.id))))) AND ((workstream_id IS NULL) OR (EXISTS ( SELECT 1\n   FROM (app_project_workstreams w\n     JOIN app_spaces s ON ((s.id = w.project_id)))\n  WHERE ((w.id = app_pages.workstream_id) AND (w.project_id = app_pages.space_id) AND (s.workspace_id = app_pages.workspace_id) AND private.app_can_edit_space(s.id))))))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_profile_report_projects: rls=true force=false
-- policy app_profile_report_projects_self_delete | DELETE | roles=["public"] | using="(user_id = auth.uid())" | check=null
-- policy app_profile_report_projects_self_insert | INSERT | roles=["public"] | using=null | check="(user_id = auth.uid())"
-- policy app_profile_report_projects_self_update | UPDATE | roles=["public"] | using="(user_id = auth.uid())" | check="(user_id = auth.uid())"
-- policy app_profile_report_projects_team_read | SELECT | roles=["public"] | using="private.app_can_read_profile(user_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_profile_weekly_reports: rls=true force=false
-- policy app_profile_weekly_reports_self_delete | DELETE | roles=["public"] | using="(user_id = auth.uid())" | check=null
-- policy app_profile_weekly_reports_self_insert | INSERT | roles=["public"] | using=null | check="(user_id = auth.uid())"
-- policy app_profile_weekly_reports_self_update | UPDATE | roles=["public"] | using="(user_id = auth.uid())" | check="(user_id = auth.uid())"
-- policy app_profile_weekly_reports_team_read | SELECT | roles=["public"] | using="private.app_can_read_profile(user_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_profile_workplace_statuses: rls=true force=false
-- policy app_profile_workplace_statuses_self_delete | DELETE | roles=["public"] | using="(user_id = auth.uid())" | check=null
-- policy app_profile_workplace_statuses_self_insert | INSERT | roles=["public"] | using=null | check="(user_id = auth.uid())"
-- policy app_profile_workplace_statuses_self_update | UPDATE | roles=["public"] | using="(user_id = auth.uid())" | check="(user_id = auth.uid())"
-- policy app_profile_workplace_statuses_team_read | SELECT | roles=["public"] | using="private.app_can_read_profile(user_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_profile_workplaces: rls=true force=false
-- policy app_profile_workplaces_self_delete | DELETE | roles=["public"] | using="(user_id = auth.uid())" | check=null
-- policy app_profile_workplaces_self_insert | INSERT | roles=["public"] | using=null | check="(user_id = auth.uid())"
-- policy app_profile_workplaces_self_update | UPDATE | roles=["public"] | using="(user_id = auth.uid())" | check="(user_id = auth.uid())"
-- policy app_profile_workplaces_team_read | SELECT | roles=["public"] | using="private.app_can_read_profile(user_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_profiles: rls=true force=false
-- policy app_profiles_self_or_colleague_read | SELECT | roles=["authenticated"] | using="private.app_can_read_profile(user_id)" | check=null
-- policy app_profiles_self_update | UPDATE | roles=["authenticated"] | using="(user_id = auth.uid())" | check="(user_id = auth.uid())"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_spaces: rls=true force=false
-- policy app_spaces_create | INSERT | roles=["authenticated"] | using=null | check="((created_by = auth.uid()) AND (owner_id = auth.uid()) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20))"
-- policy app_spaces_delete | DELETE | roles=["authenticated"] | using="(owner_id = auth.uid())" | check=null
-- policy app_spaces_scoped_read | SELECT | roles=["authenticated"] | using="(owner_id = ( SELECT auth.uid() AS uid))" | check=null
-- policy app_spaces_update | UPDATE | roles=["authenticated"] | using="private.app_can_manage_space(id)" | check="private.app_can_manage_space(id)"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganization_affiliations: rls=true force=false
-- policy app_suborganization_affiliations_delete | DELETE | roles=["authenticated"] | using="private.app_can_edit_suborganization(organization_id)" | check=null
-- policy app_suborganization_affiliations_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = auth.uid()) AND private.app_can_edit_suborganization(organization_id) AND (EXISTS ( SELECT 1\n   FROM (app_suborganizations o\n     JOIN app_org_affiliation_tags t ON ((t.id = app_suborganization_affiliations.tag_id)))\n  WHERE ((o.id = app_suborganization_affiliations.organization_id) AND (o.workspace_id = t.workspace_id) AND (t.active = true)))))"
-- policy app_suborganization_affiliations_read | SELECT | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_affiliations.organization_id) AND private.app_is_workspace_member(o.workspace_id))))" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganization_assignees: rls=true force=false
-- policy app_suborg_assignees_delete | DELETE | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_assignees.organization_id) AND private.app_is_workspace_admin(o.workspace_id))))" | check=null
-- policy app_suborg_assignees_insert | INSERT | roles=["authenticated"] | using=null | check="((assigned_by = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_assignees.organization_id) AND private.app_is_workspace_admin(o.workspace_id)))) AND (EXISTS ( SELECT 1\n   FROM (app_workspace_members wm\n     JOIN app_suborganizations o ON ((o.workspace_id = wm.workspace_id)))\n  WHERE ((o.id = app_suborganization_assignees.organization_id) AND (wm.user_id = app_suborganization_assignees.user_id)))))"
-- policy app_suborg_assignees_read | SELECT | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_assignees.organization_id) AND private.app_is_workspace_member(o.workspace_id))))" | check=null
-- policy app_suborg_assignees_self_assign_v2 | INSERT | roles=["authenticated"] | using=null | check="((user_id = ( SELECT auth.uid() AS uid)) AND (assigned_by = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM (app_suborganizations o\n     JOIN app_workspace_members wm ON (((wm.workspace_id = o.workspace_id) AND (wm.user_id = ( SELECT auth.uid() AS uid)))))\n  WHERE ((o.id = app_suborganization_assignees.organization_id) AND (o.active = true)))))"
-- policy app_suborg_assignees_self_claim_named | INSERT | roles=["authenticated"] | using=null | check="((user_id = ( SELECT auth.uid() AS uid)) AND (assigned_by = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM ((app_suborganizations o\n     JOIN app_profiles p ON ((p.user_id = ( SELECT auth.uid() AS uid))))\n     JOIN app_workspace_members wm ON (((wm.workspace_id = o.workspace_id) AND (wm.user_id = ( SELECT auth.uid() AS uid)))))\n  WHERE ((o.id = app_suborganization_assignees.organization_id) AND (o.active = true) AND (NULLIF(btrim(o.default_assignee_name), ''::text) IS NOT NULL) AND (btrim(o.default_assignee_name) = btrim(COALESCE(p.display_name, ''::text)))))))"
-- policy app_suborg_assignees_self_delete_v2 | DELETE | roles=["authenticated"] | using="((user_id = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM (app_suborganizations o\n     JOIN app_workspace_members wm ON (((wm.workspace_id = o.workspace_id) AND (wm.user_id = ( SELECT auth.uid() AS uid)))))\n  WHERE (o.id = app_suborganization_assignees.organization_id))))" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganization_status_items: rls=true force=false
-- policy app_suborganization_status_items_delete | DELETE | roles=["authenticated"] | using="private.app_can_edit_suborganization(organization_id)" | check=null
-- policy app_suborganization_status_items_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = ( SELECT auth.uid() AS uid)) AND private.app_can_edit_suborganization(organization_id))"
-- policy app_suborganization_status_items_read | SELECT | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_status_items.organization_id) AND private.app_is_workspace_member(o.workspace_id))))" | check=null
-- policy app_suborganization_status_items_update | UPDATE | roles=["authenticated"] | using="private.app_can_edit_suborganization(organization_id)" | check="private.app_can_edit_suborganization(organization_id)"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganization_timeline: rls=true force=false
-- policy app_suborganization_timeline_delete | DELETE | roles=["authenticated"] | using="private.app_can_edit_suborganization(organization_id)" | check=null
-- policy app_suborganization_timeline_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = ( SELECT auth.uid() AS uid)) AND private.app_can_edit_suborganization(organization_id))"
-- policy app_suborganization_timeline_read | SELECT | roles=["authenticated"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_timeline.organization_id) AND private.app_is_workspace_member(o.workspace_id))))" | check=null
-- policy app_suborganization_timeline_update | UPDATE | roles=["authenticated"] | using="private.app_can_edit_suborganization(organization_id)" | check="private.app_can_edit_suborganization(organization_id)"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganization_updates: rls=true force=false
-- policy app_suborganization_updates_delete | DELETE | roles=["public"] | using="private.app_can_edit_suborganization(organization_id)" | check=null
-- policy app_suborganization_updates_insert | INSERT | roles=["public"] | using=null | check="((created_by = auth.uid()) AND private.app_can_edit_suborganization(organization_id))"
-- policy app_suborganization_updates_read | SELECT | roles=["public"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_updates.organization_id) AND private.app_is_workspace_member(o.workspace_id))))" | check=null
-- policy app_suborganization_updates_update | UPDATE | roles=["public"] | using="private.app_can_edit_suborganization(organization_id)" | check="private.app_can_edit_suborganization(organization_id)"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganization_weekly_reports: rls=true force=false
-- policy app_suborganization_weekly_reports_delete | DELETE | roles=["public"] | using="private.app_can_edit_suborganization(organization_id)" | check=null
-- policy app_suborganization_weekly_reports_insert | INSERT | roles=["public"] | using=null | check="((created_by = auth.uid()) AND private.app_can_edit_suborganization(organization_id))"
-- policy app_suborganization_weekly_reports_read | SELECT | roles=["public"] | using="(EXISTS ( SELECT 1\n   FROM app_suborganizations o\n  WHERE ((o.id = app_suborganization_weekly_reports.organization_id) AND private.app_is_workspace_member(o.workspace_id))))" | check=null
-- policy app_suborganization_weekly_reports_update | UPDATE | roles=["public"] | using="private.app_can_edit_suborganization(organization_id)" | check="private.app_can_edit_suborganization(organization_id)"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_suborganizations: rls=true force=false
-- policy app_suborganizations_assignee_update | UPDATE | roles=["authenticated"] | using="private.app_can_edit_suborganization(id)" | check="private.app_can_edit_suborganization(id)"
-- policy app_suborganizations_delete | DELETE | roles=["authenticated"] | using="((created_by = ( SELECT auth.uid() AS uid)) OR private.app_is_workspace_admin(workspace_id))" | check=null
-- policy app_suborganizations_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = ( SELECT auth.uid() AS uid)) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20))"
-- policy app_suborganizations_read | SELECT | roles=["authenticated"] | using="private.app_is_workspace_member(workspace_id)" | check=null
-- policy app_suborganizations_update | UPDATE | roles=["authenticated"] | using="((created_by = ( SELECT auth.uid() AS uid)) OR private.app_is_workspace_admin(workspace_id))" | check="((created_by = ( SELECT auth.uid() AS uid)) OR private.app_is_workspace_admin(workspace_id))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"REFERENCES"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"TRIGGER"},{"grantee":"authenticated","grantable":false,"privilege":"TRUNCATE"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_tasks: rls=true force=false
-- policy app_tasks_scoped_delete | DELETE | roles=["authenticated"] | using="(((project_id IS NULL) AND (assignee_id = auth.uid())) OR ((project_id IS NOT NULL) AND ((created_by = auth.uid()) OR (assignee_id = auth.uid()) OR private.app_can_manage_space(project_id))))" | check=null
-- policy app_tasks_scoped_insert | INSERT | roles=["authenticated"] | using=null | check="((created_by = auth.uid()) AND (private.app_role_rank(private.app_workspace_role(workspace_id)) >= 20) AND ((project_id IS NULL) OR private.app_can_edit_space(project_id)) AND private.app_space_in_workspace(project_id, workspace_id) AND private.app_workstream_in_context(workstream_id, project_id, workspace_id) AND private.app_user_in_workspace(assignee_id, workspace_id) AND ((COALESCE(source_type, 'manual'::text) = 'manual'::text) OR ((source_type = 'meeting'::text) AND (source_id IS NOT NULL) AND private.app_meeting_in_workspace(source_id, workspace_id) AND (EXISTS ( SELECT 1\n   FROM app_meetings m\n  WHERE ((m.id = app_tasks.source_id) AND ((m.created_by = auth.uid()) OR (private.app_role_rank(private.app_workspace_role(m.workspace_id)) >= 30)))))) OR ((source_type = 'project'::text) AND (project_id IS NOT NULL) AND private.app_can_edit_space(project_id))))"
-- policy app_tasks_scoped_read | SELECT | roles=["authenticated"] | using="(private.app_is_workspace_member(workspace_id) AND (((project_id IS NULL) AND (assignee_id = auth.uid())) OR ((project_id IS NOT NULL) AND private.app_can_view_space(project_id))))" | check=null
-- policy app_tasks_scoped_update | UPDATE | roles=["authenticated"] | using="(((project_id IS NULL) AND (assignee_id = auth.uid())) OR ((project_id IS NOT NULL) AND private.app_can_view_space(project_id) AND ((created_by = auth.uid()) OR (assignee_id = auth.uid()) OR private.app_can_edit_space(project_id))))" | check="(private.app_space_in_workspace(project_id, workspace_id) AND private.app_workstream_in_context(workstream_id, project_id, workspace_id) AND private.app_user_in_workspace(assignee_id, workspace_id) AND (((project_id IS NULL) AND (assignee_id = auth.uid())) OR ((project_id IS NOT NULL) AND private.app_can_view_space(project_id) AND ((created_by = auth.uid()) OR (assignee_id = auth.uid()) OR private.app_can_edit_space(project_id)))))"
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"INSERT"},{"grantee":"authenticated","grantable":false,"privilege":"MAINTAIN"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"authenticated","grantable":false,"privilege":"UPDATE"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_workspace_members: rls=true force=false
-- policy app_members_owner_delete_guard | DELETE | roles=["authenticated"] | using="((user_id <> ( SELECT auth.uid() AS uid)) AND (role <> 'owner'::text) AND (private.app_workspace_role(workspace_id) = 'owner'::text))" | check=null
-- policy app_members_read | SELECT | roles=["authenticated"] | using="private.app_is_workspace_member(workspace_id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"DELETE"},{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- app_workspaces: rls=true force=false
-- policy app_workspaces_member_read | SELECT | roles=["authenticated"] | using="private.app_is_workspace_member(id)" | check=null
-- grants [{"grantee":"authenticated","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"DELETE"},{"grantee":"service_role","grantable":false,"privilege":"INSERT"},{"grantee":"service_role","grantable":false,"privilege":"MAINTAIN"},{"grantee":"service_role","grantable":false,"privilege":"REFERENCES"},{"grantee":"service_role","grantable":false,"privilege":"SELECT"},{"grantee":"service_role","grantable":false,"privilege":"TRIGGER"},{"grantee":"service_role","grantable":false,"privilege":"TRUNCATE"},{"grantee":"service_role","grantable":false,"privilege":"UPDATE"}]
-- END CAPTURED PRODUCTION STATE

-- CAPTURED WEB2 FUNCTION STATE (definitions remain queryable below)
-- function private.app_can_edit_page(p_page uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=false | definition_md5=7470e924528d888ea1fa179558b276c6
-- function private.app_can_edit_space(p_space uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{=X/postgres,postgres=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=true | definition_md5=19fbe8fdb834672bca771c0f87d7ee00
-- function private.app_can_edit_suborganization(p_organization uuid) | definer=true | settings=["search_path=public, private, pg_temp"] | acl="{=X/postgres,postgres=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=true | definition_md5=f1b040ec8b092ada10b8c7f4e8064741
-- function private.app_can_manage_page(p_page uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=false | definition_md5=91da62141defbc923aafcc7c8c856d74
-- function private.app_can_manage_space(p_space uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{=X/postgres,postgres=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=true | definition_md5=f91e8a0148becedabb8b2d6a1d7da42d
-- function private.app_can_read_profile(p_user uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres}" | anon=false | authenticated=true | service_role=false | definition_md5=be289f7fc799569c2e4aff600def04b1
-- function private.app_can_view_document(p_document uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=c0b967293f31b46eca7ae515a4b58a96
-- function private.app_can_view_event(p_event uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{=X/postgres,postgres=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=true | definition_md5=66aeff49a238fa8f2c59c857ebc70b16
-- function private.app_can_view_page(p_page uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=false | definition_md5=bef27846ef243c23298d09dadceb7d52
-- function private.app_can_view_space(p_space uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{=X/postgres,postgres=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=true | definition_md5=f874eccae00b17bb636c0ecfc4f5e9b3
-- function private.app_claim_named_suborganizations() | definer=false | settings=["search_path=public, pg_temp"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=48855ed7aa5ea782433aca484a0a1431
-- function private.app_enforce_space_workspace() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres}" | anon=false | authenticated=false | service_role=false | definition_md5=8061f5136035a594913240642216ed6d
-- function private.app_enforce_workspace_links() | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres}" | anon=false | authenticated=false | service_role=false | definition_md5=e46cbd9c98ee587d649f305e45e5e797
-- function private.app_enforce_workspace_member_role() | definer=true | settings=["search_path=public, private, auth, pg_temp"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=93bacf6ff9361bd3da3cc5f6d9425ee6
-- function private.app_event_in_workspace(p_event uuid, p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=bf536bd287627975aa71ef7e6b38417c
-- function private.app_is_workspace_admin(p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=false | definition_md5=1441443a60a81685be4b9d86b4cf24cc
-- function private.app_is_workspace_member(p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres}" | anon=false | authenticated=true | service_role=false | definition_md5=e4d0e938b6ba42caf1d50768f64c305e
-- function private.app_link_profile_workplace_org() | definer=true | settings=["search_path=public, private, pg_temp"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=a9ea4638aae4561fbc9a41526d5aa7cc
-- function private.app_meeting_in_workspace(p_meeting uuid, p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=5e507568e1e23ee1295d514304ee5312
-- function private.app_new_profile() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres}" | anon=false | authenticated=false | service_role=false | definition_md5=6545e10bc9132c4b9c4c5bbf5ec70bf4
-- function private.app_role_rank(p_role text) | definer=false | settings=["search_path=pg_catalog"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=83c7d794294a2b335e89c918c3beb084
-- function private.app_seed_child_project_management() | definer=true | settings=["search_path=public, pg_temp"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=6af61f290342bb1408ab0d118b8b7429
-- function private.app_set_updated_at() | definer=false | settings=["search_path=pg_catalog"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=5af290fadcb0398530f7d6a54f0084c7
-- function private.app_snapshot_page() | definer=false | settings=["search_path=pg_catalog, public"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=754f40c0767153ad62fc3ade642f59b2
-- function private.app_space_in_workspace(p_space uuid, p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=3f96690f95f74755062cf052ea6ffbec
-- function private.app_space_role_rank(p_role text) | definer=false | settings=["search_path=pg_catalog"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=e0e9e66ef2c198ae393089d03b7136e1
-- function private.app_sync_profile_workplace_name() | definer=true | settings=["search_path=public, private, pg_temp"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=35f01bf8caed17b2f6342a6fb455006c
-- function private.app_task_child_project_guard() | definer=true | settings=["search_path=public, pg_temp"] | acl=null | anon=true | authenticated=true | service_role=true | definition_md5=c71c490525675e16edbd70fdc6bffc81
-- function private.app_unlink_retained_project_records() | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres}" | anon=false | authenticated=false | service_role=false | definition_md5=654550f950edb4bbced1b8f7ac0c94ec
-- function private.app_user_in_workspace(p_user uuid, p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=66ae5ecee13ab9ec61bcd17023892e71
-- function private.app_workspace_role(p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres}" | anon=true | authenticated=true | service_role=false | definition_md5=62cf53a46bcffede3f8a8cf2eb7b2c10
-- function private.app_workstream_in_context(p_workstream uuid, p_project uuid, p_workspace uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=497565c061e31ff37c8aa183979e5cff
-- function public.app_accept_invite(p_token text) | definer=true | settings=["search_path=pg_catalog, public, extensions"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=1b8ba9856df7b82d19eb6cda9cbcec1b
-- function public.app_add_event_creator_attendee() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=f5895167349a60a1e1e05dbfacce4261
-- function public.app_approve_access_request(p_request uuid, p_role text) | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=bb1f4c3321d9efa3d4a89a2c997ad2ec
-- function public.app_can_edit_page_rpc(p_page uuid) | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=a9bb59b998937cdf54d46f9c77b894e1
-- function public.app_claim_owner(p_code text, p_display_name text) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=a6e4ab9089a0d9935aeeba84703cd42b
-- function public.app_create_invite(p_role text, p_group uuid, p_expires_at timestamp with time zone) | definer=true | settings=["search_path=pg_catalog, public, extensions"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=7178efbc3a2c4935c834f7edc54cae88
-- function public.app_create_share_link(p_page uuid, p_expires_at timestamp with time zone) | definer=true | settings=["search_path=pg_catalog, public, extensions"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=f292c8e319e0f2c5fa062f46345f0746
-- function public.app_delete_pages(p_page_ids uuid[]) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=40d3c46eedd40d9d659e7d1dcecd8279
-- function public.app_join_default_team() | definer=true | settings=["search_path=pg_catalog, public, auth, private"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=ff11354f8ec4ba35caf9676857f7e69a
-- function public.app_move_project_public_block(p_block uuid, p_direction integer) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=d713e652c1faf40604374d1b76051cd2
-- function public.app_open_share(p_token text) | definer=true | settings=["search_path=pg_catalog, public, extensions"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=8668dad197badd185970895f1cc6affe
-- function public.app_prepare_task_assignment() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=3c4fbd1ec0f47ab615fa7cad008a020b
-- function public.app_project_publication_state(p_project uuid) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=f9a1f80d1332e2d7265faa5ed2a85362
-- function public.app_public_post(p_slug text) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=true | authenticated=true | service_role=true | definition_md5=5b5577eba2fb6d44f336b912b0a26abe
-- function public.app_public_project(p_slug text) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=787e9f795404ce11981aef19590f0c23
-- function public.app_public_projects_snapshot() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=fd0178c249097a91af0241028e0976a2
-- function public.app_public_suborganization_facets() | definer=true | settings=["search_path=public, pg_temp"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=2a9b224262a56702a669fbaa2a4a429e
-- function public.app_public_workspace_index() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres,anon=X/postgres}" | anon=true | authenticated=false | service_role=true | definition_md5=7c7428c36e530737ea801338948458d4
-- function public.app_public_workspace_snapshot() | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=1722b26ee96ffe8a39f65f6bd751db6f
-- function public.app_reject_access_request(p_request uuid) | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=80fd5f37a585b9b5b55ec9d3dba711d0
-- function public.app_request_workspace_access(p_token text) | definer=true | settings=["search_path=pg_catalog, public, private, extensions"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=de30ba05366498f83f36a423f0a4ed05
-- function public.app_respond_project_invitation(p_invitation uuid, p_accept boolean) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=e3900fecfc412545626fd74e00bbf333
-- function public.app_save_page_v2(p_id uuid, p_workspace uuid, p_space uuid, p_title text, p_slug text, p_summary text, p_body text, p_status text, p_visibility text) | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=bb7e279448d0a589b498e25557a673c8
-- function public.app_set_project_block_publication(p_block uuid, p_publish boolean, p_confirm boolean, p_order integer) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=0db9a185ebeb39aa6f064a804a275e15
-- function public.app_set_project_publication(p_project uuid, p_publish boolean, p_confirm boolean, p_summary text) | definer=true | settings=["search_path=pg_catalog, public"] | acl="{postgres=X/postgres,service_role=X/postgres}" | anon=false | authenticated=false | service_role=true | definition_md5=a702b2bf832b9f5a43ab7823667192e6
-- function public.app_set_workspace_member_role(p_user uuid, p_role text) | definer=true | settings=["search_path=public, private, pg_temp"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=2c5939357505806abab6e10f67768679
-- function public.app_sync_project_suborganizations(p_project uuid, p_organizations uuid[]) | definer=false | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=0f1acfefbb32e83aed5c0e7698fe1b2f
-- function public.app_sync_suborganization_projects(p_organization uuid, p_projects uuid[]) | definer=false | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=1ee9b89829b586555478b2d6b85c628f
-- function public.app_update_event_body(p_event uuid, p_body text) | definer=true | settings=["search_path=pg_catalog, public, private"] | acl="{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}" | anon=false | authenticated=true | service_role=true | definition_md5=b1d737509698dc0feca50f9f16b40013
-- END CAPTURED WEB2 FUNCTION STATE

with target_tables(table_name) as (
  values
    ('app_meetings'),
    ('app_documents'),
    ('app_events'),
    ('app_event_attendees'),
    ('app_event_comments'),
    ('app_event_photos'),
    ('app_event_suborganizations'),
    ('app_suborganizations'),
    ('app_suborganization_affiliations'),
    ('app_suborganization_assignees'),
    ('app_suborganization_status_items'),
    ('app_suborganization_timeline'),
    ('app_suborganization_updates'),
    ('app_suborganization_weekly_reports'),
    ('app_org_affiliation_tags'),
    ('app_invites'),
    ('app_workspaces'),
    ('app_workspace_members'),
    ('app_profiles'),
    ('app_profile_workplaces'),
    ('app_profile_report_projects'),
    ('app_profile_weekly_reports'),
    ('app_profile_workplace_statuses'),
    ('app_direct_messages'),
    ('app_ai_conversations'),
    ('app_ai_daily_usage'),
    ('app_ai_messages'),
    ('app_ai_workspace_settings'),
    ('app_document_ai_index'),
    ('app_document_chunks'),
    ('app_tasks'),
    ('app_pages'),
    ('app_spaces')
), table_state as (
  select c.relname as table_name,
         c.relrowsecurity as rls_enabled,
         c.relforcerowsecurity as rls_forced
  from pg_catalog.pg_class c
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  join target_tables t on t.table_name = c.relname
  where n.nspname = 'public' and c.relkind in ('r', 'p')
), policies as (
  select p.tablename as table_name,
         jsonb_agg(jsonb_build_object(
           'name', p.policyname,
           'command', p.cmd,
           'roles', p.roles,
           'using', p.qual,
           'with_check', p.with_check
         ) order by p.policyname) as policies
  from pg_catalog.pg_policies p
  join target_tables t on t.table_name = p.tablename
  where p.schemaname = 'public'
  group by p.tablename
), table_grants as (
  select g.table_name,
         jsonb_agg(jsonb_build_object(
           'grantee', g.grantee,
           'privilege', g.privilege_type,
           'grantable', g.is_grantable
         ) order by g.grantee, g.privilege_type) as grants
  from information_schema.role_table_grants g
  join target_tables t on t.table_name = g.table_name
  where g.table_schema = 'public'
    and g.grantee in ('PUBLIC', 'anon', 'authenticated', 'service_role')
  group by g.table_name
), functions as (
  select n.nspname as schema_name,
         p.proname as function_name,
         pg_catalog.pg_get_function_identity_arguments(p.oid) as identity_arguments,
         p.prosecdef as security_definer,
         p.proconfig as settings,
         pg_catalog.pg_get_functiondef(p.oid) as definition,
         p.proacl::text as explicit_acl,
         pg_catalog.has_function_privilege('anon', p.oid, 'EXECUTE') as anon_execute,
         pg_catalog.has_function_privilege('authenticated', p.oid, 'EXECUTE') as authenticated_execute,
         pg_catalog.has_function_privilege('service_role', p.oid, 'EXECUTE') as service_role_execute
  from pg_catalog.pg_proc p
  join pg_catalog.pg_namespace n on n.oid = p.pronamespace
  where n.nspname in ('public', 'private')
    and p.proname like 'app\_%' escape '\'
    and p.proname not like 'app\_google\_%' escape '\'
)
select jsonb_build_object(
  'tables', coalesce((
    select jsonb_agg(jsonb_build_object(
      'name', s.table_name,
      'rls_enabled', s.rls_enabled,
      'rls_forced', s.rls_forced,
      'policies', coalesce(p.policies, '[]'::jsonb),
      'grants', coalesce(g.grants, '[]'::jsonb)
    ) order by s.table_name)
    from table_state s
    left join policies p using (table_name)
    left join table_grants g using (table_name)
  ), '[]'::jsonb),
  'functions', coalesce((select jsonb_agg(to_jsonb(f) order by schema_name, function_name, identity_arguments) from functions f), '[]'::jsonb)
) as task12a_authorization_snapshot;
