import {test,expect} from '@playwright/test';
import {openHome} from './helpers/home-entry.mjs';
const ready=page=>page.waitForFunction(()=>window.KPTUHome?.metrics.readyAt);
const start=page=>page.evaluate(()=>new Promise(resolve=>{addEventListener('kptu:home-ready',()=>resolve(),{once:true});KPTUHome.start();}));
test('cold cached meeting controls wait for the task module and current task state',async({page})=>{
  await openHome(page);await ready(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let release;const pending=new Promise(r=>release=r);
  await page.route('**/app/google-tasks.js?*',async route=>{await pending;await route.continue();});
  await page.reload();const button=page.locator('[data-home-card="meetings"] [data-home-toggle="meeting"]');
  await expect(button).toBeVisible();await expect(button).toBeDisabled();release();await ready(page);
  await expect(button).toBeEnabled();await button.click();
  await expect(page.locator('[data-home-card="meetings"] [data-home-task="meeting"]')).toHaveClass(/completed/);
  expect(errors).toEqual([]);
});
test('cached cards paint silently before refresh and calendar status and events run together',async({page})=>{
  const c=await openHome(page,{delays:{status:1200,events:1200,overview:1000,app_record_links:400},query:'?homeTiming=1'});
  await ready(page);c.requests.length=0;
  const refresh=start(page);
  await expect(page.locator('[data-home-card="calendar"]')).toContainText('오전 일정',{timeout:500});
  await expect(page.locator('[data-home-unlinked]')).toContainText('3개',{timeout:500});
  await expect(page.locator('#homeView')).not.toContainText('기기 사본');
  await expect.poll(()=>c.requests.filter(r=>['status','events'].includes(r.action)).length,{timeout:500}).toBe(2);
  await refresh;
  const metrics=await page.evaluate(()=>KPTUHome.metrics);
  expect(metrics.firstPaint.calendar).toBeLessThan(500);
  expect(metrics.firstPaint.unlinked).toBeLessThan(500);
  expect(metrics.refreshed.calendar).toBeLessThan(1800);
  expect(c.requests.filter(r=>r.action==='overview')).toHaveLength(1);
  await expect(page.locator('[data-home-timing]')).toContainText('ms');
});
test('first visit task rows appear before links; overlapping starts share the read',async({page})=>{
  const c=await openHome(page,{delays:{overview:1000,app_record_links:1200,status:1200,events:1200}});
  await expect.poll(()=>c.requests.filter(r=>r.action==='overview').length).toBe(1);
  await page.evaluate(()=>{KPTUHome.start();dispatchEvent(new Event('focus'));dispatchEvent(new CustomEvent('kptu:tasks-changed'));dispatchEvent(new CustomEvent('kptu:google-tasks-changed'));dispatchEvent(new Event('pageshow'));dispatchEvent(new CustomEvent('kptu:view-changed',{detail:{view:'home'}}));});
  await expect(page.locator('[data-home-card="tasks"]')).toContainText('오늘 항목',{timeout:1600});
  expect(c.requests.filter(r=>r.path.endsWith('app_record_links'))).toHaveLength(1);
  await ready(page);
  expect(c.requests.filter(r=>r.action==='overview')).toHaveLength(1);
  expect(c.requests.filter(r=>r.action==='status')).toHaveLength(1);
  expect(c.requests.filter(r=>r.action==='events')).toHaveLength(1);
  await expect(page.locator('[data-home-timing]')).toHaveCount(0);
});
test('calendar copy survives reload but is ignored on next KST day; week copy expires on Monday',async({page})=>{
  const c=await openHome(page);await ready(page);
  c.setDelay('status',1200);c.setDelay('events',1200);c.setDelay('overview',1000);c.setDelay('app_suborganization_updates',1200);
  await page.reload();await expect(page.locator('[data-home-card="calendar"]')).toContainText('오전 일정',{timeout:700});
  await ready(page);
  await page.clock.setFixedTime(new Date('2026-10-06T15:00:00Z'));
  const next=start(page);
  await expect(page.locator('[data-home-card="calendar"]')).toContainText('불러오는 중',{timeout:500});await next;
  await page.clock.setFixedTime(new Date('2026-10-11T15:00:00Z'));
  const monday=start(page);await expect(page.locator('[data-home-card="updates"]')).toContainText('불러오는 중',{timeout:500});await monday;
});
test('latest failure is visible and does not replace the last successful copy',async({page})=>{
  const c=await openHome(page);await ready(page);c.setFailure('google-calendar');await start(page);
  await expect(page.locator('[data-home-card="calendar"]')).toHaveAttribute('data-state','failed');
  c.setDelay('google-calendar',1200);const retry=start(page);
  await expect(page.locator('[data-home-card="calendar"]')).toContainText('오전 일정',{timeout:500});await retry;
  c.setFailure('');c.setConnected(false);await start(page);
  await expect(page.locator('[data-home-card="calendar"]')).toHaveAttribute('data-state','disconnected');
  await expect(page.locator('[data-home-card="tasks"]')).toHaveAttribute('data-state','disconnected');
});
test('fresh task event refreshes only task cards and preserves calendar and updates',async({page})=>{
  const c=await openHome(page);await ready(page);c.requests.length=0;
  c.tasks.push({id:'new',title:'새 항목',status:'needsAction',due:'2026-10-06'});
  await page.evaluate(()=>dispatchEvent(new CustomEvent('kptu:tasks-changed')));
  await expect(page.locator('[data-home-card="tasks"]')).toContainText('새 항목');
  await expect(page.locator('[data-home-unlinked]')).toContainText('4개');
  expect(c.requests.filter(r=>r.action==='status'||r.action==='events')).toHaveLength(0);
  expect(c.requests.filter(r=>r.path.endsWith('app_suborganization_updates'))).toHaveLength(0);
});
