const CM_GOOGLE_DEFAULT='#4285f4';
let cmGoogle=null;
function cmRuntime(){const rt=window.KPTURuntime;if(!rt?.session||!rt?.api)throw new Error('앱 런타임을 불러오지 못했습니다.');return rt}
async function cmGoogleCall(action,{method='GET',body=null,params=null}={}){const rt=cmRuntime();if(!(await rt.session.ensure()))throw new Error('로그인이 필요합니다.');const u=new URL(rt.config.url+'/functions/v1/google-calendar');if(action)u.searchParams.set('action',action);if(params)Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const d=await rt.api(u.toString(),{method,body});if(d?.error)throw new Error(d.error||'Google Calendar 요청 실패');return d}
function cmToast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(cmToast.t);cmToast.t=setTimeout(()=>t.classList.add('hidden'),2400)}
function cmCloseModal(){const m=document.querySelector('#eventModal');if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true');window.KPTUA11y?.dialog.deactivate(m,{restoreFocus:true,fallbackFocus:'#calendarView h2'})}}
function cmStatus(msg,err=false){const e=document.querySelector('#eventStatus');if(e){e.textContent=msg||'';e.className='status'+(err?' error':'');if(err){e.setAttribute('role','alert');e.removeAttribute('aria-live')}else{e.setAttribute('role','status');e.setAttribute('aria-live','polite')}}}
function cmSetBusy(value){const b=document.querySelector('#saveEventBtn');if(!b)return;b.disabled=!!value;if(value)b.setAttribute('aria-busy','true');else b.removeAttribute('aria-busy')}
function cmInjectControls(){const bar=document.querySelector('#googleCalendarControls');if(bar)bar.querySelectorAll('#showTeamCalendar,#showGoogleCalendar,#showPersonalCalendar').forEach(x=>x.closest('label')?.remove());const toolbar=document.querySelector('.calendar-toolbar');if(toolbar&&!document.querySelector('#calendarQuickAdd')){const b=document.createElement('button');b.id='calendarQuickAdd';b.type='button';b.className='mini calendar-quick-add';b.textContent='+';b.title='Google 일정 등록';b.setAttribute('aria-label','Google 일정 등록');b.onclick=()=>document.querySelector('#newEventBtn')?.click();toolbar.appendChild(b)}}
async function cmGoogleState(){if(window.__KPTU_GOOGLE_STATE__?.connected){cmGoogle=window.__KPTU_GOOGLE_STATE__;return cmGoogle}try{cmGoogle=await cmGoogleCall('status');window.__KPTU_GOOGLE_STATE__=cmGoogle;return cmGoogle}catch{return null}}
function cmInjectModal(){const modal=document.querySelector('#eventModal .modal-card');if(!modal||document.querySelector('#eventGoogleOptions'))return;const title=document.querySelector('#eventTitle')?.closest('label');if(!title)return;title.insertAdjacentHTML('afterend',`<div id="eventGoogleOptions" class="cm-google-options"><label>Google 캘린더<select id="eventGoogleCalendar"></select></label><label>색상<div class="cm-color-row"><input id="eventGoogleColor" type="color" value="${CM_GOOGLE_DEFAULT}"><span>Google 일정 색상</span></div></label></div>`);document.querySelector('#eventGoogleCalendar')?.addEventListener('change',cmGoogleCalendarChanged);const btn=document.querySelector('#saveEventBtn');if(btn){btn.textContent='Google Calendar에 저장';btn.onclick=()=>cmSaveGoogle()}}
async function cmPopulateGoogleCalendars(){const sel=document.querySelector('#eventGoogleCalendar');if(!sel)return;sel.innerHTML='<option>불러오는 중…</option>';const s=await cmGoogleState();if(!s?.connected){sel.innerHTML='<option value="">Google Calendar 연결 필요</option>';cmStatus('먼저 Google Calendar를 연결해 주세요.',true);return}const cals=s.calendars||[];sel.innerHTML=cals.map(c=>{const writable=['owner','writer'].includes(c.accessRole||'owner');return `<option value="${String(c.id).replace(/"/g,'&quot;')}" ${writable?'':'disabled'}>${String(c.summary||c.id).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}${c.primary?' (기본)':''}${writable?'':' · 읽기 전용'}</option>`}).join('')||'<option value="">사용 가능한 캘린더 없음</option>';const preferred=[...sel.options].find(o=>!o.disabled&&s.selected?.includes(o.value))||[...sel.options].find(o=>!o.disabled&&o.value);if(preferred)sel.value=preferred.value;cmGoogleCalendarChanged()}
function cmGoogleCalendarChanged(){const id=document.querySelector('#eventGoogleCalendar')?.value,s=cmGoogle||window.__KPTU_GOOGLE_STATE__,c=s?.calendars?.find(x=>x.id===id),custom=s?.colors?.[id],picker=document.querySelector('#eventGoogleColor');if(picker)picker.value=custom||c?.backgroundColor||CM_GOOGLE_DEFAULT}
async function cmSaveGoogle(){const title=document.querySelector('#eventTitle')?.value.trim(),start=document.querySelector('#eventStart')?.value,end=document.querySelector('#eventEnd')?.value,calendar=document.querySelector('#eventGoogleCalendar')?.value;if(!title||!start)return cmStatus('제목과 시작시간을 입력해 주세요.',true);if(!end)return cmStatus('Google 일정은 종료시간도 입력해 주세요.',true);if(new Date(end)<=new Date(start))return cmStatus('종료시간은 시작시간보다 뒤여야 합니다.',true);if(!calendar)return cmStatus('Google 캘린더를 선택해 주세요.',true);cmSetBusy(true);try{cmStatus('Google Calendar에 저장 중…');const organizationIds=window.__KPTU_SELECTED_EVENT_ORGS__?.()||[];await cmGoogleCall('',{method:'POST',body:{action:'create-event',calendar_id:calendar,title,memo:document.querySelector('#eventDescription')?.value||'',location:document.querySelector('#eventLocation')?.value||'',all_day:false,start_iso:new Date(start).toISOString(),end_iso:new Date(end).toISOString(),color_hex:document.querySelector('#eventGoogleColor')?.value||CM_GOOGLE_DEFAULT,organization_ids:organizationIds}});cmCloseModal();await window.__KPTU_RELOAD_GOOGLE_EVENTS__?.();cmToast('Google Calendar에 저장했습니다.')}catch(e){cmStatus(e.message,true)}finally{cmSetBusy(false)}}
async function cmPrepareNewEvent(){cmStatus('');await cmPopulateGoogleCalendars()}
async function cmInit(){if(!document.querySelector('#calendarView'))return false;cmInjectControls();cmInjectModal();return true}
window.KPTUCalendarPlus={paint:()=>{},refresh:async()=>true,prepareNewEvent:cmPrepareNewEvent,savePrefs:()=>{}};
window.__KPTU_RELOAD_APP_EVENTS__=async()=>true;
window.__KPTU_CALENDAR_PLUS_READY__=cmInit().catch(e=>{console.warn('calendar plus init',e);return false});