const CM_GOOGLE_DEFAULT='#4285f4';
let cmGoogle=null;
function cmRuntime(){const rt=window.KPTURuntime;if(!rt?.session||!rt?.api)throw new Error('앱 런타임을 불러오지 못했습니다.');return rt}
async function cmGoogleCall(action,{method='GET',body=null,params=null}={}){const rt=cmRuntime();if(!(await rt.session.ensure()))throw new Error('로그인이 필요합니다.');const u=new URL(rt.config.url+'/functions/v1/google-calendar');if(action)u.searchParams.set('action',action);if(params)Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const d=await rt.api(u.toString(),{method,body});if(d?.error)throw new Error(d.error||'Google Calendar 요청 실패');return d}
function cmToast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(cmToast.t);cmToast.t=setTimeout(()=>t.classList.add('hidden'),2400)}
function cmCloseModal(){const m=document.querySelector('#eventModal');if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true');window.KPTUA11y?.dialog.deactivate(m,{restoreFocus:true,fallbackFocus:'#calendarView h2'})}}
function cmStatus(msg,err=false){const e=document.querySelector('#eventStatus');if(e){e.textContent=msg||'';e.className='status'+(err?' error':'');if(err){e.setAttribute('role','alert');e.removeAttribute('aria-live')}else{e.setAttribute('role','status');e.setAttribute('aria-live','polite')}}}
function cmSetBusy(value){const b=document.querySelector('#saveEventBtn');if(!b)return;b.disabled=!!value;if(value)b.setAttribute('aria-busy','true');else b.removeAttribute('aria-busy')}
function cmInjectControls(){const bar=document.querySelector('#googleCalendarControls');if(bar)bar.querySelectorAll('#showTeamCalendar,#showGoogleCalendar,#showPersonalCalendar').forEach(x=>x.closest('label')?.remove());const toolbar=document.querySelector('.calendar-toolbar');if(toolbar&&!document.querySelector('#calendarQuickAdd')){const b=document.createElement('button');b.id='calendarQuickAdd';b.type='button';b.className='mini calendar-quick-add';b.textContent='+';b.title='일정 등록';b.setAttribute('aria-label','일정 등록');b.onclick=()=>document.querySelector('#newEventBtn')?.click();toolbar.appendChild(b)}}
async function cmGoogleState(){if(window.__KPTU_GOOGLE_STATE__?.connected){cmGoogle=window.__KPTU_GOOGLE_STATE__;return cmGoogle}try{cmGoogle=await cmGoogleCall('status');window.__KPTU_GOOGLE_STATE__=cmGoogle;return cmGoogle}catch{return null}}
async function cmPopulateGoogleCalendars(){const sel=document.querySelector('#eventGoogleCalendar');if(!sel)return;sel.innerHTML='<option>불러오는 중…</option>';const s=await cmGoogleState();if(!s?.connected){sel.innerHTML='<option value="">Google Calendar 연결 필요</option>';cmStatus('Google Calendar에 저장하려면 먼저 연결해 주세요.',true);return}const cals=s.calendars||[];sel.innerHTML=cals.map(c=>{const writable=['owner','writer'].includes(c.accessRole||'owner');return `<option value="${String(c.id).replace(/"/g,'&quot;')}" ${writable?'':'disabled'}>${String(c.summary||c.id).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}${c.primary?' (기본)':''}${writable?'':' · 읽기 전용'}</option>`}).join('')||'<option value="">사용 가능한 캘린더 없음</option>';const preferred=[...sel.options].find(o=>!o.disabled&&s.selected?.includes(o.value))||[...sel.options].find(o=>!o.disabled&&o.value);if(preferred)sel.value=preferred.value;cmGoogleCalendarChanged()}
function cmGoogleCalendarChanged(){const id=document.querySelector('#eventGoogleCalendar')?.value,s=cmGoogle||window.__KPTU_GOOGLE_STATE__,c=s?.calendars?.find(x=>x.id===id),custom=s?.colors?.[id],picker=document.querySelector('#eventGoogleColor');if(picker)picker.value=custom||c?.backgroundColor||CM_GOOGLE_DEFAULT}
function cmToggleAllDay(){const allDay=!!document.querySelector('#eventAllDay')?.checked;document.querySelectorAll('.event-time-row').forEach(x=>x.classList.toggle('hidden',allDay))}
async function cmTargetChanged(){const target=document.querySelector('#eventTarget')?.value||'web2',google=document.querySelector('#eventGoogleOptions'),project=document.querySelector('#eventProjectRow');google?.classList.toggle('hidden',target!=='google');project?.classList.toggle('hidden',target==='google');cmStatus('');if(target==='google')await cmPopulateGoogleCalendars()}
function cmForm(){const title=document.querySelector('#eventTitle')?.value.trim(),allDay=!!document.querySelector('#eventAllDay')?.checked,startDate=document.querySelector('#eventStartDate')?.value,endDate=document.querySelector('#eventEndDate')?.value||startDate;if(!title)throw new Error('제목을 입력해 주세요.');if(!startDate||!endDate)throw new Error('시작·종료 날짜를 입력해 주세요.');const f={title,allDay,startDate,endDate,memo:document.querySelector('#eventDescription')?.value||'',location:document.querySelector('#eventLocation')?.value||'',color_hex:document.querySelector('#eventGoogleColor')?.value||CM_GOOGLE_DEFAULT};if(!allDay){const st=document.querySelector('#eventStartTime')?.value,et=document.querySelector('#eventEndTime')?.value;if(!st||!et)throw new Error('시작·종료 시간을 입력해 주세요.');const start=new Date(startDate+'T'+st),end=new Date(endDate+'T'+et);if(end<=start)throw new Error('종료시간은 시작시간보다 뒤여야 합니다.');f.start_iso=start.toISOString();f.end_iso=end.toISOString()}return f}
async function cmSaveGoogle(){cmSetBusy(true);try{const f=cmForm(),calendar=document.querySelector('#eventGoogleCalendar')?.value;if(!calendar)throw new Error('Google 세부 캘린더를 선택해 주세요.');cmStatus('Google Calendar에 저장 중…');const organizationIds=window.__KPTU_SELECTED_EVENT_ORGS__?.()||[];const body={action:'create-event',calendar_id:calendar,title:f.title,memo:f.memo,location:f.location,color_hex:f.color_hex,all_day:f.allDay,organization_ids:organizationIds};if(f.allDay){body.start_date=f.startDate;body.end_date=f.endDate}else{body.start_iso=f.start_iso;body.end_iso=f.end_iso}await cmGoogleCall('',{method:'POST',body});cmCloseModal();await window.__KPTU_RELOAD_GOOGLE_EVENTS__?.();cmToast('Google Calendar에 저장했습니다.');return true}catch(e){cmStatus(e.message||String(e),true);return false}finally{cmSetBusy(false)}}
async function cmPrepareNewEvent(){cmStatus('');cmToggleAllDay();await cmTargetChanged()}
function cmBindCreate(){const target=document.querySelector('#eventTarget'),allDay=document.querySelector('#eventAllDay'),calendar=document.querySelector('#eventGoogleCalendar'),btn=document.querySelector('#saveEventBtn');if(!target||!allDay||!btn)return false;target.addEventListener('change',()=>cmTargetChanged().catch(e=>cmStatus(e.message||String(e),true)));allDay.addEventListener('change',cmToggleAllDay);calendar?.addEventListener('change',cmGoogleCalendarChanged);const appSave=btn.onclick;btn.onclick=e=>{e?.preventDefault?.();return (target.value||'web2')==='google'?cmSaveGoogle():appSave?.call(btn,e)};return true}
async function cmInit(){if(!document.querySelector('#calendarView'))return false;cmInjectControls();cmBindCreate();return true}
window.KPTUCalendarPlus={paint:()=>{},refresh:async()=>true,prepareNewEvent:cmPrepareNewEvent,saveGoogle:cmSaveGoogle,savePrefs:()=>{}};
window.__KPTU_CALENDAR_PLUS_READY__=cmInit().catch(e=>{console.warn('calendar plus init',e);return false});
