const CM_PREF='kptu_calendar_visibility_v1';
let cmWorkspace=null,cmUser=null,cmEvents=[],cmPainting=false,cmGoogle=null,cmLoadedRange='';
function cmRuntime(){const rt=window.KPTURuntime;if(!rt?.session||!rt?.api)throw new Error('앱 런타임을 불러오지 못했습니다.');return rt}
async function cmFetch(url,{method='GET',body=null,prefer=''}={}){const rt=cmRuntime();if(!(await rt.session.ensure()))throw new Error('로그인이 필요합니다.');return rt.api(url,{method,body,prefer})}
async function cmContext(){if(cmWorkspace&&cmUser)return;const rt=cmRuntime();if(!(await rt.session.ensure()))throw new Error('로그인이 필요합니다.');const account=await rt.api('/auth/v1/user');cmUser=account?.id||null;if(!cmUser)throw new Error('로그인 정보를 확인할 수 없습니다.');const u=new URL(rt.config.url+'/rest/v1/app_workspace_members');u.searchParams.set('user_id','eq.'+cmUser);u.searchParams.set('select','workspace_id');u.searchParams.set('limit','1');const rows=await rt.api(u.toString());if(!rows?.length)throw new Error('팀 Workspace를 확인할 수 없습니다.');cmWorkspace=rows[0].workspace_id}
async function cmGoogleCall(action,{method='GET',body=null,params=null}={}){const rt=cmRuntime();if(!(await rt.session.ensure()))throw new Error('로그인이 필요합니다.');const u=new URL(rt.config.url+'/functions/v1/google-calendar');if(action)u.searchParams.set('action',action);if(params)Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const d=await rt.api(u.toString(),{method,body});if(d?.error)throw new Error(d.error||'Google Calendar 요청 실패');return d}
function cmPad(n){return String(n).padStart(2,'0')}
function cmKey(v){const d=new Date(v);return `${d.getFullYear()}-${cmPad(d.getMonth()+1)}-${cmPad(d.getDate())}`}
function cmRange(){const txt=document.querySelector('#monthTitle')?.textContent||'',m=txt.match(/(\d{4})년\s*(\d{1,2})월/),now=new Date(),y=m?Number(m[1]):now.getFullYear(),mo=m?Number(m[2])-1:now.getMonth(),f=new Date(y,mo,1),s=new Date(f);s.setDate(1-f.getDay());s.setHours(0,0,0,0);const e=new Date(s);e.setDate(s.getDate()+42);return {s,e,key:s.toISOString().slice(0,10)+'_'+e.toISOString().slice(0,10)}}
function cmText(hex){const h=String(hex||'').replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(h))return '#fff';const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);return r*299+g*587+b*114>160000?'#24313d':'#fff'}
function cmToast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(cmToast.t);cmToast.t=setTimeout(()=>t.classList.add('hidden'),2400)}
function cmCloseModal(){const m=document.querySelector('#eventModal');if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}}
function cmStatus(msg,err=false){const e=document.querySelector('#eventStatus');if(e){e.textContent=msg||'';e.className='status'+(err?' error':'')}}
function cmPrefs(){try{return {...{team:true,personal:true},...JSON.parse(localStorage.getItem(CM_PREF)||'{}')}}catch{return {team:true,personal:true}}}
function cmSavePrefs(){localStorage.setItem(CM_PREF,JSON.stringify({team:document.querySelector('#showTeamCalendar')?.checked!==false,personal:document.querySelector('#showPersonalCalendar')?.checked!==false}))}
function cmInjectControls(){const bar=document.querySelector('#googleCalendarControls');if(bar&&!document.querySelector('#showPersonalCalendar')){const team=bar.querySelector('#showTeamCalendar')?.closest('label');if(team){team.lastChild.textContent=' 팀 캘린더';team.insertAdjacentHTML('afterend','<label class="toggle-line cm-personal-toggle"><input id="showPersonalCalendar" type="checkbox"> 개인 캘린더</label>')}const gl=bar.querySelector('#showGoogleCalendar')?.closest('label');if(gl)gl.lastChild.textContent=' Google 캘린더';const p=cmPrefs();if(document.querySelector('#showTeamCalendar'))document.querySelector('#showTeamCalendar').checked=p.team;if(document.querySelector('#showPersonalCalendar'))document.querySelector('#showPersonalCalendar').checked=p.personal;document.querySelector('#showPersonalCalendar')?.addEventListener('change',()=>{cmSavePrefs();cmPaintAppEvents()});document.querySelector('#showTeamCalendar')?.addEventListener('change',()=>{cmSavePrefs();setTimeout(cmPaintAppEvents,40)},true)}
 const toolbar=document.querySelector('.calendar-toolbar');if(toolbar&&!document.querySelector('#calendarQuickAdd')){const b=document.createElement('button');b.id='calendarQuickAdd';b.type='button';b.className='mini calendar-quick-add';b.textContent='+';b.title='일정 등록';b.setAttribute('aria-label','일정 등록');b.onclick=()=>document.querySelector('#newEventBtn')?.click();toolbar.appendChild(b)}
}
async function cmGoogleState(){if(window.__KPTU_GOOGLE_STATE__?.connected){cmGoogle=window.__KPTU_GOOGLE_STATE__;return cmGoogle}try{cmGoogle=await cmGoogleCall('status');window.__KPTU_GOOGLE_STATE__=cmGoogle;return cmGoogle}catch{return null}}
function cmInjectModal(){const modal=document.querySelector('#eventModal .modal-card');if(!modal||document.querySelector('#eventCalendarScope'))return;const title=document.querySelector('#eventTitle')?.closest('label');if(!title)return;title.insertAdjacentHTML('afterend',`<label id="eventCalendarScopeRow">캘린더<select id="eventCalendarScope"><option value="team">팀 캘린더</option><option value="personal">개인 캘린더</option><option value="google">Google 캘린더</option></select></label><div id="eventGoogleOptions" class="cm-google-options hidden"><label>Google 세부 캘린더<select id="eventGoogleCalendar"></select></label><label>색상<div class="cm-color-row"><input id="eventGoogleColor" type="color" value="#4285f4"><span>이 일정의 Google 색상</span></div></label></div>`);document.querySelector('#eventCalendarScope').addEventListener('change',cmScopeChanged);document.querySelector('#eventGoogleCalendar').addEventListener('change',cmGoogleCalendarChanged);const btn=document.querySelector('#saveEventBtn'),old=btn?.onclick;if(btn){btn.onclick=async function(e){const scope=document.querySelector('#eventCalendarScope')?.value||'team';if(scope==='team')return old?.call(this,e);if(scope==='personal')return cmSavePersonal();if(scope==='google')return cmSaveGoogle()}}
 document.addEventListener('click',e=>{if(e.target.closest('#newEventBtn,#homeAddEvent,#calendarQuickAdd'))setTimeout(cmResetScope,0)},true);cmResetScope()}
function cmResetScope(){const s=document.querySelector('#eventCalendarScope');if(s){s.value='team';cmScopeChanged()}}
async function cmScopeChanged(){const scope=document.querySelector('#eventCalendarScope')?.value||'team';const google=document.querySelector('#eventGoogleOptions'),att=document.querySelector('#eventAttendees')?.closest('.permission-box'),proj=document.querySelector('#eventProject')?.closest('label'),type=document.querySelector('#eventType')?.closest('label'),btn=document.querySelector('#saveEventBtn');if(google)google.classList.toggle('hidden',scope!=='google');if(att)att.style.display=scope==='team'?'':'none';if(proj)proj.style.display=scope==='team'?'':'none';if(type)type.style.display=scope==='google'?'none':'';if(btn)btn.textContent=scope==='google'?'Google 일정 저장':scope==='personal'?'개인 일정 저장':'팀 일정 저장';if(scope!=='team'&&document.querySelector('#eventProject'))document.querySelector('#eventProject').value='';if(scope==='google')await cmPopulateGoogleCalendars()}
async function cmPopulateGoogleCalendars(){const sel=document.querySelector('#eventGoogleCalendar');if(!sel)return;sel.innerHTML='<option>불러오는 중…</option>';const s=await cmGoogleState();if(!s?.connected){sel.innerHTML='<option value="">Google Calendar 연결 필요</option>';cmStatus('먼저 Google Calendar를 연결해 주세요.',true);return}const cals=s.calendars||[];sel.innerHTML=cals.map(c=>{const writable=['owner','writer'].includes(c.accessRole||'owner');return `<option value="${String(c.id).replace(/"/g,'&quot;')}" ${writable?'':'disabled'}>${String(c.summary||c.id).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}${c.primary?' (기본)':''}${writable?'':' · 읽기 전용'}</option>`}).join('')||'<option value="">사용 가능한 캘린더 없음</option>';const first=[...sel.options].find(o=>!o.disabled&&o.value);if(first)sel.value=first.value;cmGoogleCalendarChanged()}
function cmGoogleCalendarChanged(){const id=document.querySelector('#eventGoogleCalendar')?.value,s=cmGoogle||window.__KPTU_GOOGLE_STATE__,c=s?.calendars?.find(x=>x.id===id),custom=s?.colors?.[id],picker=document.querySelector('#eventGoogleColor');if(picker)picker.value=custom||c?.backgroundColor||'#4285f4'}
async function cmSavePersonal(){const title=document.querySelector('#eventTitle')?.value.trim(),start=document.querySelector('#eventStart')?.value,end=document.querySelector('#eventEnd')?.value;if(!title||!start)return cmStatus('제목과 시작시간을 입력해 주세요.',true);if(end&&new Date(end)<=new Date(start))return cmStatus('종료시간은 시작시간보다 뒤여야 합니다.',true);try{cmStatus('개인 일정 저장 중…');await cmContext();await cmFetch('/rest/v1/app_events',{method:'POST',prefer:'return=representation',body:{workspace_id:cmWorkspace,project_id:null,title,description:document.querySelector('#eventDescription')?.value.trim()||null,event_type:document.querySelector('#eventType')?.value||'other',start_at:new Date(start).toISOString(),end_at:end?new Date(end).toISOString():null,location:document.querySelector('#eventLocation')?.value.trim()||null,created_by:cmUser,calendar_scope:'personal',color_hex:'#7656a8'}});cmCloseModal();await cmLoadAppEvents(true);cmToast('개인 캘린더에 저장했습니다.')}catch(e){cmStatus(e.message,true)}}
async function cmSaveGoogle(){const title=document.querySelector('#eventTitle')?.value.trim(),start=document.querySelector('#eventStart')?.value,end=document.querySelector('#eventEnd')?.value,calendar=document.querySelector('#eventGoogleCalendar')?.value;if(!title||!start)return cmStatus('제목과 시작시간을 입력해 주세요.',true);if(!end)return cmStatus('Google 일정은 종료시간도 입력해 주세요.',true);if(new Date(end)<=new Date(start))return cmStatus('종료시간은 시작시간보다 뒤여야 합니다.',true);if(!calendar)return cmStatus('Google 세부 캘린더를 선택해 주세요.',true);try{cmStatus('Google Calendar에 저장 중…');await cmGoogleCall('',{method:'POST',body:{action:'create-event',calendar_id:calendar,title,memo:document.querySelector('#eventDescription')?.value||'',location:document.querySelector('#eventLocation')?.value||'',all_day:false,start_iso:new Date(start).toISOString(),end_iso:new Date(end).toISOString(),color_hex:document.querySelector('#eventGoogleColor')?.value||'#4285f4'}});cmCloseModal();await window.__KPTU_RELOAD_GOOGLE_EVENTS__?.();cmToast('Google Calendar에 저장했습니다.')}catch(e){cmStatus(e.message,true)}}
async function cmLoadAppEvents(force=false){try{await cmContext();const {s,e,key}=cmRange();if(!force&&key===cmLoadedRange&&cmEvents.length){cmPaintAppEvents();return}const u=new URL(cmRuntime().config.url+'/rest/v1/app_events');u.searchParams.set('workspace_id','eq.'+cmWorkspace);u.searchParams.set('start_at','gte.'+s.toISOString());u.searchParams.append('start_at','lt.'+e.toISOString());u.searchParams.set('select','id,title,description,start_at,end_at,calendar_scope,color_hex,location,event_type,created_by,project_id');u.searchParams.set('order','start_at.asc');cmEvents=await cmFetch(u.toString());cmLoadedRange=key;cmPaintAppEvents()}catch(e){console.warn('calendar app events',e)}}
function cmPaintAppEvents(){const grid=document.querySelector('#calendarGrid');if(!grid||cmPainting)return;cmPainting=true;try{grid.querySelectorAll('.cal-event:not(.google)').forEach(x=>x.remove());grid.querySelectorAll('.cal-cell>small').forEach(x=>{if(/^\+\d+/.test(x.textContent||''))x.remove()});const txt=document.querySelector('#monthTitle')?.textContent||'',m=txt.match(/(\d{4})년\s*(\d{1,2})월/);if(!m)return;const f=new Date(Number(m[1]),Number(m[2])-1,1),s=new Date(f);s.setDate(1-f.getDay());s.setHours(0,0,0,0);const cells=[...grid.querySelectorAll('.cal-cell')],map=new Map();cells.forEach((c,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);map.set(cmKey(d),c)});const showTeam=document.querySelector('#showTeamCalendar')?.checked!==false,showPersonal=document.querySelector('#showPersonalCalendar')?.checked!==false;cmEvents.filter(ev=>(ev.calendar_scope==='personal'?showPersonal:showTeam)).forEach(ev=>{const cell=map.get(cmKey(ev.start_at));if(!cell)return;const d=document.createElement('div');const personal=ev.calendar_scope==='personal';d.className='cal-event cm-app '+(personal?'cm-personal':'cm-team');d.textContent=ev.title;d.title=(personal?'개인':'팀')+' · '+ev.title+' · 눌러서 수정';d.dataset.appEvent=ev.id;d.dataset.appScope=personal?'personal':'team';const bg=ev.color_hex||(personal?'#7656a8':'#24496f');d.style.setProperty('background',bg,'important');d.style.setProperty('color',cmText(bg),'important');d.style.setProperty('font-weight','750');d.style.cursor='pointer';cell.appendChild(d)})}finally{setTimeout(()=>{cmPainting=false},0)}}
function cmObserveGrid(){const g=document.querySelector('#calendarGrid');if(!g||g.dataset.cmObserved)return;g.dataset.cmObserved='1';new MutationObserver(()=>{if(!cmPainting)setTimeout(cmPaintAppEvents,25)}).observe(g,{childList:true,subtree:true})}
function cmStyle(){const st=document.createElement('style');st.textContent=`.calendar-toolbar{position:relative}.calendar-quick-add{position:absolute;right:0;top:50%;transform:translateY(-50%);width:34px;height:34px;border-radius:50%;font-size:21px;line-height:1;padding:0}.cm-personal-toggle:before{content:'';width:8px;height:8px;border-radius:50%;background:#7656a8}.cm-google-options{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:10px 0}.cm-google-options.hidden{display:none!important}.cm-color-row{display:flex;align-items:center;gap:8px}.cm-color-row input{width:50px;height:38px;padding:2px}.cm-color-row span{font-size:10px;color:#7b8793}.cal-event.cm-team{box-shadow:inset 3px 0 rgba(255,255,255,.22)}.cal-event.cm-personal{box-shadow:inset 3px 0 rgba(255,255,255,.22)}@media(max-width:600px){.cm-google-options{grid-template-columns:1fr}.calendar-quick-add{right:2px}}`;document.head.appendChild(st)}
async function cmInit(){if(!document.querySelector('#calendarView'))return;cmStyle();cmInjectControls();cmInjectModal();cmObserveGrid();document.querySelector('#prevMonthBtn')?.addEventListener('click',()=>setTimeout(()=>cmLoadAppEvents(true),120),true);document.querySelector('#nextMonthBtn')?.addEventListener('click',()=>setTimeout(()=>cmLoadAppEvents(true),120),true);setTimeout(()=>cmLoadAppEvents(true),350)}
window.__KPTU_RELOAD_APP_EVENTS__=()=>cmLoadAppEvents(true);
setTimeout(cmInit,0);
window.addEventListener('focus',()=>setTimeout(()=>cmLoadAppEvents(false),250));