const cmv={appId:null,appScope:null,googleId:null,googleCalendar:null,googleState:null,workspace:null,user:null,hooked:false};
function cmvRt(){const r=window.KPTURuntime;if(!r?.session||!r?.api)throw new Error('앱 런타임을 불러오지 못했습니다.');return r}
async function cmvApi(path,o={}){const r=cmvRt();if(!(await r.session.ensure()))throw new Error('로그인이 필요합니다.');return r.api(path,o)}
async function cmvGoogle(action,{method='GET',body=null,params=null}={}){const r=cmvRt(),u=new URL(r.config.url+'/functions/v1/google-calendar');if(action)u.searchParams.set('action',action);if(params)Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const d=await cmvApi(u.toString(),{method,body});if(d?.error)throw new Error(d.error);return d}
function cmvStatus(id,msg,err=false){const e=document.querySelector(id);if(e){e.textContent=msg||'';e.className='status'+(err?' error':'')}}
function cmvToast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(cmvToast.t);cmvToast.t=setTimeout(()=>t.classList.add('hidden'),2200)}
function cmvClose(id){const m=document.querySelector(id);if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}}
function cmvWritable(role){return role==='owner'||role==='writer'}
async function cmvGState(){if(cmv.googleState?.connected)return cmv.googleState;cmv.googleState=await cmvGoogle('status');return cmv.googleState}
async function cmvContext(){if(cmv.workspace&&cmv.user)return cmv;const u=await cmvApi('/auth/v1/user');cmv.user=u?.id;const rows=await cmvApi('/rest/v1/app_workspace_members?user_id=eq.'+encodeURIComponent(cmv.user)+'&select=workspace_id&limit=1');cmv.workspace=rows?.[0]?.workspace_id;if(!cmv.workspace)throw new Error('팀 Workspace를 확인할 수 없습니다.');return cmv}
async function cmvFillGoogle(id,current=''){const s=document.querySelector(id);if(!s)return;const g=await cmvGState();if(!g?.connected){s.innerHTML='<option value="">Google Calendar 연결 필요</option>';return}const cals=g.calendars||[];s.innerHTML=cals.map(c=>`<option value="${String(c.id).replace(/"/g,'&quot;')}" ${cmvWritable(c.accessRole)?'':'disabled'}>${String(c.summary||c.id).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}${c.primary?' (기본)':''}${cmvWritable(c.accessRole)?'':' · 읽기 전용'}</option>`).join('');if(current&&[...s.options].some(o=>o.value===current))s.value=current;else{const first=[...s.options].find(o=>!o.disabled&&o.value);if(first)s.value=first.value}}
function cmvAppTarget(){const v=document.querySelector('#cmvAppTarget')?.value||cmv.appScope||'team';document.querySelector('#cmvAppGoogleRow')?.classList.toggle('hidden',v!=='google');if(v==='google')cmvFillGoogle('#cmvAppGoogleCalendar').catch(e=>cmvStatus('#ciAppStatus',e.message,true))}
function cmvGoogleTarget(){const v=document.querySelector('#cmvGoogleTarget')?.value||'google';document.querySelector('#cmvGoogleCalendarRow')?.classList.toggle('hidden',v!=='google');if(v==='google')cmvFillGoogle('#cmvGoogleCalendar',cmv.googleCalendar||'').catch(e=>cmvStatus('#ciGoogleStatus',e.message,true))}
function cmvAppForm(){const title=document.querySelector('#ciAppTitle')?.value.trim(),start=document.querySelector('#ciAppStart')?.value,end=document.querySelector('#ciAppEnd')?.value;if(!title)throw new Error('제목을 입력해 주세요.');if(!start)throw new Error('시작시간을 입력해 주세요.');if(end&&new Date(end)<=new Date(start))throw new Error('종료시간은 시작시간보다 뒤여야 합니다.');return {title,start,end,event_type:document.querySelector('#ciAppType')?.value||'other',location:document.querySelector('#ciAppLocation')?.value.trim()||null,description:document.querySelector('#ciAppDescription')?.value.trim()||null,color_hex:document.querySelector('#ciAppColor')?.value||'#24496f'}}
function cmvGoogleForm(){const title=document.querySelector('#ciGoogleTitle')?.value.trim(),allDay=!!document.querySelector('#ciGoogleAllDay')?.checked,startDate=document.querySelector('#ciGoogleStartDate')?.value,endDate=document.querySelector('#ciGoogleEndDate')?.value;if(!title)throw new Error('제목을 입력해 주세요.');if(!startDate||!endDate)throw new Error('시작 날짜와 종료 날짜를 입력해 주세요.');const f={title,allDay,startDate,endDate,memo:document.querySelector('#ciGoogleMemo')?.value||'',color_hex:document.querySelector('#ciGoogleColor')?.value||'#4285f4'};if(!allDay){const st=document.querySelector('#ciGoogleStartTime')?.value,et=document.querySelector('#ciGoogleEndTime')?.value;if(!st||!et)throw new Error('시작 시간과 종료 시간을 입력해 주세요.');const s=new Date(`${startDate}T${st}`),e=new Date(`${endDate}T${et}`);if(e<=s)throw new Error('종료 시각은 시작 시각보다 뒤여야 합니다.');f.start_iso=s.toISOString();f.end_iso=e.toISOString()}return f}
function cmvGoogleBody(f,calendar,location=''){const b={action:'create-event',calendar_id:calendar,title:f.title,memo:f.memo??f.description??'',location:location||f.location||'',color_hex:f.color_hex,all_day:!!f.allDay};if(f.allDay){b.start_date=f.startDate;b.end_date=f.endDate}else{b.start_iso=f.start_iso||new Date(f.start).toISOString();b.end_iso=f.end_iso||new Date(f.end).toISOString()}return b}
function cmvAppTimes(f){if(!f.allDay)return {start_at:f.start_iso,end_at:f.end_iso};const s=new Date(`${f.startDate}T00:00:00`),e=new Date(`${f.endDate}T00:00:00`);e.setDate(e.getDate()+1);return {start_at:s.toISOString(),end_at:e.toISOString()}}
async function cmvGetApp(){const r=await cmvApi('/rest/v1/app_events?id=eq.'+encodeURIComponent(cmv.appId)+'&select=id,title,description,event_type,start_at,end_at,location,calendar_scope,color_hex,project_id,created_by&limit=1');if(!r?.length)throw new Error('일정을 찾을 수 없습니다.');return r[0]}
async function cmvGetGoogle(){const d=await cmvGoogle('event',{params:{eventId:cmv.googleId,calendarId:cmv.googleCalendar}});if(!d?.event)throw new Error('Google 일정을 찾을 수 없습니다.');return d.event}
async function cmvSaveApp(oldSave,btn){const target=document.querySelector('#cmvAppTarget')?.value||cmv.appScope||'team';if(target===cmv.appScope&&target!=='google')return oldSave?.call(btn);btn.disabled=true;try{const f=cmvAppForm(),src=await cmvGetApp(),sourceScope=src.calendar_scope;if(target==='team'||target==='personal'){cmvStatus('#ciAppStatus','캘린더를 변경하는 중…');await cmvApi('/rest/v1/app_events?id=eq.'+encodeURIComponent(src.id),{method:'PATCH',body:{title:f.title,event_type:f.event_type,start_at:new Date(f.start).toISOString(),end_at:f.end?new Date(f.end).toISOString():null,location:f.location,description:f.description,color_hex:f.color_hex,calendar_scope:target,project_id:target==='personal'?null:src.project_id}});if(sourceScope==='team'&&target==='personal'){try{await cmvApi('/rest/v1/app_event_attendees?event_id=eq.'+encodeURIComponent(src.id),{method:'DELETE'})}catch{}}cmvClose('#ciAppModal');await window.__KPTU_RELOAD_APP_EVENTS__?.();cmvToast(target==='team'?'팀 캘린더로 옮겼습니다.':'개인 캘린더로 옮겼습니다.');return}if(!f.end)throw new Error('Google 캘린더로 옮기려면 종료시간이 필요합니다.');const cal=document.querySelector('#cmvAppGoogleCalendar')?.value;if(!cal)throw new Error('Google 세부 캘린더를 선택해 주세요.');cmvStatus('#ciAppStatus','Google Calendar로 옮기는 중…');const made=await cmvGoogle('',{method:'POST',body:cmvGoogleBody({...f,memo:f.description,allDay:false,start_iso:new Date(f.start).toISOString(),end_iso:new Date(f.end).toISOString()},cal,f.location||'')});try{try{await cmvApi('/rest/v1/app_event_attendees?event_id=eq.'+encodeURIComponent(src.id),{method:'DELETE'})}catch{}await cmvApi('/rest/v1/app_events?id=eq.'+encodeURIComponent(src.id),{method:'DELETE'})}catch(e){if(made?.event?.id)try{await cmvGoogle('',{method:'POST',body:{action:'delete-event',calendar_id:cal,event_id:made.event.id}})}catch{}throw new Error('원본 일정 삭제에 실패해 Google 일정 생성도 취소했습니다.')}cmvClose('#ciAppModal');await Promise.all([window.__KPTU_RELOAD_APP_EVENTS__?.(),window.__KPTU_RELOAD_GOOGLE_EVENTS__?.()]);cmvToast('Google Calendar로 옮겼습니다.')}catch(e){cmvStatus('#ciAppStatus',e.message||String(e),true)}finally{btn.disabled=false}}
async function cmvSourceWritable(){const g=await cmvGState(),c=g?.calendars?.find(x=>x.id===cmv.googleCalendar);if(c&&!cmvWritable(c.accessRole))throw new Error('현재 Google 캘린더가 읽기 전용이라 이동할 수 없습니다.')}
async function cmvSaveGoogle(oldSave,btn){const target=document.querySelector('#cmvGoogleTarget')?.value||'google',cal=document.querySelector('#cmvGoogleCalendar')?.value||cmv.googleCalendar;if(target==='google'&&cal===cmv.googleCalendar)return oldSave?.call(btn);btn.disabled=true;try{const f=cmvGoogleForm(),src=await cmvGetGoogle();await cmvSourceWritable();if(target==='google'){if(!cal)throw new Error('Google 세부 캘린더를 선택해 주세요.');cmvStatus('#ciGoogleStatus','다른 Google 캘린더로 옮기는 중…');const made=await cmvGoogle('',{method:'POST',body:cmvGoogleBody(f,cal,src.location||'')});try{await cmvGoogle('',{method:'POST',body:{action:'delete-event',calendar_id:cmv.googleCalendar,event_id:src.id}})}catch(e){if(made?.event?.id)try{await cmvGoogle('',{method:'POST',body:{action:'delete-event',calendar_id:cal,event_id:made.event.id}})}catch{}throw new Error('원본 일정 삭제에 실패해 새 Google 일정 생성도 취소했습니다.')}cmvClose('#ciGoogleModal');await window.__KPTU_RELOAD_GOOGLE_EVENTS__?.();cmvToast('Google 세부 캘린더를 변경했습니다.');return}if(target!=='team'&&target!=='personal')throw new Error('옮길 캘린더를 선택해 주세요.');const ctx=await cmvContext(),t=cmvAppTimes(f);cmvStatus('#ciGoogleStatus',target==='team'?'팀 캘린더로 옮기는 중…':'개인 캘린더로 옮기는 중…');const rows=await cmvApi('/rest/v1/app_events',{method:'POST',prefer:'return=representation',body:{workspace_id:ctx.workspace,project_id:null,title:f.title,description:f.memo||null,event_type:'other',start_at:t.start_at,end_at:t.end_at,location:src.location||null,created_by:ctx.user,calendar_scope:target,color_hex:f.color_hex}}),made=Array.isArray(rows)?rows[0]:rows;try{await cmvGoogle('',{method:'POST',body:{action:'delete-event',calendar_id:cmv.googleCalendar,event_id:src.id}})}catch(e){if(made?.id)try{await cmvApi('/rest/v1/app_events?id=eq.'+encodeURIComponent(made.id),{method:'DELETE'})}catch{}throw new Error('Google 원본 삭제에 실패해 새 일정 생성도 취소했습니다.')}cmvClose('#ciGoogleModal');await Promise.all([window.__KPTU_RELOAD_APP_EVENTS__?.(),window.__KPTU_RELOAD_GOOGLE_EVENTS__?.()]);cmvToast(target==='team'?'팀 캘린더로 옮겼습니다.':'개인 캘린더로 옮겼습니다.')}catch(e){cmvStatus('#ciGoogleStatus',e.message||String(e),true)}finally{btn.disabled=false}}
function cmvPrepareApp(el){cmv.appId=el.dataset.appEvent;cmv.appScope=el.dataset.appScope==='personal'?'personal':'team';const s=document.querySelector('#cmvAppTarget');if(s){s.value=cmv.appScope;cmvAppTarget()}}
function cmvPrepareGoogle(el){cmv.googleId=el.dataset.googleEvent;cmv.googleCalendar=el.dataset.googleCalendar||'primary';const s=document.querySelector('#cmvGoogleTarget');if(s){s.value='google';cmvGoogleTarget()}}
function cmvHook(){if(cmv.hooked)return true;const at=document.querySelector('#ciAppTitle')?.closest('label'),gt=document.querySelector('#ciGoogleTitle')?.closest('label'),as=document.querySelector('#ciAppSave'),gs=document.querySelector('#ciGoogleSave');if(!at||!gt||!as||!gs)return false;at.insertAdjacentHTML('afterend','<label>캘린더<select id="cmvAppTarget"><option value="team">팀 캘린더</option><option value="personal">개인 캘린더</option><option value="google">Google 캘린더</option></select></label><label id="cmvAppGoogleRow" class="hidden">Google 세부 캘린더<select id="cmvAppGoogleCalendar"></select></label>');gt.insertAdjacentHTML('afterend','<label>캘린더<select id="cmvGoogleTarget"><option value="google">Google 캘린더</option><option value="team">팀 캘린더</option><option value="personal">개인 캘린더</option></select></label><label id="cmvGoogleCalendarRow">Google 세부 캘린더<select id="cmvGoogleCalendar"></select></label>');document.querySelector('#cmvAppTarget').onchange=cmvAppTarget;document.querySelector('#cmvGoogleTarget').onchange=cmvGoogleTarget;const oa=as.onclick,og=gs.onclick;as.onclick=e=>{e?.preventDefault?.();return cmvSaveApp(oa,as)};gs.onclick=e=>{e?.preventDefault?.();return cmvSaveGoogle(og,gs)};const st=document.createElement('style');st.textContent='#cmvAppGoogleRow.hidden,#cmvGoogleCalendarRow.hidden{display:none!important}#cmvAppTarget,#cmvAppGoogleCalendar,#cmvGoogleTarget,#cmvGoogleCalendar{width:100%}';document.head.appendChild(st);cmv.hooked=true;return true}
window.addEventListener('click',e=>{const a=e.target.closest?.('.cm-app[data-app-event]');if(a){cmvPrepareApp(a);return}const g=e.target.closest?.('.cp-event[data-google-event]');if(g)cmvPrepareGoogle(g)},true);
if(!cmvHook()){const o=new MutationObserver(()=>{if(cmvHook())o.disconnect()});o.observe(document.body,{childList:true,subtree:true})}
