const CC_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const CC_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const CC_SESSION='kptu_collab_session_v1';
let ccUser=null,ccWorkspace=null,ccRole=null,ccMembers=[],ccProfiles=[],ccSpaces=[],ccCurrentProject=null,ccPeer=null,ccTimer=null;
function ccSession(){try{return JSON.parse(localStorage.getItem(CC_SESSION)||'null')}catch{return null}}
async function ccApi(path,{method='GET',body=null,prefer=''}={}){const s=ccSession();if(!s?.access_token)throw new Error('로그인이 필요합니다.');const h={apikey:CC_KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'};if(prefer)h.Prefer=prefer;const r=await fetch(CC_SB+path,{method,headers:h,body:body===null?null:JSON.stringify(body),cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.hint||('요청 실패 '+r.status));return d}
function ccEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ccName(id){return ccProfiles.find(x=>x.user_id===id)?.display_name||id?.slice(0,8)||'팀원'}
function ccFmt(v){return v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}
function ccToast(msg){const t=document.querySelector('#toast');if(t){t.textContent=msg;t.classList.remove('hidden');clearTimeout(ccToast.t);ccToast.t=setTimeout(()=>t.classList.add('hidden'),2200)}}
function ccOpen(id){const m=document.querySelector('#'+id);if(m){m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}}
function ccClose(id){const m=document.querySelector('#'+id);if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}}
function ccSwitch(view){document.querySelectorAll('#appView .view-panel').forEach(x=>x.classList.toggle('hidden',x.id!==view+'View'));document.querySelectorAll('.app-nav .nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelectorAll('#ccMobileDock [data-cc-view]').forEach(x=>x.classList.toggle('active',x.dataset.ccView===view));if(view==='messages')ccLoadConversation();if(view==='profile')setTimeout(()=>document.querySelector('[data-view="profile"]')?.classList.add('active'),0);window.scrollTo({top:0,behavior:'instant'})}
async function ccContext(){const s=ccSession();if(!s?.access_token)return false;const ur=await fetch(CC_SB+'/auth/v1/user',{headers:{apikey:CC_KEY,Authorization:'Bearer '+s.access_token},cache:'no-store'});if(!ur.ok)return false;ccUser=await ur.json();const ms=await ccApi('/rest/v1/app_workspace_members?user_id=eq.'+ccUser.id+'&select=workspace_id,role&limit=1');if(!ms?.length)return false;ccWorkspace=ms[0].workspace_id;ccRole=ms[0].role;[ccMembers,ccProfiles,ccSpaces]=await Promise.all([ccApi('/rest/v1/app_workspace_members?workspace_id=eq.'+ccWorkspace+'&select=user_id,role'),ccApi('/rest/v1/app_profiles?select=user_id,display_name,job_title'),ccApi('/rest/v1/app_spaces?workspace_id=eq.'+ccWorkspace+'&select=id,name,parent_id,status,owner_id,visibility,sort_order')]);return true}
function ccInstallStyle(){if(document.querySelector('#ccStyle'))return;const s=document.createElement('style');s.id='ccStyle';s.textContent=`
#ccNotifTop,#ccProfileTop{white-space:nowrap}.cc-count{display:inline-flex;min-width:17px;height:17px;border-radius:999px;align-items:center;justify-content:center;padding:0 4px;margin-left:4px;background:#ad2831;color:#fff;font-size:9px;font-weight:900}.cc-notif-list{display:grid;gap:9px}.cc-notif{padding:12px;border:1px solid #e2e7ec;border-radius:12px;background:#fff}.cc-notif.unread{border-color:#bfd0e1;background:#f8fbff}.cc-notif b{display:block;font-size:13px}.cc-notif p{margin:4px 0;color:#5f6b77;font-size:12px}.cc-notif small{color:#8a949e;font-size:10px}.cc-notif-actions{display:flex;gap:6px;margin-top:9px}.cc-notif-actions button{padding:6px 10px}.cc-notif-actions .accept{background:#1d3557;color:#fff;border-color:#1d3557}.cc-notif-actions .decline{color:#9b3d45}.cc-pending-tag{display:inline-block;margin-left:5px;font-size:9px;font-weight:800;color:#8a641d;background:#fff4d8;border-radius:999px;padding:2px 6px}.cc-messages-layout{display:grid;grid-template-columns:240px minmax(0,1fr);gap:14px;min-height:520px}.cc-peer-list{border:1px solid #e1e6eb;border-radius:14px;background:#fff;padding:8px;display:grid;align-content:start;gap:4px}.cc-peer{width:100%;border:0;background:transparent;text-align:left;padding:10px;border-radius:9px;font-weight:700;color:#33404c}.cc-peer.active,.cc-peer:hover{background:#eef3f7}.cc-chat{border:1px solid #e1e6eb;border-radius:14px;background:#fff;display:flex;flex-direction:column;min-height:520px;overflow:hidden}.cc-chat-head{padding:13px 15px;border-bottom:1px solid #edf0f3;font-weight:800}.cc-message-list{padding:14px;display:flex;flex-direction:column;gap:8px;overflow:auto;flex:1}.cc-bubble{max-width:78%;padding:9px 11px;border-radius:13px;background:#f0f3f6;align-self:flex-start}.cc-bubble.mine{background:#1d3557;color:#fff;align-self:flex-end}.cc-bubble p{margin:0;white-space:pre-wrap;word-break:break-word;font-size:13px}.cc-bubble small{display:block;margin-top:4px;font-size:9px;opacity:.7}.cc-compose{display:grid;grid-template-columns:1fr auto;gap:8px;padding:11px;border-top:1px solid #edf0f3}.cc-compose textarea{min-height:44px;max-height:110px;resize:vertical}.cc-empty-chat{margin:auto;color:#8a949e;font-size:13px}.cc-mobile-dock{display:none}.top-actions #userBadge{display:none!important}
@media(max-width:700px){body{padding-bottom:72px!important}.cc-messages-layout{grid-template-columns:1fr;min-height:calc(100vh - 230px)}.cc-peer-list{display:flex;overflow-x:auto;gap:4px}.cc-peer{width:auto;white-space:nowrap}.cc-chat{min-height:420px}.cc-mobile-dock{position:fixed;z-index:90;left:0;right:0;bottom:0;height:62px;padding-bottom:env(safe-area-inset-bottom);display:grid;grid-template-columns:repeat(3,1fr);background:rgba(255,255,255,.97);border-top:1px solid #dfe5eb;box-shadow:0 -3px 16px rgba(29,53,87,.06)}.cc-mobile-dock button{border:0;background:transparent;color:#6d7884;font-size:11px;font-weight:800;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px}.cc-mobile-dock button.active{color:#1d3557}.cc-mobile-dock .cc-dock-icon{font-size:19px;line-height:1}.top-actions{gap:5px!important}.top-actions .ghost{padding:6px 7px!important;font-size:11px!important}#ccNotifTop,#ccProfileTop{min-width:auto!important}.cc-notif-modal .modal-card{max-height:82vh;overflow:auto}}
`;document.head.appendChild(s)}
function ccInstallUi(){
  const ta=document.querySelector('.top-actions');
  if(ta&&!document.querySelector('#ccNotifTop')){const n=document.createElement('button');n.id='ccNotifTop';n.type='button';n.className='ghost hidden';n.innerHTML='알림 <span id="ccNotifBadge" class="cc-count hidden">0</span>';const p=document.createElement('button');p.id='ccProfileTop';p.type='button';p.className='ghost hidden';p.textContent='프로필';const logout=document.querySelector('#logoutBtn');ta.insertBefore(n,logout);ta.insertBefore(p,logout);n.onclick=()=>{ccOpen('ccNotifModal');ccLoadNotifications()};p.onclick=()=>ccSwitch('profile')}
  if(!document.querySelector('#ccNotifModal'))document.body.insertAdjacentHTML('beforeend',`<div id="ccNotifModal" class="modal hidden cc-notif-modal" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">NOTIFICATIONS</div><h2>알림</h2><p class="muted">프로젝트 초대와 할 일 배정을 여기서 수락·거절합니다.</p></div><button id="ccNotifClose" class="icon-btn" type="button">×</button></div><div id="ccNotifList" class="cc-notif-list"></div></div></div>`);
  document.querySelector('#ccNotifClose').onclick=()=>ccClose('ccNotifModal');
  const nav=document.querySelector('.app-nav');if(nav&&!nav.querySelector('[data-view="messages"]')){const b=document.createElement('button');b.className='nav-btn';b.dataset.view='messages';b.type='button';b.textContent='메시지';const team=nav.querySelector('[data-view="team"]');team?.insertAdjacentElement('beforebegin',b);b.onclick=()=>ccSwitch('messages')}
  if(!document.querySelector('#messagesView'))document.querySelector('#appView')?.insertAdjacentHTML('beforeend',`<section id="messagesView" class="view-panel hidden"><div class="section-head"><div><h2>메시지</h2><p>팀원에게 직접 메시지를 보냅니다.</p></div></div><div class="cc-messages-layout"><aside id="ccPeerList" class="cc-peer-list"></aside><section class="cc-chat"><div id="ccChatHead" class="cc-chat-head">대화 상대를 선택하세요.</div><div id="ccMessageList" class="cc-message-list"><div class="cc-empty-chat">대화 상대를 선택하세요.</div></div><div class="cc-compose"><textarea id="ccMessageBody" rows="2" maxlength="4000" placeholder="메시지 입력"></textarea><button id="ccSendMessage" class="primary" type="button">보내기</button></div></section></div></section>`);
  document.querySelector('#ccSendMessage').onclick=ccSendMessage;document.querySelector('#ccMessageBody').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ccSendMessage()}});
  if(!document.querySelector('#ccMobileDock'))document.body.insertAdjacentHTML('beforeend',`<nav id="ccMobileDock" class="cc-mobile-dock"><button data-cc-view="home" class="active" type="button"><span class="cc-dock-icon">⌂</span><span>홈</span></button><button data-cc-view="messages" type="button"><span class="cc-dock-icon">✉</span><span>메시지 <i id="ccMsgBadge" class="cc-count hidden">0</i></span></button><button data-cc-view="profile" type="button"><span class="cc-dock-icon">○</span><span>프로필</span></button></nav>`);
  document.querySelectorAll('#ccMobileDock [data-cc-view]').forEach(b=>b.onclick=()=>ccSwitch(b.dataset.ccView));
  const stat=document.querySelector('#statUnread')?.closest('button');if(stat)stat.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();ccOpen('ccNotifModal');ccLoadNotifications()},true);
}
function ccShowLoggedUi(){document.querySelector('#ccNotifTop')?.classList.remove('hidden');document.querySelector('#ccProfileTop')?.classList.remove('hidden')}
async function ccLoadNotifications(){if(!ccUser)return;try{const [notes,invs,tasks]=await Promise.all([ccApi('/rest/v1/app_notifications?user_id=eq.'+ccUser.id+'&select=*&order=created_at.desc&limit=50'),ccApi('/rest/v1/app_project_invitations?user_id=eq.'+ccUser.id+'&select=id,project_id,role,status,created_at'),ccApi('/rest/v1/app_tasks?assignee_id=eq.'+ccUser.id+'&select=id,title,assignment_status,created_by')]);const im=new Map(invs.map(x=>[x.id,x])),tm=new Map(tasks.map(x=>[x.id,x]));const unread=notes.filter(n=>!n.read_at).length;const badge=document.querySelector('#ccNotifBadge');badge.textContent=unread>99?'99+':String(unread);badge.classList.toggle('hidden',!unread);const stat=document.querySelector('#statUnread');if(stat)stat.textContent=unread;const box=document.querySelector('#ccNotifList');if(box)box.innerHTML=notes.length?notes.map(n=>ccNotifCard(n,im,tm)).join(''):'<div class="empty compact">알림이 없습니다.</div>';ccRenderHomeNotifications(notes,im,tm)}catch(e){const box=document.querySelector('#ccNotifList');if(box)box.innerHTML=`<div class="status error">${ccEsc(e.message||String(e))}</div>`}}
function ccNotifCard(n,im,tm){let actions='';if(n.kind==='project_invite'){const i=im.get(n.related_id);if(i?.status==='pending')actions=`<div class="cc-notif-actions"><button class="mini accept" data-cc-project-response="accept" data-id="${i.id}">수락</button><button class="mini decline" data-cc-project-response="decline" data-id="${i.id}">거절</button></div>`;else if(i)actions=`<div class="cc-notif-actions"><span class="updated">${i.status==='accepted'?'수락함':i.status==='declined'?'거절함':'취소됨'}</span></div>`}else if(n.kind==='task_assigned'){const t=tm.get(n.related_id);if(t?.assignment_status==='pending')actions=`<div class="cc-notif-actions"><button class="mini accept" data-cc-task-response="accept" data-id="${t.id}">수락</button><button class="mini decline" data-cc-task-response="decline" data-id="${t.id}">거절</button></div>`;else if(t)actions=`<div class="cc-notif-actions"><span class="updated">${t.assignment_status==='accepted'?'수락함':'거절함'}</span></div>`}return `<article class="cc-notif ${n.read_at?'':'unread'}" data-cc-notif="${n.id}"><b>${ccEsc(n.title)}</b>${n.body?`<p>${ccEsc(n.body)}</p>`:''}<small>${ccEsc(ccFmt(n.created_at))}</small>${actions||(!n.read_at?`<div class="cc-notif-actions"><button class="mini" data-cc-read="${n.id}">확인</button></div>`:'')}</article>`}
function ccRenderHomeNotifications(notes,im,tm){const box=document.querySelector('#notifList');if(!box)return;box.innerHTML=notes.slice(0,8).map(n=>`<div class="list-item ${n.read_at?'':'unread'}"><b>${ccEsc(n.title)}</b><span>${ccEsc(n.body||'')}</span><small>${ccEsc(ccFmt(n.created_at))}</small>${n.kind==='project_invite'&&im.get(n.related_id)?.status==='pending'?'<small>알림에서 수락 또는 거절</small>':''}${n.kind==='task_assigned'&&tm.get(n.related_id)?.assignment_status==='pending'?'<small>알림에서 수락 또는 거절</small>':''}</div>`).join('')||'<div class="empty compact">새 알림이 없습니다.</div>'}
async function ccReadNotification(id){await ccApi('/rest/v1/app_notifications?id=eq.'+id,{method:'PATCH',body:{read_at:new Date().toISOString()}});await ccLoadNotifications()}
async function ccRespondProject(id,accept){try{await ccApi('/rest/v1/rpc/app_respond_project_invitation',{method:'POST',body:{p_invitation:id,p_accept:accept}});ccToast(accept?'프로젝트 초대를 수락했습니다.':'프로젝트 초대를 거절했습니다.');await ccRefreshSpaces();await ccLoadNotifications()}catch(e){alert(e.message||String(e))}}
async function ccRespondTask(id,accept){try{await ccApi('/rest/v1/app_tasks?id=eq.'+id,{method:'PATCH',body:{assignment_status:accept?'accepted':'declined',assignment_responded_at:new Date().toISOString(),updated_at:new Date().toISOString()}});const ns=await ccApi('/rest/v1/app_notifications?user_id=eq.'+ccUser.id+'&related_type=eq.task&related_id=eq.'+id+'&read_at=is.null&select=id');if(ns.length)await ccApi('/rest/v1/app_notifications?user_id=eq.'+ccUser.id+'&related_type=eq.task&related_id=eq.'+id+'&read_at=is.null',{method:'PATCH',body:{read_at:new Date().toISOString()}});ccToast(accept?'할 일을 수락했습니다.':'할 일을 거절했습니다.');window.dispatchEvent(new CustomEvent('kptu:tasks-changed'));await ccRenderAcceptedHomeTasks();await ccLoadNotifications()}catch(e){alert(e.message||String(e))}}
async function ccRenderAcceptedHomeTasks(){if(!ccUser||!ccWorkspace)return;try{const rows=await ccApi('/rest/v1/app_tasks?workspace_id=eq.'+ccWorkspace+'&assignee_id=eq.'+ccUser.id+'&assignment_status=eq.accepted&status=neq.done&select=id,title,project_id,due_at&order=due_at.asc.nullslast,created_at.desc');const box=document.querySelector('#myTaskMini');if(box)box.innerHTML=rows.slice(0,6).map(t=>`<div class="list-item"><b>${ccEsc(t.title)}</b><span>${ccEsc(ccSpaces.find(x=>x.id===t.project_id)?.name||'일반 업무')}${t.due_at?' · '+ccFmt(t.due_at):''}</span></div>`).join('')||'<div class="empty compact">미완료 업무가 없습니다.</div>';const stat=document.querySelector('#statMyTasks');if(stat)stat.textContent=rows.length;const pending=await ccApi('/rest/v1/app_tasks?workspace_id=eq.'+ccWorkspace+'&assignee_id=eq.'+ccUser.id+'&assignment_status=in.(pending,declined)&select=id');pending.forEach(t=>document.querySelector(`[data-tl-task-row="${CSS.escape(t.id)}"]`)?.remove())}catch(_){} }
async function ccUnreadMessages(){if(!ccUser)return 0;try{const rows=await ccApi('/rest/v1/app_direct_messages?workspace_id=eq.'+ccWorkspace+'&recipient_id=eq.'+ccUser.id+'&read_at=is.null&select=id');const n=rows.length,b=document.querySelector('#ccMsgBadge');if(b){b.textContent=n>99?'99+':String(n);b.classList.toggle('hidden',!n)}return n}catch{return 0}}
function ccRenderPeers(){const box=document.querySelector('#ccPeerList');if(!box)return;const peers=ccMembers.filter(m=>m.user_id!==ccUser.id);box.innerHTML=peers.length?peers.map(m=>`<button class="cc-peer ${ccPeer===m.user_id?'active':''}" data-cc-peer="${m.user_id}" type="button">${ccEsc(ccName(m.user_id))}</button>`).join(''):'<div class="empty compact">다른 팀원이 없습니다.</div>'}
async function ccLoadConversation(){if(!ccUser||!document.querySelector('#messagesView'))return;ccRenderPeers();if(!ccPeer){document.querySelector('#ccChatHead').textContent='대화 상대를 선택하세요.';document.querySelector('#ccMessageList').innerHTML='<div class="cc-empty-chat">대화 상대를 선택하세요.</div>';return}try{const or=`(and(sender_id.eq.${ccUser.id},recipient_id.eq.${ccPeer}),and(sender_id.eq.${ccPeer},recipient_id.eq.${ccUser.id}))`;const rows=await ccApi('/rest/v1/app_direct_messages?workspace_id=eq.'+ccWorkspace+'&or='+encodeURIComponent(or)+'&select=*&order=created_at.asc');document.querySelector('#ccChatHead').textContent=ccName(ccPeer);const box=document.querySelector('#ccMessageList');box.innerHTML=rows.length?rows.map(m=>`<div class="cc-bubble ${m.sender_id===ccUser.id?'mine':''}"><p>${ccEsc(m.body)}</p><small>${ccEsc(ccFmt(m.created_at))}</small></div>`).join(''):'<div class="cc-empty-chat">아직 메시지가 없습니다.</div>';box.scrollTop=box.scrollHeight;await ccApi('/rest/v1/app_direct_messages?workspace_id=eq.'+ccWorkspace+'&sender_id=eq.'+ccPeer+'&recipient_id=eq.'+ccUser.id+'&read_at=is.null',{method:'PATCH',body:{read_at:new Date().toISOString()}});await ccUnreadMessages()}catch(e){document.querySelector('#ccMessageList').innerHTML=`<div class="status error">${ccEsc(e.message||String(e))}</div>`}}
async function ccSendMessage(){const body=document.querySelector('#ccMessageBody')?.value.trim()||'';if(!ccPeer)return ccToast('대화 상대를 선택해 주세요.');if(!body)return;const btn=document.querySelector('#ccSendMessage');btn.disabled=true;try{await ccApi('/rest/v1/app_direct_messages',{method:'POST',body:{workspace_id:ccWorkspace,sender_id:ccUser.id,recipient_id:ccPeer,body}});document.querySelector('#ccMessageBody').value='';await ccLoadConversation()}catch(e){alert(e.message||String(e))}finally{btn.disabled=false}}
async function ccRefreshSpaces(){ccSpaces=await ccApi('/rest/v1/app_spaces?workspace_id=eq.'+ccWorkspace+'&select=id,name,parent_id,status,owner_id,visibility,sort_order')}
async function ccAugmentProjectAccess(){if(!ccCurrentProject)return;try{const pending=await ccApi('/rest/v1/app_project_invitations?project_id=eq.'+ccCurrentProject+'&status=eq.pending&select=id,user_id,role');for(const i of pending){const cb=document.querySelector(`#paPeople [data-pa-user="${CSS.escape(i.user_id)}"]`),sel=document.querySelector(`#paPeople [data-pa-role="${CSS.escape(i.user_id)}"]`);if(cb){cb.checked=true;if(sel){sel.disabled=false;sel.value=i.role}const row=cb.closest('.pa-person');if(row&&!row.querySelector('.cc-pending-tag'))cb.closest('label')?.insertAdjacentHTML('beforeend','<span class="cc-pending-tag">초대 대기</span>')}}const btn=document.querySelector('#paSave');if(btn)btn.textContent='초대·권한 저장'}catch(_){} }
async function ccSaveProjectAccess(e){const btn=e.target.closest('#paSave');if(!btn||!ccCurrentProject)return false;e.preventDefault();e.stopImmediatePropagation();const st=document.querySelector('#paStatus');st.textContent='저장 중…';st.className='status';btn.disabled=true;try{await ccApi('/rest/v1/app_spaces?id=eq.'+ccCurrentProject,{method:'PATCH',body:{visibility:document.querySelector('#paVisibility')?.value||'restricted'}});const [members,pending]=await Promise.all([ccApi('/rest/v1/app_space_members?project_id=eq.'+ccCurrentProject+'&select=user_id,role'),ccApi('/rest/v1/app_project_invitations?project_id=eq.'+ccCurrentProject+'&status=eq.pending&select=id,user_id,role')]);const selected=new Map([...document.querySelectorAll('#paPeople [data-pa-user]:checked')].map(cb=>[cb.dataset.paUser,document.querySelector(`#paPeople [data-pa-role="${CSS.escape(cb.dataset.paUser)}"]`)?.value||'view']));for(const m of members){if(!selected.has(m.user_id))await ccApi('/rest/v1/app_space_members?project_id=eq.'+ccCurrentProject+'&user_id=eq.'+m.user_id,{method:'DELETE'});else if(selected.get(m.user_id)!==m.role)await ccApi('/rest/v1/app_space_members?project_id=eq.'+ccCurrentProject+'&user_id=eq.'+m.user_id,{method:'PATCH',body:{role:selected.get(m.user_id)}})}for(const i of pending){if(!selected.has(i.user_id))await ccApi('/rest/v1/app_project_invitations?id=eq.'+i.id,{method:'PATCH',body:{status:'cancelled',updated_at:new Date().toISOString()}});else if(selected.get(i.user_id)!==i.role)await ccApi('/rest/v1/app_project_invitations?id=eq.'+i.id,{method:'PATCH',body:{role:selected.get(i.user_id),updated_at:new Date().toISOString()}})}const existing=new Set([...members.map(x=>x.user_id),...pending.map(x=>x.user_id)]);const news=[...selected].filter(([uid])=>!existing.has(uid)).map(([user_id,role])=>({workspace_id:ccWorkspace,project_id:ccCurrentProject,user_id,role,invited_by:ccUser.id,status:'pending'}));if(news.length)await ccApi('/rest/v1/app_project_invitations',{method:'POST',body:news});st.textContent=news.length?`${news.length}명에게 프로젝트 초대를 보냈습니다.`:'권한을 저장했습니다.';st.className='status ok';await ccAugmentProjectAccess();return true}catch(err){st.textContent=err.message||String(err);st.className='status error';return true}finally{btn.disabled=false}}
async function ccCreateProject(e){const btn=e.target.closest('#saveProjectBtn');if(!btn)return false;e.preventDefault();e.stopImmediatePropagation();const name=document.querySelector('#newProjectName')?.value.trim()||'',st=document.querySelector('#projectCreateStatus');if(!name){st.textContent='프로젝트명을 입력해 주세요.';st.className='status error';return true}btn.disabled=true;st.textContent='저장 중…';st.className='status';try{const parent=document.querySelector('#newProjectParent')?.value||null;if(parent&&ccSpaces.find(x=>x.id===parent)?.parent_id)throw new Error('하위 프로젝트 아래에는 추가 하위 프로젝트를 만들 수 없습니다.');const max=Math.max(0,...ccSpaces.map(x=>Number(x.sort_order)||0));const rows=await ccApi('/rest/v1/app_spaces',{method:'POST',body:{workspace_id:ccWorkspace,parent_id:parent,slug:'project-'+Date.now().toString(36),name,description:document.querySelector('#newProjectDescription')?.value.trim()||null,sort_order:max+10,created_by:ccUser.id,owner_id:ccUser.id,status:'active',visibility:document.querySelector('#newProjectVisibility')?.value||'restricted'},prefer:'return=representation'});const p=rows[0];const invites=[...document.querySelectorAll('#newProjectPeople [data-pa-user]:checked')].map(cb=>({workspace_id:ccWorkspace,project_id:p.id,user_id:cb.dataset.paUser,role:document.querySelector(`#newProjectPeople [data-pa-role="${CSS.escape(cb.dataset.paUser)}"]`)?.value||'view',invited_by:ccUser.id,status:'pending'}));if(invites.length)await ccApi('/rest/v1/app_project_invitations',{method:'POST',body:invites});st.textContent=invites.length?`프로젝트를 만들고 ${invites.length}명에게 초대를 보냈습니다.`:'프로젝트를 만들었습니다.';st.className='status ok';setTimeout(()=>location.reload(),350);return true}catch(err){st.textContent=err.message||String(err);st.className='status error';return true}finally{btn.disabled=false}}
function ccBind(){document.addEventListener('click',async e=>{const peer=e.target.closest('[data-cc-peer]');if(peer){ccPeer=peer.dataset.ccPeer;ccRenderPeers();await ccLoadConversation();return}const pr=e.target.closest('[data-cc-project-response]');if(pr){await ccRespondProject(pr.dataset.id,pr.dataset.ccProjectResponse==='accept');return}const tr=e.target.closest('[data-cc-task-response]');if(tr){await ccRespondTask(tr.dataset.id,tr.dataset.ccTaskResponse==='accept');return}const rd=e.target.closest('[data-cc-read]');if(rd){await ccReadNotification(rd.dataset.ccRead);return}const pc=e.target.closest('[data-project]');if(pc?.dataset.project){ccCurrentProject=pc.dataset.project}if(e.target.closest('#projectAccessBtn'))setTimeout(ccAugmentProjectAccess,140);if(e.target.closest('#paSave')){await ccSaveProjectAccess(e);return}if(e.target.closest('#saveProjectBtn')){await ccCreateProject(e);return}},true)}
async function ccBoot(){ccInstallStyle();if(!(await ccContext()))return;ccInstallUi();ccShowLoggedUi();ccBind();ccRenderPeers();await Promise.all([ccLoadNotifications(),ccUnreadMessages(),ccRenderAcceptedHomeTasks()]);clearInterval(ccTimer);ccTimer=setInterval(async()=>{if(document.hidden)return;await ccUnreadMessages();if(!document.querySelector('#ccNotifModal')?.classList.contains('hidden'))await ccLoadNotifications();if(!document.querySelector('#messagesView')?.classList.contains('hidden'))await ccLoadConversation()},12000);window.addEventListener('focus',()=>{ccLoadNotifications();ccUnreadMessages();ccRenderAcceptedHomeTasks()})}
setTimeout(ccBoot,0);