let ccUser=null,ccWorkspace=null,ccRole=null,ccMembers=[],ccProfiles=[],ccPeer=null,ccTimer=null,ccBound=false,ccFocusBound=false,ccBooting=null;
function ccRuntime(){const rt=window.KPTURuntime;if(!rt?.session||!rt?.api)throw new Error('공용 런타임을 불러오지 못했습니다.');return rt}
async function ccApi(path,options={}){return ccRuntime().api(path,options)}
function ccEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ccName(id){return ccProfiles.find(x=>x.user_id===id)?.display_name||id?.slice(0,8)||'팀원'}
function ccFmt(v){return v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}
function ccToast(msg){const t=document.querySelector('#toast');if(t){t.textContent=msg;t.classList.remove('hidden');clearTimeout(ccToast.t);ccToast.t=setTimeout(()=>t.classList.add('hidden'),2200)}}
function ccSyncDock(view){document.querySelectorAll('#ccMobileDock [data-cc-view]').forEach(x=>x.classList.toggle('active',x.dataset.ccView===view))}
function ccSwitch(view){if(window.KPTURouter?.go){window.KPTURouter.go(view,{source:'collaboration'});return}document.querySelectorAll('#appView .view-panel').forEach(x=>x.classList.toggle('hidden',x.id!==view+'View'));document.querySelectorAll('.app-nav .nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===view));ccSyncDock(view);window.scrollTo({top:0,behavior:'instant'})}
async function ccContext(){const rt=ccRuntime();if(!(await rt.session.ensure()))return false;ccUser=await rt.api('/auth/v1/user');if(!ccUser?.id)return false;const ms=await rt.api('/rest/v1/app_workspace_members?user_id=eq.'+ccUser.id+'&select=workspace_id,role&limit=1');if(!ms?.length)return false;ccWorkspace=ms[0].workspace_id;ccRole=ms[0].role;[ccMembers,ccProfiles]=await Promise.all([rt.api('/rest/v1/app_workspace_members?workspace_id=eq.'+ccWorkspace+'&select=user_id,role'),rt.api('/rest/v1/app_profiles?select=user_id,display_name,job_title')]);return true}
function ccInstallUi(){const nav=document.querySelector('.app-nav');if(nav&&!nav.querySelector('[data-view="messages"]')){const b=document.createElement('button');b.className='nav-btn';b.dataset.view='messages';b.type='button';b.textContent='메시지';const team=nav.querySelector('[data-view="team"]');team?.insertAdjacentElement('beforebegin',b)}if(!document.querySelector('#messagesView'))document.querySelector('#appView')?.insertAdjacentHTML('beforeend',`<section id="messagesView" class="view-panel hidden"><div class="section-head"><div><h2>메시지</h2><p>팀원에게 직접 메시지를 보냅니다.</p></div></div><div class="cc-messages-layout"><aside id="ccPeerList" class="cc-peer-list"></aside><section class="cc-chat"><div id="ccChatHead" class="cc-chat-head">대화 상대를 선택하세요.</div><div id="ccMessageList" class="cc-message-list"><div class="cc-empty-chat">대화 상대를 선택하세요.</div></div><div class="cc-compose"><textarea id="ccMessageBody" rows="2" maxlength="4000" placeholder="메시지 입력"></textarea><button id="ccSendMessage" class="primary" type="button">보내기</button></div></section></div></section>`);const send=document.querySelector('#ccSendMessage');if(send&&send.dataset.ccBound!=='1'){send.dataset.ccBound='1';send.onclick=ccSendMessage}const body=document.querySelector('#ccMessageBody');if(body&&body.dataset.ccBound!=='1'){body.dataset.ccBound='1';body.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ccSendMessage()}})}if(!document.querySelector('#ccMobileDock'))document.body.insertAdjacentHTML('beforeend',`<nav id="ccMobileDock" class="cc-mobile-dock"><button data-cc-view="home" class="active" type="button"><span class="cc-dock-icon">⌂</span><span>홈</span></button><button data-cc-view="messages" type="button"><span class="cc-dock-icon">✉</span><span>메시지 <i id="ccMsgBadge" class="cc-count hidden">0</i></span></button><button data-cc-view="profile" type="button"><span class="cc-dock-icon">○</span><span>프로필</span></button></nav>`);const current=window.KPTURouter?.current;if(current)window.KPTURouter.keepActiveNavigationVisible(current,{behavior:'auto'})}
async function ccUnreadMessages(){if(!ccUser)return 0;try{const rows=await ccApi('/rest/v1/app_direct_messages?workspace_id=eq.'+ccWorkspace+'&recipient_id=eq.'+ccUser.id+'&read_at=is.null&select=id');const n=rows.length,b=document.querySelector('#ccMsgBadge');if(b){b.textContent=n>99?'99+':String(n);b.classList.toggle('hidden',!n)}return n}catch{return 0}}
function ccRenderPeers(){const box=document.querySelector('#ccPeerList');if(!box||!ccUser)return;const peers=ccMembers.filter(m=>m.user_id!==ccUser.id);box.innerHTML=peers.length?peers.map(m=>`<button class="cc-peer ${ccPeer===m.user_id?'active':''}" data-cc-peer="${m.user_id}" type="button">${ccEsc(ccName(m.user_id))}</button>`).join(''):'<div class="empty compact">다른 팀원이 없습니다.</div>';window.dispatchEvent(new CustomEvent('kptu:collaboration-peers-rendered'))}
async function ccLoadConversation(){if(!ccUser||!document.querySelector('#messagesView'))return;ccRenderPeers();if(!ccPeer){document.querySelector('#ccChatHead').textContent='대화 상대를 선택하세요.';document.querySelector('#ccMessageList').innerHTML='<div class="cc-empty-chat">대화 상대를 선택하세요.</div>';return}try{const or=`(and(sender_id.eq.${ccUser.id},recipient_id.eq.${ccPeer}),and(sender_id.eq.${ccPeer},recipient_id.eq.${ccUser.id}))`;const rows=await ccApi('/rest/v1/app_direct_messages?workspace_id=eq.'+ccWorkspace+'&or='+encodeURIComponent(or)+'&select=*&order=created_at.asc');document.querySelector('#ccChatHead').textContent=ccName(ccPeer);const box=document.querySelector('#ccMessageList');box.innerHTML=rows.length?rows.map(m=>`<div class="cc-bubble ${m.sender_id===ccUser.id?'mine':''}"><p>${ccEsc(m.body)}</p><small>${ccEsc(ccFmt(m.created_at))}</small></div>`).join(''):'<div class="cc-empty-chat">아직 메시지가 없습니다.</div>';box.scrollTop=box.scrollHeight;await ccApi('/rest/v1/app_direct_messages?workspace_id=eq.'+ccWorkspace+'&sender_id=eq.'+ccPeer+'&recipient_id=eq.'+ccUser.id+'&read_at=is.null',{method:'PATCH',body:{read_at:new Date().toISOString()}});await ccUnreadMessages()}catch(e){document.querySelector('#ccMessageList').innerHTML=`<div class="status error">${ccEsc(e.message||String(e))}</div>`}}
async function ccSendMessage(){const body=document.querySelector('#ccMessageBody')?.value.trim()||'';if(!ccPeer)return ccToast('대화 상대를 선택해 주세요.');if(!body)return;const btn=document.querySelector('#ccSendMessage');if(btn)btn.disabled=true;try{await ccApi('/rest/v1/app_direct_messages',{method:'POST',body:{workspace_id:ccWorkspace,sender_id:ccUser.id,recipient_id:ccPeer,body}});document.querySelector('#ccMessageBody').value='';await ccLoadConversation()}catch(e){alert(e.message||String(e))}finally{if(btn)btn.disabled=false}}
function ccBind(){if(ccBound)return;ccBound=true;document.addEventListener('click',async e=>{const peer=e.target.closest?.('[data-cc-peer]');if(peer){ccPeer=peer.dataset.ccPeer;ccRenderPeers();await ccLoadConversation();return}const dock=e.target.closest?.('[data-cc-view]');if(dock)ccSwitch(dock.dataset.ccView)});if(window.KPTURouter?.on){window.KPTURouter.on('messages',()=>{ccSyncDock('messages');ccLoadConversation()});window.KPTURouter.on('home',()=>ccSyncDock('home'));window.KPTURouter.on('profile',()=>ccSyncDock('profile'))}}
function ccReset(){ccUser=null;ccWorkspace=null;ccRole=null;ccMembers=[];ccProfiles=[];ccPeer=null;clearInterval(ccTimer);ccTimer=null;document.querySelector('#ccMsgBadge')?.classList.add('hidden')}
async function ccBoot(){if(ccBooting)return ccBooting;ccBooting=(async()=>{if(!(await ccContext()))return false;ccInstallUi();ccBind();ccRenderPeers();await ccUnreadMessages();clearInterval(ccTimer);ccTimer=setInterval(async()=>{if(document.hidden)return;await ccUnreadMessages();if(!document.querySelector('#messagesView')?.classList.contains('hidden'))await ccLoadConversation()},12000);if(!ccFocusBound){ccFocusBound=true;window.addEventListener('focus',()=>{if(!ccUser)return;ccUnreadMessages();if(!document.querySelector('#messagesView')?.classList.contains('hidden'))ccLoadConversation()})}return true})().catch(e=>{console.error('collaboration init',e);return false}).finally(()=>{ccBooting=null});return ccBooting}
window.addEventListener('kptu:session-changed',e=>{if(e.detail?.session)queueMicrotask(ccBoot);else ccReset()});
window.__KPTU_COLLABORATION_READY__=ccBoot();
