(()=>{
'use strict';
if(window.__KPTU_GOOGLE_TASKS__)return;
window.__KPTU_GOOGLE_TASKS__=true;
const rt=window.KPTURuntime;let loadingEpoch=-1,lastTasks=[],taskLists=[],cacheOwnerId='',sessionEpoch=0,editing=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const endpoint=action=>`/functions/v1/google-tasks?action=${encodeURIComponent(action)}`;
const currentOwner=()=>rt?.session?.read()?.user?.id||'';
const stillCurrent=(epoch,owner)=>epoch===sessionEpoch&&owner&&currentOwner()===owner;
const due=v=>{if(!v)return'기한 미정';const raw=String(v).slice(0,10),d=new Date(raw+'T00:00:00');return Number.isNaN(d.getTime())?'기한 미정':d.toLocaleDateString('ko-KR',{month:'numeric',day:'numeric',weekday:'short'})};
function section(){let sec=document.querySelector('#gtTaskSection');if(sec)return sec;const taskList=document.querySelector('#taskList');if(!taskList)return null;sec=document.createElement('section');sec.id='gtTaskSection';sec.className='tl-task-section';sec.innerHTML='<div class="gt-head"><div class="gt-head-left"><h3>Google 할 일</h3><span class="gt-source">G</span><span class="gt-note">Google Tasks 원본과 직접 동기화</span></div><div class="gt-actions"><label class="gt-completed-toggle"><input type="checkbox" data-gt-show-completed> 완료 포함</label><button class="mini" type="button" data-gt-add>+ Google 할 일</button><button class="mini gt-refresh" type="button" data-gt-refresh>새로고침</button></div></div><div id="gtTaskBody" class="gt-status">불러오는 중…</div>';taskList.insertAdjacentElement('afterend',sec);sec.querySelector('[data-gt-refresh]').onclick=()=>load(true);sec.querySelector('[data-gt-add]').onclick=()=>openEditor();sec.querySelector('[data-gt-show-completed]').onchange=()=>renderTasks(lastTasks);return sec}
function ensureModal(){let m=document.querySelector('#gtTaskModal');if(m)return m;document.body.insertAdjacentHTML('beforeend',`<div id="gtTaskModal" class="modal hidden" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="gtTaskHeading"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">GOOGLE TASKS</div><h2 id="gtTaskHeading">Google 할 일</h2></div><button class="icon-btn" data-gt-close type="button" aria-label="닫기">×</button></div><label>할 일<input id="gtEditTitle" type="text"></label><label>목록<select id="gtEditList"></select></label><label>기한<input id="gtEditDue" type="date"></label><label>메모<textarea id="gtEditNotes" rows="4"></textarea></label><div class="gt-modal-actions"><button id="gtDeleteBtn" class="ghost tl-danger hidden" type="button">삭제</button><button id="gtSaveBtn" class="primary" type="button">저장</button></div><div id="gtEditStatus" class="status"></div></div></div>`);m=document.querySelector('#gtTaskModal');m.querySelector('[data-gt-close]').onclick=closeEditor;document.querySelector('#gtSaveBtn').onclick=saveEditor;document.querySelector('#gtDeleteBtn').onclick=deleteEditor;return m}
function closeEditor(){const m=document.querySelector('#gtTaskModal');if(!m)return;m.classList.add('hidden');m.setAttribute('aria-hidden','true');window.KPTUA11y?.dialog.deactivate(m,{restoreFocus:true,fallbackFocus:'#gtTaskSection h3'});editing=null}
async function ensureLists(){if(taskLists.length)return taskLists;const d=await rt.api(endpoint('lists'));taskLists=d?.lists||[];return taskLists}
async function openEditor(task=null){const m=ensureModal(),lists=await ensureLists();editing=task;document.querySelector('#gtTaskHeading').textContent=task?'Google 할 일 수정':'Google 할 일 추가';document.querySelector('#gtEditTitle').value=task?.title||'';document.querySelector('#gtEditDue').value=task?.due?String(task.due).slice(0,10):'';document.querySelector('#gtEditNotes').value=task?.notes||'';const sel=document.querySelector('#gtEditList');sel.innerHTML=lists.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('');if(task?.taskListId)sel.value=task.taskListId;sel.disabled=!!task;document.querySelector('#gtDeleteBtn').classList.toggle('hidden',!task);document.querySelector('#gtEditStatus').textContent='';m.classList.remove('hidden');m.setAttribute('aria-hidden','false');window.KPTUA11y?.dialog.activate(m,{trigger:document.activeElement,initialFocus:'#gtEditTitle',onRequestClose:closeEditor});document.querySelector('#gtEditTitle').focus()}
async function saveEditor(){const title=document.querySelector('#gtEditTitle').value.trim(),listId=document.querySelector('#gtEditList').value;if(!title)return document.querySelector('#gtEditStatus').textContent='할 일을 입력해 주세요.';const body={action:editing?'update':'create',task_list_id:listId,task_id:editing?.id||null,task_list_title:document.querySelector('#gtEditList').selectedOptions[0]?.textContent||'Google Tasks',title,notes:document.querySelector('#gtEditNotes').value,due:document.querySelector('#gtEditDue').value||null};const b=document.querySelector('#gtSaveBtn');b.disabled=true;try{await rt.api(endpoint(body.action),{method:'POST',body});closeEditor();await load(true)}catch(e){const msg=String(e?.message||e);if(/TASKS_SCOPE_REQUIRED|권한/.test(msg))renderConnect('Google 할 일을 수정하려면 Google 계정을 다시 연결해 주세요.');else document.querySelector('#gtEditStatus').textContent=msg}finally{b.disabled=false}}
async function deleteEditor(){if(!editing||!confirm('이 Google 할 일을 삭제할까요?'))return;try{await rt.api(endpoint('delete'),{method:'POST',body:{action:'delete',task_list_id:editing.taskListId,task_id:editing.id}});closeEditor();await load(true)}catch(e){document.querySelector('#gtEditStatus').textContent=String(e?.message||e)}}
async function toggleTask(task){try{await rt.api(endpoint('toggle'),{method:'POST',body:{action:'toggle',task_list_id:task.taskListId,task_id:task.id,task_list_title:task.taskListTitle,completed:task.status!=='completed'}});await load(true)}catch(e){const msg=String(e?.message||e);if(/TASKS_SCOPE_REQUIRED|권한/.test(msg))renderConnect('Google 할 일을 수정하려면 Google 계정을 다시 연결해 주세요.');else renderError(msg)}}
function renderTasks(tasks){const body=section()?.querySelector('#gtTaskBody');if(!body)return;const showCompleted=!!section()?.querySelector('[data-gt-show-completed]')?.checked,visible=tasks.filter(t=>showCompleted||t.status!=='completed');if(!visible.length){body.className='gt-status';body.innerHTML='표시할 Google 할 일이 없습니다.';return}body.className='gt-list';body.innerHTML=visible.map(t=>`<div class="gt-row ${t.status==='completed'?'completed':''}" data-google-task="${esc(t.id)}"><button class="gt-check" type="button" data-gt-toggle="${esc(t.id)}" aria-label="${t.status==='completed'?'완료 취소':'완료'}">${t.status==='completed'?'✓':''}</button><button class="gt-main" type="button" data-gt-edit="${esc(t.id)}"><b>${esc(t.title||'제목 없음')}</b><div class="gt-meta"><span>${esc(t.taskListTitle||'Google Tasks')}</span><span>${esc(due(t.due))}</span>${t.notes?`<span>${esc(t.notes)}</span>`:''}</div></button></div>`).join('');body.querySelectorAll('[data-gt-toggle]').forEach(b=>b.onclick=()=>toggleTask(lastTasks.find(t=>t.id===b.dataset.gtToggle)));body.querySelectorAll('[data-gt-edit]').forEach(b=>b.onclick=()=>openEditor(lastTasks.find(t=>t.id===b.dataset.gtEdit)))}
function renderConnect(message='Google 할 일을 함께 보려면 Google Tasks 권한을 연결해 주세요.'){const body=section()?.querySelector('#gtTaskBody');if(!body)return;body.className='gt-status';body.innerHTML=`<div>${esc(message)}</div><button class="secondary gt-connect gt-reconnect" type="button" data-gt-connect>Google 할 일 권한 다시 연결</button>`;body.querySelector('[data-gt-connect]').onclick=connect}
function renderError(message){const body=section()?.querySelector('#gtTaskBody');if(body){body.className='gt-status';body.innerHTML=`<span style="color:#a33b45">${esc(message)}</span>`}}
async function connect(){const epoch=sessionEpoch;let owner='';try{if(!rt?.session||!(await rt.session.ensure())||epoch!==sessionEpoch)return;owner=currentOwner();if(!owner)return;const params=new URLSearchParams(location.search),platform=/KPTUAndroid/i.test(navigator.userAgent)||params.get('native')==='android'?'android':'web',d=await rt.api(endpoint('start')+'&platform='+platform);if(!stillCurrent(epoch,owner))return;if(d?.url)location.href=d.url;else throw new Error('Google 권한 연결 주소를 받지 못했습니다.')}catch(e){if(stillCurrent(epoch,owner))renderError(e.message||String(e))}}
async function load(force=false){const epoch=sessionEpoch;if(loadingEpoch===epoch)return;const sec=section();if(!sec)return;if(!rt?.session||!(await rt.session.ensure())||epoch!==sessionEpoch)return;const owner=currentOwner();if(!owner)return;if(!force&&cacheOwnerId===owner&&lastTasks.length){renderTasks(lastTasks);return}loadingEpoch=epoch;const body=sec.querySelector('#gtTaskBody');if(body){body.className='gt-status';body.textContent='Google 할 일을 불러오는 중…'}try{const status=await rt.api(endpoint('status'));if(!stillCurrent(epoch,owner))return;if(status?.needs_reconnect||status?.authorized===false){lastTasks=[];cacheOwnerId=owner;renderConnect(status?.connected?'기존 Google 연결에 Google Tasks 수정 권한이 없습니다. 한 번 다시 연결해 주세요.':'Google 계정을 연결하면 Google 할 일을 함께 관리할 수 있습니다.');return}const d=await rt.api(endpoint('tasks'));if(!stillCurrent(epoch,owner))return;if(d?.needs_reconnect){lastTasks=[];cacheOwnerId=owner;renderConnect(d.warning||'Google Tasks 권한이 없어 다시 연결이 필요합니다.');return}if(d?.error)throw new Error(d.error);lastTasks=d?.tasks||[];cacheOwnerId=owner;renderTasks(lastTasks)}catch(e){if(!stillCurrent(epoch,owner))return;const msg=String(e?.message||e);if(/연결되지|재인증|TASKS_SCOPE_REQUIRED|권한/i.test(msg))renderConnect(msg);else renderError(msg)}finally{if(loadingEpoch===epoch)loadingEpoch=-1}}
async function boot(){section();ensureModal();window.KPTURouter?.on?.('tasks',()=>load(true));window.addEventListener('focus',()=>{if(!document.querySelector('#tasksView')?.classList.contains('hidden'))load(true)});window.addEventListener('kptu:session-changed',e=>{sessionEpoch++;lastTasks=[];taskLists=[];cacheOwnerId='';document.querySelector('#gtTaskSection')?.remove();if(e.detail?.session)queueMicrotask(()=>load(true))});await load(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(console.error),{once:true});else boot().catch(console.error);
})();