(()=>{
  if(window.KPTUGuest)return;
  const rt=window.KPTURuntime;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
  const dateKey=v=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const state={workspace:null,spaces:[],project_updates:[],milestones:[],events:[],tasks:[],meetings:[],documents:[],pages:[],suborganizations:[],suborganization_updates:[],assignees:[],affiliations:[]};
  const empty=msg=>`<div class="empty compact">${esc(msg)}</div>`;
  const projectName=id=>state.spaces.find(x=>x.id===id)?.name||'일반 업무';
  const showOnly=id=>['authView','bootstrapView','appView'].forEach(x=>document.querySelector('#'+x)?.classList.toggle('hidden',x!==id));
  const css=document.createElement('style');css.id='guestBrowseCss';css.textContent=`body.kptu-guest #workspaceRole{color:#657383}.guest-login{white-space:nowrap}.guest-readonly{display:inline-flex;font-size:10px;font-weight:900;color:#48647f;background:#edf3f8;border-radius:999px;padding:4px 8px}.guest-write:after{content:'🔒';font-size:9px;margin-left:4px}.guest-detail{display:grid;gap:12px}.guest-detail-section{border-top:1px solid #edf0f3;padding-top:10px}.guest-detail-section:first-child{border-top:0;padding-top:0}.guest-detail-section h3{font-size:14px;margin:0 0 7px}.guest-pre{white-space:pre-wrap;word-break:break-word;font-size:12px;line-height:1.65;color:#43505d;background:#f7f9fb;border-radius:10px;padding:10px;margin:0}.guest-page-body{white-space:pre-wrap;word-break:break-word;line-height:1.72;font-size:13px}.guest-org-tools{display:grid;grid-template-columns:1.3fr 1fr 1fr;gap:8px;margin-bottom:12px}.guest-org-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.guest-org-card{background:#fff;border:1px solid var(--line);border-radius:13px;padding:13px;text-align:left;color:inherit}.guest-org-card b{display:block;font-size:14px}.guest-org-card span,.guest-org-card small{display:block;color:var(--muted);font-size:11px;margin-top:3px}@media(max-width:760px){.guest-org-tools{grid-template-columns:1fr}.guest-org-grid{grid-template-columns:1fr}.guest-login{padding:7px 10px!important}}`;document.head.appendChild(css);
  function loginView(){showOnly('authView');document.querySelector('#authPreloadStyle')?.remove();document.querySelector('#emailAuthWrap')?.classList.remove('hidden');let back=document.querySelector('#guestBackBtn');if(!back){back=document.createElement('button');back.id='guestBackBtn';back.type='button';back.className='secondary wide';back.textContent='로그인 없이 계속 둘러보기';document.querySelector('#authStatus')?.insertAdjacentElement('afterend',back);back.onclick=()=>{showOnly('appView');window.__KPTU_MARK_APP_UI_READY__?.()}}document.querySelector('#authEmail')?.focus()}
  function setupShell(){document.body.classList.add('kptu-guest');showOnly('appView');const badge=document.querySelector('#userBadge');if(badge){badge.textContent='게스트 · 읽기 전용';badge.classList.remove('hidden')}document.querySelector('#logoutBtn')?.classList.add('hidden');const old=document.querySelector('#emailAuthToggle');if(old&&!old.classList.contains('guest-login')){const b=old.cloneNode(true);old.remove();b.className='secondary guest-login';b.textContent='로그인';document.querySelector('.top-actions')?.appendChild(b);b.onclick=e=>{e.preventDefault();loginView()}}const role=document.querySelector('#workspaceRole');if(role)role.innerHTML='비로그인 열람 모드 · 작성/수정은 로그인 후 가능 <span class="guest-readonly">보기만 가능</span>';document.querySelectorAll('.admin-only').forEach(x=>x.classList.add('hidden'));document.querySelector('[data-view="myspace"]')?.remove();document.querySelector('#myspaceView')?.remove();const tb=document.querySelector('.app-nav [data-view="team"]');if(tb)tb.textContent='산하조직';const th=document.querySelector('#teamView .section-head');if(th)th.innerHTML='<div><h2>산하조직</h2><p>담당자·협의회별로 산하조직 현황을 살펴볼 수 있습니다.</p></div>';document.querySelector('#memberList')?.remove();document.querySelector('#groupList')?.remove();document.querySelectorAll('#teamView .minor-title').forEach(x=>x.remove());document.querySelector('#googleCalendarControls')?.classList.add('hidden');document.querySelector('#googleCalendarList')?.classList.add('hidden');const labels=document.querySelectorAll('#homeView .stat-card span');if(labels[1])labels[1].textContent='미완료 할 일';if(labels[3])labels[3].textContent='산하조직'}
  function bindLoginGate(){['quickTaskBtn','newTaskBtn','homeAddEvent','newEventBtn','newDocumentBtn','newMeetingBtn','newPageBtn','newProjectBtn','googleConnectBtn','inviteBtn','newGroupBtn','quickInviteBtn'].forEach(id=>document.getElementById(id)?.classList.add('guest-write'));document.addEventListener('click',e=>{const b=e.target.closest?.('button,a');if(!b)return;if(b.matches('.guest-write,[data-guest-login]')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loginView()}},true);window.addEventListener('kptu:session-changed',e=>{if(e.detail?.session)location.reload()})}
  async function rpc(name){return rt.api('/rest/v1/rpc/'+name,{method:'POST',body:{},auth:false})}
  async function load(){const [base,projects,facets]=await Promise.all([rpc('app_public_workspace_snapshot'),rpc('app_public_projects_snapshot').catch(()=>({})),rpc('app_public_suborganization_facets').catch(()=>({}))]);Object.assign(state,base||{});if(projects?.spaces)state.spaces=projects.spaces;if(projects?.project_updates)state.project_updates=projects.project_updates;if(projects?.milestones)state.milestones=projects.milestones;state.assignees=facets?.assignees||[];state.affiliations=facets?.affiliations||[]}
  function ensureModal(){if(document.querySelector('#guestDetailModal'))return;document.body.insertAdjacentHTML('beforeend','<div id="guestDetailModal" class="modal hidden" aria-hidden="true"><div class="modal-card medium-card"><div class="modal-head"><div><div class="eyebrow">READ ONLY</div><h2 id="guestDetailTitle"></h2></div><button id="guestDetailClose" class="icon-btn" type="button">×</button></div><div id="guestDetailBody" class="guest-detail"></div></div></div>');document.querySelector('#guestDetailClose').onclick=()=>document.querySelector('#guestDetailModal').classList.add('hidden')}
  function openDetail(title,html){ensureModal();document.querySelector('#guestDetailTitle').textContent=title;document.querySelector('#guestDetailBody').innerHTML=html;const m=document.querySelector('#guestDetailModal');m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}
  window.KPTUGuest={rt,state,esc,fmt,dateKey,todayKey:()=>dateKey(new Date()),empty,projectName,showOnly,loginView,setupShell,bindLoginGate,load,openDetail};
})();