const LU_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const LU_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const LU_SESSION='kptu_collab_session_v1';
let luSession=null,luUser=null,luWorkspace=null,luRole=null,luSpaces=[],luDocuments=[],luUploadEntries=[];
function luRead(){if(window.KPTURuntime?.session)return window.KPTURuntime.session.read();try{return JSON.parse(localStorage.getItem(LU_SESSION)||'null')}catch{return null}}
async function luEnsure(){if(window.KPTURuntime?.session){const ok=await window.KPTURuntime.session.ensure();luSession=window.KPTURuntime.session.read();return ok}luSession=luRead();if(!luSession)return false;if((luSession.expires_at||0)<Math.floor(Date.now()/1000)+60&&luSession.refresh_token){const r=await fetch(LU_SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:LU_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:luSession.refresh_token})});if(!r.ok)return false;const d=await r.json();d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);luSession=d;localStorage.setItem(LU_SESSION,JSON.stringify(d))}return true}
async function luApi(path,{method='GET',body=null,prefer=''}={}){if(window.KPTURuntime?.api)return window.KPTURuntime.api(path,{method,body,prefer});if(!(await luEnsure()))throw new Error('로그인이 필요합니다.');const form=body instanceof FormData,h={apikey:LU_KEY,Authorization:'Bearer '+luSession.access_token};if(!form)h['Content-Type']='application/json';if(prefer)h.Prefer=prefer;const r=await fetch(LU_SB+path,{method,headers:h,body:body===null?null:(form?body:JSON.stringify(body)),cache:'no-store'});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.hint||('요청 실패 '+r.status));return d}
function luEsc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function luSize(n){n=Number(n)||0;if(!n)return'';if(n<1024)return n+'B';if(n<1048576)return(n/1024).toFixed(1)+'KB';return(n/1048576).toFixed(1)+'MB'}
function luProjectName(id){return luSpaces.find(x=>x.id===id)?.name||''}
function luVisibilityLabel(v){return {public:'외부 공개',workspace:'팀 내부',private:'나만 보기'}[v]||'팀 내부'}
function luIsDriveAuthError(e){return /token has been expired or revoked|invalid_grant|Google Drive 토큰 갱신/i.test(String(e?.message||''))}
async function luReconnectDrive(){if(!['owner','admin'].includes(luRole)){alert('Google Drive 연결이 만료됐습니다. 워크스페이스 관리자에게 Drive 재연결을 요청해 주세요.');return false}try{const d=await luApi('/functions/v1/public-policy-drive',{method:'POST',body:{action:'drive-start'}});const url=d?.url||d?.auth_url;if(!url)throw new Error('Google Drive 연결 주소를 받지 못했습니다.');location.href=url;return true}catch(e){alert(e.message||String(e));return false}}
async function luMaybeReconnectDrive(e){if(!luIsDriveAuthError(e))return false;if(!['owner','admin'].includes(luRole))return false;if(!confirm('Google Drive 연결이 만료됐습니다. 지금 관리자 계정을 다시 연결할까요?\n재연결 후 같은 작업을 다시 실행하면 됩니다.'))return false;return await luReconnectDrive()}
function luHandleDriveReturn(){const u=new URL(location.href),result=u.searchParams.get('drive');if(!result)return;if(result==='connected')setTimeout(()=>alert('Google Drive 재연결이 완료됐습니다. 업로드 또는 삭제를 다시 실행해 주세요.'),0);else setTimeout(()=>alert('Google Drive 재연결을 완료하지 못했습니다. 다시 시도해 주세요.'),0);u.searchParams.delete('drive');u.searchParams.delete('reason');history.replaceState({},'',u.pathname+(u.searchParams.toString()?'?'+u.searchParams.toString():'')+u.hash)}

async function luContext(){if(!(await luEnsure()))return false;const shared=window.KPTURuntime?.context?.read?.()||window.__KPTU_BOOT_CONTEXT__;if(shared?.user?.id&&shared?.workspace?.id){luUser=shared.user;luWorkspace=shared.workspace.id;luRole=shared.membership?.role||null}else{luUser=await luApi('/auth/v1/user');if(!luUser?.id)return false;const ms=await luApi('/rest/v1/app_workspace_members?user_id=eq.'+luUser.id+'&select=workspace_id,role&limit=1');if(!ms?.length)return false;luWorkspace=ms[0].workspace_id;luRole=ms[0].role||null}luSpaces=await luApi('/rest/v1/app_spaces?workspace_id=eq.'+luWorkspace+'&select=id,name,status&order=sort_order.asc,created_at.asc');return true}
function luProjectOptions(selected=''){return '<option value="">프로젝트 없음</option>'+luSpaces.filter(s=>s.status!=='archived').map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${luEsc(s.name)}</option>`).join('')}
function luRenderSelectedFiles(){const box=document.querySelector('#librarySelectedFiles');if(!box)return;if(!luUploadEntries.length){box.innerHTML='';return}box.innerHTML=luUploadEntries.map((entry,index)=>{const file=entry.file,state=entry.kind||'pending',label=entry.label||'선택됨';return `<div class="library-selected-file ${state}" data-lu-upload-file="${index}"><div class="library-selected-file-main"><b>${luEsc(file?.name||'파일')}</b><small>${luEsc(luSize(file?.size||0))}</small></div><span class="library-upload-state" data-lu-upload-state>${luEsc(label)}</span></div>`}).join('')+(luUploadEntries.length>1?'<div class="library-multi-note">여러 파일은 각각 별도 자료로 등록되며 자료명은 파일별로 자동 정리됩니다.</div>':'')}
function luSetSelectedFiles(files){luUploadEntries=Array.from(files||[]).map(file=>({file,kind:'pending',label:'선택됨'}));luRenderSelectedFiles()}
function luSetFileStatus(entry,kind,label){entry.kind=kind;entry.label=label;luRenderSelectedFiles()}
function luResetUploadSelection({clearStatus=true}={}){luUploadEntries=[];const input=document.querySelector('#libraryFileInput');if(input)input.value='';luRenderSelectedFiles();if(clearStatus)luSetStatus(document.querySelector('#documentStatus'),'')}
function luEnhanceUpload(){const modal=document.querySelector('#documentModal .modal-card');const title=document.querySelector('#docTitle');if(!modal||!title||document.querySelector('#libraryFileInput'))return;const picker=document.createElement('div');picker.className='library-file-block';picker.innerHTML='<input id="libraryFileInput" class="library-file-input" type="file" multiple><label id="libraryDropzone" class="library-dropzone" for="libraryFileInput" tabindex="0" aria-label="자료 파일 여러 개 선택 또는 끌어놓기"><strong class="library-picker-desktop">파일을 여기로 끌어다 놓거나 클릭하세요</strong><span class="library-picker-mobile library-picker-button">+ 파일 추가</span><span class="library-picker-hint">여러 파일을 한 번에 선택할 수 있습니다.</span></label><div id="librarySelectedFiles" class="library-selected-files" aria-live="polite"></div><p>자료명을 비워두면 파일명을 그대로 쓰지 않고 불필요한 날짜·버전표시를 정리해 제목화합니다. 여러 파일을 선택하면 파일별로 제목을 자동 정리합니다.</p>';title.closest('label')?.insertAdjacentElement('beforebegin',picker);const lab=title.closest('label');if(lab&&lab.firstChild?.nodeType===3)lab.firstChild.nodeValue='자료명 (선택)';const input=picker.querySelector('#libraryFileInput'),zone=picker.querySelector('#libraryDropzone');zone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}});['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();zone.classList.add('dragover')}));['dragleave','dragend'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();e.stopPropagation();zone.classList.remove('dragover')}));zone.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();zone.classList.remove('dragover');const files=Array.from(e.dataTransfer?.files||[]);if(files.length)luSetSelectedFiles(files)});input.addEventListener('change',()=>luSetSelectedFiles(input.files));luRenderSelectedFiles()}
function luSetStatus(st,msg,error=false){if(!st)return;st.textContent=msg||'';st.className='status'+(error?' error':msg?' ok':'');if(error){st.setAttribute('role','alert');st.removeAttribute('aria-live')}else{st.setAttribute('role','status');st.setAttribute('aria-live','polite')}}
function luSetBusy(btn,value){if(!btn)return;btn.disabled=!!value;if(value)btn.setAttribute('aria-busy','true');else btn.removeAttribute('aria-busy')}
async function luUploadOrOriginal(original){const pending=luUploadEntries.filter(entry=>entry.kind!=='success');if(!pending.length)return original?.();const st=document.querySelector('#documentStatus'),btn=document.querySelector('#saveDocumentBtn'),visibility=document.querySelector('#docVisibility')?.value||(document.querySelector('#docProject')?.value?'workspace':'public');if(visibility==='public'&&!confirm('이 자료를 로그인하지 않은 사용자도 볼 수 있도록 외부 공개할까요?\n자료명·분류·출처·날짜·설명과 연결된 공개 링크가 노출됩니다.'))return;luSetBusy(btn,true);let succeeded=0,lastProjectId=null,firstError=null,driveBlocked=false;try{for(let index=0;index<pending.length;index++){const entry=pending[index],file=entry.file;luSetFileStatus(entry,'uploading','업로드 중');luSetStatus(st,`${index+1}/${pending.length} · ${file.name} 업로드 중…`);try{const fd=new FormData();fd.append('file',file);const fields={title:'#docTitle',category:'#docCategory',source:'#docSource',document_date:'#docDate',tags:'#docTags',project_id:'#docProject',description:'#docDescription',visibility:'#docVisibility'};for(const[k,sel]of Object.entries(fields)){if(k==='title'&&luUploadEntries.length>1)continue;const el=document.querySelector(sel),raw=el?.value??'',v=typeof raw==='string'?raw.trim():raw;if(v)fd.append(k,v)}const d=await luApi('/functions/v1/library-files',{method:'POST',body:fd});if(d?.error)throw new Error(d.error||'자료 업로드 실패');succeeded++;lastProjectId=d?.document?.project_id||lastProjectId;luSetFileStatus(entry,'success','완료')}catch(e){if(!firstError)firstError=e;luSetFileStatus(entry,'error','실패 · 다시 시도');if(luIsDriveAuthError(e)){driveBlocked=true;await luMaybeReconnectDrive(e);break}}}if(succeeded){await luLoadDocuments();luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed',{detail:{project_id:lastProjectId}}))}const remaining=luUploadEntries.filter(entry=>entry.kind!=='success');if(remaining.length){const done=luUploadEntries.length-remaining.length,reason=firstError?.message?' · '+firstError.message:'';luSetStatus(st,`${done}개 완료 · ${remaining.length}개 미완료. ${driveBlocked?'Google Drive 재연결 후 다시 시도해 주세요.':'실패한 파일만 다시 시도할 수 있습니다.'}${reason}`,true);return}luSetStatus(st,luUploadEntries.length===1?'등록 완료 · 자동분류 결과는 자료실에서 수정할 수 있습니다.':`${luUploadEntries.length}개 파일 등록 완료 · 자동분류 결과는 자료실에서 수정할 수 있습니다.`);luResetUploadSelection({clearStatus:false});document.querySelector('#documentModal')?.classList.add('hidden')}finally{luSetBusy(btn,false)}}
function luEnsureManageUi(){if(document.querySelector('#libraryManageModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="libraryManageModal" class="modal hidden" aria-hidden="true"><div class="modal-card medium-card"><div class="modal-head"><div><div class="eyebrow">LIBRARY</div><h2>자료 분류 수정</h2><p class="muted">자동분류가 틀린 자료를 직접 수정합니다.</p></div><button id="libraryManageClose" class="icon-btn" type="button">×</button></div><div id="libraryManageList" class="library-manage-list"></div></div></div><div id="libraryEditModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">EDIT METADATA</div><h2>자료 정보 수정</h2></div><button id="libraryEditClose" class="icon-btn" type="button">×</button></div><input id="libraryEditId" type="hidden"><label>자료명<input id="libraryEditTitle" type="text"></label><div class="library-edit-grid"><label>분류<input id="libraryEditCategory" type="text"></label><label>프로젝트<select id="libraryEditProject"></select></label><label>출처<input id="libraryEditSource" type="text"></label><label>문서 날짜<input id="libraryEditDate" type="date"></label></div><label>태그<input id="libraryEditTags" type="text" placeholder="쉼표로 구분"></label><label>공개 범위<select id="libraryEditVisibility"><option value="public">외부 공개</option><option value="workspace">팀 내부</option><option value="private">나만 보기</option></select></label><label>설명<textarea id="libraryEditDescription" rows="4"></textarea></label><button id="libraryEditSave" class="primary wide" type="button">수정 저장</button><div id="libraryEditStatus" class="status"></div></div></div>`);document.querySelector('#libraryManageClose').onclick=()=>luClose('libraryManageModal');document.querySelector('#libraryEditClose').onclick=()=>luClose('libraryEditModal');document.querySelector('#libraryEditSave').onclick=luSaveEdit}
function luOpen(id){const m=document.querySelector('#'+id);m?.classList.remove('hidden');m?.setAttribute('aria-hidden','false')}
function luClose(id){const m=document.querySelector('#'+id);m?.classList.add('hidden');m?.setAttribute('aria-hidden','true')}
async function luLoadDocuments(){if(!luWorkspace)return;luDocuments=await luApi('/rest/v1/app_documents?workspace_id=eq.'+luWorkspace+'&select=*&order=document_date.desc.nullslast,created_at.desc')}
function luRenderLibrary(){const box=document.querySelector('#documentList');if(!box)return;const q=(document.querySelector('#documentSearch')?.value||'').trim().toLowerCase(),pid=document.querySelector('#documentProject')?.value||'all';const rows=luDocuments.filter(d=>(pid==='all'||d.project_id===pid)&&(!q||[d.title,d.file_name,d.source,d.category,(d.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));box.innerHTML=rows.length?rows.map(d=>`<article class="item-card compact-entry" role="button" tabindex="0" data-lu-document="${d.id}"><div class="compact-entry-main"><div class="badges"><span class="badge">${luEsc(d.category||'기타')}</span><span class="badge ${d.visibility==='public'?'published':d.visibility==='private'?'private':'workspace'}">${luEsc(luVisibilityLabel(d.visibility))}</span>${d.project_id?`<span class="badge">${luEsc(luProjectName(d.project_id))}</span>`:''}</div><h3>${luEsc(d.title||d.file_name||'파일')}</h3><p class="compact-entry-meta">${luEsc(d.source||'출처 미기재')}${d.document_date?' · '+luEsc(d.document_date):''}${d.file_size?' · '+luSize(d.file_size):''}</p>${d.description?`<small class="compact-entry-summary">${luEsc(d.description)}</small>`:''}</div><div class="lu-document-actions compact-entry-actions"><button class="mini" type="button" data-lu-toggle-public="${d.id}">${d.visibility==='public'?'공개 해제':'외부 공개'}</button><button class="mini" type="button" data-lu-download="${d.id}">다운로드</button><button class="mini" type="button" data-lu-edit="${d.id}">정보 수정</button><button class="mini danger" type="button" data-lu-delete="${d.id}">삭제</button></div></article>`).join(''):'<div class="empty">자료가 없습니다.</div>'}
async function luOpenDocument(id){const d=luDocuments.find(x=>x.id===id)||await luFetchOne(id);if(d?.drive_url){try{const url=new URL(d.drive_url);if(['https:','http:'].includes(url.protocol)){location.href=url.href;return}}catch{}console.error('invalid document URL',{documentId:id});alert('자료 링크가 올바르지 않습니다.');return}if(d?.file_id){await luDownload(id);return}alert('열 수 있는 파일 링크가 없습니다.')}
async function luDownload(id){try{const d=await luApi('/functions/v1/workspace-drive?action=download-token',{method:'POST',body:{document_id:id}});if(!d?.url)throw new Error('다운로드 주소를 받지 못했습니다.');location.href=d.url}catch(e){alert(e.message||String(e))}}
async function luFetchOne(id){const rows=await luApi('/rest/v1/app_documents?id=eq.'+encodeURIComponent(id)+'&select=*&limit=1');return rows?.[0]||null}
async function luOpenEditById(id){let d=luDocuments.find(x=>x.id===id);if(!d)d=await luFetchOne(id);if(!d)return;luEdit(d)}
function luEdit(d){document.querySelector('#libraryEditId').value=d.id;document.querySelector('#libraryEditTitle').value=d.title||'';document.querySelector('#libraryEditCategory').value=d.category||'';document.querySelector('#libraryEditProject').innerHTML=luProjectOptions(d.project_id||'');document.querySelector('#libraryEditSource').value=d.source||'';document.querySelector('#libraryEditDate').value=d.document_date||'';document.querySelector('#libraryEditTags').value=(d.tags||[]).join(', ');document.querySelector('#libraryEditVisibility').value=['public','workspace','private'].includes(d.visibility)?d.visibility:'workspace';document.querySelector('#libraryEditDescription').value=d.description||'';document.querySelector('#libraryEditStatus').textContent='';luOpen('libraryEditModal')}
async function luSaveEdit(){const id=document.querySelector('#libraryEditId').value,st=document.querySelector('#libraryEditStatus'),visibility=document.querySelector('#libraryEditVisibility').value,current=luDocuments.find(x=>x.id===id);if(visibility==='public'&&current?.visibility!=='public'&&!confirm('이 자료를 로그인하지 않은 사용자도 볼 수 있도록 외부 공개할까요?\n자료명·분류·출처·날짜·설명과 연결된 공개 링크가 노출됩니다.'))return;st.textContent='저장 중…';st.className='status';try{await luApi('/rest/v1/app_documents?id=eq.'+id,{method:'PATCH',body:{title:document.querySelector('#libraryEditTitle').value.trim(),category:document.querySelector('#libraryEditCategory').value.trim()||'기타',project_id:document.querySelector('#libraryEditProject').value||null,source:document.querySelector('#libraryEditSource').value.trim()||null,document_date:document.querySelector('#libraryEditDate').value||null,tags:document.querySelector('#libraryEditTags').value.split(',').map(x=>x.trim()).filter(Boolean),description:document.querySelector('#libraryEditDescription').value.trim()||null,auto_classified:false,classification_note:'사용자 수정',updated_at:new Date().toISOString()}});if(current?.visibility!==visibility)await luApi('/functions/v1/library-files',{method:'POST',body:{action:'set-visibility',document_id:id,visibility}});st.textContent='수정했습니다.';st.className='status ok';luClose('libraryEditModal');await luLoadDocuments();luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed'))}catch(e){st.textContent=e.message;st.className='status error'}}
async function luToggleVisibility(id){const d=luDocuments.find(x=>x.id===id)||await luFetchOne(id);if(!d)return;const next=d.visibility==='public'?'workspace':'public';if(next==='public'&&!confirm('이 자료를 로그인하지 않은 사용자도 볼 수 있도록 외부 공개할까요?\n자료명·분류·출처·날짜·설명과 연결된 공개 링크가 노출됩니다.'))return;try{const result=await luApi('/functions/v1/library-files',{method:'POST',body:{action:'set-visibility',document_id:id,visibility:next}});d.visibility=result?.document?.visibility||next;luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed',{detail:{id,visibility:d.visibility}}))}catch(e){alert(e.message||String(e))}}
function luDeleteErrorMessage(e){if(e?.code==='session_required'||e?.status===401)return '로그인 세션이 만료됐습니다. 다시 로그인한 뒤 삭제해 주세요.';if(/token has been expired or revoked|invalid_grant/i.test(String(e?.message||'')))return 'Google Drive 연결이 만료됐습니다. 관리자에게 Drive 재연결을 요청해 주세요. 자료 기록은 삭제되지 않았습니다.';return '자료를 삭제하지 못했습니다. 관리자에게 오류 확인을 요청해 주세요.'}
async function luDeleteDocument(id){const d=luDocuments.find(x=>x.id===id)||await luFetchOne(id);if(!d)return;if(!confirm(`“${d.file_name||d.title}” 파일을 삭제할까요?\nGoogle Drive 원본과 자료실 기록이 함께 삭제됩니다.`))return;try{const data=await luApi('/functions/v1/document-actions',{method:'POST',body:{action:'delete',document_id:id}});if(data?.error)throw new Error(data.error||'삭제 실패');luDocuments=luDocuments.filter(x=>x.id!==id);luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed',{detail:{project_id:d.project_id||null}}))}catch(e){console.error('library document deletion failed',e);if(!(await luMaybeReconnectDrive(e)))alert(luDeleteErrorMessage(e))}}
async function luManage(){luEnsureManageUi();const box=document.querySelector('#libraryManageList');box.innerHTML='<div class="empty compact">불러오는 중…</div>';luOpen('libraryManageModal');try{await luLoadDocuments();box.innerHTML=luDocuments.length?luDocuments.map(d=>`<div class="library-manage-row"><div><b>${luEsc(d.file_name||d.title)}</b><small>${luEsc(d.category||'기타')}${d.auto_classified?' · 자동분류':''}${d.project_id?' · 프로젝트 연결':''}</small></div><button class="mini" type="button" data-library-edit="${d.id}">정보 수정</button></div>`).join(''):'<div class="empty">자료가 없습니다.</div>';box.querySelectorAll('[data-library-edit]').forEach(b=>b.onclick=()=>luOpenEditById(b.dataset.libraryEdit))}catch(e){box.innerHTML='<div class="empty">'+luEsc(e.message)+'</div>'}}
function luBindList(){const list=document.querySelector('#documentList');if(!list||list.dataset.luBound)return;list.dataset.luBound='1';list.addEventListener('click',async e=>{const toggle=e.target.closest('[data-lu-toggle-public]');if(toggle){await luToggleVisibility(toggle.dataset.luTogglePublic);return}const dl=e.target.closest('[data-lu-download]');if(dl){await luDownload(dl.dataset.luDownload);return}const edit=e.target.closest('[data-lu-edit]');if(edit){await luOpenEditById(edit.dataset.luEdit);return}const del=e.target.closest('[data-lu-delete]');if(del){await luDeleteDocument(del.dataset.luDelete);return}const card=e.target.closest('[data-lu-document]');if(card)await luOpenDocument(card.dataset.luDocument)});list.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches?.('[data-lu-document]')){e.preventDefault();luOpenDocument(e.target.dataset.luDocument)}})}
async function luInit(){if(!(await luContext()))return;luHandleDriveReturn();luEnhanceUpload();luEnsureManageUi();luBindList();await luLoadDocuments();luRenderLibrary();const save=document.querySelector('#saveDocumentBtn');if(save){const original=save.onclick;save.onclick=()=>luUploadOrOriginal(original)}const newDocument=document.querySelector('#newDocumentBtn');if(newDocument)newDocument.addEventListener('click',()=>luResetUploadSelection(),true);const head=document.querySelector('#libraryView .section-head');if(head&&!document.querySelector('#manageLibraryBtn')){const btn=document.createElement('button');btn.id='manageLibraryBtn';btn.className='secondary';btn.type='button';btn.textContent='분류 수정';const actions=head.querySelector('.head-actions');if(actions)actions.prepend(btn);else head.appendChild(btn);btn.onclick=luManage}const search=document.querySelector('#documentSearch'),project=document.querySelector('#documentProject');if(search)search.oninput=luRenderLibrary;if(project)project.onchange=luRenderLibrary;document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="library"], [data-goto="library"]'))setTimeout(async()=>{await luLoadDocuments();luRenderLibrary()},80)},true);window.addEventListener('kptu:edit-document',e=>{const id=e.detail?.id;if(id)luOpenEditById(id)});window.addEventListener('kptu:documents-changed',async()=>{await luLoadDocuments();luRenderLibrary()})}
setTimeout(luInit,0);
