const LU_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const LU_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const LU_SESSION='kptu_collab_session_v1';
let luSession=null,luUser=null,luWorkspace=null,luSpaces=[],luDocuments=[];
function luRead(){try{return JSON.parse(localStorage.getItem(LU_SESSION)||'null')}catch{return null}}
async function luEnsure(){luSession=luRead();if(!luSession)return false;if((luSession.expires_at||0)<Math.floor(Date.now()/1000)+60&&luSession.refresh_token){const r=await fetch(LU_SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:LU_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:luSession.refresh_token})});if(!r.ok)return false;const d=await r.json();d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);luSession=d;localStorage.setItem(LU_SESSION,JSON.stringify(d))}return true}
async function luApi(path,{method='GET',body=null,prefer=''}={}){if(!(await luEnsure()))throw new Error('로그인이 필요합니다.');const h={apikey:LU_KEY,Authorization:'Bearer '+luSession.access_token,'Content-Type':'application/json'};if(prefer)h.Prefer=prefer;const r=await fetch(LU_SB+path,{method,headers:h,body:body===null?null:JSON.stringify(body),cache:'no-store'});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.hint||('요청 실패 '+r.status));return d}
function luEsc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function luSize(n){n=Number(n)||0;if(!n)return'';if(n<1024)return n+'B';if(n<1048576)return(n/1024).toFixed(1)+'KB';return(n/1048576).toFixed(1)+'MB'}
function luProjectName(id){return luSpaces.find(x=>x.id===id)?.name||''}
async function luContext(){if(!(await luEnsure()))return false;const ur=await fetch(LU_SB+'/auth/v1/user',{headers:{apikey:LU_KEY,Authorization:'Bearer '+luSession.access_token}});if(!ur.ok)return false;luUser=await ur.json();const ms=await luApi('/rest/v1/app_workspace_members?user_id=eq.'+luUser.id+'&select=workspace_id&limit=1');if(!ms?.length)return false;luWorkspace=ms[0].workspace_id;luSpaces=await luApi('/rest/v1/app_spaces?workspace_id=eq.'+luWorkspace+'&select=id,name,status&order=sort_order.asc,created_at.asc');return true}
function luProjectOptions(selected=''){return '<option value="">프로젝트 없음</option>'+luSpaces.filter(s=>s.status!=='archived').map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${luEsc(s.name)}</option>`).join('')}
function luInstallStyle(){if(document.querySelector('#luStyle'))return;const style=document.createElement('style');style.id='luStyle';style.textContent='.library-file-block{padding:12px;border-radius:12px;background:#f4f7f9;margin-bottom:12px}.library-file-block p{margin:6px 0 0;color:#71808d;font-size:12px;line-height:1.45}.library-file-block .optional{font-size:11px;color:#768492;font-weight:500}.library-manage-list{display:grid;gap:8px;max-height:55vh;overflow:auto}.library-manage-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px;border:1px solid #e1e6eb;border-radius:11px}.library-manage-row>div{min-width:0}.library-manage-row b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.library-manage-row small{color:#78838e}.library-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.lu-document-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.lu-document-actions .mini{white-space:nowrap}.lu-document-actions .danger{color:#a33b45;border-color:#ead2d5;background:#fff}@media(max-width:650px){.library-edit-grid{grid-template-columns:1fr}.lu-document-actions{justify-content:flex-start;margin-top:10px}.lu-document-actions .mini{padding:6px 8px;font-size:11px}}';document.head.appendChild(style)}
function luEnhanceUpload(){const modal=document.querySelector('#documentModal .modal-card');const title=document.querySelector('#docTitle');if(!modal||!title||document.querySelector('#libraryFileInput'))return;const picker=document.createElement('div');picker.className='library-file-block';picker.innerHTML='<label>파일 <span class="optional">(이것만 선택해도 등록 가능)</span><input id="libraryFileInput" type="file"></label><p>제목·분류·출처·날짜·태그·프로젝트를 비워두면 자동으로 분류합니다. 입력한 항목은 자동분류가 덮어쓰지 않습니다.</p>';title.closest('label')?.insertAdjacentElement('beforebegin',picker);const lab=title.closest('label');if(lab&&lab.firstChild?.nodeType===3)lab.firstChild.nodeValue='자료명 (선택)'}
async function luUploadOrOriginal(original){const file=document.querySelector('#libraryFileInput')?.files?.[0];if(!file)return original?.();const st=document.querySelector('#documentStatus');st.textContent='파일 업로드·자동분류 중…';st.className='status';try{if(!(await luEnsure()))throw new Error('로그인이 필요합니다.');const fd=new FormData();fd.append('file',file);const fields={title:'#docTitle',category:'#docCategory',source:'#docSource',document_date:'#docDate',tags:'#docTags',project_id:'#docProject',description:'#docDescription'};for(const[k,sel]of Object.entries(fields)){const v=document.querySelector(sel)?.value?.trim?.()||document.querySelector(sel)?.value||'';if(v)fd.append(k,v)}const r=await fetch(LU_SB+'/functions/v1/library-files',{method:'POST',headers:{Authorization:'Bearer '+luSession.access_token},body:fd});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'자료 업로드 실패');st.textContent='등록 완료 · 자동분류 결과는 자료실에서 수정할 수 있습니다.';st.className='status ok';document.querySelector('#documentModal')?.classList.add('hidden');await luLoadDocuments();luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed',{detail:{project_id:d?.document?.project_id||null}}))}catch(e){st.textContent=e.message;st.className='status error'}}
function luEnsureManageUi(){if(document.querySelector('#libraryManageModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="libraryManageModal" class="modal hidden" aria-hidden="true"><div class="modal-card medium-card"><div class="modal-head"><div><div class="eyebrow">LIBRARY</div><h2>자료 분류 수정</h2><p class="muted">자동분류가 틀린 자료를 직접 수정합니다.</p></div><button id="libraryManageClose" class="icon-btn" type="button">×</button></div><div id="libraryManageList" class="library-manage-list"></div></div></div><div id="libraryEditModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">EDIT METADATA</div><h2>자료 정보 수정</h2></div><button id="libraryEditClose" class="icon-btn" type="button">×</button></div><input id="libraryEditId" type="hidden"><label>자료명<input id="libraryEditTitle" type="text"></label><div class="library-edit-grid"><label>분류<input id="libraryEditCategory" type="text"></label><label>프로젝트<select id="libraryEditProject"></select></label><label>출처<input id="libraryEditSource" type="text"></label><label>문서 날짜<input id="libraryEditDate" type="date"></label></div><label>태그<input id="libraryEditTags" type="text" placeholder="쉼표로 구분"></label><label>설명<textarea id="libraryEditDescription" rows="4"></textarea></label><button id="libraryEditSave" class="primary wide" type="button">수정 저장</button><div id="libraryEditStatus" class="status"></div></div></div>`);document.querySelector('#libraryManageClose').onclick=()=>luClose('libraryManageModal');document.querySelector('#libraryEditClose').onclick=()=>luClose('libraryEditModal');document.querySelector('#libraryEditSave').onclick=luSaveEdit}
function luOpen(id){const m=document.querySelector('#'+id);m?.classList.remove('hidden');m?.setAttribute('aria-hidden','false')}
function luClose(id){const m=document.querySelector('#'+id);m?.classList.add('hidden');m?.setAttribute('aria-hidden','true')}
async function luLoadDocuments(){if(!luWorkspace)return;luDocuments=await luApi('/rest/v1/app_documents?workspace_id=eq.'+luWorkspace+'&select=*&order=document_date.desc.nullslast,created_at.desc')}
function luRenderLibrary(){const box=document.querySelector('#documentList');if(!box)return;const q=(document.querySelector('#documentSearch')?.value||'').trim().toLowerCase(),pid=document.querySelector('#documentProject')?.value||'all';const rows=luDocuments.filter(d=>(pid==='all'||d.project_id===pid)&&(!q||[d.title,d.file_name,d.source,d.category,(d.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));box.innerHTML=rows.length?rows.map(d=>`<article class="item-card" data-lu-document="${d.id}"><div><div class="badges"><span class="badge">${luEsc(d.category||'기타')}</span>${d.project_id?`<span class="badge">${luEsc(luProjectName(d.project_id))}</span>`:''}</div><h3>${luEsc(d.title||d.file_name||'파일')}</h3><p>${luEsc(d.source||'출처 미기재')}${d.document_date?' · '+luEsc(d.document_date):''}${d.file_size?' · '+luSize(d.file_size):''}</p>${d.file_name&&d.file_name!==d.title?`<small>${luEsc(d.file_name)}</small>`:''}${d.description?`<small>${luEsc(d.description)}</small>`:''}</div><div class="lu-document-actions"><button class="mini" type="button" data-lu-open="${d.id}">열기</button><button class="mini" type="button" data-lu-download="${d.id}">다운로드</button><button class="mini" type="button" data-lu-edit="${d.id}">정보 수정</button><button class="mini danger" type="button" data-lu-delete="${d.id}">삭제</button></div></article>`).join(''):'<div class="empty">자료가 없습니다.</div>'}
async function luOpenDocument(id){const d=luDocuments.find(x=>x.id===id)||await luFetchOne(id);if(d?.drive_url){location.href=d.drive_url;return}if(d?.file_id){await luDownload(id);return}alert('열 수 있는 파일 링크가 없습니다.')}
async function luDownload(id){try{const d=await luApi('/functions/v1/workspace-drive?action=download-token',{method:'POST',body:{document_id:id}});if(!d?.url)throw new Error('다운로드 주소를 받지 못했습니다.');location.href=d.url}catch(e){alert(e.message||String(e))}}
async function luFetchOne(id){const rows=await luApi('/rest/v1/app_documents?id=eq.'+encodeURIComponent(id)+'&select=*&limit=1');return rows?.[0]||null}
async function luOpenEditById(id){let d=luDocuments.find(x=>x.id===id);if(!d)d=await luFetchOne(id);if(!d)return;luEdit(d)}
function luEdit(d){document.querySelector('#libraryEditId').value=d.id;document.querySelector('#libraryEditTitle').value=d.title||'';document.querySelector('#libraryEditCategory').value=d.category||'';document.querySelector('#libraryEditProject').innerHTML=luProjectOptions(d.project_id||'');document.querySelector('#libraryEditSource').value=d.source||'';document.querySelector('#libraryEditDate').value=d.document_date||'';document.querySelector('#libraryEditTags').value=(d.tags||[]).join(', ');document.querySelector('#libraryEditDescription').value=d.description||'';document.querySelector('#libraryEditStatus').textContent='';luOpen('libraryEditModal')}
async function luSaveEdit(){const id=document.querySelector('#libraryEditId').value,st=document.querySelector('#libraryEditStatus');st.textContent='저장 중…';st.className='status';try{await luApi('/rest/v1/app_documents?id=eq.'+id,{method:'PATCH',body:{title:document.querySelector('#libraryEditTitle').value.trim(),category:document.querySelector('#libraryEditCategory').value.trim()||'기타',project_id:document.querySelector('#libraryEditProject').value||null,source:document.querySelector('#libraryEditSource').value.trim()||null,document_date:document.querySelector('#libraryEditDate').value||null,tags:document.querySelector('#libraryEditTags').value.split(',').map(x=>x.trim()).filter(Boolean),description:document.querySelector('#libraryEditDescription').value.trim()||null,auto_classified:false,classification_note:'사용자 수정',updated_at:new Date().toISOString()}});st.textContent='수정했습니다.';st.className='status ok';luClose('libraryEditModal');await luLoadDocuments();luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed'))}catch(e){st.textContent=e.message;st.className='status error'}}
async function luDeleteDocument(id){const d=luDocuments.find(x=>x.id===id)||await luFetchOne(id);if(!d)return;if(!confirm(`“${d.file_name||d.title}” 파일을 삭제할까요?\nGoogle Drive 원본과 자료실 기록이 함께 삭제됩니다.`))return;try{if(!(await luEnsure()))throw new Error('로그인이 필요합니다.');const r=await fetch(LU_SB+'/functions/v1/document-actions',{method:'POST',headers:{Authorization:'Bearer '+luSession.access_token,'Content-Type':'application/json'},body:JSON.stringify({action:'delete',document_id:id})});const data=await r.json().catch(()=>null);if(!r.ok||data?.error)throw new Error(data?.error||'삭제 실패');luDocuments=luDocuments.filter(x=>x.id!==id);luRenderLibrary();window.dispatchEvent(new CustomEvent('kptu:documents-changed',{detail:{project_id:d.project_id||null}}))}catch(e){alert(e.message||String(e))}}
async function luManage(){luEnsureManageUi();const box=document.querySelector('#libraryManageList');box.innerHTML='<div class="empty compact">불러오는 중…</div>';luOpen('libraryManageModal');try{await luLoadDocuments();box.innerHTML=luDocuments.length?luDocuments.map(d=>`<div class="library-manage-row"><div><b>${luEsc(d.file_name||d.title)}</b><small>${luEsc(d.category||'기타')}${d.auto_classified?' · 자동분류':''}${d.project_id?' · 프로젝트 연결':''}</small></div><button class="mini" type="button" data-library-edit="${d.id}">정보 수정</button></div>`).join(''):'<div class="empty">자료가 없습니다.</div>';box.querySelectorAll('[data-library-edit]').forEach(b=>b.onclick=()=>luOpenEditById(b.dataset.libraryEdit))}catch(e){box.innerHTML='<div class="empty">'+luEsc(e.message)+'</div>'}}
function luBindList(){const list=document.querySelector('#documentList');if(!list||list.dataset.luBound)return;list.dataset.luBound='1';list.addEventListener('click',async e=>{const open=e.target.closest('[data-lu-open]');if(open){await luOpenDocument(open.dataset.luOpen);return}const dl=e.target.closest('[data-lu-download]');if(dl){await luDownload(dl.dataset.luDownload);return}const edit=e.target.closest('[data-lu-edit]');if(edit){await luOpenEditById(edit.dataset.luEdit);return}const del=e.target.closest('[data-lu-delete]');if(del){await luDeleteDocument(del.dataset.luDelete)}})}
async function luInit(){if(!(await luContext()))return;luInstallStyle();luEnhanceUpload();luEnsureManageUi();luBindList();await luLoadDocuments();luRenderLibrary();const save=document.querySelector('#saveDocumentBtn');if(save){const original=save.onclick;save.onclick=()=>luUploadOrOriginal(original)}const head=document.querySelector('#libraryView .section-head');if(head&&!document.querySelector('#manageLibraryBtn')){const btn=document.createElement('button');btn.id='manageLibraryBtn';btn.className='secondary';btn.type='button';btn.textContent='분류 수정';const actions=head.querySelector('.head-actions');if(actions)actions.prepend(btn);else head.appendChild(btn);btn.onclick=luManage}const search=document.querySelector('#documentSearch'),project=document.querySelector('#documentProject');if(search)search.oninput=luRenderLibrary;if(project)project.onchange=luRenderLibrary;const dm=document.querySelector('#documentModal');if(dm)new MutationObserver(()=>{if(!dm.classList.contains('hidden'))luEnhanceUpload()}).observe(dm,{attributes:true,attributeFilter:['class']});document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="library"], [data-goto="library"]'))setTimeout(async()=>{await luLoadDocuments();luRenderLibrary()},80)},true);window.addEventListener('kptu:edit-document',e=>{const id=e.detail?.id;if(id)luOpenEditById(id)});window.addEventListener('kptu:documents-changed',async()=>{await luLoadDocuments();luRenderLibrary()})}
setTimeout(luInit,0);