(()=>{
'use strict';
const pbRt=window.KPTURuntime;
const PB_TEMPLATES={
  article:{label:'기사·보도자료',hint:'제목·리드·본문 중심의 읽기 좋은 기사형'},
  notice:{label:'공지·알림',hint:'핵심 안내와 행동 요청을 빠르게 전달'},
  status:{label:'업무현황 공유',hint:'진행상황·쟁점·다음 계획을 구조적으로 공유'},
  event:{label:'행사·집회 안내',hint:'일시·장소·핵심 메시지를 한눈에 안내'},
  brief:{label:'정책 브리핑·Q&A',hint:'핵심 요약과 쟁점을 설명하는 브리핑형'}
};
let pbTemplate='article',pbDesign={},pbPageId=null,pbMetadata={},pbMetadataLoaded=false,pbGenerating=false,pbOpenSeq=0;
let pbWorkspaceId=null,pbSourceLoaded=false,pbMeetings=[],pbDocuments=[],pbIndexed=new Set(),pbUsedSources=[];
let pbSources={project:false,project_updates:false,project_milestones:false,meeting_ids:new Set(),document_ids:new Set()};
const pbEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pbPd=()=>window.KPTUPageDesign;
const pbProjectId=()=>document.querySelector('#pageSpace')?.value||null;
function pbSourceSnapshot(){return {project_id:pbProjectId(),project:!!pbSources.project,project_updates:!!pbSources.project_updates,project_milestones:!!pbSources.project_milestones,meeting_ids:[...pbSources.meeting_ids],document_ids:[...pbSources.document_ids],used_sources:pbUsedSources,generated_at:pbUsedSources.length?new Date().toISOString():null}}
function pbRestoreSourceSnapshot(saved){const s=saved&&typeof saved==='object'?saved:{};pbSources={project:!!s.project,project_updates:!!s.project_updates,project_milestones:!!s.project_milestones,meeting_ids:new Set(Array.isArray(s.meeting_ids)?s.meeting_ids:[]),document_ids:new Set(Array.isArray(s.document_ids)?s.document_ids:[])};pbUsedSources=Array.isArray(s.used_sources)?s.used_sources:[]}
function pbSetOpening(on){document.querySelector('#pageBuilderPanel')?.classList.toggle('pb-open-loading',!!on)}
function pbClearStatus(){for(const id of ['pbSourceStatus','pbAiStatus']){const el=document.querySelector('#'+id);if(el){el.textContent='';el.className='status'}}}
function pbInstall(){const main=document.querySelector('#editorModal .editor-main');if(!main||document.querySelector('#pageBuilderPanel'))return false;main.insertAdjacentHTML('afterbegin',`<section id="pageBuilderPanel" class="pb-panel"><div class="pb-head"><div><b>페이지 유형</b><span id="pbTemplateHint"></span></div><button id="pbPreviewToggle" class="mini" type="button">미리보기</button></div><div class="pb-templates">${Object.entries(PB_TEMPLATES).map(([k,v])=>`<button class="pb-template" data-pb-template="${k}" type="button">${v.label}</button>`).join('')}</div><div class="pb-sources"><div class="pb-source-head"><div><b>AI 참고자료</b><span id="pbSourceSummary">선택한 자료만 AI가 참고합니다.</span></div><button id="pbSourceToggle" class="mini" type="button">자료 선택</button></div><div id="pbSourcePicker" class="pb-source-picker hidden"><div id="pbProjectSources" class="pb-source-project"></div><details open><summary>회의결과 <span id="pbMeetingCount"></span></summary><div id="pbMeetingSources" class="pb-source-list"></div></details><details open><summary>자료실 <span id="pbDocumentCount"></span></summary><div class="pb-source-tools"><input id="pbDocumentSearch" type="search" placeholder="자료명·분류 검색"><label class="secondary pb-upload-label">+ 새 파일 업로드<input id="pbSourceUpload" type="file" accept=".pdf,.hwp,.hwpx,.doc,.docx,.ppt,.pptx,.txt,.md,.csv,.json"></label></div><div id="pbDocumentSources" class="pb-source-list"></div></details><div id="pbSourceStatus" class="status"></div></div></div><div class="pb-ai"><textarea id="pbPrompt" rows="2" placeholder="예: 민자철도 프로젝트와 선택한 회의결과·PDF를 참고해서 현장 알림을 작성해줘."></textarea><button id="pbGenerate" class="secondary" type="button">AI로 초안 만들기 · 디자인 포함</button></div><div id="pbDesignSummary" class="pb-design-summary"></div><div id="pbAiStatus" class="status"></div></section><section id="pbPreview" class="pb-preview hidden"><div class="pb-preview-label">LIVE PREVIEW</div><article class="pb-paper pd-design"><header class="pd-hero"><div class="pb-eyebrow pd-kicker"></div><h1 class="pd-title"></h1><p class="pb-summary pd-summary"></p></header><div class="pb-body pd-body"></div></article></section>`);
  document.querySelectorAll('[data-pb-template]').forEach(b=>b.addEventListener('click',()=>{pbDesign={};pbSelect(b.dataset.pbTemplate)}));
  document.querySelector('#pbPreviewToggle')?.addEventListener('click',()=>{document.querySelector('#pbPreview')?.classList.toggle('hidden');pbPreview()});
  document.querySelector('#pbSourceToggle')?.addEventListener('click',()=>document.querySelector('#pbSourcePicker')?.classList.toggle('hidden'));
  document.querySelector('#pbGenerate')?.addEventListener('click',pbGenerate);
  document.querySelector('#pbDocumentSearch')?.addEventListener('input',pbRenderDocuments);
  document.querySelector('#pbSourcePicker')?.addEventListener('change',pbSourceChanged);
  document.querySelector('#pbSourceUpload')?.addEventListener('change',e=>pbUploadSource(e.currentTarget.files?.[0]).catch(pbSourceError));
  document.querySelector('#pageSpace')?.addEventListener('change',()=>{pbUsedSources=[];pbRenderSources()});
  ['#pageTitle','#pageSummary','#pageBody'].forEach(sel=>document.querySelector(sel)?.addEventListener('input',pbPreview));
  pbSelect('article');
  return true
}
function pbSelect(key){if(!PB_TEMPLATES[key])key='article';pbTemplate=key;document.querySelectorAll('[data-pb-template]').forEach(b=>b.classList.toggle('active',b.dataset.pbTemplate===key));const hint=document.querySelector('#pbTemplateHint');if(hint)hint.textContent=PB_TEMPLATES[key].hint;pbPreview()}
function pbPreview(){const p=document.querySelector('#pbPreview'),pd=pbPd();if(!p)return;const design=pd?.normalize(pbDesign,pbTemplate)||pbDesign;p.className=`pb-preview ${pbTemplate}${p.classList.contains('hidden')?' hidden':''}`;const paper=p.querySelector('.pb-paper');if(paper)paper.className=`pb-paper ${pd?.classNames(design,pbTemplate)||'pd-design'}`;const title=document.querySelector('#pageTitle')?.value.trim()||'페이지 제목',summary=document.querySelector('#pageSummary')?.value.trim()||'',body=document.querySelector('#pageBody')?.value||'';p.querySelector('h1').textContent=title;p.querySelector('.pb-summary').textContent=summary;p.querySelector('.pb-body').innerHTML=pd?.renderMarkdown(body)||pbEsc(body);p.querySelector('.pb-eyebrow').textContent=PB_TEMPLATES[pbTemplate].label;const ds=document.querySelector('#pbDesignSummary');if(ds)ds.textContent=pd?.describe(design,pbTemplate)||'기본 구성'}
async function pbEnsureWorkspace(){if(pbWorkspaceId)return pbWorkspaceId;if(!pbRt||!(await pbRt.session.ensure()))throw new Error('로그인이 필요합니다.');const user=await pbRt.api('/auth/v1/user');const ms=await pbRt.api(`/rest/v1/app_workspace_members?user_id=eq.${user.id}&select=workspace_id&limit=1`);if(!ms?.[0]?.workspace_id)throw new Error('Workspace 정보를 찾을 수 없습니다.');pbWorkspaceId=ms[0].workspace_id;return pbWorkspaceId}
async function pbLoadSources(force=false){if(pbSourceLoaded&&!force){pbRenderSources();return}const ws=await pbEnsureWorkspace();const [meetings,docs]=await Promise.all([pbRt.api(`/rest/v1/app_meetings?workspace_id=eq.${ws}&select=id,title,meeting_at,project_id,result_status&order=meeting_at.desc&limit=40`),pbRt.api(`/rest/v1/app_documents?workspace_id=eq.${ws}&select=id,title,file_name,project_id,category,document_date,extraction_status&order=created_at.desc&limit=80`)]);pbMeetings=meetings||[];pbDocuments=docs||[];pbIndexed=new Set();if(pbDocuments.length){const ids=pbDocuments.map(x=>x.id).join(',');try{const idx=await pbRt.api(`/rest/v1/app_document_ai_index?document_id=in.(${ids})&select=document_id`);pbIndexed=new Set((idx||[]).map(x=>x.document_id))}catch{pbIndexed=new Set()}}pbSourceLoaded=true;pbRenderSources()}
function pbRenderSources(){pbRenderProjectSources();pbRenderMeetings();pbRenderDocuments();pbUpdateSourceSummary()}
function pbRenderProjectSources(){const box=document.querySelector('#pbProjectSources');if(!box)return;const pid=pbProjectId();if(!pid){box.innerHTML='<div class="pb-source-empty">페이지의 프로젝트를 먼저 선택하면 프로젝트 기본정보·진행 기록·주요 일정을 참고할 수 있습니다.</div>';return}const options=[['project','현재 프로젝트','프로젝트 기본정보·현재단계'],['project_updates','진행 기록','최근 진행 경과와 업데이트'],['project_milestones','주요 일정','마일스톤·예정 일정']];box.innerHTML=options.map(([key,label,hint])=>`<label class="pb-source-option"><input type="checkbox" data-pb-source="${key}" ${pbSources[key]?'checked':''}><span><b>${label}</b><small>${hint}</small></span></label>`).join('')}
function pbRenderMeetings(){const box=document.querySelector('#pbMeetingSources'),count=document.querySelector('#pbMeetingCount');if(!box)return;const pid=pbProjectId();const rows=[...pbMeetings].sort((a,b)=>(b.project_id===pid)-(a.project_id===pid));if(count)count.textContent=pbSources.meeting_ids.size?`· ${pbSources.meeting_ids.size}개 선택`:'';box.innerHTML=rows.length?rows.map(m=>`<label class="pb-source-option"><input type="checkbox" data-pb-meeting="${m.id}" ${pbSources.meeting_ids.has(m.id)?'checked':''}><span><b>${pbEsc(m.title)}</b><small>${m.meeting_at?new Date(m.meeting_at).toLocaleDateString('ko-KR'):''}${m.project_id===pid&&pid?' · 현재 프로젝트':''}${m.result_status==='final'?' · 확정':''}</small></span></label>`).join(''):'<div class="pb-source-empty">등록된 회의결과가 없습니다.</div>'}
function pbRenderDocuments(){const box=document.querySelector('#pbDocumentSources'),count=document.querySelector('#pbDocumentCount');if(!box)return;const q=(document.querySelector('#pbDocumentSearch')?.value||'').trim().toLowerCase(),pid=pbProjectId();const rows=pbDocuments.filter(d=>!q||[d.title,d.file_name,d.category].join(' ').toLowerCase().includes(q)).sort((a,b)=>(b.project_id===pid)-(a.project_id===pid));if(count)count.textContent=pbSources.document_ids.size?`· ${pbSources.document_ids.size}개 선택`:'';box.innerHTML=rows.length?rows.map(d=>{const ready=pbIndexed.has(d.id);return `<label class="pb-source-option"><input type="checkbox" data-pb-document="${d.id}" ${pbSources.document_ids.has(d.id)?'checked':''}><span><b>${pbEsc(d.title||d.file_name||'자료')}</b><small>${pbEsc(d.category||'기타')}${d.document_date?' · '+pbEsc(d.document_date):''}${d.project_id===pid&&pid?' · 현재 프로젝트':''} · <em class="${ready?'pb-source-ready':'pb-source-wait'}">${ready?'AI 준비됨':'선택 시 AI 준비'}</em></small></span></label>`}).join(''):'<div class="pb-source-empty">조건에 맞는 자료가 없습니다.</div>'}
function pbSourceChanged(e){const el=e.target;if(el.matches('[data-pb-source]'))pbSources[el.dataset.pbSource]=el.checked;else if(el.matches('[data-pb-meeting]'))el.checked?pbSources.meeting_ids.add(el.dataset.pbMeeting):pbSources.meeting_ids.delete(el.dataset.pbMeeting);else if(el.matches('[data-pb-document]'))el.checked?pbSources.document_ids.add(el.dataset.pbDocument):pbSources.document_ids.delete(el.dataset.pbDocument);else return;pbUsedSources=[];pbRenderMeetings();pbRenderDocuments();pbUpdateSourceSummary()}
function pbUpdateSourceSummary(){const n=(pbSources.project?1:0)+(pbSources.project_updates?1:0)+(pbSources.project_milestones?1:0)+pbSources.meeting_ids.size+pbSources.document_ids.size;const el=document.querySelector('#pbSourceSummary');if(el)el.textContent=n?`${n}개 참고 범위 선택 · 선택한 자료만 AI 입력`:'선택한 자료만 AI가 참고합니다.'}
function pbSourceError(e){const st=document.querySelector('#pbSourceStatus');if(st){st.textContent=e?.message||String(e);st.className='status error'}}
async function pbPrepareDocuments(){const ids=[...pbSources.document_ids].filter(id=>!pbIndexed.has(id));if(!ids.length)return;const st=document.querySelector('#pbSourceStatus');if(st){st.textContent=`선택 자료 ${ids.length}개 본문 추출·요약·청크 준비 중…`;st.className='status'}const data=await pbRt.api('/functions/v1/document-ai-index',{method:'POST',body:{document_ids:ids}});const errors=(data?.documents||[]).filter(x=>x.status==='error');for(const r of data?.documents||[])if(r.status==='indexed'||r.status==='cached')pbIndexed.add(r.document_id);pbRenderDocuments();if(errors.length)throw new Error(errors.map(x=>x.error).join(' / '));if(st){st.textContent='선택 자료의 AI 참고 준비가 완료되었습니다. 이후에는 저장된 요약·청크를 재사용합니다.';st.className='status ok'}}
async function pbUploadSource(file){if(!file)return;const st=document.querySelector('#pbSourceStatus');if(st){st.textContent='파일 업로드 중…';st.className='status'}const fd=new FormData();fd.append('file',file);const pid=pbProjectId();if(pid)fd.append('project_id',pid);const d=await pbRt.api('/functions/v1/library-files',{method:'POST',body:fd});const id=d?.document?.id;if(!id)throw new Error('업로드된 자료 ID를 받지 못했습니다.');pbSources.document_ids.add(id);pbUsedSources=[];pbSourceLoaded=false;await pbLoadSources(true);await pbPrepareDocuments();if(st){st.textContent='파일을 자료실에 등록하고 AI 참고자료로 선택했습니다.';st.className='status ok'}const input=document.querySelector('#pbSourceUpload');if(input)input.value=''}
async function pbLoadMetadata(id,seq){if(!id||!pbRt)return;try{const rows=await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}&select=metadata&limit=1`);if(pbPageId!==id||seq!==pbOpenSeq)return;pbMetadata=rows?.[0]?.metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{};pbMetadataLoaded=true;const saved=pbMetadata?.page_design&&typeof pbMetadata.page_design==='object'?pbMetadata.page_design:{};pbDesign={layout:saved.layout,hero:saved.hero,accent:saved.accent,section_style:saved.section_style,density:saved.density};pbRestoreSourceSnapshot(pbMetadata?.ai_sources);pbSelect(saved.template||'article');await pbLoadSources(true)}catch(e){if(seq!==pbOpenSeq)return;pbMetadata={};pbMetadataLoaded=true;pbDesign={};pbRestoreSourceSnapshot({});pbSelect('article');pbSourceError(e)}}
async function pbEditorOpened(detail={}){const seq=++pbOpenSeq;pbSetOpening(true);pbClearStatus();pbSourceLoaded=false;pbUsedSources=[];document.querySelector('#pbPrompt')&&(document.querySelector('#pbPrompt').value='');document.querySelector('#pbSourcePicker')?.classList.add('hidden');document.querySelector('#pbPreview')?.classList.add('hidden');pbPageId=detail.page_id||null;if(pbPageId){pbMetadata={};pbMetadataLoaded=false;await pbLoadMetadata(pbPageId,seq)}else{pbMetadata={};pbMetadataLoaded=true;pbDesign={};pbRestoreSourceSnapshot({});pbSelect('article');try{await pbLoadSources(true)}catch(e){pbSourceError(e)}}if(seq===pbOpenSeq){pbRenderSources();pbPreview();pbSetOpening(false)}}
async function pbSaveMetadata(id){if(!id||!pbRt)return;if(!pbMetadataLoaded){try{const rows=await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}&select=metadata&limit=1`);pbMetadata=rows?.[0]?.metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{}}catch{pbMetadata={}}pbMetadataLoaded=true}const design=pbPd()?.normalize(pbDesign,pbTemplate)||pbDesign;const metadata={...pbMetadata,page_design:{template:pbTemplate,version:2,...design},ai_sources:pbSourceSnapshot()};await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{metadata}});pbMetadata=metadata;pbPageId=id}
function pbParseAnswer(answer){let raw=String(answer||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(raw)}catch{return {body:String(answer||'').trim()}}}
async function pbGenerate(){if(pbGenerating)return;const prompt=document.querySelector('#pbPrompt')?.value.trim();if(!prompt)return;pbGenerating=true;const btn=document.querySelector('#pbGenerate'),st=document.querySelector('#pbAiStatus');if(btn){btn.disabled=true;btn.textContent='내용·디자인 생성 중…'}if(st){st.textContent='선택한 참고자료를 준비하고 관련 부분만 추려 내용과 화면 구성을 만들고 있습니다.';st.className='status'}try{await pbEnsureWorkspace();await pbPrepareDocuments();const sources=pbSourceSnapshot();const data=await pbRt.api('/functions/v1/page-ai-draft',{method:'POST',body:{workspace_id:pbWorkspaceId,prompt,page_type:PB_TEMPLATES[pbTemplate].label,sources}});const draft=data?.draft||pbParseAnswer(data?.answer||'');if(draft.title)document.querySelector('#pageTitle').value=String(draft.title).slice(0,160);if(draft.summary)document.querySelector('#pageSummary').value=String(draft.summary).slice(0,500);if(draft.body)document.querySelector('#pageBody').value=String(draft.body);if(draft.design&&typeof draft.design==='object')pbDesign=pbPd()?.normalize(draft.design,pbTemplate)||draft.design;pbUsedSources=Array.isArray(data?.used_sources)?data.used_sources:[];pbPreview();document.querySelector('#pbPreview')?.classList.remove('hidden');pbUpdateSourceSummary();if(st){st.textContent=pbUsedSources.length?`선택한 참고자료 ${pbUsedSources.length}개 범위를 근거로 초안을 만들었습니다. 확인·수정한 뒤 저장하세요.`:'작성 목적만으로 초안을 만들었습니다. 확인·수정한 뒤 저장하세요.';st.className='status ok'}}catch(e){if(st){st.textContent=e.message||String(e);st.className='status error'}}finally{pbGenerating=false;if(btn){btn.disabled=false;btn.textContent='AI로 초안 만들기 · 디자인 포함'}}}
async function pbInit(){if(!pbRt||!(await pbRt.session.ensure()))return false;if(!pbInstall())return false;await pbEnsureWorkspace();window.addEventListener('kptu:page-editor-opened',e=>pbEditorOpened(e.detail||{}).catch(pbSourceError));return true}
window.KPTUPageBuilder={saveMetadata:pbSaveMetadata,open:pbEditorOpened,get template(){return pbTemplate},get design(){return pbPd()?.normalize(pbDesign,pbTemplate)||pbDesign},get sources(){return pbSourceSnapshot()}};
window.__KPTU_PAGE_BUILDER_READY__=pbInit().catch(e=>{console.error('page builder init',e);return false});
})();
