const pbRt=window.KPTURuntime;
const PB_TEMPLATES={
  article:{label:'기사·보도자료',hint:'제목·리드·본문 중심의 읽기 좋은 기사형'},
  notice:{label:'공지·알림',hint:'핵심 안내와 행동 요청을 빠르게 전달'},
  status:{label:'업무현황 공유',hint:'진행상황·쟁점·다음 계획을 구조적으로 공유'},
  event:{label:'행사·집회 안내',hint:'일시·장소·핵심 메시지를 한눈에 안내'},
  brief:{label:'정책 브리핑·Q&A',hint:'핵심 요약과 쟁점을 설명하는 브리핑형'}
};
let pbTemplate='article',pbPageId=null,pbMetadata={},pbMetadataLoaded=false,pbGenerating=false;
const pbEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function pbMd(src){const lines=pbEsc(src||'').split(/\r?\n/);let out='',list=null;const close=()=>{if(list){out+=`</${list}>`;list=null}};for(let line of lines){let m;if((m=line.match(/^(#{1,3})\s+(.+)$/))){close();const n=m[1].length;out+=`<h${n}>${m[2]}</h${n}>`;continue}if((m=line.match(/^[-*]\s+(.+)$/))){if(list!=='ul'){close();list='ul';out+='<ul>'}out+=`<li>${m[1]}</li>`;continue}if((m=line.match(/^\d+[.)]\s+(.+)$/))){if(list!=='ol'){close();list='ol';out+='<ol>'}out+=`<li>${m[1]}</li>`;continue}close();if(/^&gt;\s?/.test(line)){out+=`<blockquote>${line.replace(/^&gt;\s?/,'')}</blockquote>`;continue}if(!line.trim())continue;line=line.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');out+=`<p>${line}</p>`}close();return out}
function pbInstall(){const main=document.querySelector('#editorModal .editor-main');if(!main||document.querySelector('#pageBuilderPanel'))return;main.insertAdjacentHTML('afterbegin',`<section id="pageBuilderPanel" class="pb-panel"><div class="pb-head"><div><b>페이지 유형</b><span id="pbTemplateHint"></span></div><button id="pbPreviewToggle" class="mini" type="button">미리보기</button></div><div class="pb-templates">${Object.entries(PB_TEMPLATES).map(([k,v])=>`<button class="pb-template" data-pb-template="${k}" type="button">${v.label}</button>`).join('')}</div><div class="pb-ai"><textarea id="pbPrompt" rows="2" placeholder="예: 9월 14일 기자회견 안내 페이지. 2% 인력감축 철회와 안전인력 확충 요구를 강조하고 시간·장소·현장발언 순서를 넣어줘."></textarea><button id="pbGenerate" class="secondary" type="button">AI로 초안 만들기</button></div><div id="pbAiStatus" class="status"></div></section><section id="pbPreview" class="pb-preview hidden"><div class="pb-preview-label">LIVE PREVIEW</div><article class="pb-paper"><div class="pb-eyebrow"></div><h1></h1><p class="pb-summary"></p><div class="pb-body"></div></article></section>`);
  const style=document.createElement('style');style.id='pageBuilderStyle';style.textContent=`.pb-panel{border:1px solid #dfe5ea;background:#f8fafb;border-radius:14px;padding:12px;margin-bottom:13px}.pb-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.pb-head>div{display:grid;gap:2px}.pb-head b{font-size:12px}.pb-head span{font-size:10.5px;color:#75818c}.pb-templates{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.pb-template{border:1px solid #d7dee4;background:#fff;color:#425465;border-radius:999px;padding:6px 9px;font-size:10.5px;font-weight:750;cursor:pointer}.pb-template.active{background:#17324d;color:#fff;border-color:#17324d}.pb-ai{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:stretch}.pb-ai textarea{min-height:58px;resize:vertical}.pb-ai button{white-space:nowrap}.pb-preview{margin:0 0 14px;border:1px solid #dfe5ea;border-radius:14px;background:#edf1f4;padding:14px}.pb-preview-label{font-size:9px;font-weight:900;letter-spacing:.14em;color:#667786;margin-bottom:7px}.pb-paper{background:#fff;border-radius:12px;padding:24px;min-height:250px;box-shadow:0 5px 18px rgba(20,40,60,.08)}.pb-paper h1{font-size:27px;line-height:1.25;margin:6px 0 9px;letter-spacing:-.7px}.pb-eyebrow{font-size:9px;font-weight:900;letter-spacing:.12em;color:#496a89}.pb-summary{font-size:13px;color:#65717c;border-bottom:1px solid #e8ecef;padding-bottom:14px;margin-bottom:14px}.pb-body{font-size:12.5px;line-height:1.7}.pb-body h2{font-size:18px;margin:1.3em 0 .45em}.pb-body h3{font-size:15px}.pb-body blockquote{border-left:3px solid #aab9c6;padding-left:10px;color:#566675}.pb-preview.notice .pb-paper{border-top:7px solid #17324d}.pb-preview.notice .pb-eyebrow:after{content:'NOTICE'}.pb-preview.status .pb-paper{background:#f9fafb}.pb-preview.status .pb-body h2{background:#fff;border:1px solid #e2e7eb;border-radius:10px;padding:9px 11px;margin-top:12px}.pb-preview.status .pb-eyebrow:after{content:'STATUS UPDATE'}.pb-preview.event .pb-paper{background:linear-gradient(145deg,#fff,#f3f6f8)}.pb-preview.event .pb-paper h1{font-size:30px}.pb-preview.event .pb-eyebrow:after{content:'EVENT'}.pb-preview.brief .pb-paper{border-left:6px solid #17324d}.pb-preview.brief .pb-eyebrow:after{content:'POLICY BRIEF'}.pb-preview.article .pb-eyebrow:after{content:'ARTICLE'}.pb-preview .pb-summary:empty{display:none}@media(max-width:700px){.pb-ai{grid-template-columns:1fr}.pb-ai button{width:100%}.pb-paper{padding:18px}.pb-paper h1{font-size:23px}.pb-template{padding:6px 8px}}`;document.head.appendChild(style);
  document.querySelectorAll('[data-pb-template]').forEach(b=>b.addEventListener('click',()=>pbSelect(b.dataset.pbTemplate)));
  document.querySelector('#pbPreviewToggle')?.addEventListener('click',()=>{const p=document.querySelector('#pbPreview');p?.classList.toggle('hidden');pbPreview()});
  document.querySelector('#pbGenerate')?.addEventListener('click',pbGenerate);
  ['#pageTitle','#pageSummary','#pageBody'].forEach(sel=>document.querySelector(sel)?.addEventListener('input',pbPreview));
  document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit-page]');if(edit){pbPageId=edit.dataset.editPage;pbMetadata={};pbMetadataLoaded=false;pbLoadMetadata(pbPageId)}if(e.target.closest?.('#newPageBtn')){pbPageId=null;pbMetadata={};pbMetadataLoaded=true;pbSelect('article')}},false);
  const modal=document.querySelector('#editorModal');if(modal)new MutationObserver(()=>{if(!modal.classList.contains('hidden')){setTimeout(()=>{pbSelect(pbTemplate);pbPreview()},40)}}).observe(modal,{attributes:true,attributeFilter:['class']});
  pbSelect('article');
}
function pbSelect(key){if(!PB_TEMPLATES[key])key='article';pbTemplate=key;document.querySelectorAll('[data-pb-template]').forEach(b=>b.classList.toggle('active',b.dataset.pbTemplate===key));const hint=document.querySelector('#pbTemplateHint');if(hint)hint.textContent=PB_TEMPLATES[key].hint;pbPreview()}
function pbPreview(){const p=document.querySelector('#pbPreview');if(!p)return;p.className=`pb-preview ${pbTemplate}${p.classList.contains('hidden')?' hidden':''}`;const title=document.querySelector('#pageTitle')?.value.trim()||'페이지 제목',summary=document.querySelector('#pageSummary')?.value.trim()||'',body=document.querySelector('#pageBody')?.value||'';p.querySelector('h1').textContent=title;p.querySelector('.pb-summary').textContent=summary;p.querySelector('.pb-body').innerHTML=pbMd(body)}
async function pbLoadMetadata(id){if(!id||!pbRt)return;try{const rows=await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}&select=metadata&limit=1`);if(pbPageId!==id)return;pbMetadata=rows?.[0]?.metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{};pbMetadataLoaded=true;pbSelect(pbMetadata?.page_design?.template||'article')}catch{pbMetadata={};pbMetadataLoaded=true;pbSelect('article')}}
async function pbSaveMetadata(id){if(!id||!pbRt)return;if(!pbMetadataLoaded){try{const rows=await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}&select=metadata&limit=1`);pbMetadata=rows?.[0]?.metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{}}catch{pbMetadata={}}pbMetadataLoaded=true}const metadata={...pbMetadata,page_design:{...(pbMetadata.page_design||{}),template:pbTemplate,version:1}};await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{metadata}});pbMetadata=metadata;pbPageId=id}
function pbParseAnswer(answer){let raw=String(answer||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(raw)}catch{return {body:String(answer||'').trim()}}}
async function pbGenerate(){if(pbGenerating)return;const prompt=document.querySelector('#pbPrompt')?.value.trim();if(!prompt)return;pbGenerating=true;const btn=document.querySelector('#pbGenerate'),st=document.querySelector('#pbAiStatus');if(btn){btn.disabled=true;btn.textContent='초안 생성 중…'}if(st){st.textContent='팀 업무자료를 참고해 초안을 만들고 있습니다.';st.className='status'}try{const type=PB_TEMPLATES[pbTemplate].label,projectId=document.querySelector('#pageSpace')?.value||null;const instruction=`${prompt}\n\n페이지 유형: ${type}. 현장 공유용 페이지 초안을 작성해줘. 사실을 새로 만들어내지 말고, 제공된 팀 업무 컨텍스트에 없는 정보는 [확인 필요]로 표시해. 반드시 다른 설명 없이 JSON 하나만 출력해. JSON 형식은 {"title":"짧은 제목","summary":"1~2문장 요약","body":"Markdown 본문"}. body는 ## 소제목, 불릿, 굵은 글씨를 적절히 써서 바로 게시할 수 있게 구성해.`;const data=await pbRt.api('/functions/v1/team-ai',{method:'POST',body:{prompt:instruction,scope:projectId?'project':'workspace',project_id:projectId||null}});const draft=pbParseAnswer(data?.answer||'');if(draft.title)document.querySelector('#pageTitle').value=String(draft.title).slice(0,160);if(draft.summary)document.querySelector('#pageSummary').value=String(draft.summary).slice(0,500);if(draft.body)document.querySelector('#pageBody').value=String(draft.body);pbPreview();document.querySelector('#pbPreview')?.classList.remove('hidden');if(st){st.textContent='초안을 만들었습니다. 내용을 확인·수정한 뒤 저장하세요.';st.className='status ok'}}catch(e){if(st){st.textContent=e.message||String(e);st.className='status error'}}finally{pbGenerating=false;if(btn){btn.disabled=false;btn.textContent='AI로 초안 만들기'}}}
window.KPTUPageBuilder={saveMetadata:pbSaveMetadata,get template(){return pbTemplate}};
pbInstall();