const pbRt=window.KPTURuntime;
const PB_TEMPLATES={
  article:{label:'기사·보도자료',hint:'제목·리드·본문 중심의 읽기 좋은 기사형'},
  notice:{label:'공지·알림',hint:'핵심 안내와 행동 요청을 빠르게 전달'},
  status:{label:'업무현황 공유',hint:'진행상황·쟁점·다음 계획을 구조적으로 공유'},
  event:{label:'행사·집회 안내',hint:'일시·장소·핵심 메시지를 한눈에 안내'},
  brief:{label:'정책 브리핑·Q&A',hint:'핵심 요약과 쟁점을 설명하는 브리핑형'}
};
let pbTemplate='article',pbDesign={},pbPageId=null,pbMetadata={},pbMetadataLoaded=false,pbGenerating=false;
const pbEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pbPd=()=>window.KPTUPageDesign;
function pbInstall(){const main=document.querySelector('#editorModal .editor-main');if(!main||document.querySelector('#pageBuilderPanel'))return;main.insertAdjacentHTML('afterbegin',`<section id="pageBuilderPanel" class="pb-panel"><div class="pb-head"><div><b>페이지 유형</b><span id="pbTemplateHint"></span></div><button id="pbPreviewToggle" class="mini" type="button">미리보기</button></div><div class="pb-templates">${Object.entries(PB_TEMPLATES).map(([k,v])=>`<button class="pb-template" data-pb-template="${k}" type="button">${v.label}</button>`).join('')}</div><div class="pb-ai"><textarea id="pbPrompt" rows="2" placeholder="예: 9월 14일 기자회견 안내 페이지. 2% 인력감축 철회와 안전인력 확충 요구를 강조하고 시간·장소·현장발언 순서를 넣어줘."></textarea><button id="pbGenerate" class="secondary" type="button">AI로 내용·디자인 만들기</button></div><div id="pbDesignSummary" class="pb-design-summary"></div><div id="pbAiStatus" class="status"></div></section><section id="pbPreview" class="pb-preview hidden"><div class="pb-preview-label">LIVE PREVIEW</div><article class="pb-paper pd-design"><header class="pd-hero"><div class="pb-eyebrow pd-kicker"></div><h1 class="pd-title"></h1><p class="pb-summary pd-summary"></p></header><div class="pb-body pd-body"></div></article></section>`);
  const style=document.createElement('style');style.id='pageBuilderStyle';style.textContent=`.pb-panel{border:1px solid #dfe5ea;background:#f8fafb;border-radius:14px;padding:12px;margin-bottom:13px}.pb-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.pb-head>div{display:grid;gap:2px}.pb-head b{font-size:12px}.pb-head span{font-size:10.5px;color:#75818c}.pb-templates{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.pb-template{border:1px solid #d7dee4;background:#fff;color:#425465;border-radius:999px;padding:6px 9px;font-size:10.5px;font-weight:750;cursor:pointer}.pb-template.active{background:#17324d;color:#fff;border-color:#17324d}.pb-ai{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:stretch}.pb-ai textarea{min-height:58px;resize:vertical}.pb-ai button{white-space:nowrap}.pb-design-summary{margin-top:8px;border:1px dashed #d5dde3;background:#fff;border-radius:10px;padding:7px 9px;font-size:10.5px;color:#60707e}.pb-design-summary:before{content:'디자인 구성 · ';font-weight:850;color:#394d60}.pb-preview{margin:0 0 14px;border:1px solid #dfe5ea;border-radius:14px;background:#edf1f4;padding:14px}.pb-preview-label{font-size:9px;font-weight:900;letter-spacing:.14em;color:#667786;margin-bottom:7px}.pb-paper{background:#fff;border-radius:12px;padding:24px;min-height:250px;box-shadow:0 5px 18px rgba(20,40,60,.08)}.pb-paper h1{font-size:27px}.pb-summary{font-size:13px}.pb-body{font-size:12.5px}.pb-body h2{font-size:18px}.pb-body h3{font-size:15px}.pb-preview .pb-summary:empty{display:none}@media(max-width:700px){.pb-ai{grid-template-columns:1fr}.pb-ai button{width:100%}.pb-paper{padding:18px}.pb-paper h1{font-size:23px}.pb-template{padding:6px 8px}}`;document.head.appendChild(style);
  document.querySelectorAll('[data-pb-template]').forEach(b=>b.addEventListener('click',()=>{pbDesign={};pbSelect(b.dataset.pbTemplate)}));
  document.querySelector('#pbPreviewToggle')?.addEventListener('click',()=>{const p=document.querySelector('#pbPreview');p?.classList.toggle('hidden');pbPreview()});
  document.querySelector('#pbGenerate')?.addEventListener('click',pbGenerate);
  ['#pageTitle','#pageSummary','#pageBody'].forEach(sel=>document.querySelector(sel)?.addEventListener('input',pbPreview));
  document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit-page]');if(edit){pbPageId=edit.dataset.editPage;pbMetadata={};pbMetadataLoaded=false;pbLoadMetadata(pbPageId)}if(e.target.closest?.('#newPageBtn')){pbPageId=null;pbMetadata={};pbMetadataLoaded=true;pbDesign={};pbSelect('article')}},false);
  const modal=document.querySelector('#editorModal');if(modal)new MutationObserver(()=>{if(!modal.classList.contains('hidden')){setTimeout(()=>{pbSelect(pbTemplate);pbPreview()},40)}}).observe(modal,{attributes:true,attributeFilter:['class']});
  pbSelect('article');
}
function pbSelect(key){if(!PB_TEMPLATES[key])key='article';pbTemplate=key;document.querySelectorAll('[data-pb-template]').forEach(b=>b.classList.toggle('active',b.dataset.pbTemplate===key));const hint=document.querySelector('#pbTemplateHint');if(hint)hint.textContent=PB_TEMPLATES[key].hint;pbPreview()}
function pbPreview(){const p=document.querySelector('#pbPreview'),pd=pbPd();if(!p)return;const design=pd?.normalize(pbDesign,pbTemplate)||pbDesign;p.className=`pb-preview ${pbTemplate}${p.classList.contains('hidden')?' hidden':''}`;const paper=p.querySelector('.pb-paper');if(paper)paper.className=`pb-paper ${pd?.classNames(design,pbTemplate)||'pd-design'}`;const title=document.querySelector('#pageTitle')?.value.trim()||'페이지 제목',summary=document.querySelector('#pageSummary')?.value.trim()||'',body=document.querySelector('#pageBody')?.value||'';p.querySelector('h1').textContent=title;p.querySelector('.pb-summary').textContent=summary;p.querySelector('.pb-body').innerHTML=pd?.renderMarkdown(body)||pbEsc(body);p.querySelector('.pb-eyebrow').textContent=PB_TEMPLATES[pbTemplate].label;const ds=document.querySelector('#pbDesignSummary');if(ds)ds.textContent=pd?.describe(design,pbTemplate)||'기본 구성'}
async function pbLoadMetadata(id){if(!id||!pbRt)return;try{const rows=await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}&select=metadata&limit=1`);if(pbPageId!==id)return;pbMetadata=rows?.[0]?.metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{};pbMetadataLoaded=true;const saved=pbMetadata?.page_design&&typeof pbMetadata.page_design==='object'?pbMetadata.page_design:{};pbDesign={layout:saved.layout,hero:saved.hero,accent:saved.accent,section_style:saved.section_style,density:saved.density};pbSelect(saved.template||'article')}catch{pbMetadata={};pbMetadataLoaded=true;pbDesign={};pbSelect('article')}}
async function pbSaveMetadata(id){if(!id||!pbRt)return;if(!pbMetadataLoaded){try{const rows=await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}&select=metadata&limit=1`);pbMetadata=rows?.[0]?.metadata&&typeof rows[0].metadata==='object'?rows[0].metadata:{}}catch{pbMetadata={}}pbMetadataLoaded=true}const design=pbPd()?.normalize(pbDesign,pbTemplate)||pbDesign;const metadata={...pbMetadata,page_design:{template:pbTemplate,version:2,...design}};await pbRt.api(`/rest/v1/app_pages?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{metadata}});pbMetadata=metadata;pbPageId=id}
function pbParseAnswer(answer){let raw=String(answer||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(raw)}catch{return {body:String(answer||'').trim()}}}
async function pbGenerate(){if(pbGenerating)return;const prompt=document.querySelector('#pbPrompt')?.value.trim();if(!prompt)return;pbGenerating=true;const btn=document.querySelector('#pbGenerate'),st=document.querySelector('#pbAiStatus');if(btn){btn.disabled=true;btn.textContent='내용·디자인 생성 중…'}if(st){st.textContent='팀 업무자료를 참고해 내용과 화면 구성을 함께 만들고 있습니다.';st.className='status'}try{const type=PB_TEMPLATES[pbTemplate].label,projectId=document.querySelector('#pageSpace')?.value||null;const instruction=`${prompt}\n\n페이지 유형: ${type}. 현장 공유용 페이지의 내용과 디자인을 함께 구성해줘. 사실을 새로 만들어내지 말고 제공된 팀 업무 컨텍스트에 없는 정보는 [확인 필요]로 표시해. 다른 설명 없이 JSON 하나만 출력해. 형식은 {"title":"짧은 제목","summary":"1~2문장 요약","body":"Markdown 본문","design":{"layout":"editorial|dashboard|campaign|briefing 중 하나","hero":"minimal|band|split 중 하나","accent":"navy|blue|green|amber|red 중 하나","section_style":"plain|cards|rules 중 하나","density":"comfortable|compact 중 하나"}}. body는 ## 소제목, 불릿, 굵은 글씨를 사용하되 디자인 선택과 잘 맞는 정보 구조로 작성해.`;const data=await pbRt.api('/functions/v1/team-ai',{method:'POST',body:{prompt:instruction,scope:projectId?'project':'workspace',project_id:projectId||null}});const draft=pbParseAnswer(data?.answer||'');if(draft.title)document.querySelector('#pageTitle').value=String(draft.title).slice(0,160);if(draft.summary)document.querySelector('#pageSummary').value=String(draft.summary).slice(0,500);if(draft.body)document.querySelector('#pageBody').value=String(draft.body);if(draft.design&&typeof draft.design==='object')pbDesign=pbPd()?.normalize(draft.design,pbTemplate)||draft.design;pbPreview();document.querySelector('#pbPreview')?.classList.remove('hidden');if(st){st.textContent='내용과 디자인을 만들었습니다. 미리보기에서 확인·수정한 뒤 저장하세요.';st.className='status ok'}}catch(e){if(st){st.textContent=e.message||String(e);st.className='status error'}}finally{pbGenerating=false;if(btn){btn.disabled=false;btn.textContent='AI로 내용·디자인 만들기'}}}
window.KPTUPageBuilder={saveMetadata:pbSaveMetadata,get template(){return pbTemplate},get design(){return pbPd()?.normalize(pbDesign,pbTemplate)||pbDesign}};
pbInstall();