const SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const SESSION_KEY='kptu_collab_session_v1';
const $=s=>document.querySelector(s);
function status(msg,type=''){const el=$('#passwordResetStatus');if(!el)return;el.textContent=msg||'';el.className='status'+(type?' '+type:'')}
function inject(){
 const form=$('#authForm');
 if(form&&!$('#forgotPasswordBtn'))form.insertAdjacentHTML('afterend','<button id="forgotPasswordBtn" class="ghost wide" type="button" style="margin-top:8px">비밀번호를 잊으셨나요?</button>');
 if(!$('#forgotPasswordModal'))document.body.insertAdjacentHTML('beforeend',`<div id="forgotPasswordModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">PASSWORD RECOVERY</div><h2>비밀번호 찾기</h2><p>가입한 이메일로 비밀번호 재설정 링크를 보냅니다.</p></div><button id="forgotPasswordClose" class="icon-btn" type="button">×</button></div><label>이메일<input id="recoverEmail" type="email" autocomplete="email"></label><button id="sendRecoveryBtn" class="primary wide" type="button">재설정 메일 보내기</button><div id="passwordResetStatus" class="status"></div></div></div>`);
 if(!$('#changePasswordModal'))document.body.insertAdjacentHTML('beforeend',`<div id="changePasswordModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="eyebrow">NEW PASSWORD</div><h2>새 비밀번호 설정</h2><p>8자 이상으로 새 비밀번호를 입력해 주세요.</p><label>새 비밀번호<input id="newPassword" type="password" minlength="8" autocomplete="new-password"></label><label>비밀번호 확인<input id="newPasswordConfirm" type="password" minlength="8" autocomplete="new-password"></label><button id="changePasswordBtn" class="primary wide" type="button">비밀번호 변경</button><div id="changePasswordStatus" class="status"></div></div></div>`);
 $('#forgotPasswordBtn')?.addEventListener('click',()=>{const email=$('#authEmail')?.value?.trim()||'';$('#recoverEmail').value=email;$('#forgotPasswordModal').classList.remove('hidden');status('')});
 $('#forgotPasswordClose')?.addEventListener('click',()=>$('#forgotPasswordModal').classList.add('hidden'));
 $('#sendRecoveryBtn')?.addEventListener('click',sendRecovery);
 $('#changePasswordBtn')?.addEventListener('click',changePassword);
}
async function sendRecovery(){const email=$('#recoverEmail').value.trim();if(!email)return status('이메일을 입력해 주세요.','error');status('메일을 보내는 중…');const redirect='https://mj880616.github.io/work/app/';try{const r=await fetch(SB+'/auth/v1/recover?redirect_to='+encodeURIComponent(redirect),{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.error_description||'재설정 메일 발송에 실패했습니다.');status('가입된 계정이면 재설정 메일이 발송되었습니다. 메일의 링크를 눌러 주세요.','ok')}catch(e){status(e.message,'error')}}
function recoveryToken(){const h=new URLSearchParams(location.hash.replace(/^#/,''));return h.get('type')==='recovery'?h.get('access_token'):null}
async function changePassword(){const token=recoveryToken();const pw=$('#newPassword').value,confirm=$('#newPasswordConfirm').value;const st=$('#changePasswordStatus');if(!token){st.textContent='재설정 링크가 만료되었거나 유효하지 않습니다.';st.className='status error';return}if(pw.length<8){st.textContent='비밀번호는 8자 이상이어야 합니다.';st.className='status error';return}if(pw!==confirm){st.textContent='비밀번호 확인이 일치하지 않습니다.';st.className='status error';return}st.textContent='변경 중…';st.className='status';try{const r=await fetch(SB+'/auth/v1/user',{method:'PUT',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({password:pw})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.msg||d?.error_description||'비밀번호 변경에 실패했습니다.');localStorage.removeItem(SESSION_KEY);location.replace('./?password=changed')}catch(e){st.textContent=e.message;st.className='status error'}}
function handleRecovery(){const h=new URLSearchParams(location.hash.replace(/^#/,''));if(h.get('type')==='recovery'&&h.get('access_token')){$('#changePasswordModal')?.classList.remove('hidden');return}if(h.get('error_description')){const el=$('#authStatus');if(el){el.textContent=decodeURIComponent(h.get('error_description'));el.className='status error'}}const q=new URLSearchParams(location.search);if(q.get('password')==='changed'){const el=$('#authStatus');if(el){el.textContent='비밀번호가 변경되었습니다. 새 비밀번호로 로그인해 주세요.';el.className='status ok'}history.replaceState({},'',location.pathname)}}
inject();handleRecovery();