const SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const SESSION_KEY='kptu_collab_session_v1';
const MEDIA_FN=SB+'/functions/v1/event-media';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,user=null,workspaceId=null,events=[],photos=[],selectedEvent=null;
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function api(path,{method='GET',body=null}={}){session=getSession();if(!session?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(SB+path,{method,headers:{apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:body===null?null:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||'요청 실패');return d}
async function rpc(name,body){return api('/rest/v1/rpc/'+name,{method:'POST',body})}
async function media(action,{method='GET',form=null,params={}}={}){session=getSession();const u=new URL(MEDIA_FN);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const headers={Authorization:'Bearer '+session.access_token};const r=await fetch(u,{method,headers,body:form});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'사진 요청 실패');return d}
function injectDom(){
 const nav=$('.app-nav');if(nav&&!nav.querySelector('[data-view="photos"]'))nav.insertAdjacentHTML('beforeend','<button class="nav-btn" data-view="photos" type="button">포토룸</button>');
 if(!$('#photosView'))$('#appView')?.insertAdjacentHTML('beforeend',`<section id="photosView" class="view-panel hidden"><div class="section-head"><div><h2>포토룸</h2><p>팀 일정에서 올라온 사진을 날짜·이벤트·태그로 모아봅니다.</p></div><button id="photoUploadOpen" class="primary" type="button">+ 사진 올리기</button></div><div class="photo-toolbar"><input id="photoSearch" type="search" placeholder="이벤트명·캡션 검색"><select id="photoTagFilter"><option value="all">전체 태그</option><option>집회</option><option>기자회견</option><option>국회토론회</option><option>회의</option><option>교육</option><option>현장</option></select><input id="photoDateFilter" type="date"></div><div id="photoGrid" class="photo-grid"></div></section>`);
 if(!$('#eventRecordSection'))$('#calendarView')?.insertAdjacentHTML('beforeend',`<div id="eventRecordSection" class="section-head sub"><div><h3>일정 기록</h3><p>일정 본문·사진·댓글·관련자료를 함께 관리합니다.</p></div></div><div id="eventRecordList" class="card-list"></div>`);
 if(!$('#eventDetailModal'))document.body.insertAdjacentHTML('beforeend',`<div id="eventDetailModal" class="modal hidden" aria-hidden="true"><div class="modal-card event-detail-card"><div class="modal-head"><div><div class="eyebrow">EVENT WORKSPACE</div><h2 id="eventDetailTitle"></h2><p id="eventDetailMeta" class="muted"></p></div><button class="icon-btn" data-photo-close="eventDetailModal" type="button">×</button></div><div class="event-detail-grid"><section><h3>일정 본문</h3><textarea id="eventBody" rows="8" placeholder="이 일정에 대한 공통 메모·진행 상황을 적습니다."></textarea><button id="saveEventBody" class="secondary" type="button">본문 저장</button><h3>관련 자료</h3><div id="eventDocuments" class="stack-list"></div><div class="event-doc-form"><input id="eventDocTitle" type="text" placeholder="자료명"><input id="eventDocUrl" type="url" placeholder="Google Drive 또는 자료 URL"><select id="eventDocCategory"><option>회의자료</option><option>보도자료</option><option>정책자료</option><option>기타</option></select><button id="addEventDocument" class="secondary" type="button">자료 연결</button></div></section><section><h3>사진</h3><div id="eventPhotoStrip" class="event-photo-strip"></div><button id="eventPhotoUpload" class="secondary" type="button">사진 추가</button><h3>댓글</h3><div id="eventComments" class="stack-list"></div><div class="comment-compose"><input id="eventCommentBody" type="text" placeholder="댓글 입력"><button id="addEventComment" class="secondary" type="button">등록</button></div></section></div></div></div>`);
 if(!$('#photoUploadModal'))document.body.insertAdjacentHTML('beforeend',`<div id="photoUploadModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">PHOTO UPLOAD</div><h2>일정 사진 올리기</h2></div><button class="icon-btn" data-photo-close="photoUploadModal" type="button">×</button></div><label>일정<select id="photoEvent"></select></label><label>사진<input id="photoFile" type="file" accept="image/*" capture="environment"></label><label>간단한 설명<input id="photoCaption" type="text" maxlength="200"></label><label>태그<input id="photoTags" type="text" placeholder="집회, 기자회견, 회의"></label><div id="photoPreview" class="photo-preview"></div><button id="photoUploadBtn" class="primary wide" type="button">업로드</button><div id="photoUploadStatus" class="status"></div></div></div>`);
 const l=document.createElement('link');l.rel='stylesheet';l.href='./photo-room.css?v=1';document.head.appendChild(l);
}
function openModal(id){const m=$('#'+id);if(m){m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}}
function closeModal(id){const m=$('#'+id);if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}}
async function getContext(){session=getSession();if(!session?.access_token)return false;try{const u=await api('/auth/v1/user');user=u;const ms=await api('/rest/v1/app_workspace_members?user_id=eq.'+u.id+'&select=workspace_id&limit=1');if(!ms?.length)return false;workspaceId=ms[0].workspace_id;return true}catch{return false}}
async function loadEvents(){events=await api('/rest/v1/app_events?workspace_id=eq.'+workspaceId+'&select=id,title,start_at,event_type,location,body,description,project_id&order=start_at.desc');renderRecordList();$('#photoEvent').innerHTML=events.map(e=>`<option value="${e.id}">${new Date(e.start_at).toLocaleDateString('ko-KR')} · ${esc(e.title)}</option>`).join('')}
async function loadPhotos(){const d=await media('list');photos=d.photos||[];renderPhotos()}
function renderRecordList(){const now=Date.now(),rows=events.filter(e=>new Date(e.start_at).getTime()>now-90*86400000).slice(0,20);if($('#eventRecordList'))$('#eventRecordList').innerHTML=rows.map(e=>`<article class="item-card"><div><h3>${esc(e.title)}</h3><p>${new Date(e.start_at).toLocaleString('ko-KR')}${e.location?' · '+esc(e.location):''}</p><small>${e.body?esc(e.body.slice(0,120)):'아직 기록된 본문이 없습니다.'}</small></div><button class="mini" data-event-detail="${e.id}" type="button">상세·기록</button></article>`).join('')||'<div class="empty">일정이 없습니다.</div>'}
function renderPhotos(){const q=($('#photoSearch')?.value||'').trim().toLowerCase(),tag=$('#photoTagFilter')?.value||'all',date=$('#photoDateFilter')?.value||'';let rows=photos.filter(p=>{const text=((p.event?.title||'')+' '+(p.caption||'')+' '+(p.tags||[]).join(' ')).toLowerCase();const dt=(p.taken_at||p.event?.start_at||p.created_at||'').slice(0,10);return(!q||text.includes(q))&&(tag==='all'||(p.tags||[]).includes(tag))&&(!date||dt===date)});const groups={};rows.forEach(p=>{const d=(p.taken_at||p.event?.start_at||p.created_at||'').slice(0,10)||'날짜 미상';(groups[d]??=[]).push(p)});$('#photoGrid').innerHTML=Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).map(([d,ps])=>`<div class="photo-day"><h3>${esc(d)}</h3><div class="thumb-grid">${ps.map(p=>`<button class="photo-thumb" data-photo-event="${p.event_id}" title="${esc(p.caption||p.event?.title||'')}"><img src="${esc(p.thumb_url||p.url||'')}" loading="lazy" alt=""><span>${esc(p.event?.title||'')}</span>${p.caption?`<small>${esc(p.caption)}</small>`:''}</button>`).join('')}</div></div>`).join('')||'<div class="empty">조건에 맞는 사진이 없습니다.</div>'}
async function openEventDetail(id){selectedEvent=events.find(e=>e.id===id);if(!selectedEvent){await loadEvents();selectedEvent=events.find(e=>e.id===id)}if(!selectedEvent)return;$('#eventDetailTitle').textContent=selectedEvent.title;$('#eventDetailMeta').textContent=new Date(selectedEvent.start_at).toLocaleString('ko-KR')+(selectedEvent.location?' · '+selectedEvent.location:'');$('#eventBody').value=selectedEvent.body||'';await Promise.all([loadEventComments(id),loadEventDocuments(id),loadEventPhotos(id)]);openModal('eventDetailModal')}
async function loadEventComments(id){const rows=await api('/rest/v1/app_event_comments?event_id=eq.'+id+'&select=id,author_id,body,created_at&order=created_at.asc');const ps=await api('/rest/v1/app_profiles?select=user_id,display_name');const nm=x=>ps.find(p=>p.user_id===x)?.display_name||'팀원';$('#eventComments').innerHTML=rows.map(r=>`<div class="comment-row"><b>${esc(nm(r.author_id))}</b><span>${esc(r.body)}</span><small>${new Date(r.created_at).toLocaleString('ko-KR')}</small></div>`).join('')||'<div class="empty compact">댓글이 없습니다.</div>'}
async function loadEventDocuments(id){const rows=await api('/rest/v1/app_documents?event_id=eq.'+id+'&select=id,title,category,drive_url,description,document_date&order=created_at.desc');$('#eventDocuments').innerHTML=rows.map(r=>`<div class="list-item"><b>${esc(r.title)}</b><span>${esc(r.category||'자료')}</span>${r.drive_url?`<a href="${esc(r.drive_url)}" target="_blank" rel="noopener">열기</a>`:''}</div>`).join('')||'<div class="empty compact">연결된 자료가 없습니다.</div>'}
async function loadEventPhotos(id){const d=await media('list',{params:{event_id:id}});const rows=d.photos||[];$('#eventPhotoStrip').innerHTML=rows.map(p=>`<button class="strip-photo"><img src="${esc(p.thumb_url||p.url||'')}" alt=""><span>${esc(p.caption||'')}</span></button>`).join('')||'<div class="empty compact">사진이 없습니다.</div>'}
async function saveEventBody(){if(!selectedEvent)return;await rpc('app_update_event_body',{p_event:selectedEvent.id,p_body:$('#eventBody').value});selectedEvent.body=$('#eventBody').value;const idx=events.findIndex(e=>e.id===selectedEvent.id);if(idx>=0)events[idx].body=selectedEvent.body;renderRecordList();toastLocal('일정 본문을 저장했습니다.')}
async function addComment(){const body=$('#eventCommentBody').value.trim();if(!body||!selectedEvent)return;await api('/rest/v1/app_event_comments',{method:'POST',body:{event_id:selectedEvent.id,author_id:user.id,body}});$('#eventCommentBody').value='';await loadEventComments(selectedEvent.id)}
async function addDocument(){if(!selectedEvent)return;const title=$('#eventDocTitle').value.trim(),url=$('#eventDocUrl').value.trim();if(!title)return;await api('/rest/v1/app_documents',{method:'POST',body:{workspace_id:workspaceId,event_id:selectedEvent.id,title,category:$('#eventDocCategory').value,drive_url:url||null,visibility:'workspace',uploaded_by:user.id}});$('#eventDocTitle').value='';$('#eventDocUrl').value='';await loadEventDocuments(selectedEvent.id);toastLocal('일정과 자료실에 함께 등록했습니다.')}
async function compress(file,maxW=2000,quality=.82){const img=await createImageBitmap(file);const scale=Math.min(1,maxW/img.width);const w=Math.round(img.width*scale),h=Math.round(img.height*scale);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return await new Promise(res=>c.toBlob(res,'image/jpeg',quality))}
async function openPhotoUpload(eventId=null){if(!events.length)await loadEvents();$('#photoEvent').innerHTML=events.map(e=>`<option value="${e.id}" ${eventId===e.id?'selected':''}>${new Date(e.start_at).toLocaleDateString('ko-KR')} · ${esc(e.title)}</option>`).join('');$('#photoFile').value='';$('#photoCaption').value='';$('#photoTags').value='';$('#photoPreview').innerHTML='';setPhotoStatus('');openModal('photoUploadModal')}
function setPhotoStatus(m,t=''){const el=$('#photoUploadStatus');el.textContent=m;el.className='status'+(t?' '+t:'')}
async function uploadPhoto(){const f=$('#photoFile').files?.[0],eventId=$('#photoEvent').value;if(!f||!eventId)return setPhotoStatus('사진과 일정을 선택해 주세요.','error');setPhotoStatus('이미지 최적화 중…');try{const [main,thumb]=await Promise.all([compress(f,2000,.82),compress(f,480,.76)]);const fd=new FormData();fd.append('event_id',eventId);fd.append('image',main,'photo.jpg');fd.append('thumb',thumb,'thumb.jpg');fd.append('caption',$('#photoCaption').value.trim());fd.append('tags',$('#photoTags').value.trim());fd.append('taken_at',new Date(f.lastModified||Date.now()).toISOString());setPhotoStatus('업로드 중…');await media('upload',{method:'POST',form:fd});closeModal('photoUploadModal');await loadPhotos();if(selectedEvent?.id===eventId)await loadEventPhotos(eventId);toastLocal('사진을 올렸습니다.')}catch(e){setPhotoStatus(e.message,'error')}}
function toastLocal(msg){const t=$('#toast');if(t){t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2500)}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.eventDetail){openEventDetail(b.dataset.eventDetail);return}if(b.dataset.photoEvent){openEventDetail(b.dataset.photoEvent);return}if(b.dataset.photoClose){closeModal(b.dataset.photoClose);return}});$('#photoUploadOpen').onclick=()=>openPhotoUpload();$('#eventPhotoUpload').onclick=()=>openPhotoUpload(selectedEvent?.id);$('#photoUploadBtn').onclick=uploadPhoto;$('#saveEventBody').onclick=saveEventBody;$('#addEventComment').onclick=addComment;$('#addEventDocument').onclick=addDocument;$('#photoSearch').oninput=renderPhotos;$('#photoTagFilter').onchange=renderPhotos;$('#photoDateFilter').onchange=renderPhotos;$('#photoFile').onchange=()=>{const f=$('#photoFile').files?.[0];if(f)$('#photoPreview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="">`}}
async function bootWhenReady(){injectDom();bind();const check=async()=>{if(!$('#appView')||$('#appView').classList.contains('hidden'))return false;if(!(await getContext()))return false;await Promise.all([loadEvents(),loadPhotos()]);return true};if(await check())return;const obs=new MutationObserver(async()=>{if(await check())obs.disconnect()});obs.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']})}
bootWhenReady();