(()=>{
'use strict';
const rt=window.KPTURuntime;if(!rt)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=(p,o={})=>rt.api(p,o);
let user=null,workspaceId=null,archived=[],bound=false,detailObserver=null;
function isV2(p){return p?.metadata?.project_system==='v2'||Number(p?.metadata?.management_version)===2}
function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2400)}
async function context(){if(!(await rt.session.ensure()))return false;user=await api('/auth/v1/user');const ms=await api(`/rest/v1/app_workspace_members?user_id=eq.${user.id}&select=workspace_id&limit=1`);workspaceId=ms?.[0]?.workspace_id||null;return !!workspaceId}
function ensureStyle(){if(document.querySelector('#projectArchiveStyle'))return;const s=document.createElement('style');s.id='projectArchiveStyle';s.textContent=`.pa-danger{color:#9a3340!important;border-color:#e5c7cc!important}.pa-profile-list{display:grid;gap:7px}.pa-profile-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid #edf0f3}.pa-profile-row:first-child{border-top:0}.pa-profile-main{min-width:0}.pa-profile-main b{display:block;font-size:12px}.pa-profile-main p{margin:3px 0 0;font-size:10.5px;line-height:1.45;color:#73818c}.pa-profile-main small{display:block;margin-top:4px;font-size:9.5px;color:#919aa2}.pa-profile-empty{font-size:11px;color:#87919b;padding:5px 0}.pa-profile-note{margin:0 0 9px;color:#7b8790;font-size:10.5px;line-height:1.5}@media(max-width:700px){.pa-profile-row{grid-template-columns:1fr}.pa-profile-row button{justify-self:start}}`;document.head.appendChild(s)}
function ensureProfilePanel(){const grid=document.querySelector('#profileView .ps-profile-grid');if(!grid||document.querySelector('#paArchivedProjectsPanel'))return false;grid.insertAdjacentHTML('beforeend',`<article id="paArchivedProjectsPanel" class="panel"><div class="panel-head"><div><h3>보관한 프로젝트</h3><p>Live 프로젝트에서 보관 처리한 프로젝트입니다.</p></div></div><p class="pa-profile-note">보관한 프로젝트는 프로젝트 목록에서 숨겨지며 데이터는 그대로 유지됩니다. 필요할 때 다시 Live 프로젝트로 복구할 수 있습니다.</p><div id="paArchivedProjectsList"><div class="pa-profile-empty">보관한 프로젝트가 없습니다.</div></div></article>`);return true}
function fmtDate(v){if(!v)return'';try{return new Date(v).toLocaleDateString('ko-KR',{year:'numeric',month:'numeric',day:'numeric'})}catch{return''}}
function renderArchived(){ensureProfilePanel();const host=document.querySelector('#paArchivedProjectsList');if(!host)return;host.innerHTML=archived.length?`<div class="pa-profile-list">${archived.map(p=>`<div class="pa-profile-row"><div class="pa-profile-main"><b>${esc(p.name)}</b><p>${esc(p.metadata?.objective||p.description||'설명 없음')}</p><small>${p.parent_id?'하위 프로젝트 · ':''}보관 상태${p.updated_at?' · '+esc(fmtDate(p.updated_at)):''}</small></div><button class="secondary" data-pa-restore="${p.id}" type="button">Live 프로젝트로 복구</button></div>`).join('')}</div>`:'<div class="pa-profile-empty">보관한 프로젝트가 없습니다.</div>'}
async function loadArchived(){if(!workspaceId&&!(await context()))return[];const rows=await api(`/rest/v1/app_spaces?workspace_id=eq.${workspaceId}&status=eq.archived&select=id,name,description,parent_id,status,owner_id,metadata,updated_at&order=updated_at.desc`);archived=(rows||[]).filter(isV2);renderArchived();return archived}
function currentProjectId(){try{return new URL(location.href).searchParams.get('project')}catch{return null}}
function injectArchiveButton(){const modal=document.querySelector('#pm2DetailModal');if(!modal||modal.classList.contains('hidden'))return;const actions=modal.querySelector('#pm2DetailBody .pm2-detail-head .pm2-actions');if(!actions||actions.querySelector('[data-pa-archive]'))return;const id=currentProjectId();if(!id)return;const b=document.createElement('button');b.className='mini pa-danger';b.type='button';b.dataset.paArchive=id;b.textContent='프로젝트 보관';actions.appendChild(b)}
function observeDetail(){const body=document.querySelector('#pm2DetailBody');if(!body||detailObserver)return;detailObserver=new MutationObserver(()=>queueMicrotask(injectArchiveButton));detailObserver.observe(body,{childList:true,subtree:true});injectArchiveButton()}
async function fetchProject(id){const rows=await api(`/rest/v1/app_spaces?id=eq.${encodeURIComponent(id)}&select=id,name,description,parent_id,status,metadata&limit=1`);const p=rows?.[0];return p&&isV2(p)?p:null}
async function archiveProject(id){const p=await fetchProject(id);if(!p||p.status==='archived')return;const extra=p.parent_id?'':'\n하위 프로젝트가 있다면 상위 프로젝트가 보관된 동안 프로젝트 화면에서 함께 보이지 않습니다.';if(!confirm(`“${p.name}” 프로젝트를 보관할까요?\n\n보관하면 Live 프로젝트 목록에서 숨겨지고, 프로필 > 보관한 프로젝트에서 다시 복구할 수 있습니다.${extra}`))return;await api(`/rest/v1/app_spaces?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{status:'archived',updated_at:new Date().toISOString()}});toast('프로젝트를 보관했습니다.');window.dispatchEvent(new CustomEvent('kptu:project-status-changed',{detail:{id,status:'archived'}}));const u=new URL(location.href);u.searchParams.delete('project');history.replaceState({},'',u);setTimeout(()=>location.reload(),180)}
async function restoreProject(id){const p=archived.find(x=>x.id===id)||await fetchProject(id);if(!p)return;await api(`/rest/v1/app_spaces?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{status:'active',updated_at:new Date().toISOString()}});archived=archived.filter(x=>x.id!==id);renderArchived();toast('Live 프로젝트로 복구했습니다.');window.dispatchEvent(new CustomEvent('kptu:project-status-changed',{detail:{id,status:'active'}}));setTimeout(()=>location.reload(),260)}
function bind(){if(bound)return;bound=true;document.addEventListener('click',e=>{const a=e.target.closest?.('[data-pa-archive]');if(a){e.preventDefault();archiveProject(a.dataset.paArchive).catch(err=>toast(err.message||String(err)));return}const r=e.target.closest?.('[data-pa-restore]');if(r){e.preventDefault();restoreProject(r.dataset.paRestore).catch(err=>toast(err.message||String(err)));return}if(e.target.closest?.('[data-pm2-project]'))setTimeout(()=>{observeDetail();injectArchiveButton()},120)},true);window.KPTURouter?.on?.('profile',()=>{ensureProfilePanel();loadArchived().catch(console.error)});window.addEventListener('kptu:session-changed',()=>{user=null;workspaceId=null;archived=[];setTimeout(()=>{context().then(ok=>ok&&loadArchived()).catch(console.error)},0)})}
async function boot(){ensureStyle();ensureProfilePanel();bind();observeDetail();if(await context())await loadArchived();injectArchiveButton()}
window.KPTUProjectArchive={load:loadArchived,archive:archiveProject,restore:restoreProject};
boot().catch(console.error);
})();
