const pdRt=window.KPTURuntime;
let pdUser=null,pdWorkspace=null,pdProject=null,pdSpaces=[];
const pdE=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pdApi=(p,o={})=>pdRt.api(p,o);
function pdId(){return new URLSearchParams(location.search).get('project')||''}
function pdInstall(){if(document.querySelector('#deleteProjectBtn'))return;const add=document.querySelector('#newSubprojectBtn');if(add){const b=document.createElement('button');b.id='deleteProjectBtn';b.type='button';b.className='mini hidden';b.textContent='삭제';b.style.color='#a33b45';add.insertAdjacentElement('afterend',b);b.addEventListener('click',pdOpen)}document.body.insertAdjacentHTML('beforeend',`<div id="pdModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">DELETE PROJECT</div><h2>프로젝트 삭제</h2></div><button class="icon-btn" data-pd-close type="button">×</button></div><div id="pdMessage" class="notice"></div><p class="muted">연결된 할 일·일정·회의·자료·공유 페이지 자체는 삭제하지 않고 프로젝트 연결만 해제됩니다. 프로젝트 전용 현황·체크리스트·댓글 등은 함께 삭제됩니다.</p><button id="pdConfirm" class="primary wide" type="button" style="background:#a33b45;border-color:#a33b45">삭제</button><div id="pdState" class="status"></div></div></div>`);document.querySelector('[data-pd-close]')?.addEventListener('click',()=>pdModal(false));document.querySelector('#pdConfirm')?.addEventListener('click',pdDelete)}
function pdModal(on){const m=document.querySelector('#pdModal');if(!m)return;m.classList.toggle('hidden',!on);m.setAttribute('aria-hidden',on?'false':'true')}
async function pdContext(){if(!pdRt||!(await pdRt.session.ensure()))return false;pdUser=await pdApi('/auth/v1/user');const m=await pdApi(`/rest/v1/app_workspace_members?user_id=eq.${pdUser.id}&select=workspace_id&limit=1`);if(!m?.length)return false;pdWorkspace=m[0].workspace_id;return true}
function pdDescendants(id){const out=[];const walk=p=>pdSpaces.filter(x=>x.parent_id===p).forEach(x=>{out.push(x);walk(x.id)});walk(id);return out}
async function pdRefresh(id=pdId()){pdInstall();if(!id){document.querySelector('#deleteProjectBtn')?.classList.add('hidden');pdProject=null;return}if(!pdUser&&!(await pdContext()))return;pdSpaces=await pdApi(`/rest/v1/app_spaces?workspace_id=eq.${pdWorkspace}&select=id,parent_id,name,owner_id,status`);pdProject=pdSpaces.find(x=>x.id===id)||null;document.querySelector('#deleteProjectBtn')?.classList.toggle('hidden',!pdProject||pdProject.owner_id!==pdUser.id)}
async function pdOpen(){const id=pdId();if(!id||!pdProject||pdProject.id!==id)await pdRefresh(id);if(!pdProject||pdProject.owner_id!==pdUser.id)return;const kids=pdDescendants(pdProject.id),kind=pdProject.parent_id?'하위 프로젝트':'프로젝트';document.querySelector('#pdMessage').innerHTML=`<b>${pdE(pdProject.name)}</b><br>${kind}을 삭제합니다.${kids.length?` 하위 프로젝트 <b>${kids.length}개</b>도 함께 삭제됩니다.`:''}`;document.querySelector('#pdState').textContent='';pdModal(true)}
async function pdDelete(){if(!pdProject||pdProject.owner_id!==pdUser.id)return;const btn=document.querySelector('#pdConfirm'),st=document.querySelector('#pdState');btn.disabled=true;st.textContent='삭제 중…';try{await pdApi(`/rest/v1/app_spaces?id=eq.${encodeURIComponent(pdProject.id)}&owner_id=eq.${encodeURIComponent(pdUser.id)}`,{method:'DELETE'});const u=new URL(location.href);u.searchParams.delete('project');location.href=u.pathname+(u.search||'')+u.hash}catch(e){st.textContent=e.message||String(e);st.className='status error';btn.disabled=false}}
document.addEventListener('click',e=>{const card=e.target.closest?.('[data-project]');if(card?.dataset.project)setTimeout(()=>pdRefresh(card.dataset.project),60);const close=e.target.closest?.('[data-close="projectModal"]');if(close)setTimeout(()=>pdRefresh(''),0)},true);window.addEventListener('popstate',()=>setTimeout(()=>pdRefresh(),60));window.addEventListener('kptu:session-changed',()=>{pdUser=null;pdWorkspace=null;setTimeout(()=>pdRefresh(),100)});pdInstall();pdContext().then(()=>pdRefresh());
