const PF_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const PF_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const PF_SESSION='kptu_collab_session_v1';
let pfProjectId=null,pfSession=null;
function pfRead(){try{return JSON.parse(localStorage.getItem(PF_SESSION)||'null')}catch{return null}}
async function pfEnsure(){pfSession=pfRead();if(!pfSession)return false;if((pfSession.expires_at||0)<Math.floor(Date.now()/1000)+60&&pfSession.refresh_token){const r=await fetch(PF_SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:PF_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:pfSession.refresh_token})});if(!r.ok)return false;const d=await r.json();d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);pfSession=d;localStorage.setItem(PF_SESSION,JSON.stringify(d))}return true}
async function pfApi(path,opts={}){if(!(await pfEnsure()))throw new Error('로그인이 필요합니다.');const h={apikey:PF_KEY,Authorization:'Bearer '+pfSession.access_token};if(opts.json){h['Content-Type']='application/json'}const r=await fetch(PF_SB+path,{method:opts.method||'GET',headers:h,body:opts.body?(opts.json?JSON.stringify(opts.body):opts.body):null});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok||d?.error)throw new Error(d?.error||d?.message||('요청 실패 '+r.status));return d}
function pfEsc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pfEnsureUi(){const modal=document.querySelector('#projectModal .project-modal');if(!modal||document.querySelector('#projectFilesSection'))return;const sec=document.createElement('section');sec.id='projectFilesSection';sec.className='project-files-section';sec.innerHTML='<div class="project-files-head"><div><h3>관련 파일</h3><p>파일은 Google Drive에 저장되고 자료실에도 자동 등록됩니다.</p></div><label class="project-file-upload"><input id="projectFileInput" type="file" hidden><span>+ 파일 업로드</span></label></div><div id="projectFileStatus" class="status"></div><div id="projectFileList" class="stack-list"><div class="empty compact">불러오는 중…</div></div>';modal.querySelector('.project-detail-grid')?.insertAdjacentElement('afterend',sec);const input=sec.querySelector('#projectFileInput');input?.addEventListener('change',pfUpload);const style=document.createElement('style');style.textContent='.project-files-section{margin-top:18px;padding-top:18px;border-top:1px solid #e7ebef}.project-files-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.project-files-head h3{margin:0 0 3px}.project-files-head p{margin:0;color:#7b8792;font-size:12px}.project-file-upload span{display:inline-block;padding:9px 12px;border:1px solid #cfd7df;border-radius:10px;font-weight:750;cursor:pointer;background:#fff}.project-file-row{display:flex;justify-content:space-between;gap:12px;align-items:center}.project-file-row>div{min-width:0}.project-file-row b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.project-file-row small{color:#7a8590}.project-file-actions{display:flex;gap:6px;flex-shrink:0}';document.head.appendChild(style)}
async function pfList(){if(!pfProjectId)return;pfEnsureUi();const box=document.querySelector('#projectFileList');if(!box)return;box.innerHTML='<div class="empty compact">불러오는 중…</div>';try{const rows=await pfApi('/rest/v1/app_documents?project_id=eq.'+encodeURIComponent(pfProjectId)+'&file_id=not.is.null&select=id,title,file_name,mime_type,file_size,category,created_at&order=created_at.desc');box.innerHTML=rows.length?rows.map(d=>`<div class="list-item project-file-row"><div><b>${pfEsc(d.file_name||d.title)}</b><small>${pfEsc(d.category||'기타')} · ${new Date(d.created_at).toLocaleDateString('ko-KR')}${d.file_size?' · '+pfSize(d.file_size):''}</small></div><div class="project-file-actions"><button class="mini" type="button" data-pf-download="${d.id}">다운로드</button></div></div>`).join(''):'<div class="empty compact">등록된 파일이 없습니다.</div>';box.querySelectorAll('[data-pf-download]').forEach(b=>b.onclick=()=>pfDownload(b.dataset.pfDownload))}catch(e){box.innerHTML='<div class="empty compact">'+pfEsc(e.message)+'</div>'}}
function pfSize(n){n=Number(n)||0;if(n<1024)return n+'B';if(n<1048576)return (n/1024).toFixed(1)+'KB';return (n/1048576).toFixed(1)+'MB'}
async function pfUpload(e){const file=e.target.files?.[0],st=document.querySelector('#projectFileStatus');if(!file||!pfProjectId)return;st.textContent='업로드 중…';st.className='status';try{if(!(await pfEnsure()))throw new Error('로그인이 필요합니다.');const fd=new FormData();fd.append('project_id',pfProjectId);fd.append('file',file);const r=await fetch(PF_SB+'/functions/v1/workspace-drive?action=upload',{method:'POST',headers:{Authorization:'Bearer '+pfSession.access_token},body:fd});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'업로드 실패');st.textContent='업로드 완료 · 자료실에도 등록되었습니다.';st.className='status ok';e.target.value='';await pfList()}catch(err){st.textContent=err.message;st.className='status error'}}
async function pfDownload(id){try{const d=await pfApi('/functions/v1/workspace-drive?action=download-token',{method:'POST',json:true,body:{document_id:id}});location.href=d.url}catch(e){const st=document.querySelector('#projectFileStatus');if(st){st.textContent=e.message;st.className='status error'}}}
function pfOpenProject(id){pfProjectId=id;setTimeout(()=>{pfEnsureUi();pfList()},120)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b?.dataset.project)pfOpenProject(b.dataset.project)},true);
const pm=document.querySelector('#projectModal');if(pm)new MutationObserver(()=>{if(!pm.classList.contains('hidden')&&pfProjectId){pfEnsureUi();pfList()}}).observe(pm,{attributes:true,attributeFilter:['class']});
pfEnsureUi();