(()=>{
'use strict';
const rt=window.KPTURuntime;if(!rt)return;
let user=null,workspaceId=null,myName='',orgs=[],assignments=[],profiles=[],updates=[],councils=[],affiliations=[],editingOrgId=null,observer=null,refreshTimer=null,sorting=false;
const api=(p,o={})=>rt.api(p,o);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLocaleLowerCase('ko-KR');
const profileName=id=>profiles.find(x=>x.user_id===id)?.display_name||'';
const actualAssignees=id=>assignments.filter(x=>x.organization_id===id);
function effectiveNames(o){const a=actualAssignees(o.id).map(x=>profileName(x.user_id)).filter(Boolean);return a.length?a:(o.default_assignee_name?[o.default_assignee_name]:[])}
function isMine(o){const a=actualAssignees(o.id);if(a.some(x=>x.user_id===user?.id))return true;return !a.length&&!!myName&&norm(o.default_assignee_name)===norm(myName)}
function lastUpdate(id){const row=updates.find(x=>x.organization_id===id);return row?.occurred_at?new Date(row.occurred_at):null}
function isStale(o){const d=lastUpdate(o.id);return !d||Date.now()-d.getTime()>30*86400000}
function councilIds(id){return affiliations.filter(x=>x.organization_id===id).map(x=>x.tag_id)}
function installStyle(){if(document.querySelector('#sofStyle'))return;const s=document.createElement('style');s.id='sofStyle';s.textContent=`
.sof-tools{display:grid;grid-template-columns:minmax(180px,1.6fr) repeat(3,minmax(120px,.7fr));gap:8px;margin:0 0 10px}.sof-flags{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 10px}.sof-flag{display:inline-flex;align-items:center;gap:5px;padding:6px 9px;border:1px solid #dde4e9;border-radius:999px;background:#fff;font-size:11px;font-weight:700;color:#526270;cursor:pointer}.sof-flag input{width:auto!important;margin:0!important}.sof-meta{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:0 0 8px;font-size:11px;color:#788590}.sof-reset{border:0;background:transparent;color:#536b81;font-size:11px;cursor:pointer;padding:2px 0}.sof-type{display:inline-flex;margin-left:6px;padding:2px 6px;border-radius:999px;background:#f1f4f6;color:#667582;font-size:9px;font-weight:800;vertical-align:1px}.sof-no-results{padding:18px;text-align:center;color:#77838d;border:1px dashed #dfe5ea;border-radius:12px}.sof-hidden{display:none!important}.sof-type-label{display:block;margin-top:10px}.sof-type-label input{width:100%}
@media(max-width:980px){.sof-tools{grid-template-columns:1fr 1fr}.sof-tools .sof-search{grid-column:1/-1}}@media(max-width:520px){.sof-tools{grid-template-columns:1fr}.sof-tools .sof-search{grid-column:auto}.sof-flags{gap:5px}.sof-flag{font-size:10px;padding:6px 8px}}
`;document.head.appendChild(s)}
async function context(){if(!(await rt.session.ensure()))return false;user=await api('/auth/v1/user');const ms=await api(`/rest/v1/app_workspace_members?user_id=eq.${user.id}&select=workspace_id&limit=1`);workspaceId=ms?.[0]?.workspace_id||null;if(!workspaceId)return false;profiles=await api('/rest/v1/app_profiles?select=user_id,display_name');myName=profileName(user.id)||user?.user_metadata?.display_name||'';return true}
async function loadData(){if(!workspaceId)return;[orgs,assignments,updates,councils,affiliations]=await Promise.all([
 api(`/rest/v1/app_suborganizations?workspace_id=eq.${workspaceId}&active=eq.true&select=id,name,aliases,description,organization_type,default_assignee_name&order=name.asc`),
 api('/rest/v1/app_suborganization_assignees?select=organization_id,user_id'),
 api('/rest/v1/app_suborganization_updates?select=organization_id,occurred_at&order=occurred_at.desc'),
 api(`/rest/v1/app_org_affiliation_tags?workspace_id=eq.${workspaceId}&active=eq.true&kind=eq.council&select=id,name&order=name.asc`),
 api('/rest/v1/app_suborganization_affiliations?select=organization_id,tag_id')
]);orgs.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'ko'));renderOptions();sortCards();apply();decorateCards()}
function installToolbar(){const list=document.querySelector('#soOrganizationList');if(!list||document.querySelector('#sofToolbar'))return false;const bar=document.createElement('div');bar.id='sofToolbar';bar.innerHTML=`<div class="sof-tools"><input id="sofSearch" class="sof-search" type="search" placeholder="조직명·약칭·설명 검색"><select id="sofAssignee"><option value="">담당자 전체</option></select><select id="sofCouncil"><option value="">협의회 전체</option></select><select id="sofType"><option value="">조직유형 전체</option></select></div><div class="sof-flags"><label class="sof-flag"><input id="sofMine" type="checkbox"> 내 담당조직</label><label class="sof-flag"><input id="sofUnassigned" type="checkbox"> 담당자 미지정</label><label class="sof-flag"><input id="sofStale" type="checkbox"> 30일 이상 업데이트 없음</label></div><div class="sof-meta"><span id="sofCount"></span><button id="sofReset" class="sof-reset" type="button">필터 초기화</button></div>`;list.insertAdjacentElement('beforebegin',bar);['sofSearch','sofAssignee','sofCouncil','sofType','sofMine','sofUnassigned','sofStale'].forEach(id=>document.querySelector('#'+id)?.addEventListener(id==='sofSearch'?'input':'change',apply));document.querySelector('#sofReset')?.addEventListener('click',reset);observeList();return true}
function renderOptions(){if(!installToolbar()){}const assignee=document.querySelector('#sofAssignee'),council=document.querySelector('#sofCouncil'),type=document.querySelector('#sofType');if(!assignee||!council||!type)return;const av=assignee.value,cv=council.value,tv=type.value;const names=[...new Set(orgs.flatMap(effectiveNames).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));const cs=[...councils].sort((a,b)=>a.name.localeCompare(b.name,'ko'));const types=[...new Set(orgs.map(o=>o.organization_type||'미분류'))].sort((a,b)=>a.localeCompare(b,'ko'));assignee.innerHTML='<option value="">담당자 전체</option>'+names.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');council.innerHTML='<option value="">협의회 전체</option>'+cs.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');type.innerHTML='<option value="">조직유형 전체</option>'+types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(names.includes(av))assignee.value=av;if(cs.some(x=>x.id===cv))council.value=cv;if(types.includes(tv))type.value=tv}
function state(){return{q:norm(document.querySelector('#sofSearch')?.value),assignee:document.querySelector('#sofAssignee')?.value||'',council:document.querySelector('#sofCouncil')?.value||'',type:document.querySelector('#sofType')?.value||'',mine:!!document.querySelector('#sofMine')?.checked,unassigned:!!document.querySelector('#sofUnassigned')?.checked,stale:!!document.querySelector('#sofStale')?.checked}}
function matches(o,s){const names=effectiveNames(o),hay=norm([o.name,...(o.aliases||[]),o.description||'',o.default_assignee_name||''].join(' '));if(s.q&&!hay.includes(s.q))return false;if(s.assignee&&!names.includes(s.assignee))return false;if(s.council&&!councilIds(o.id).includes(s.council))return false;if(s.type&&(o.organization_type||'미분류')!==s.type)return false;if(s.mine&&!isMine(o))return false;if(s.unassigned&&names.length)return false;if(s.stale&&!isStale(o))return false;return true}
function sortCards(){if(sorting)return;const list=document.querySelector('#soOrganizationList');if(!list)return;const cards=[...list.querySelectorAll('.so-card[data-so-org]')];if(cards.length<2)return;const names=new Map(orgs.map(o=>[o.id,o.name||'']));const sorted=[...cards].sort((a,b)=>String(names.get(a.dataset.soOrg)||'').localeCompare(String(names.get(b.dataset.soOrg)||''),'ko'));if(cards.every((x,i)=>x===sorted[i]))return;sorting=true;sorted.forEach(card=>list.appendChild(card));sorting=false}
function apply(){const list=document.querySelector('#soOrganizationList');if(!list)return;sortCards();const s=state();let shown=0;orgs.forEach(o=>{const card=list.querySelector(`.so-card[data-so-org="${CSS.escape(o.id)}"]`);if(!card)return;const ok=matches(o,s);card.classList.toggle('sof-hidden',!ok);if(ok)shown++});let empty=list.querySelector('#sofNoResults');if(!empty){empty=document.createElement('div');empty.id='sofNoResults';empty.className='sof-no-results sof-hidden';empty.textContent='조건에 맞는 산하조직이 없습니다.';list.appendChild(empty)}empty.classList.toggle('sof-hidden',shown!==0||orgs.length===0);const c=document.querySelector('#sofCount');if(c)c.textContent=`${shown} / ${orgs.length}개 조직`}
function decorateCards(){const list=document.querySelector('#soOrganizationList');if(!list)return;orgs.forEach(o=>{const h=list.querySelector(`.so-card[data-so-org="${CSS.escape(o.id)}"] h4`);if(!h||h.querySelector('.sof-type'))return;h.insertAdjacentHTML('beforeend',`<span class="sof-type">${esc(o.organization_type||'미분류')}</span>`)})}
function reset(){const q=document.querySelector('#sofSearch'),a=document.querySelector('#sofAssignee'),c=document.querySelector('#sofCouncil'),t=document.querySelector('#sofType'),m=document.querySelector('#sofMine'),u=document.querySelector('#sofUnassigned'),s=document.querySelector('#sofStale');if(q)q.value='';if(a)a.value='';if(c)c.value='';if(t)t.value='';if(m)m.checked=false;if(u)u.checked=false;if(s)s.checked=false;apply()}
function observeList(){const list=document.querySelector('#soOrganizationList');if(!list||observer)return;observer=new MutationObserver(()=>{if(sorting)return;clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{sortCards();decorateCards();apply()},30)});observer.observe(list,{childList:true,subtree:false})}
function installTypeField(){const modal=document.querySelector('#soEditModal .modal-card');const aliases=document.querySelector('#soEditAliases')?.closest('label');if(!modal||!aliases||document.querySelector('#sofEditType'))return;const label=document.createElement('label');label.className='sof-type-label';label.innerHTML='조직유형 <span class="optional">선택</span><input id="sofEditType" type="text" maxlength="80" list="sofTypeSuggestions" placeholder="예: 철도·도시철도"><datalist id="sofTypeSuggestions"><option value="중앙공공기관"><option value="지방공기업·출연기관"><option value="철도·도시철도"><option value="자회사·용역"><option value="기타"></datalist>';aliases.insertAdjacentElement('afterend',label);wrapSave()}
function fillType(id){editingOrgId=id||null;const input=document.querySelector('#sofEditType');if(!input)return;const o=id?orgs.find(x=>x.id===id):null;input.value=o?.organization_type&&o.organization_type!=='미분류'?o.organization_type:''}
function wrapSave(){const btn=document.querySelector('#soSaveOrg');if(!btn||btn.dataset.sofWrapped==='1')return;btn.dataset.sofWrapped='1';const old=btn.onclick;btn.onclick=async function(e){const type=document.querySelector('#sofEditType')?.value.trim()||'미분류',name=document.querySelector('#soEditName')?.value.trim()||'',id=editingOrgId;const ret=await old?.call(this,e);if(document.querySelector('#soEditModal')?.classList.contains('hidden')){try{let target=id;if(!target&&name){const rows=await api(`/rest/v1/app_suborganizations?workspace_id=eq.${workspaceId}&name=eq.${encodeURIComponent(name)}&select=id&order=created_at.desc&limit=1`);target=rows?.[0]?.id||null}if(target)await api(`/rest/v1/app_suborganizations?id=eq.${target}`,{method:'PATCH',body:{organization_type:type,updated_at:new Date().toISOString()}});await loadData();window.dispatchEvent(new Event('kptu:suborganization-updated'))}catch(err){console.warn('organization type save',err)}}return ret}}
function bind(){document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-so-edit]');if(edit){setTimeout(()=>{installTypeField();fillType(edit.dataset.soEdit)},0);return}if(e.target.closest?.('#soAddOrg'))setTimeout(()=>{installTypeField();fillType(null)},0)},true);window.addEventListener('kptu:view-changed',e=>{if(e.detail?.view==='team')setTimeout(()=>{installToolbar();installTypeField();loadData().catch(console.error)},60)});window.addEventListener('kptu:suborganization-updated',()=>setTimeout(()=>loadData().catch(console.error),40))}
async function init(){installStyle();if(!(await context()))return;installToolbar();installTypeField();bind();await loadData()}
setTimeout(()=>init().catch(console.error),0);
})();