(()=>{
'use strict';
const rt=window.KPTURuntime;if(!rt)return;
let user=null,workspaceId=null,myName='',orgs=[],assignments=[],profiles=[],councils=[],affiliations=[],sorting=false,bound=false;
const api=(p,o={})=>rt.api(p,o);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLocaleLowerCase('ko-KR');
const profileName=id=>profiles.find(x=>x.user_id===id)?.display_name||'';
const actualAssignees=id=>assignments.filter(x=>x.organization_id===id);
function effectiveNames(o){const a=actualAssignees(o.id).map(x=>profileName(x.user_id)).filter(Boolean);return a.length?a:(o.default_assignee_name?[o.default_assignee_name]:[])}
function isMine(o){const a=actualAssignees(o.id);if(a.some(x=>x.user_id===user?.id))return true;return !a.length&&!!myName&&norm(o.default_assignee_name)===norm(myName)}
function councilIds(id){return affiliations.filter(x=>x.organization_id===id).map(x=>x.tag_id)}
async function context(){if(!(await rt.session.ensure()))return false;user=await api('/auth/v1/user');const ms=await api(`/rest/v1/app_workspace_members?user_id=eq.${user.id}&select=workspace_id&limit=1`);workspaceId=ms?.[0]?.workspace_id||null;if(!workspaceId)return false;profiles=await api('/rest/v1/app_profiles?select=user_id,display_name');myName=profileName(user.id)||user?.user_metadata?.display_name||'';return true}
async function loadData(){if(!workspaceId)return;[orgs,assignments,councils,affiliations]=await Promise.all([
 api(`/rest/v1/app_suborganizations?workspace_id=eq.${workspaceId}&active=eq.true&select=id,name,aliases,description,organization_type,default_assignee_name&order=name.asc`),
 api('/rest/v1/app_suborganization_assignees?select=organization_id,user_id'),
 api(`/rest/v1/app_org_affiliation_tags?workspace_id=eq.${workspaceId}&active=eq.true&kind=eq.council&select=id,name&order=name.asc`),
 api('/rest/v1/app_suborganization_affiliations?select=organization_id,tag_id')
]);orgs.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'ko'));renderOptions();sortCards();decorateCards();apply()}
function installToolbar(){const list=document.querySelector('#soOrganizationList');if(!list)return false;if(document.querySelector('#sofToolbar'))return true;const bar=document.createElement('div');bar.id='sofToolbar';bar.innerHTML=`<div class="sof-tools"><label class="sr-only" for="sofSearch">담당조직 검색</label><input id="sofSearch" class="sof-search" type="search" placeholder="담당조직 검색"><label class="sr-only" for="sofCouncil">협의회 필터</label><select id="sofCouncil"><option value="">협의회 전체</option></select><label class="sr-only" for="sofType">조직유형 필터</label><select id="sofType"><option value="">조직유형 전체</option></select></div><div class="sof-meta"><span id="sofCount"></span><button id="sofReset" class="sof-reset" type="button">초기화</button></div>`;list.insertAdjacentElement('beforebegin',bar);['sofSearch','sofCouncil','sofType'].forEach(id=>document.querySelector('#'+id)?.addEventListener(id==='sofSearch'?'input':'change',apply));document.querySelector('#sofReset')?.addEventListener('click',reset);return true}
function renderOptions(){installToolbar();const council=document.querySelector('#sofCouncil'),type=document.querySelector('#sofType');if(!council||!type)return;const cv=council.value,tv=type.value,mine=orgs.filter(isMine);const cs=[...councils].sort((a,b)=>a.name.localeCompare(b.name,'ko'));const types=[...new Set(mine.map(o=>o.organization_type||'미분류'))].sort((a,b)=>a.localeCompare(b,'ko'));council.innerHTML='<option value="">협의회 전체</option>'+cs.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');type.innerHTML='<option value="">조직유형 전체</option>'+types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(cs.some(x=>x.id===cv))council.value=cv;if(types.includes(tv))type.value=tv}
function state(){return{q:norm(document.querySelector('#sofSearch')?.value),council:document.querySelector('#sofCouncil')?.value||'',type:document.querySelector('#sofType')?.value||''}}
function matches(o,s){const hay=norm([o.name,...(o.aliases||[]),o.description||''].join(' '));if(s.q&&!hay.includes(s.q))return false;if(s.council&&!councilIds(o.id).includes(s.council))return false;if(s.type&&(o.organization_type||'미분류')!==s.type)return false;return true}
function sortCards(){if(sorting)return;const list=document.querySelector('#soOrganizationList');if(!list)return;const cards=[...list.querySelectorAll('.so-card[data-so-org]')];if(cards.length<2)return;const names=new Map(orgs.map(o=>[o.id,o.name||'']));const sorted=[...cards].sort((a,b)=>String(names.get(a.dataset.soOrg)||'').localeCompare(String(names.get(b.dataset.soOrg)||''),'ko'));if(cards.every((x,i)=>x===sorted[i]))return;sorting=true;sorted.forEach(card=>list.appendChild(card));sorting=false}
function decorateCards(){const list=document.querySelector('#soOrganizationList');if(!list)return;orgs.filter(isMine).forEach(o=>{const badge=list.querySelector(`.so-card[data-so-org="${CSS.escape(o.id)}"] .sof-type`);if(badge)badge.textContent=o.organization_type||'미분류'})}
function apply(){const list=document.querySelector('#soOrganizationList');if(!list)return;sortCards();const s=state(),mine=orgs.filter(isMine);let shown=0;mine.forEach(o=>{const card=list.querySelector(`.so-card[data-so-org="${CSS.escape(o.id)}"]`);if(!card)return;const ok=matches(o,s);card.classList.toggle('sof-hidden',!ok);if(ok)shown++});let empty=list.querySelector('#sofNoResults');if(!empty){empty=document.createElement('div');empty.id='sofNoResults';empty.className='sof-no-results sof-hidden';empty.textContent='조건에 맞는 담당조직이 없습니다.';list.appendChild(empty)}empty.classList.toggle('sof-hidden',shown!==0||mine.length===0);const count=document.querySelector('#sofCount');if(count)count.textContent=`${shown}개 담당조직`}
function reset(){const q=document.querySelector('#sofSearch'),c=document.querySelector('#sofCouncil'),t=document.querySelector('#sofType');if(q)q.value='';if(c)c.value='';if(t)t.value='';apply()}
function bind(){if(bound)return;bound=true;window.addEventListener('kptu:view-changed',e=>{if(e.detail?.view==='team')loadData().catch(console.error)});window.addEventListener('kptu:suborganization-updated',()=>loadData().catch(console.error));window.addEventListener('kptu:suborganizations-rendered',()=>{sortCards();decorateCards();apply()})}
async function init(){if(!(await context()))return;installToolbar();bind();await loadData()}
window.__KPTU_SUBORGANIZATION_FILTERS_READY__=init().catch(console.error);
})();
