const SO_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const SO_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const SO_SESSION='kptu_collab_session_v1';
let soUser=null,soWorkspace=null,soRole=null,soMembers=[],soProfiles=[],soOrganizations=[],soAssignments=[],soEditing=null,soEditEventId=null;
function soSession(){try{return JSON.parse(localStorage.getItem(SO_SESSION)||'null')}catch{return null}}
async function soApi(path,{method='GET',body=null,prefer=''}={}){const s=soSession();if(!s?.access_token)throw new Error('로그인이 필요합니다.');const h={apikey:SO_KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'};if(prefer)h.Prefer=prefer;const r=await fetch(SO_SB+path,{method,headers:h,body:body===null?null:JSON.stringify(body),cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.hint||('요청 실패 '+r.status));return d}
function soEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function soName(id){return soProfiles.find(x=>x.user_id===id)?.display_name||id?.slice(0,8)||'팀원'}
function soCanAdd(){return ['owner','admin','editor','author'].includes(soRole)}
function soIsAdmin(){return ['owner','admin'].includes(soRole)}
function soCanEdit(o){return soIsAdmin()||o?.created_by===soUser?.id}
function soToast(msg){const t=document.querySelector('#toast');if(t){t.textContent=msg;t.classList.remove('hidden');clearTimeout(soToast.t);soToast.t=setTimeout(()=>t.classList.add('hidden'),2300)}}
function soInstallStyle(){if(document.querySelector('#soStyle'))return;const s=document.createElement('style');s.id='soStyle';s.textContent=`
.so-team-section{margin-top:26px;padding-top:20px;border-top:1px solid #e3e8ed}.so-team-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px}.so-team-head h3{margin:0}.so-list{display:grid;gap:9px}.so-card{border:1px solid #e0e6eb;background:#fff;border-radius:13px;padding:12px}.so-card-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.so-card h4{margin:0;font-size:14px}.so-card p{margin:3px 0 0;font-size:11px;color:#7b8792}.so-card-actions{display:flex;gap:5px;flex-wrap:wrap}.so-card-actions .danger{color:#a33b45;border-color:#ead2d5}.so-assignees{margin-top:9px;padding-top:8px;border-top:1px solid #edf0f3;font-size:11px;color:#65717d}.so-assignee-chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}.so-chip{display:inline-flex;padding:3px 7px;border-radius:999px;background:#eef3f7;color:#506273;font-size:10px;font-weight:750}.so-org-checks{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:7px}.so-org-check{display:flex!important;flex-direction:row!important;align-items:center!important;gap:7px!important;margin:0!important;padding:7px 8px;border:1px solid #e1e6eb;border-radius:9px;background:#fff}.so-org-check input{width:auto!important;margin:0!important}.so-org-check small{color:#7a8590}.so-org-box{margin:10px 0;padding:11px;border:1px solid #e3e8ed;border-radius:11px;background:#f8fafb}.so-org-box>b{display:block;font-size:12px;margin-bottom:2px}.so-org-box>p{margin:0 0 6px;font-size:10px;color:#7b8792}.so-modal-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:10px}.so-admin-members{display:grid;gap:5px;margin-top:8px}.so-admin-member{display:flex!important;flex-direction:row!important;align-items:center!important;gap:7px!important;margin:0!important}.so-admin-member input{width:auto!important}.so-badge{display:inline-flex;margin-left:5px;padding:2px 6px;border-radius:999px;background:#edf3f8;color:#52677a;font-size:9px;font-weight:800}@media(max-width:650px){.so-org-checks{grid-template-columns:1fr}.so-card-top{display:block}.so-card-actions{margin-top:8px}.so-modal-actions>*{flex:1}}
`;document.head.appendChild(s)}
async function soContext(){const s=soSession();if(!s?.access_token)return false;const ur=await fetch(SO_SB+'/auth/v1/user',{headers:{apikey:SO_KEY,Authorization:'Bearer '+s.access_token},cache:'no-store'});if(!ur.ok)return false;soUser=await ur.json();const ms=await soApi('/rest/v1/app_workspace_members?user_id=eq.'+soUser.id+'&select=workspace_id,role&limit=1');if(!ms?.length)return false;soWorkspace=ms[0].workspace_id;soRole=ms[0].role;[soMembers,soProfiles]=await Promise.all([soApi('/rest/v1/app_workspace_members?workspace_id=eq.'+soWorkspace+'&select=user_id,role'),soApi('/rest/v1/app_profiles?select=user_id,display_name')]);return true}
async function soLoad(){if(!soWorkspace)return;[soOrganizations,soAssignments]=await Promise.all([soApi('/rest/v1/app_suborganizations?workspace_id=eq.'+soWorkspace+'&active=eq.true&select=*&order=name.asc'),soApi('/rest/v1/app_suborganization_assignees?select=organization_id,user_id,assigned_by,created_at')]);soRenderTeam();soRenderEventCreate();}
function soAssigned(id){return soAssignments.filter(x=>x.organization_id===id).map(x=>x.user_id)}
function soRenderTeam(){const box=document.querySelector('#soOrganizationList');if(!box)return;box.innerHTML=soOrganizations.length?soOrganizations.map(o=>{const people=soAssigned(o.id);return `<article class="so-card" data-so-org="${o.id}"><div class="so-card-top"><div><h4>${soEsc(o.name)}</h4>${o.aliases?.length?`<p>${soEsc(o.aliases.join(' · '))}</p>`:''}${o.description?`<p>${soEsc(o.description)}</p>`:''}</div>${soCanEdit(o)?`<div class="so-card-actions"><button class="mini" data-so-edit="${o.id}" type="button">수정</button>${soIsAdmin()?`<button class="mini" data-so-assign="${o.id}" type="button">담당자 지정</button>`:''}<button class="mini danger" data-so-delete="${o.id}" type="button">삭제</button></div>`:''}</div><div class="so-assignees"><b>담당</b><div class="so-assignee-chips">${people.length?people.map(uid=>`<span class="so-chip">${soEsc(soName(uid))}</span>`).join(''):'<span class="updated">담당자 미지정</span>'}</div></div></article>`}).join(''):'<div class="empty compact">등록된 산하조직이 없습니다.</div>'}
function soInstallTeam(){const team=document.querySelector('#teamView');if(!team||document.querySelector('#soTeamSection'))return;const section=document.createElement('section');section.id='soTeamSection';section.className='so-team-section';section.innerHTML=`<div class="so-team-head"><div><h3>산하조직</h3><p class="muted">조직 목록과 담당자를 관리합니다.</p></div>${soCanAdd()?'<button id="soAddOrg" class="secondary" type="button">+ 산하조직</button>':''}</div><div id="soOrganizationList" class="so-list"></div>`;team.appendChild(section);document.querySelector('#soAddOrg')?.addEventListener('click',()=>soOpenEdit())}
function soInstallModals(){if(document.querySelector('#soEditModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="soEditModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">SUB ORGANIZATION</div><h2 id="soEditHeading">산하조직 추가</h2></div><button class="icon-btn" data-so-close="soEditModal" type="button">×</button></div><label>조직명<input id="soEditName" type="text" maxlength="120"></label><label>약칭 <span class="optional">쉼표로 구분</span><input id="soEditAliases" type="text" placeholder="예: 철도, 철도노조"></label><label>설명 <span class="optional">선택</span><textarea id="soEditDescription" rows="3"></textarea></label><button id="soSaveOrg" class="primary wide" type="button">저장</button><div id="soEditStatus" class="status"></div></div></div><div id="soAssignModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">ASSIGNEES</div><h2 id="soAssignHeading">담당자 지정</h2></div><button class="icon-btn" data-so-close="soAssignModal" type="button">×</button></div><p class="muted">관리자가 이 조직의 담당자를 지정합니다. 여러 명 지정할 수 있습니다.</p><div id="soAssignMembers" class="so-admin-members"></div><button id="soSaveAssignees" class="primary wide" type="button">담당자 저장</button><div id="soAssignStatus" class="status"></div></div></div>`);document.querySelector('#soSaveOrg').onclick=soSaveOrg;document.querySelector('#soSaveAssignees').onclick=soSaveAssignees}
function soOpen(id){const m=document.querySelector('#'+id);if(m){m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}}
function soClose(id){const m=document.querySelector('#'+id);if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}}
function soOpenEdit(id=null){soEditing=id?soOrganizations.find(x=>x.id===id):null;document.querySelector('#soEditHeading').textContent=soEditing?'산하조직 수정':'산하조직 추가';document.querySelector('#soEditName').value=soEditing?.name||'';document.querySelector('#soEditAliases').value=(soEditing?.aliases||[]).join(', ');document.querySelector('#soEditDescription').value=soEditing?.description||'';document.querySelector('#soEditStatus').textContent='';soOpen('soEditModal')}
async function soSaveOrg(){const name=document.querySelector('#soEditName').value.trim(),aliases=document.querySelector('#soEditAliases').value.split(',').map(x=>x.trim()).filter(Boolean),description=document.querySelector('#soEditDescription').value.trim(),st=document.querySelector('#soEditStatus');if(!name){st.textContent='조직명을 입력해 주세요.';st.className='status error';return}const b=document.querySelector('#soSaveOrg');b.disabled=true;st.textContent='저장 중…';try{if(soEditing)await soApi('/rest/v1/app_suborganizations?id=eq.'+soEditing.id,{method:'PATCH',body:{name,aliases,description:description||null,updated_at:new Date().toISOString()}});else await soApi('/rest/v1/app_suborganizations',{method:'POST',body:{workspace_id:soWorkspace,name,aliases,description:description||null,created_by:soUser.id,active:true}});soClose('soEditModal');await soLoad();soToast(soEditing?'산하조직을 수정했습니다.':'산하조직을 추가했습니다.')}catch(e){st.textContent=e.message||String(e);st.className='status error'}finally{b.disabled=false}}
async function soDelete(id){const o=soOrganizations.find(x=>x.id===id);if(!o||!soCanEdit(o))return;if(!confirm(`“${o.name}” 산하조직을 삭제할까요?\n담당자 지정과 일정 연결도 함께 삭제됩니다.`))return;try{await soApi('/rest/v1/app_suborganizations?id=eq.'+id,{method:'DELETE'});await soLoad();soToast('산하조직을 삭제했습니다.')}catch(e){alert(e.message||String(e))}}
function soOpenAssign(id){if(!soIsAdmin())return;soEditing=soOrganizations.find(x=>x.id===id);if(!soEditing)return;const selected=new Set(soAssigned(id));document.querySelector('#soAssignHeading').textContent=soEditing.name+' · 담당자';document.querySelector('#soAssignMembers').innerHTML=soMembers.map(m=>`<label class="so-admin-member"><input type="checkbox" value="${m.user_id}" ${selected.has(m.user_id)?'checked':''}> <span>${soEsc(soName(m.user_id))}</span></label>`).join('');document.querySelector('#soAssignStatus').textContent='';soOpen('soAssignModal')}
async function soSaveAssignees(){if(!soEditing||!soIsAdmin())return;const st=document.querySelector('#soAssignStatus'),btn=document.querySelector('#soSaveAssignees'),ids=[...document.querySelectorAll('#soAssignMembers input:checked')].map(x=>x.value);btn.disabled=true;st.textContent='저장 중…';try{await soApi('/rest/v1/app_suborganization_assignees?organization_id=eq.'+soEditing.id,{method:'DELETE'});if(ids.length)await soApi('/rest/v1/app_suborganization_assignees',{method:'POST',body:ids.map(user_id=>({organization_id:soEditing.id,user_id,assigned_by:soUser.id}))});soClose('soAssignModal');await soLoad();soToast('담당자를 저장했습니다.')}catch(e){st.textContent=e.message||String(e);st.className='status error'}finally{btn.disabled=false}}
function soChecks(prefix,selected=[]){const set=new Set(selected);return soOrganizations.length?`<div class="so-org-checks">${soOrganizations.map(o=>{const people=soAssigned(o.id).map(soName);return `<label class="so-org-check"><input type="checkbox" data-${prefix}-org="${o.id}" ${set.has(o.id)?'checked':''}><span>${soEsc(o.name)}${people.length?`<small> · 담당 ${soEsc(people.join(', '))}</small>`:''}</span></label>`}).join('')}</div>`:'<div class="updated">등록된 산하조직이 없습니다.</div>'}
function soInstallEventCreate(){const modal=document.querySelector('#eventModal .modal-card');if(!modal||document.querySelector('#soEventOrganizations'))return;const desc=document.querySelector('#eventDescription')?.closest('label');if(!desc)return;const box=document.createElement('div');box.id='soEventOrganizations';box.className='so-org-box';box.innerHTML='<b>관련 산하조직 <span class="optional">선택</span></b><p>관련 조직이 없으면 선택하지 않아도 됩니다.</p><div id="soEventOrgChecks"></div>';desc.insertAdjacentElement('afterend',box);soRenderEventCreate()}
function soRenderEventCreate(selected=[]){const box=document.querySelector('#soEventOrgChecks');if(box)box.innerHTML=soChecks('event',selected)}
function soSelectedCreate(){return [...document.querySelectorAll('[data-event-org]:checked')].map(x=>x.dataset.eventOrg)}
async function soSyncEvent(eventId,ids){await soApi('/rest/v1/app_event_suborganizations?event_id=eq.'+encodeURIComponent(eventId),{method:'DELETE'});if(ids.length)await soApi('/rest/v1/app_event_suborganizations',{method:'POST',body:ids.map(organization_id=>({event_id:eventId,organization_id,created_by:soUser.id}))})}
function soWrapCreateSave(){const btn=document.querySelector('#saveEventBtn');if(!btn||btn.dataset.soWrapped)return;btn.dataset.soWrapped='1';const old=btn.onclick;btn.onclick=async function(e){const scope=document.querySelector('#eventCalendarScope')?.value||'team',ids=soSelectedCreate(),title=document.querySelector('#eventTitle')?.value.trim()||'',start=document.querySelector('#eventStart')?.value;if(scope!=='team')return old?.call(this,e);const beforeHidden=document.querySelector('#eventModal')?.classList.contains('hidden');const ret=await old?.call(this,e);const succeeded=!beforeHidden&&document.querySelector('#eventModal')?.classList.contains('hidden');if(succeeded&&ids.length&&title&&start){try{const iso=new Date(start).toISOString();const rows=await soApi('/rest/v1/app_events?workspace_id=eq.'+soWorkspace+'&created_by=eq.'+soUser.id+'&title=eq.'+encodeURIComponent(title)+'&start_at=eq.'+encodeURIComponent(iso)+'&select=id&order=created_at.desc&limit=1');if(rows?.[0])await soSyncEvent(rows[0].id,ids)}catch(err){console.warn('event suborganizations',err);soToast('일정은 저장됐지만 관련 산하조직 연결을 확인해 주세요.')}}return ret}}
function soInstallEditSelector(){const modal=document.querySelector('#ciAppModal .modal-card');if(!modal||document.querySelector('#soEditEventOrganizations'))return;const desc=document.querySelector('#ciAppDescription')?.closest('label');if(!desc)return;const box=document.createElement('div');box.id='soEditEventOrganizations';box.className='so-org-box';box.innerHTML='<b>관련 산하조직 <span class="optional">선택</span></b><div id="soEditEventOrgChecks"></div>';desc.insertAdjacentElement('afterend',box);const save=document.querySelector('#ciAppSave');if(save&&!save.dataset.soWrapped){save.dataset.soWrapped='1';const old=save.onclick;save.onclick=async function(e){const id=soEditEventId,ids=[...document.querySelectorAll('[data-edit-event-org]:checked')].map(x=>x.dataset.editEventOrg);const ret=await old?.call(this,e);if(id&&document.querySelector('#ciAppModal')?.classList.contains('hidden')){try{await soSyncEvent(id,ids)}catch(err){soToast('일정은 수정됐지만 산하조직 연결 저장에 실패했습니다.')}}return ret}}}
async function soLoadEditEvent(id){soEditEventId=id;const box=document.querySelector('#soEditEventOrgChecks');if(!box)return;try{const links=await soApi('/rest/v1/app_event_suborganizations?event_id=eq.'+encodeURIComponent(id)+'&select=organization_id');box.innerHTML=soChecks('edit-event',links.map(x=>x.organization_id))}catch(e){box.innerHTML='<div class="updated">산하조직 정보를 불러오지 못했습니다.</div>'}}
function soResetCreate(){document.querySelectorAll('[data-event-org]').forEach(x=>x.checked=false)}
function soBind(){document.addEventListener('click',e=>{const close=e.target.closest('[data-so-close]');if(close){soClose(close.dataset.soClose);return}const edit=e.target.closest('[data-so-edit]');if(edit){soOpenEdit(edit.dataset.soEdit);return}const del=e.target.closest('[data-so-delete]');if(del){soDelete(del.dataset.soDelete);return}const assign=e.target.closest('[data-so-assign]');if(assign){soOpenAssign(assign.dataset.soAssign);return}if(e.target.closest('#newEventBtn,#homeAddEvent,#calendarQuickAdd'))setTimeout(soResetCreate,0);const app=e.target.closest('[data-app-event]');if(app?.dataset.appEvent)setTimeout(()=>soLoadEditEvent(app.dataset.appEvent),60)},true)}
async function soBoot(){soInstallStyle();if(!(await soContext()))return;soInstallTeam();soInstallModals();soInstallEventCreate();soInstallEditSelector();soBind();await soLoad();soWrapCreateSave();setTimeout(()=>{soInstallEventCreate();soInstallEditSelector();soWrapCreateSave()},500)}
setTimeout(soBoot,0);