(()=>{
'use strict';
const rt=window.KPTURuntime;
let soUser=null,soWorkspace=null,soRole=null,soMembers=[],soProfiles=[],soOrganizations=[],soAssignments=[],soEditing=null,soEditEventId=null,soBound=false;
const api=(path,options={})=>rt.api(path,options);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nameOf=id=>soProfiles.find(x=>x.user_id===id)?.display_name||id?.slice(0,8)||'팀원';
const norm=v=>String(v??'').trim().toLocaleLowerCase('ko-KR');
const canAdd=()=>['owner','admin','editor','author'].includes(soRole);
const isAdmin=()=>['owner','admin'].includes(soRole);
const canEdit=o=>isAdmin()||o?.created_by===soUser?.id;
function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2300)}
function setStatus(el,msg,type=''){if(!el)return;el.textContent=msg||'';el.className='status'+(type?' '+type:'');if(type==='error'){el.setAttribute('role','alert');el.removeAttribute('aria-live')}else{el.setAttribute('role','status');el.setAttribute('aria-live','polite')}}
function setBusy(btn,busy){if(!btn)return;btn.disabled=!!busy;if(busy)btn.setAttribute('aria-busy','true');else btn.removeAttribute('aria-busy')}
async function context(){if(!rt?.session||!(await rt.session.ensure()))return false;soUser=await api('/auth/v1/user');const ms=await api(`/rest/v1/app_workspace_members?user_id=eq.${soUser.id}&select=workspace_id,role&limit=1`);if(!ms?.length)return false;soWorkspace=ms[0].workspace_id;soRole=ms[0].role;[soMembers,soProfiles]=await Promise.all([api(`/rest/v1/app_workspace_members?workspace_id=eq.${soWorkspace}&select=user_id,role`),api('/rest/v1/app_profiles?select=user_id,display_name')]);return true}
function assignedIds(id){return soAssignments.filter(x=>x.organization_id===id).map(x=>x.user_id)}
function actualNames(o){return assignedIds(o.id).map(nameOf).filter(Boolean)}
function effectiveNames(o){const actual=actualNames(o);return actual.length?actual:(o.default_assignee_name?[String(o.default_assignee_name).trim()].filter(Boolean):[])}
function myOrganizations(){const myName=soUser?.id?nameOf(soUser.id):'';return soOrganizations.filter(o=>{const ids=assignedIds(o.id);if(ids.includes(soUser?.id))return true;return !ids.length&&!!myName&&norm(o.default_assignee_name)===norm(myName)})}
function assigneeMarkup(o){const actual=actualNames(o);if(actual.length)return actual.map(n=>`<span class="so-chip">${esc(n)}</span>`).join('');if(o.default_assignee_name)return `<span class="so-chip">${esc(o.default_assignee_name)}</span><span class="so-planned-note">계정 연결 전</span>`;return '<span class="updated">담당자 미지정</span>'}
function installTeam(){const team=document.querySelector('#teamView');if(!team)return false;let section=document.querySelector('#soTeamSection');if(!section){section=document.createElement('section');section.id='soTeamSection';section.className='so-team-section';section.innerHTML='<div class="so-team-actions"><span id="soOrgCount" class="muted"></span><button id="soAddOrg" class="secondary" type="button">+ 담당조직</button></div><div id="soOrganizationList" class="so-list"></div>';team.appendChild(section)}const add=document.querySelector('#soAddOrg');if(add)add.classList.toggle('hidden',!canAdd());return true}
function installModals(){if(document.querySelector('#soEditModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="soEditModal" class="modal hidden" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="soEditHeading"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">SUB ORGANIZATION</div><h2 id="soEditHeading">담당조직 추가</h2></div><button class="icon-btn" data-so-close="soEditModal" type="button" aria-label="닫기">×</button></div><label>조직명<input id="soEditName" type="text" maxlength="120"></label><label>약칭 <span class="optional">쉼표로 구분</span><input id="soEditAliases" type="text" placeholder="예: 철도, 철도노조"></label><label>조직유형 <span class="optional">선택</span><input id="sofEditType" type="text" maxlength="80" list="sofTypeSuggestions" placeholder="예: 철도·도시철도"><datalist id="sofTypeSuggestions"><option value="중앙공공기관"><option value="지방공기업·출연기관"><option value="철도·도시철도"><option value="자회사·용역"><option value="기타"></datalist></label><label>설명 <span class="optional">선택</span><textarea id="soEditDescription" rows="3"></textarea></label><button id="soSaveOrg" class="primary wide" type="button">저장</button><div id="soEditStatus" class="status"></div></div></div><div id="soAssignModal" class="modal hidden" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="soAssignHeading"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">ASSIGNEES</div><h2 id="soAssignHeading">담당자 지정</h2></div><button class="icon-btn" data-so-close="soAssignModal" type="button" aria-label="닫기">×</button></div><p class="muted">관리자가 이 조직의 담당자를 지정합니다. 여러 명 지정할 수 있습니다.</p><div id="soAssignMembers" class="so-admin-members"></div><button id="soSaveAssignees" class="primary wide" type="button">담당자 저장</button><div id="soAssignStatus" class="status"></div></div></div>`)}
function renderTeam(){const box=document.querySelector('#soOrganizationList');if(!box)return;const mine=myOrganizations(),count=document.querySelector('#soOrgCount');if(count)count.textContent=mine.length?`${mine.length}개 담당조직`:'담당조직 없음';box.innerHTML=mine.length?mine.map(o=>`<article class="so-card" data-so-org="${esc(o.id)}" data-ps-workplace-org="${esc(o.id)}" role="button" tabindex="0" aria-label="${esc(o.name)} 상세 열기"><div class="so-card-main"><h4>${esc(o.name)}</h4><span class="sof-type">${esc(o.organization_type||'미분류')}</span><span class="so-chevron" aria-hidden="true">›</span></div></article>`).join(''):'<div class="empty compact">등록된 담당조직이 없습니다.</div>';window.dispatchEvent(new CustomEvent('kptu:suborganizations-rendered',{detail:{count:mine.length}}))}
function checks(prefix,selected=[],source=soOrganizations){const set=new Set(selected);return source.length?`<div class="so-org-checks">${source.map(o=>{const names=effectiveNames(o),planned=!actualNames(o).length&&!!o.default_assignee_name;return `<label class="so-org-check"><input type="checkbox" data-${prefix}-org="${esc(o.id)}" ${set.has(o.id)?'checked':''}><span>${esc(o.name)}${names.length?`<small> · 담당 ${esc(names.join(', '))}${planned?' (계정 연결 전)':''}</small>`:''}</span></label>`}).join('')}</div>`:'<div class="updated">표시할 담당조직이 없습니다.</div>'}
function renderEventCreate(selected=[]){const box=document.querySelector('#soEventOrgChecks');if(box)box.innerHTML=checks('event',selected,myOrganizations())}
async function load(){if(!soWorkspace)return;[soOrganizations,soAssignments]=await Promise.all([api(`/rest/v1/app_suborganizations?workspace_id=eq.${soWorkspace}&active=eq.true&select=*&order=name.asc`),api('/rest/v1/app_suborganization_assignees?select=organization_id,user_id,assigned_by,created_at')]);renderTeam();renderEventCreate();return {organizations:soOrganizations,assignments:soAssignments}}
function open(id,{trigger=document.activeElement,initialFocus=null}={}){const m=document.querySelector('#'+id);if(!m)return;m.classList.remove('hidden');m.setAttribute('aria-hidden','false');window.KPTUA11y?.dialog.activate(m,{trigger,initialFocus,onRequestClose:()=>close(id)})}
function close(id){const m=document.querySelector('#'+id);if(!m)return;m.classList.add('hidden');m.setAttribute('aria-hidden','true');window.KPTUA11y?.dialog.deactivate(m,{restoreFocus:true,fallbackFocus:'#soAddOrg'})}
function openEdit(id=null){soEditing=id?soOrganizations.find(x=>x.id===id):null;document.querySelector('#soEditHeading').textContent=soEditing?'담당조직 수정':'담당조직 추가';document.querySelector('#soEditName').value=soEditing?.name||'';document.querySelector('#soEditAliases').value=(soEditing?.aliases||[]).join(', ');document.querySelector('#sofEditType').value=soEditing?.organization_type&&soEditing.organization_type!=='미분류'?soEditing.organization_type:'';document.querySelector('#soEditDescription').value=soEditing?.description||'';setStatus(document.querySelector('#soEditStatus'),'');open('soEditModal',{initialFocus:'#soEditName'})}
async function saveOrg(){const name=document.querySelector('#soEditName').value.trim(),aliases=document.querySelector('#soEditAliases').value.split(',').map(x=>x.trim()).filter(Boolean),organization_type=document.querySelector('#sofEditType').value.trim()||'미분류',description=document.querySelector('#soEditDescription').value.trim(),st=document.querySelector('#soEditStatus'),btn=document.querySelector('#soSaveOrg');if(!name){setStatus(st,'조직명을 입력해 주세요.','error');return}setBusy(btn,true);setStatus(st,'저장 중…');try{const body={name,aliases,organization_type,description:description||null,updated_at:new Date().toISOString()};if(soEditing)await api(`/rest/v1/app_suborganizations?id=eq.${encodeURIComponent(soEditing.id)}`,{method:'PATCH',body});else await api('/rest/v1/app_suborganizations',{method:'POST',body:{workspace_id:soWorkspace,...body,created_by:soUser.id,active:true}});close('soEditModal');await load();window.dispatchEvent(new Event('kptu:suborganization-updated'));toast(soEditing?'담당조직을 수정했습니다.':'담당조직을 추가했습니다.')}catch(e){setStatus(st,e.message||String(e),'error')}finally{setBusy(btn,false)}}
async function removeOrg(id){const o=soOrganizations.find(x=>x.id===id);if(!o||!canEdit(o)||!confirm(`“${o.name}” 담당조직을 삭제할까요?\n연결된 일정 정보도 함께 정리됩니다.`))return;try{await api(`/rest/v1/app_suborganizations?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});await load();window.dispatchEvent(new Event('kptu:suborganization-updated'));toast('담당조직을 삭제했습니다.')}catch(e){alert(e.message||String(e))}}
function openAssign(id){if(!isAdmin())return;soEditing=soOrganizations.find(x=>x.id===id);if(!soEditing)return;const selected=new Set(assignedIds(id));document.querySelector('#soAssignHeading').textContent=soEditing.name+' · 담당자';document.querySelector('#soAssignMembers').innerHTML=soMembers.map(m=>`<label class="so-admin-member"><input type="checkbox" value="${esc(m.user_id)}" ${selected.has(m.user_id)?'checked':''}> <span>${esc(nameOf(m.user_id))}</span></label>`).join('');setStatus(document.querySelector('#soAssignStatus'),'');open('soAssignModal',{initialFocus:'#soAssignMembers input'})}
async function saveAssignees(){if(!soEditing||!isAdmin())return;const st=document.querySelector('#soAssignStatus'),btn=document.querySelector('#soSaveAssignees'),ids=[...document.querySelectorAll('#soAssignMembers input:checked')].map(x=>x.value);setBusy(btn,true);setStatus(st,'저장 중…');try{await api(`/rest/v1/app_suborganization_assignees?organization_id=eq.${encodeURIComponent(soEditing.id)}`,{method:'DELETE'});if(ids.length)await api('/rest/v1/app_suborganization_assignees',{method:'POST',body:ids.map(user_id=>({organization_id:soEditing.id,user_id,assigned_by:soUser.id}))});close('soAssignModal');await load();window.dispatchEvent(new Event('kptu:suborganization-updated'));toast('담당자를 저장했습니다.')}catch(e){setStatus(st,e.message||String(e),'error')}finally{setBusy(btn,false)}}
function installEventCreate(){const modal=document.querySelector('#eventModal .modal-card');if(!modal||document.querySelector('#soEventOrganizations'))return;const desc=document.querySelector('#eventDescription')?.closest('label');if(!desc)return;const box=document.createElement('div');box.id='soEventOrganizations';box.className='so-org-box';box.innerHTML='<b>관련 담당조직 <span class="optional">선택</span></b><p>내 담당조직만 표시됩니다.</p><div id="soEventOrgChecks"></div>';desc.insertAdjacentElement('afterend',box);renderEventCreate()}
function selectedCreate(){return [...document.querySelectorAll('[data-event-org]:checked')].map(x=>x.dataset.eventOrg)}
window.__KPTU_SELECTED_EVENT_ORGS__=selectedCreate;
async function syncEvent(eventId,ids){await api(`/rest/v1/app_event_suborganizations?event_id=eq.${encodeURIComponent(eventId)}`,{method:'DELETE'});if(ids.length)await api('/rest/v1/app_event_suborganizations',{method:'POST',body:ids.map(organization_id=>({event_id:eventId,organization_id,created_by:soUser.id}))})}
window.__KPTU_SYNC_EVENT_ORGS__=eventId=>syncEvent(eventId,selectedCreate());
function installEditSelector(){const modal=document.querySelector('#ciAppModal .modal-card');if(!modal||document.querySelector('#soEditEventOrganizations'))return;const desc=document.querySelector('#ciAppDescription')?.closest('label');if(!desc)return;const box=document.createElement('div');box.id='soEditEventOrganizations';box.className='so-org-box';box.innerHTML='<b>관련 담당조직 <span class="optional">선택</span></b><div id="soEditEventOrgChecks"></div>';desc.insertAdjacentElement('afterend',box);const save=document.querySelector('#ciAppSave');if(save&&!save.dataset.soWrapped){save.dataset.soWrapped='1';const old=save.onclick;save.onclick=async function(e){const id=soEditEventId,ids=[...document.querySelectorAll('[data-edit-event-org]:checked')].map(x=>x.dataset.editEventOrg);const ret=await old?.call(this,e);if(id&&document.querySelector('#ciAppModal')?.classList.contains('hidden')){try{await syncEvent(id,ids)}catch{toast('일정은 수정됐지만 담당조직 연결 저장에 실패했습니다.')}}return ret}}}
async function loadEditEvent(id){soEditEventId=id;const box=document.querySelector('#soEditEventOrgChecks');if(!box)return;try{const links=await api(`/rest/v1/app_event_suborganizations?event_id=eq.${encodeURIComponent(id)}&select=organization_id`);box.innerHTML=checks('edit-event',links.map(x=>x.organization_id))}catch{box.innerHTML='<div class="updated">담당조직 정보를 불러오지 못했습니다.</div>'}}
function resetCreate(){document.querySelectorAll('[data-event-org]').forEach(x=>x.checked=false)}
function bind(){if(soBound)return;soBound=true;document.querySelector('#soAddOrg')?.addEventListener('click',()=>openEdit());document.querySelector('#soSaveOrg')?.addEventListener('click',saveOrg);document.querySelector('#soSaveAssignees')?.addEventListener('click',saveAssignees);document.addEventListener('keydown',e=>{const card=e.target.closest?.('[data-ps-workplace-org]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();card.click()}});document.addEventListener('click',e=>{const closeBtn=e.target.closest('[data-so-close]');if(closeBtn){close(closeBtn.dataset.soClose);return}const edit=e.target.closest('[data-so-edit]');if(edit){openEdit(edit.dataset.soEdit);return}const del=e.target.closest('[data-so-delete]');if(del){removeOrg(del.dataset.soDelete);return}const assign=e.target.closest('[data-so-assign]');if(assign){openAssign(assign.dataset.soAssign);return}if(e.target.closest('#newEventBtn,#homeAddEvent,#calendarQuickAdd'))resetCreate();const app=e.target.closest('[data-app-event]');if(app?.dataset.appEvent)loadEditEvent(app.dataset.appEvent)},true);window.addEventListener('kptu:view-changed',e=>{if(e.detail?.view==='team')load().catch(console.error)});window.addEventListener('kptu:session-changed',()=>{context().then(ok=>ok&&load()).catch(console.error)})}
async function boot(){if(!rt)return false;if(!(await context()))return false;installTeam();installModals();installEventCreate();installEditSelector();bind();await load();window.__KPTU_RELOAD_SUBORGANIZATIONS__=()=>load();return true}
window.__KPTU_SUBORGANIZATIONS_READY__=boot().catch(err=>{console.error('suborganizations init',err);return false});
})();