const TN_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const TN_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const TN_SESSION='kptu_collab_session_v1';
let tnNotes=new Map(),tnEditing=null,tnTimer=null,tnLoading=false;

function tnSession(){try{return JSON.parse(localStorage.getItem(TN_SESSION)||'null')}catch{return null}}
async function tnApi(path,{method='GET',body=null}={}){const s=tnSession();if(!s?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(TN_SB+path,{method,headers:{apikey:TN_KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:body==null?null:JSON.stringify(body),cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||d?.error_description||('요청 실패 '+r.status));return d}
function tnEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tnRows(){return [...document.querySelectorAll('[data-tl-task-row],[data-pt-task-row]')]}
function tnId(row){return row.dataset.tlTaskRow||row.dataset.ptTaskRow||''}
function tnMarkup(id,note){if(tnEditing===id)return `<div class="tn-editor" data-tn-wrap="${id}"><textarea class="tn-input" maxlength="1000" placeholder="처리 결과, 섭외 결과, 완료 방식 등을 메모하세요.">${tnEsc(note||'')}</textarea><div class="tn-editor-actions"><button class="mini" data-tn-save="${id}" type="button">저장</button><button class="mini" data-tn-cancel="${id}" type="button">취소</button></div><div class="tn-status"></div></div>`;if(String(note||'').trim())return `<div class="tn-view" data-tn-wrap="${id}"><div class="tn-body"><span class="tn-label">메모</span><span>${tnEsc(note)}</span></div><button class="mini" data-tn-edit="${id}" type="button">메모 수정</button></div>`;return `<div class="tn-view tn-empty" data-tn-wrap="${id}"><button class="mini" data-tn-edit="${id}" type="button">＋ 메모 추가</button></div>`}
function tnDecorate(){for(const row of tnRows()){const id=tnId(row);if(!id)continue;const note=tnNotes.get(id)||'';const old=row.querySelector(':scope > [data-tn-wrap]');if(old&&old.dataset.tnWrap===id&&old.dataset.tnEditing===String(tnEditing===id)&&old.dataset.tnValue===note)continue;old?.remove();const box=document.createElement('div');box.innerHTML=tnMarkup(id,note);const node=box.firstElementChild;if(!node)continue;node.dataset.tnEditing=String(tnEditing===id);node.dataset.tnValue=note;row.appendChild(node)}}
async function tnRefresh(){clearTimeout(tnTimer);tnTimer=setTimeout(async()=>{if(tnLoading)return;const ids=[...new Set(tnRows().map(tnId).filter(Boolean))];if(!ids.length)return;tnLoading=true;try{const rows=await tnApi(`/rest/v1/app_tasks?id=in.(${ids.join(',')})&select=id,note`);tnNotes=new Map(rows.map(x=>[x.id,x.note||'']));tnDecorate()}catch(e){console.error('task notes load',e)}finally{tnLoading=false}},90)}
function tnStartEdit(id){tnEditing=id;tnDecorate();setTimeout(()=>{const input=document.querySelector(`[data-tn-wrap="${CSS.escape(id)}"] .tn-input`);if(input){input.focus();input.setSelectionRange(input.value.length,input.value.length)}},0)}
function tnCancel(){tnEditing=null;tnDecorate()}
async function tnSave(id){const wrap=document.querySelector(`[data-tn-wrap="${CSS.escape(id)}"]`),input=wrap?.querySelector('.tn-input'),status=wrap?.querySelector('.tn-status'),btn=wrap?.querySelector('[data-tn-save]');if(!input)return;const note=input.value.trim();if(btn)btn.disabled=true;if(status)status.textContent='저장 중…';try{await tnApi(`/rest/v1/app_tasks?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{note:note||null,updated_at:new Date().toISOString()}});tnNotes.set(id,note);tnEditing=null;tnDecorate()}catch(e){if(status)status.textContent='저장 실패 · '+(e.message||String(e));if(btn)btn.disabled=false}}
function tnInstallStyle(){if(document.querySelector('#tnStyle'))return;const s=document.createElement('style');s.id='tnStyle';s.textContent=`
.tl-task-row>.tn-view,.tl-task-row>.tn-editor{grid-column:1/-1;margin-top:1px}.tn-view{display:flex;align-items:flex-start;gap:7px}.tn-body{flex:1;min-width:0;padding:8px 10px;border-radius:9px;background:#f7f8fa;border:1px solid #edf0f2;color:#525a64;font-size:12px;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}.tn-label{font-weight:850;color:#3f4750;margin-right:6px}.tn-view>.mini{flex:0 0 auto}.tn-empty{justify-content:flex-start}.tn-editor{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:start}.tn-input{grid-column:1/-1;width:100%;min-height:68px;resize:vertical;padding:9px 10px;border:1px solid #aeb6bf;border-radius:9px;background:#fff;font:inherit;font-size:13px;line-height:1.55}.tn-editor-actions{display:flex;gap:6px}.tn-status{font-size:11px;color:#a33b45;align-self:center}@media(max-width:700px){.tn-view{flex-direction:column}.tn-view>.mini{align-self:flex-start}.tn-editor{grid-template-columns:1fr}.tn-editor-actions{grid-column:1}.tn-status{grid-column:1}}
`;document.head.appendChild(s)}
function tnBind(){document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-tn-edit]');if(edit){e.preventDefault();e.stopPropagation();tnStartEdit(edit.dataset.tnEdit);return}const save=e.target.closest?.('[data-tn-save]');if(save){e.preventDefault();e.stopPropagation();tnSave(save.dataset.tnSave);return}const cancel=e.target.closest?.('[data-tn-cancel]');if(cancel){e.preventDefault();e.stopPropagation();tnCancel()}},true);document.addEventListener('keydown',e=>{const input=e.target.closest?.('.tn-input');if(!input)return;const wrap=input.closest('[data-tn-wrap]');if(e.key==='Escape'){e.preventDefault();tnCancel()}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();tnSave(wrap?.dataset.tnWrap)}},true);for(const root of [document.querySelector('#tlTaskSections'),document.querySelector('#projectTaskList')])if(root)new MutationObserver(()=>tnRefresh()).observe(root,{childList:true,subtree:true});const bodyObs=new MutationObserver(()=>{const a=document.querySelector('#tlTaskSections'),b=document.querySelector('#projectTaskList');if(a&&!a.dataset.tnObs){a.dataset.tnObs='1';new MutationObserver(()=>tnRefresh()).observe(a,{childList:true,subtree:true})}if(b&&!b.dataset.tnObs){b.dataset.tnObs='1';new MutationObserver(()=>tnRefresh()).observe(b,{childList:true,subtree:true})}tnRefresh()});bodyObs.observe(document.body,{childList:true,subtree:true})}

(async()=>{tnInstallStyle();tnBind();await tnRefresh()})();
