const TL_SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const TL_KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const TL_SESSION='kptu_collab_session_v1';
let tlRendering=false,tlUser=null,tlWorkspace=null,tlProjects=[];
function tlSession(){try{return JSON.parse(localStorage.getItem(TL_SESSION)||'null')}catch{return null}}
async function tlApi(path,{method='GET',body=null}={}){const s=tlSession();if(!s?.access_token)throw new Error('로그인이 필요합니다.');const r=await fetch(TL_SB+path,{method,headers:{apikey:TL_KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:body==null?null:JSON.stringify(body)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error_description||('요청 실패 '+r.status));return d}
function tlEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tlDue(v){if(!v)return '기한 미정';const d=new Date(v);return d.toLocaleString('ko-KR',{month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'})}
function tlProject(id){return tlProjects.find(x=>x.id===id)?.name||''}
function tlCard(t){const project=tlProject(t.project_id);return `<article class="tl-task-row ${t.status==='done'?'done':''}"><div class="tl-task-content"><b>${tlEsc(t.title)}</b>${t.description?`<small>${tlEsc(t.description)}</small>`:''}${project?`<em>${tlEsc(project)}</em>`:''}</div><div class="tl-task-meta"><span><i>기한</i>${tlEsc(tlDue(t.due_at))}</span><span><i>대상</i>${tlEsc(t.target||'대상 미정')}</span></div><button class="mini" data-tl-toggle="${t.id}" data-done="${t.status==='done'?'1':'0'}" type="button">${t.status==='done'?'되돌리기':'완료'}</button></article>`}
async function tlRender(){if(tlRendering||!tlUser||!tlWorkspace)return;tlRendering=true;try{const tasks=await tlApi(`/rest/v1/app_tasks?workspace_id=eq.${tlWorkspace}&assignee_id=eq.${tlUser}&select=*&order=due_at.asc.nullslast,created_at.desc`);const mine=tasks.filter(t=>(t.source_type||'manual')==='manual'&&t.created_by===tlUser);const assigned=tasks.filter(t=>!((t.source_type||'manual')==='manual'&&t.created_by===tlUser));const root=document.querySelector('#tlTaskSections');if(!root)return;root.innerHTML=`<section class="tl-task-section"><div class="tl-section-head"><h3>내 할 일</h3><span>${mine.filter(t=>t.status!=='done').length}건</span></div><div class="tl-columns"><b>내용</b><b>기한</b><b>대상</b></div>${mine.length?mine.map(tlCard).join(''):'<div class="empty compact">내가 추가한 할 일이 없습니다.</div>'}</section><section class="tl-task-section"><div class="tl-section-head"><h3>팀에서 부여된 할 일</h3><span>${assigned.filter(t=>t.status!=='done').length}건</span></div><div class="tl-columns"><b>내용</b><b>기한</b><b>대상</b></div>${assigned.length?assigned.map(tlCard).join(''):'<div class="empty compact">팀에서 부여된 할 일이 없습니다.</div>'}</section>`}catch(e){const root=document.querySelector('#tlTaskSections');if(root)root.innerHTML=`<div class="status error">${tlEsc(e.message)}</div>`}finally{tlRendering=false}}
function tlAddTargetFields(){const taskDue=document.querySelector('#taskDue')?.closest('label');if(taskDue&&!document.querySelector('#taskTarget')){const lab=document.createElement('label');lab.innerHTML='대상 <span class="tl-help">제출처·취합처·전달처 등</span><input id="taskTarget" type="text" placeholder="예: 공성식 팀장 / 재경부 / 산하조직 취합">';taskDue.parentElement?.insertAdjacentElement('afterend',lab)}document.querySelectorAll('.meeting-action-row').forEach(row=>{if(row.querySelector('.meeting-action-target'))return;const input=document.createElement('input');input.className='meeting-action-target';input.type='text';input.placeholder='대상(제출·취합·전달처)';const due=row.querySelector('.meeting-action-due');row.insertBefore(input,due)})}
function tlInstallFetchPatch(){if(window.__KPTU_TASK_TARGET_PATCH__)return;window.__KPTU_TASK_TARGET_PATCH__=true;const raw=window.fetch.bind(window);window.fetch=async function(input,init={}){try{const url=typeof input==='string'?input:(input?.url||'');if(url.includes('/rest/v1/app_tasks')&&String(init.method||'GET').toUpperCase()==='POST'&&typeof init.body==='string'){const payload=JSON.parse(init.body);if(Array.isArray(payload)){const rows=[...document.querySelectorAll('.meeting-action-row')].map(r=>({title:r.querySelector('.meeting-action-title')?.value.trim()||'',assignee:r.querySelector('.meeting-action-assignee')?.value||'',target:r.querySelector('.meeting-action-target')?.value.trim()||null})).filter(x=>x.title&&x.assignee);payload.forEach((x,i)=>{if(x.source_type==='meeting'&&rows[i])x.target=rows[i].target});init={...init,body:JSON.stringify(payload)}}else if(payload&&payload.source_type==='manual'){payload.target=document.querySelector('#taskTarget')?.value.trim()||null;init={...init,body:JSON.stringify(payload)}}}}
    catch(_){}
    return raw(input,init)} }
async function tlInitContext(){const s=tlSession();if(!s?.access_token)return false;const u=await fetch(TL_SB+'/auth/v1/user',{headers:{apikey:TL_KEY,Authorization:'Bearer '+s.access_token}});if(!u.ok)return false;const user=await u.json();const ms=await tlApi(`/rest/v1/app_workspace_members?user_id=eq.${user.id}&select=workspace_id&limit=1`);if(!ms?.length)return false;tlUser=user.id;tlWorkspace=ms[0].workspace_id;tlProjects=await tlApi(`/rest/v1/app_spaces?workspace_id=eq.${tlWorkspace}&select=id,name`);return true}
function tlInstallUi(){const original=document.querySelector('#taskList');if(!original)return;document.querySelector('#tasksView .toolbar')?.classList.add('hidden');original.style.display='none';if(!document.querySelector('#tlTaskSections')){const root=document.createElement('div');root.id='tlTaskSections';original.insertAdjacentElement('afterend',root)}tlAddTargetFields();const mo=new MutationObserver(()=>{tlAddTargetFields();setTimeout(tlRender,50)});mo.observe(document.querySelector('#tasksView'),{childList:true,subtree:true});document.addEventListener('click',async e=>{const b=e.target.closest('[data-tl-toggle]');if(b){const done=b.dataset.done==='1';try{await tlApi(`/rest/v1/app_tasks?id=eq.${b.dataset.tlToggle}`,{method:'PATCH',body:{status:done?'todo':'done',completed_at:done?null:new Date().toISOString(),updated_at:new Date().toISOString()}});await tlRender()}catch(err){alert(err.message)}return}if(e.target.closest('#saveTaskBtn')){if(!document.querySelector('#taskDue')?.value){e.preventDefault();e.stopImmediatePropagation();const st=document.querySelector('#taskModalStatus');if(st){st.textContent='기한을 입력해 주세요.';st.className='status error'}return}}if(e.target.closest('#saveMeetingBtn')){const bad=[...document.querySelectorAll('.meeting-action-row')].some(r=>r.querySelector('.meeting-action-title')?.value.trim()&&r.querySelector('.meeting-action-assignee')?.value&&!r.querySelector('.meeting-action-due')?.value);if(bad){e.preventDefault();e.stopImmediatePropagation();const st=document.querySelector('#meetingStatus');if(st){st.textContent='역할분담 할 일에는 기한을 입력해 주세요.';st.className='status error'}return}}},true);new MutationObserver(()=>setTimeout(tlRender,80)).observe(original,{childList:true,subtree:true})}
function tlStyle(){if(document.querySelector('#tlStyle'))return;const s=document.createElement('style');s.id='tlStyle';s.textContent=`#tlTaskSections{display:grid;gap:18px}.tl-task-section{background:#fff;border:1px solid var(--line);border-radius:15px;padding:14px}.tl-section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.tl-section-head h3{margin:0;font-size:17px}.tl-section-head span{font-size:11px;color:var(--muted)}.tl-columns{display:grid;grid-template-columns:minmax(0,1.5fr) 170px 170px 56px;gap:10px;padding:0 8px 6px;color:#85909b;font-size:10px}.tl-task-row{display:grid;grid-template-columns:minmax(0,1.5fr) 350px 56px;gap:10px;align-items:center;border-top:1px solid #edf0f3;padding:11px 8px}.tl-task-row.done{opacity:.55}.tl-task-content b{display:block;font-size:13px}.tl-task-content small,.tl-task-content em{display:block;font-size:11px;color:var(--muted);font-style:normal;margin-top:2px}.tl-task-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tl-task-meta span{font-size:12px}.tl-task-meta i{display:none;font-style:normal;color:#8a949e;margin-right:5px}.tl-help{font-size:10px;font-weight:500;color:#86909a}.meeting-action-row{grid-template-columns:minmax(0,1.4fr) minmax(110px,.8fr) minmax(130px,.9fr) 132px auto!important}@media(max-width:700px){.tl-columns{display:none}.tl-task-row{grid-template-columns:1fr auto;align-items:start}.tl-task-meta{grid-column:1/-1;grid-template-columns:1fr 1fr;background:#f6f8fa;border-radius:8px;padding:7px 9px}.tl-task-meta i{display:inline}.meeting-action-row{grid-template-columns:1fr 1fr!important}.meeting-action-title,.meeting-action-target{grid-column:1/-1}.tl-task-section{padding:12px}}`;document.head.appendChild(s)}
(async()=>{tlInstallFetchPatch();tlStyle();if(await tlInitContext()){tlInstallUi();await tlRender()}})();