(()=>{
'use strict';
const rt=window.KPTURuntime;if(!rt)return;
let userId='',workspaceId='',projects=[],tasks=[],editing=null,installed=false,rendering=false;
const openState=new Map();
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=(p,o={})=>rt.api(p,o);
const due=v=>{if(!v)return'기한 미정';const d=new Date(v);return d.toLocaleDateString('ko-KR',{month:'numeric',day:'numeric',weekday:'short'})};
const dateValue=v=>{if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const projectName=id=>projects.find(x=>x.id===id)?.name||'';
const canDelete=t=>t?.created_by===userId;
const teamAssigned=t=>t?.source_type==='meeting'||Boolean(t?.created_by&&t.created_by!==userId);
const origin=t=>t?.source_type==='meeting'?'팀에서 부여 · 회의':teamAssigned(t)?'팀에서 부여':'내가 추가';
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2200)}
function root(){const r=$('#taskList');if(r)r.classList.add('tl-task-list');return r}
function rememberOpen(){root()?.querySelectorAll('details[data-tl-state]').forEach(d=>openState.set(d.dataset.tlState,d.open))}
function stateOpen(key,fallback){return openState.has(key)?openState.get(key):fallback}
function card(t){const p=projectName(t.project_id),title=t.title||'제목 없음';return `<article class="tl-task-row ${t.status==='done'?'done':''}" data-tl-task-row="${esc(t.id)}"><div class="tl-task-content"><div class="tl-task-title-line"><b>${esc(title)}</b><span class="tl-origin">${esc(origin(t))}</span></div><div class="tl-task-sub">${p?`<span>${esc(p)}</span>`:''}<span>${esc(due(t.due_at))}</span>${t.description?`<span class="tl-desc">${esc(t.description)}</span>`:''}</div></div><div class="tl-task-actions"><button class="mini" data-tl-edit="${esc(t.id)}" type="button">수정</button>${canDelete(t)?`<button class="mini tl-delete" data-tl-delete="${esc(t.id)}" type="button" aria-label="${esc(title+' 삭제')}">삭제</button>`:''}<button class="mini tl-complete" data-tl-toggle="${esc(t.id)}" data-done="${t.status==='done'?'1':'0'}" type="button">${t.status==='done'?'미완료':'완료'}</button></div></article>`}
function group(key,title,rows){const pending=rows.filter(t=>t.status!=='done'),done=rows.filter(t=>t.status==='done'),pendingKey=`${key}:pending`,doneKey=`${key}:done`;return `<section class="tl-task-section" data-tl-section="${key}"><div class="tl-section-head"><h3>${esc(title)}</h3><span>${rows.length}건</span></div><details class="tl-status-group tl-incomplete" data-tl-state="${pendingKey}" ${stateOpen(pendingKey,true)?'open':''}><summary><span>미완료된 할 일</span><b>${pending.length}</b></summary><div class="tl-open-list">${pending.length?pending.map(card).join(''):'<div class="empty compact">미완료된 할 일이 없습니다.</div>'}</div></details><details class="tl-status-group tl-completed" data-tl-state="${doneKey}" ${stateOpen(doneKey,false)?'open':''}><summary><span>완료된 할 일</span><b>${done.length}</b></summary><div class="tl-done-list">${done.length?done.map(card).join(''):'<div class="empty compact">완료된 할 일이 없습니다.</div>'}</div></details></section>`}
async function context(){if(!(await rt.session.ensure()))return false;const u=await api('/auth/v1/user'),ms=await api(`/rest/v1/app_workspace_members?user_id=eq.${encodeURIComponent(u.id)}&select=workspace_id&limit=1`);if(!ms?.length)return false;userId=u.id;workspaceId=ms[0].workspace_id;await loadProjects();return true}
async function loadProjects(){if(!workspaceId)return;projects=await api(`/rest/v1/app_spaces?workspace_id=eq.${encodeURIComponent(workspaceId)}&status=neq.archived&select=id,name,parent_id,status&order=sort_order.asc,created_at.asc`)||[]}
async function render(){if(rendering||!userId||!workspaceId)return;const r=root();if(!r)return;rememberOpen();rendering=true;try{tasks=await api(`/rest/v1/app_tasks?workspace_id=eq.${encodeURIComponent(workspaceId)}&assignee_id=eq.${encodeURIComponent(userId)}&select=*&order=due_at.asc.nullslast,created_at.desc`)||[];const mine=tasks.filter(t=>!teamAssigned(t)),assigned=tasks.filter(teamAssigned);r.innerHTML=group('mine','내 할 일',mine)+group('assigned','팀에서 부여된 할 일',assigned)}catch(e){r.innerHTML=`<div class="status error">${esc(e.message||String(e))}</div>`}finally{rendering=false}}
function setMode(task=null){editing=task;const modal=$('#taskModal'),h=modal?.querySelector('.modal-head h2'),btn=$('#saveTaskBtn'),status=$('#taskModalStatus');if(h)h.textContent=task?'할 일 수정':'할 일 추가';if(btn){btn.textContent=task?'수정 저장':'저장';btn.disabled=false}if(status){status.textContent='';status.className='status'}}
function closeModal(){const m=$('#taskModal');if(m){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}setMode(null)}
function ensureProjectOption(id){const s=$('#taskProject');if(!s||!id||[...s.options].some(o=>o.value===id))return;const o=document.createElement('option');o.value=id;o.textContent=projectName(id)||'기존 연결 프로젝트';s.prepend(o)}
function ensureToolbarLabels(){const pairs=[['taskScope','할 일 범위'],['taskStatus','할 일 상태']];for(const [id,text] of pairs){const control=$('#'+id);if(!control||document.querySelector(`label[for="${id}"]`))continue;const label=document.createElement('label');label.className='sr-only';label.htmlFor=id;label.textContent=text;control.before(label)}}
function openEdit(id){const t=tasks.find(x=>x.id===id);if(!t)return;setMode(t);ensureProjectOption(t.project_id);const vals={taskTitle:t.title||'',taskAssignee:t.assignee_id||userId,taskProject:t.project_id||'',taskDue:dateValue(t.due_at),taskPriority:t.priority||'normal',taskDescription:t.description||''};Object.entries(vals).forEach(([id,v])=>{const e=$('#'+id);if(e)e.value=v});const m=$('#taskModal');if(m){m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}$('#taskTitle')?.focus()}
function payload(){return{title:$('#taskTitle')?.value.trim()||'',project_id:$('#taskProject')?.value||null,assignee_id:userId,due_at:$('#taskDue')?.value?new Date($('#taskDue').value).toISOString():null,priority:$('#taskPriority')?.value||'normal',description:$('#taskDescription')?.value.trim()||null}}
function changed(id=null){window.dispatchEvent(new CustomEvent('kptu:tasks-changed',{detail:{source:'task-layout',task_id:id}}))}
async function saveTask(){const body=payload(),status=$('#taskModalStatus'),btn=$('#saveTaskBtn');if(!body.title){if(status){status.textContent='할 일을 입력해 주세요.';status.className='status error'}return}if(btn)btn.disabled=true;try{if(editing){const id=editing.id;await api(`/rest/v1/app_tasks?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{...body,updated_at:new Date().toISOString()}});closeModal();await render();changed(id);toast('할 일을 수정했습니다.')}else{const rows=await api('/rest/v1/app_tasks',{method:'POST',body:{workspace_id:workspaceId,...body,status:'todo',source_type:'manual',created_by:userId},prefer:'return=representation'});closeModal();await render();changed(rows?.[0]?.id||null);toast('할 일을 추가했습니다.')}}catch(e){if(status){status.textContent=e.message||String(e);status.className='status error'}}finally{if(btn)btn.disabled=false}}
async function remove(id){const t=tasks.find(x=>x.id===id);if(!t||!canDelete(t)||!confirm(`“${t.title}” 할 일을 삭제할까요?`))return;try{await api(`/rest/v1/app_tasks?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});await render();changed(id);toast('할 일을 삭제했습니다.')}catch(e){alert(e.message||String(e))}}
async function toggle(id,done){try{rememberOpen();await api(`/rest/v1/app_tasks?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{status:done?'todo':'done',completed_at:done?null:new Date().toISOString(),updated_at:new Date().toISOString()}});await render();changed(id)}catch(e){alert(e.message||String(e))}}
function install(){if(installed)return;const r=root(),btn=$('#saveTaskBtn');if(!r||!btn)return;installed=true;ensureToolbarLabels();document.querySelector('#taskTarget')?.closest('label')?.remove();document.querySelectorAll('.meeting-action-target').forEach(x=>x.remove());btn.onclick=saveTask;document.addEventListener('toggle',e=>{const d=e.target?.closest?.('#taskList details[data-tl-state]');if(d)openState.set(d.dataset.tlState,d.open)},true);document.addEventListener('click',e=>{if(e.target.closest?.('#quickTaskBtn,#newTaskBtn')){setMode(null);return}const edit=e.target.closest?.('[data-tl-edit]');if(edit){e.preventDefault();openEdit(edit.dataset.tlEdit);return}const del=e.target.closest?.('[data-tl-delete]');if(del){e.preventDefault();remove(del.dataset.tlDelete);return}const t=e.target.closest?.('[data-tl-toggle]');if(t){e.preventDefault();toggle(t.dataset.tlToggle,t.dataset.done==='1');return}if(e.target.closest?.('[data-close="taskModal"]')&&editing)setMode(null)},true);window.KPTURouter?.on?.('tasks',render);window.addEventListener('kptu:tasks-changed',e=>{if(e.detail?.source!=='task-layout')render()});window.addEventListener('kptu:projects-changed',async()=>{await loadProjects();render()})}
async function boot(){if(!(await context()))return false;install();await render();return true}
window.__KPTU_TASK_LAYOUT_READY__=boot().catch(e=>{console.error('task layout init',e);return false});
window.addEventListener('kptu:session-changed',e=>{if(!e.detail?.session){userId='';workspaceId='';projects=[];tasks=[];openState.clear();return}window.__KPTU_TASK_LAYOUT_READY__=context().then(async ok=>{if(ok){install();await render()}return ok}).catch(()=>false)});
})();
