const SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const SESSION_KEY='kptu_collab_session_v1';
const GOOGLE_FN=SB+'/functions/v1/google-calendar';
const ROLE_LABEL={owner:'소유자',admin:'관리자',editor:'편집자',author:'작성자',viewer:'열람자'};
const VIS_LABEL={public:'전체 공개',unlisted:'링크 공개',workspace:'로그인 사용자',groups:'지정 그룹',private:'비공개'};
const STATUS_LABEL={draft:'초안',review:'검토중',published:'게시',archived:'보관'};
const EVENT_LABEL={meeting:'회의',press:'기자회견',rally:'집회',field:'현장',deadline:'마감',education:'교육',other:'기타'};
const TASK_LABEL={todo:'할 일',doing:'진행',done:'완료',blocked:'막힘'};
let session=null,user=null,membership=null,workspace=null,authMode='signin';
let members=[],profiles=[],spaces=[],groups=[],pages=[],events=[],attendees=[],tasks=[],meetings=[],documents=[],notifications=[];
let editingPage=null,currentProject=null,monthCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let googleState={connected:false,enabled:false,selected:[],calendars:[],events:[],email:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
const dateKey=v=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const slugify=v=>{const s=String(v||'').toLowerCase().trim().replace(/[^a-z0-9가-힣]+/g,'-').replace(/^-+|-+$/g,'');return s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9-]/g,'')||('project-'+Date.now().toString(36))};
const todayKey=()=>dateKey(new Date());
function setStatus(el,msg,type=''){if(!el)return;el.textContent=msg||'';el.className='status'+(type?' '+type:'')}
function toast(msg){const t=$('#toast');if(!t)return; t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2600)}
function saveSession(s){session=s;if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY)}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function refreshSession(){if(!session?.refresh_token)return false;const r=await fetch(SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){saveSession(null);return false}const d=await r.json();d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d);return true}
async function ensureSession(){if(!session)return false;if((session.expires_at||0)<Math.floor(Date.now()/1000)+60)return refreshSession();return true}
async function api(path,{method='GET',body=null,auth=true,prefer=''}={}){if(auth&&!(await ensureSession()))throw new Error('로그인이 필요합니다.');const headers={apikey:KEY,'Content-Type':'application/json'};headers.Authorization='Bearer '+(auth?session.access_token:KEY);if(prefer)headers.Prefer=prefer;const r=await fetch(SB+path,{method,headers,body:body===null?null:JSON.stringify(body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.hint||('요청 실패 '+r.status));return data}
async function rpc(name,payload={}){return api('/rest/v1/rpc/'+name,{method:'POST',body:payload})}
async function getUser(){return api('/auth/v1/user')}
function profileName(id){const p=profiles.find(x=>x.user_id===id);const m=members.find(x=>x.user_id===id);return p?.display_name||m?.email||id?.slice(0,8)||'미지정'}
function projectName(id){return spaces.find(x=>x.id===id)?.name||''}
function projectOptions(includeBlank=true){return (includeBlank?'<option value="">프로젝트 없음</option>':'')+spaces.filter(x=>x.status!=='archived').map(x=>`<option value="${x.id}">${esc(x.parent_id?'↳ ':'')}${esc(x.name)}</option>`).join('')}
function memberOptions(includeBlank=true){return (includeBlank?'<option value="">담당자 없음</option>':'')+members.map(m=>`<option value="${m.user_id}">${esc(profileName(m.user_id))}</option>`).join('')}
function showOnly(id){['authView','bootstrapView','appView'].forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id))}
function setAuthMode(mode){authMode=mode;$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===mode));$('#displayNameRow')?.classList.toggle('hidden',mode!=='signup');$('#passwordConfirmRow')?.classList.toggle('hidden',mode!=='signup');if($('#authSubmit'))$('#authSubmit').textContent=mode==='signup'?'계정 만들기':'로그인';if($('#authPassword'))$('#authPassword').autocomplete=mode==='signup'?'new-password':'current-password';setStatus($('#authStatus'),'')}
function enhanceDom(){
  if(!$('#passwordConfirmRow')){const pw=$('#authPassword')?.closest('label');if(pw){const lab=document.createElement('label');lab.id='passwordConfirmRow';lab.className='hidden';lab.innerHTML='비밀번호 확인<input id="authPasswordConfirm" type="password" minlength="8" autocomplete="new-password" required>';pw.after(lab)}}
  const nav=$('.app-nav');if(nav&&!nav.querySelector('[data-view="myspace"]'))nav.insertAdjacentHTML('beforeend','<button class="nav-btn" data-view="myspace" type="button">내 공간</button>');
  if(!$('#myspaceView'))$('#appView')?.insertAdjacentHTML('beforeend',`<section id="myspaceView" class="view-panel hidden"><div class="section-head"><div><h2>내 공간</h2><p>기존 개인 업무현황과 직접 운영하는 현장공유 페이지에 접근합니다.</p></div></div><div id="mySpaceLinks" class="project-grid"></div><div class="notice">이 영역은 팀 공용 프로젝트와 별개로 계속 사용할 수 있습니다.</div></section>`);
  const ph=$('#projectsView .section-head');if(ph&&!$('#newProjectBtn'))ph.insertAdjacentHTML('beforeend','<button id="newProjectBtn" class="primary" type="button">+ 프로젝트 만들기</button>');
  const ch=$('#calendarView .section-head');if(ch&&!$('#googleCalendarControls'))ch.insertAdjacentHTML('afterend',`<div id="googleCalendarControls" class="google-bar"><label class="toggle-line"><input id="showTeamCalendar" type="checkbox" checked> 팀 일정</label><label class="toggle-line"><input id="showGoogleCalendar" type="checkbox"> Google 일정</label><button id="googleConnectBtn" class="secondary" type="button">Google Calendar 연결</button><span id="googleAccountLabel" class="updated"></span></div><div id="googleCalendarList" class="google-cal-list hidden"></div>`);
  if(!$('#projectCreateModal'))document.body.insertAdjacentHTML('beforeend',`<div id="projectCreateModal" class="modal hidden" aria-hidden="true"><div class="modal-card small-card"><div class="modal-head"><div><div class="eyebrow">PROJECT</div><h2>프로젝트 만들기</h2></div><button class="icon-btn" data-close="projectCreateModal" type="button">×</button></div><label>프로젝트명<input id="newProjectName" type="text"></label><label>상위 프로젝트<select id="newProjectParent"></select></label><label>목표·설명<textarea id="newProjectDescription" rows="4" placeholder="무엇을 하려는 프로젝트인지 간단히 적습니다."></textarea></label><button id="saveProjectBtn" class="primary wide" type="button">프로젝트 개설</button><div id="projectCreateStatus" class="status"></div></div></div>`);
  const pm=$('#projectModal .modal-head');if(pm&&!$('#newSubprojectBtn'))pm.querySelector('div')?.insertAdjacentHTML('beforeend','<button id="newSubprojectBtn" class="mini" type="button">+ 하위 프로젝트</button>');
  const css=document.createElement('link');css.rel='stylesheet';css.href='./team.css?v=1';document.head.appendChild(css);
}
async function signIn(email,password){const r=await fetch(SB+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'로그인에 실패했습니다.');d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d)}
async function signUp(email,password,displayName){const r=await fetch(SB+'/auth/v1/signup',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password,data:{display_name:displayName||''}})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'계정 생성에 실패했습니다.');if(d.access_token){d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d);return true}return false}
async function logout(){try{if(session)await api('/auth/v1/logout',{method:'POST'})}catch{}saveSession(null);location.href='./'}
async function acceptInviteIfPresent(){const token=new URLSearchParams(location.search).get('invite');if(!token)return;try{await rpc('app_accept_invite',{p_token:token});history.replaceState({},'',location.pathname);toast('초대가 적용되었습니다.')}catch(e){toast('초대 링크: '+e.message)}}
async function loadWorkspaceState(){user=await getUser();await acceptInviteIfPresent();const ms=await api('/rest/v1/app_workspace_members?user_id=eq.'+user.id+'&select=workspace_id,role&limit=1');if(!ms?.length){showOnly('bootstrapView');$('#bootstrapName').value=user.user_metadata?.display_name||user.email?.split('@')[0]||'';$('#userBadge').textContent=user.email||'';$('#userBadge').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');return}membership=ms[0];const ws=await api('/rest/v1/app_workspaces?id=eq.'+membership.workspace_id+'&select=id,slug,name&limit=1');workspace=ws[0];showOnly('appView');$('#workspaceName').textContent='공공기관사업팀 Workspace';$('#workspaceRole').textContent='내 권한 · '+(ROLE_LABEL[membership.role]||membership.role);$('#userBadge').textContent=(user.user_metadata?.display_name||user.email||'')+' · '+(ROLE_LABEL[membership.role]||membership.role);$('#userBadge').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');const admin=['owner','admin'].includes(membership.role);$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!admin));await loadAll();renderAll();if(new URLSearchParams(location.search).get('google')==='connected'){history.replaceState({},'',location.pathname);await loadGoogleStatus(true)}}
async function loadAll(){const wid=workspace.id;[members,profiles,spaces,groups,pages,events,attendees,tasks,meetings,documents,notifications]=await Promise.all([
 api('/rest/v1/app_workspace_members?workspace_id=eq.'+wid+'&select=workspace_id,user_id,role,created_at'),
 api('/rest/v1/app_profiles?select=user_id,display_name,created_at,updated_at'),
 api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc'),
 api('/rest/v1/app_groups?workspace_id=eq.'+wid+'&select=*&order=name.asc'),
 api('/rest/v1/app_pages?workspace_id=eq.'+wid+'&select=id,space_id,slug,title,summary,visibility,status,owner_id,legacy_path,published_at,created_at,updated_at&order=updated_at.desc'),
 api('/rest/v1/app_events?workspace_id=eq.'+wid+'&select=*&order=start_at.asc'),
 api('/rest/v1/app_event_attendees?select=*'),
 api('/rest/v1/app_tasks?workspace_id=eq.'+wid+'&select=*&order=due_at.asc.nullslast,created_at.desc'),
 api('/rest/v1/app_meetings?workspace_id=eq.'+wid+'&select=*&order=meeting_at.desc'),
 api('/rest/v1/app_documents?workspace_id=eq.'+wid+'&select=*&order=document_date.desc.nullslast,created_at.desc'),
 api('/rest/v1/app_notifications?user_id=eq.'+user.id+'&select=*&order=created_at.desc&limit=30')
] )}
function renderAll(){fillSelects();renderHome();renderCalendar();renderTasks();renderProjects();renderDocuments();renderMeetings();renderPages();renderTeam();renderMySpace()}
function fillSelects(){const po=projectOptions(true),mo=memberOptions(true);['eventProject','taskProject','docProject','meetingProject','pageSpace'].forEach(id=>{if($('#'+id))$('#'+id).innerHTML=po});['taskAssignee','meetingTaskAssignee','projectCheckAssignee'].forEach(id=>{if($('#'+id))$('#'+id).innerHTML=mo});if($('#documentProject'))$('#documentProject').innerHTML='<option value="all">전체 프로젝트</option>'+spaces.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if($('#eventAttendees'))$('#eventAttendees').innerHTML=members.filter(m=>m.user_id!==user.id).map(m=>`<label class="group-check"><input type="checkbox" value="${m.user_id}"><span>${esc(profileName(m.user_id))}</span></label>`).join('');if($('#inviteGroup'))$('#inviteGroup').innerHTML='<option value="">그룹 지정 없음</option>'+groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');if($('#newProjectParent'))$('#newProjectParent').innerHTML='<option value="">상위 프로젝트 없음</option>'+spaces.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
function eventPeople(ev){const aa=attendees.filter(a=>a.event_id===ev.id&&a.status==='accepted').map(a=>profileName(a.user_id));if(!aa.length)aa.push(profileName(ev.created_by));return [...new Set(aa)]}
function renderHome(){const t=todayKey(),todayEvents=events.filter(e=>dateKey(e.start_at)===t),myOpen=tasks.filter(x=>x.assignee_id===user.id&&x.status!=='done'),unread=notifications.filter(n=>!n.read_at);$('#statToday').textContent=todayEvents.length;$('#statMyTasks').textContent=myOpen.length;$('#statProjects').textContent=spaces.filter(s=>s.status==='active').length;$('#statUnread').textContent=unread.length;$('#todayList').innerHTML=todayEvents.length?todayEvents.map(e=>`<div class="list-item"><b>${esc(e.title)}</b><span>${fmt(e.start_at)} · ${esc(e.location||'장소 미정')}</span><small>${esc(eventPeople(e).join(', '))}</small></div>`).join(''):'<div class="empty compact">오늘 등록된 일정이 없습니다.</div>';$('#myTaskMini').innerHTML=myOpen.slice(0,6).map(t=>`<div class="list-item"><b>${esc(t.title)}</b><span>${esc(projectName(t.project_id)||'일반 업무')}${t.due_at?' · '+fmt(t.due_at):''}</span></div>`).join('')||'<div class="empty compact">미완료 업무가 없습니다.</div>';$('#notifList').innerHTML=notifications.slice(0,8).map(n=>`<button class="notif-row ${n.read_at?'':'unread'}" data-read-notif="${n.id}"><b>${esc(n.title)}</b><span>${esc(n.body||'')}</span><small>${fmt(n.created_at)}</small></button>`).join('')||'<div class="empty compact">새 알림이 없습니다.</div>';renderWeeklyPreview()}
function renderWeeklyPreview(){const now=new Date(),start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+7);const es=events.filter(e=>new Date(e.start_at)>=start&&new Date(e.start_at)<end);const ts=tasks.filter(t=>new Date(t.created_at)>=start&&new Date(t.created_at)<end);const lines=['[이번 주 업무]'];if(es.length){lines.push('◦ 일정');es.forEach(e=>lines.push(`- ${new Date(e.start_at).toLocaleDateString('ko-KR')} ${e.title}${e.location?' / '+e.location:''}`))}if(ts.length){lines.push('◦ 업무');ts.forEach(t=>lines.push(`- ${t.title} / ${profileName(t.assignee_id)} / ${TASK_LABEL[t.status]||t.status}`))}$('#weeklyPreview').textContent=lines.join('\n')}
function renderCalendar(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthTitle').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1),start=new Date(first);start.setDate(1-first.getDay());const showTeam=$('#showTeamCalendar')?.checked!==false,showGoogle=$('#showGoogleCalendar')?.checked===true;const all=[];if(showTeam)all.push(...events.map(e=>({...e,source:'team',start:e.start_at})));if(showGoogle)all.push(...googleState.events);let html=['<div class="cal-head">일</div>','<div class="cal-head">월</div>','<div class="cal-head">화</div>','<div class="cal-head">수</div>','<div class="cal-head">목</div>','<div class="cal-head">금</div>','<div class="cal-head">토</div>'].join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),inMonth=d.getMonth()===m,dayEvents=all.filter(e=>dateKey(e.start)===key);html+=`<div class="cal-cell ${inMonth?'':'other'} ${key===todayKey()?'today':''}"><span class="cal-day">${d.getDate()}</span>${dayEvents.slice(0,4).map(e=>`<div class="cal-event ${e.source==='google'?'google':''}" title="${esc(e.title)}">${esc(e.title)}</div>`).join('')}${dayEvents.length>4?`<small>+${dayEvents.length-4}</small>`:''}</div>`}$('#calendarGrid').innerHTML=html;const now=new Date();const up=all.filter(e=>new Date(e.start)>=now).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,20);$('#upcomingEvents').innerHTML=up.map(e=>eventCard(e)).join('')||'<div class="empty">다가오는 일정이 없습니다.</div>';renderGoogleControls()}
function eventCard(e){if(e.source==='google')return `<article class="item-card"><div><span class="badge google">Google</span><h3>${esc(e.title)}</h3><p>${fmt(e.start)}${e.location?' · '+esc(e.location):''}</p></div><div class="card-actions"><button class="mini" data-import-google="${esc(e.id)}">팀 일정으로 가져오기</button></div></article>`;const mine=attendees.find(a=>a.event_id===e.id&&a.user_id===user.id);return `<article class="item-card"><div><span class="badge">${esc(EVENT_LABEL[e.event_type]||e.event_type)}</span><h3>${esc(e.title)}</h3><p>${fmt(e.start_at)}${e.location?' · '+esc(e.location):''}</p><small>${esc(eventPeople(e).join(', '))}</small></div><div class="card-actions">${mine?.status==='invited'?`<button class="mini" data-event-response="accepted" data-event="${e.id}">수락</button><button class="mini" data-event-response="declined" data-event="${e.id}">거절</button>`:''}</div></article>`}
function renderTasks(){const scope=$('#taskScope')?.value||'mine',stat=$('#taskStatus')?.value||'open';let rows=tasks.filter(t=>scope==='team'||t.assignee_id===user.id);if(stat==='open')rows=rows.filter(t=>t.status!=='done');if(stat==='done')rows=rows.filter(t=>t.status==='done');$('#taskList').innerHTML=rows.map(t=>`<article class="item-card ${t.status==='done'?'done':''}"><div><div class="badges"><span class="badge ${t.priority}">${esc(t.priority)}</span><span class="badge">${esc(TASK_LABEL[t.status]||t.status)}</span></div><h3>${esc(t.title)}</h3><p>${esc(projectName(t.project_id)||'일반 업무')} · ${esc(profileName(t.assignee_id))}${t.due_at?' · '+fmt(t.due_at):''}</p>${t.description?`<small>${esc(t.description)}</small>`:''}</div><div class="card-actions"><button class="mini" data-task-toggle="${t.id}">${t.status==='done'?'되돌리기':'완료'}</button></div></article>`).join('')||'<div class="empty">해당하는 할 일이 없습니다.</div>'}
function renderProjects(){const tops=spaces.filter(s=>!s.parent_id&&s.status!=='archived');$('#projectGrid').innerHTML=tops.map(s=>projectCard(s)).join('')||'<div class="empty">프로젝트가 없습니다.</div>'}
function projectCard(s){const children=spaces.filter(x=>x.parent_id===s.id&&x.status!=='archived'),openTasks=tasks.filter(t=>t.project_id===s.id&&t.status!=='done').length;return `<button class="project-card" data-project="${s.id}"><span class="badge">${esc(s.status)}</span><h3>${esc(s.name)}</h3><p>${esc(s.description||'설명 없음')}</p><div class="project-stats"><span>할 일 ${openTasks}</span><span>하위 ${children.length}</span></div>${children.length?`<div class="subchips">${children.slice(0,4).map(c=>`<span>${esc(c.name)}</span>`).join('')}</div>`:''}</button>`}
async function openProject(id){currentProject=spaces.find(s=>s.id===id);if(!currentProject)return;$('#projectModalTitle').textContent=currentProject.name;$('#projectModalDesc').textContent=currentProject.description||'';$('#projectCheckAssignee').innerHTML=memberOptions(true);const [ups,checks,comments]=await Promise.all([api('/rest/v1/app_project_updates?project_id=eq.'+id+'&select=*&order=created_at.desc'),api('/rest/v1/app_project_checkitems?project_id=eq.'+id+'&select=*&order=created_at.asc'),api('/rest/v1/app_project_comments?project_id=eq.'+id+'&select=*&order=created_at.asc')]);$('#projectUpdates').innerHTML=ups.map(x=>`<div class="list-item"><b>${esc(x.kind)} · ${esc(profileName(x.author_id))}</b><span>${esc(x.body)}</span><small>${fmt(x.created_at)}</small></div>`).join('')||'<div class="empty compact">업데이트가 없습니다.</div>';$('#projectChecks').innerHTML=checks.map(x=>`<label class="check-row"><input type="checkbox" data-project-check="${x.id}" ${x.checked?'checked':''}><span>${esc(x.title)}</span><small>${esc(profileName(x.assignee_id))}</small></label>`).join('')||'<div class="empty compact">체크리스트가 없습니다.</div>';$('#projectComments').innerHTML=comments.map(x=>`<div class="comment-row"><b>${esc(profileName(x.author_id))}</b><span>${esc(x.body)}</span><small>${fmt(x.created_at)}</small></div>`).join('')||'<div class="empty compact">댓글이 없습니다.</div>';openModal('projectModal')}
function renderDocuments(){const q=($('#documentSearch')?.value||'').trim().toLowerCase(),pid=$('#documentProject')?.value||'all';const rows=documents.filter(d=>(pid==='all'||d.project_id===pid)&&(!q||[d.title,d.source,d.category,(d.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));$('#documentList').innerHTML=rows.map(d=>`<article class="item-card"><div><div class="badges"><span class="badge">${esc(d.category)}</span>${d.project_id?`<span class="badge">${esc(projectName(d.project_id))}</span>`:''}</div><h3>${esc(d.title)}</h3><p>${esc(d.source||'출처 미기재')}${d.document_date?' · '+esc(d.document_date):''}</p>${d.description?`<small>${esc(d.description)}</small>`:''}</div>${d.drive_url?`<a class="mini" href="${esc(d.drive_url)}" target="_blank" rel="noopener">열기</a>`:''}</article>`).join('')||'<div class="empty">자료가 없습니다.</div>'}
function renderMeetings(){$('#meetingList').innerHTML=meetings.map(m=>`<article class="item-card"><div><h3>${esc(m.title)}</h3><p>${fmt(m.meeting_at)}${m.project_id?' · '+esc(projectName(m.project_id)):''}</p>${m.decisions?`<small><b>결정:</b> ${esc(m.decisions).slice(0,260)}</small>`:''}</div></article>`).join('')||'<div class="empty">회의 결과가 없습니다.</div>'}
function renderPages(){const q=($('#pageSearch')?.value||'').trim().toLowerCase(),f=$('#pageFilter')?.value||'all';const rows=pages.filter(p=>(f==='all'||p.status===f)&&(!q||(p.title+' '+(p.summary||'')).toLowerCase().includes(q)));$('#pageEmpty')?.classList.toggle('hidden',rows.length>0);$('#pageList').innerHTML=rows.map(p=>`<article class="page-card"><div class="badges"><span class="badge ${p.status}">${esc(STATUS_LABEL[p.status]||p.status)}</span><span class="badge ${p.visibility}">${esc(VIS_LABEL[p.visibility]||p.visibility)}</span>${p.space_id?`<span class="badge">${esc(projectName(p.space_id))}</span>`:''}</div><h3>${esc(p.title)}</h3><p>${esc(p.summary||'요약 없음')}</p><div class="page-card-foot"><span class="updated">${fmt(p.updated_at)}</span><div class="card-actions"><button class="mini" data-edit-page="${p.id}">편집</button>${p.status==='published'&&['public','unlisted'].includes(p.visibility)?`<a class="mini" href="../p/?slug=${encodeURIComponent(p.slug)}" target="_blank">열기</a><button class="mini" data-copy-page="${p.slug}">링크 복사</button>`:''}</div></div></article>`).join('')}
function renderTeam(){$('#memberList').innerHTML=members.map(m=>`<div class="member-card"><b>${esc(profileName(m.user_id))}</b><span>${esc(ROLE_LABEL[m.role]||m.role)}</span></div>`).join('');$('#groupList').innerHTML=groups.map(g=>`<div class="group-card"><b>${esc(g.name)}</b><span>${esc(g.description||'')}</span></div>`).join('')||'<div class="empty">그룹이 없습니다.</div>'}
function renderMySpace(){const base=[{name:'내 업무 현황',url:'../',desc:'기존 개인 업무 현황 메인'}];spaces.filter(s=>s.owner_id===user.id&&s.legacy_path).forEach(s=>base.push({name:s.name,url:s.legacy_path,desc:s.description||'기존 프로젝트 페이지'}));$('#mySpaceLinks').innerHTML=base.map(x=>`<a class="project-card link-card" href="${esc(x.url)}"><h3>${esc(x.name)}</h3><p>${esc(x.desc)}</p><span>열기 →</span></a>`).join('')}
function openModal(id){const m=$('#'+id);if(!m)return;m.classList.remove('hidden');m.setAttribute('aria-hidden','false')}
function closeModal(id){const m=$('#'+id);if(!m)return;m.classList.add('hidden');m.setAttribute('aria-hidden','true')}
async function saveEvent(){const title=$('#eventTitle').value.trim(),start=$('#eventStart').value;if(!title||!start)return setStatus($('#eventStatus'),'제목과 시작시간을 입력해 주세요.','error');setStatus($('#eventStatus'),'저장 중…');try{const rows=await api('/rest/v1/app_events',{method:'POST',body:{workspace_id:workspace.id,project_id:$('#eventProject').value||null,title,description:$('#eventDescription').value.trim()||null,event_type:$('#eventType').value,start_at:new Date(start).toISOString(),end_at:$('#eventEnd').value?new Date($('#eventEnd').value).toISOString():null,location:$('#eventLocation').value.trim()||null,created_by:user.id},prefer:'return=representation'});const ev=rows[0];const ids=$$('#eventAttendees input:checked').map(x=>x.value);if(ids.length)await api('/rest/v1/app_event_attendees',{method:'POST',body:ids.map(user_id=>({event_id:ev.id,user_id,status:'invited'}))});closeModal('eventModal');await reload(['events','attendees','notifications']);toast('일정을 등록했습니다.')}catch(e){setStatus($('#eventStatus'),e.message,'error')}}
async function saveTask(){const title=$('#taskTitle').value.trim();if(!title)return setStatus($('#taskModalStatus'),'할 일을 입력해 주세요.','error');try{await api('/rest/v1/app_tasks',{method:'POST',body:{workspace_id:workspace.id,project_id:$('#taskProject').value||null,title,description:$('#taskDescription').value.trim()||null,assignee_id:$('#taskAssignee').value||null,status:'todo',priority:$('#taskPriority').value,due_at:$('#taskDue').value?new Date($('#taskDue').value).toISOString():null,source_type:'manual',created_by:user.id}});closeModal('taskModal');await reload(['tasks','notifications']);toast('할 일을 추가했습니다.')}catch(e){setStatus($('#taskModalStatus'),e.message,'error')}}
async function saveDocument(){const title=$('#docTitle').value.trim();if(!title)return setStatus($('#documentStatus'),'자료명을 입력해 주세요.','error');try{await api('/rest/v1/app_documents',{method:'POST',body:{workspace_id:workspace.id,project_id:$('#docProject').value||null,title,category:$('#docCategory').value.trim()||'기타',source:$('#docSource').value.trim()||null,document_date:$('#docDate').value||null,description:$('#docDescription').value.trim()||null,tags:$('#docTags').value.split(',').map(x=>x.trim()).filter(Boolean),drive_url:$('#docUrl').value.trim()||null,visibility:'workspace',uploaded_by:user.id}});closeModal('documentModal');await reload(['documents']);toast('자료를 등록했습니다.')}catch(e){setStatus($('#documentStatus'),e.message,'error')}}
async function saveMeeting(){const title=$('#meetingTitle').value.trim();if(!title)return setStatus($('#meetingStatus'),'회의명을 입력해 주세요.','error');try{const rows=await api('/rest/v1/app_meetings',{method:'POST',body:{workspace_id:workspace.id,project_id:$('#meetingProject').value||null,title,meeting_at:$('#meetingAt').value?new Date($('#meetingAt').value).toISOString():new Date().toISOString(),notes:$('#meetingNotes').value,decisions:$('#meetingDecisions').value,created_by:user.id},prefer:'return=representation'});const tt=$('#meetingTaskTitle').value.trim();if(tt)await api('/rest/v1/app_tasks',{method:'POST',body:{workspace_id:workspace.id,project_id:$('#meetingProject').value||null,title:tt,assignee_id:$('#meetingTaskAssignee').value||null,status:'todo',priority:'normal',due_at:$('#meetingTaskDue').value?new Date($('#meetingTaskDue').value).toISOString():null,source_type:'meeting',source_id:rows[0].id,created_by:user.id}});closeModal('meetingModal');await reload(['meetings','tasks','notifications']);toast('회의 결과를 저장했습니다.')}catch(e){setStatus($('#meetingStatus'),e.message,'error')}}
async function saveProject(){const name=$('#newProjectName').value.trim();if(!name)return setStatus($('#projectCreateStatus'),'프로젝트명을 입력해 주세요.','error');try{const max=Math.max(0,...spaces.map(s=>s.sort_order||0));await api('/rest/v1/app_spaces',{method:'POST',body:{workspace_id:workspace.id,parent_id:$('#newProjectParent').value||null,slug:slugify(name)+'-'+Date.now().toString(36).slice(-3),name,description:$('#newProjectDescription').value.trim()||null,sort_order:max+10,created_by:user.id,owner_id:user.id,status:'active'}});closeModal('projectCreateModal');await reload(['spaces']);toast('프로젝트를 만들었습니다.')}catch(e){setStatus($('#projectCreateStatus'),e.message,'error')}}
function openProjectCreate(parent=null){$('#newProjectName').value='';$('#newProjectDescription').value='';$('#newProjectParent').innerHTML='<option value="">상위 프로젝트 없음</option>'+spaces.map(s=>`<option value="${s.id}" ${parent===s.id?'selected':''}>${esc(s.name)}</option>`).join('');setStatus($('#projectCreateStatus'),'');openModal('projectCreateModal')}
async function addProjectUpdate(){const body=$('#projectUpdateBody').value.trim();if(!body||!currentProject)return;await api('/rest/v1/app_project_updates',{method:'POST',body:{project_id:currentProject.id,author_id:user.id,kind:$('#projectUpdateKind').value,body}});$('#projectUpdateBody').value='';await openProject(currentProject.id)}
async function addProjectCheck(){const title=$('#projectCheckTitle').value.trim();if(!title||!currentProject)return;await api('/rest/v1/app_project_checkitems',{method:'POST',body:{project_id:currentProject.id,title,assignee_id:$('#projectCheckAssignee').value||null,created_by:user.id}});$('#projectCheckTitle').value='';await openProject(currentProject.id);await reload(['notifications'])}
async function addProjectComment(){const body=$('#projectCommentBody').value.trim();if(!body||!currentProject)return;await api('/rest/v1/app_project_comments',{method:'POST',body:{project_id:currentProject.id,author_id:user.id,body}});$('#projectCommentBody').value='';await notifyMentions(body,currentProject);await openProject(currentProject.id)}
async function notifyMentions(body,project){for(const m of members){const name=profileName(m.user_id);if(m.user_id!==user.id&&name&&body.includes('@'+name)){try{await rpc('app_notify_member',{p_workspace:workspace.id,p_user:m.user_id,p_title:'프로젝트에서 언급되었습니다.',p_body:`${project.name}: ${body}`,p_related_type:'project',p_related_id:project.id})}catch{}}}}
async function openEditor(id=null){editingPage=id?pages.find(p=>p.id===id):null;$('#editorHeading').textContent=editingPage?'페이지 편집':'새 페이지';$('#pageTitle').value=editingPage?.title||'';$('#pageSlug').value=editingPage?.slug||('page-'+Date.now().toString(36));$('#pageSummary').value=editingPage?.summary||'';$('#pageStatus').value=editingPage?.status||'draft';$('#pageVisibility').value=editingPage?.visibility||'private';$('#pageSpace').innerHTML=projectOptions(true);$('#pageSpace').value=editingPage?.space_id||'';$('#pageBody').value='';$('#secureShareBtn').classList.toggle('hidden',!editingPage);$('#publicOpenBtn').classList.add('hidden');renderGroupChecks();if(editingPage){const full=await api('/rest/v1/app_pages?id=eq.'+id+'&select=body&limit=1');$('#pageBody').value=full[0]?.body||'';const perms=await api('/rest/v1/app_page_permissions?page_id=eq.'+id+'&group_id=not.is.null&select=group_id');const selected=new Set(perms.map(x=>x.group_id));$$('#pageGroupChecks input').forEach(x=>x.checked=selected.has(x.value));if(editingPage.status==='published'&&['public','unlisted'].includes(editingPage.visibility)){const a=$('#publicOpenBtn');a.href='../p/?slug='+encodeURIComponent(editingPage.slug);a.classList.remove('hidden')}await loadRevisions(id)}else $('#revisionList').textContent='첫 저장부터 자동 기록됩니다.';openModal('editorModal')}
function renderGroupChecks(){$('#pageGroupChecks').innerHTML=groups.length?groups.map(g=>`<label class="group-check"><input type="checkbox" value="${g.id}"><span>${esc(g.name)}</span></label>`).join(''):'<span class="updated">그룹이 없습니다.</span>'}
async function loadRevisions(id){const rows=await api('/rest/v1/app_page_revisions?page_id=eq.'+id+'&select=revision_no,created_at&order=revision_no.desc&limit=8');$('#revisionList').innerHTML=rows.length?rows.map(r=>`<span>v${r.revision_no} · ${fmt(r.created_at)}</span>`).join(''):'이력이 없습니다.'}
async function syncPageGroups(id){const selected=$$('#pageGroupChecks input:checked').map(x=>x.value);await api('/rest/v1/app_page_permissions?page_id=eq.'+id+'&group_id=not.is.null',{method:'DELETE'});if(selected.length)await api('/rest/v1/app_page_permissions',{method:'POST',body:selected.map(group_id=>({page_id:id,group_id,permission:'view'}))})}
async function savePage(){const title=$('#pageTitle').value.trim();if(!title)return setStatus($('#editorStatus'),'제목을 입력해 주세요.','error');const body={space_id:$('#pageSpace').value||null,title,slug:slugify($('#pageSlug').value),summary:$('#pageSummary').value.trim(),body:$('#pageBody').value,content_format:'markdown',status:$('#pageStatus').value,visibility:$('#pageVisibility').value,published_at:$('#pageStatus').value==='published'?(editingPage?.published_at||new Date().toISOString()):editingPage?.published_at||null};try{let saved;if(editingPage){saved=(await api('/rest/v1/app_pages?id=eq.'+editingPage.id,{method:'PATCH',body,prefer:'return=representation'}))[0]}else{saved=(await api('/rest/v1/app_pages',{method:'POST',body:{...body,workspace_id:workspace.id,owner_id:user.id},prefer:'return=representation'}))[0]}await syncPageGroups(saved.id);editingPage=saved;await reload(['pages']);await loadRevisions(saved.id);$('#secureShareBtn').classList.remove('hidden');if(saved.status==='published'&&['public','unlisted'].includes(saved.visibility)){const a=$('#publicOpenBtn');a.href='../p/?slug='+saved.slug;a.classList.remove('hidden')}toast('페이지를 저장했습니다.')}catch(e){setStatus($('#editorStatus'),e.message,'error')}}
async function createSecureShare(){if(!editingPage)return;const token=await rpc('app_create_share_link',{p_page:editingPage.id});const url=new URL('../s/?t='+encodeURIComponent(token),location.href).href;await copy(url,'비밀 공유링크를 복사했습니다.')}
async function createInvite(){try{const token=await rpc('app_create_invite',{p_role:$('#inviteRole').value,p_group:$('#inviteGroup').value||null});const url=new URL('./?invite='+encodeURIComponent(token),location.href).href;$('#inviteResult').innerHTML=`<b>초대링크</b><br><a href="${esc(url)}">${esc(url)}</a><br><button id="copyInviteBtn" class="mini">링크 복사</button>`;$('#inviteResult').classList.remove('hidden');$('#copyInviteBtn').onclick=()=>copy(url,'초대링크를 복사했습니다.')}catch(e){$('#inviteResult').textContent=e.message;$('#inviteResult').classList.remove('hidden')}}
async function saveGroup(){const name=$('#groupName').value.trim();if(!name)return;await api('/rest/v1/app_groups',{method:'POST',body:{workspace_id:workspace.id,name,slug:slugify($('#groupSlug').value||name),description:$('#groupDescription').value.trim()||null}});closeModal('groupModal');await reload(['groups']);toast('그룹을 만들었습니다.')}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);toast(msg)}catch{prompt('복사',text)}}
async function reload(parts){const wid=workspace.id;for(const p of parts){if(p==='events')events=await api('/rest/v1/app_events?workspace_id=eq.'+wid+'&select=*&order=start_at.asc');if(p==='attendees')attendees=await api('/rest/v1/app_event_attendees?select=*');if(p==='tasks')tasks=await api('/rest/v1/app_tasks?workspace_id=eq.'+wid+'&select=*&order=due_at.asc.nullslast,created_at.desc');if(p==='meetings')meetings=await api('/rest/v1/app_meetings?workspace_id=eq.'+wid+'&select=*&order=meeting_at.desc');if(p==='documents')documents=await api('/rest/v1/app_documents?workspace_id=eq.'+wid+'&select=*&order=document_date.desc.nullslast,created_at.desc');if(p==='notifications')notifications=await api('/rest/v1/app_notifications?user_id=eq.'+user.id+'&select=*&order=created_at.desc&limit=30');if(p==='spaces')spaces=await api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc');if(p==='pages')pages=await api('/rest/v1/app_pages?workspace_id=eq.'+wid+'&select=id,space_id,slug,title,summary,visibility,status,owner_id,legacy_path,published_at,created_at,updated_at&order=updated_at.desc');if(p==='groups')groups=await api('/rest/v1/app_groups?workspace_id=eq.'+wid+'&select=*&order=name.asc')}renderAll()}
async function googleCall(action,opts={}){await ensureSession();const url=new URL(GOOGLE_FN);if(action)url.searchParams.set('action',action);if(opts.params)Object.entries(opts.params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const r=await fetch(url,{method:opts.method||'GET',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:opts.body?JSON.stringify(opts.body):null});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Google Calendar 요청 실패');return d}
async function loadGoogleStatus(loadEvents=false){try{const s=await googleCall('status');googleState={...googleState,...s};if(s.connected&&loadEvents)await loadGoogleEvents();renderGoogleControls()}catch(e){googleState.connected=false;renderGoogleControls();console.warn(e)}}
async function loadGoogleEvents(){if(!googleState.connected||!googleState.enabled)return;const min=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1).toISOString(),max=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+2,1).toISOString();const d=await googleCall('events',{params:{timeMin:min,timeMax:max}});googleState.events=d.events||[];renderCalendar()}
function renderGoogleControls(){if(!$('#googleConnectBtn'))return;$('#showGoogleCalendar').checked=!!googleState.connected&&!!googleState.enabled;$('#googleConnectBtn').textContent=googleState.connected?'Google 설정':'Google Calendar 연결';$('#googleAccountLabel').textContent=googleState.connected?(googleState.email||'연결됨'):'';const box=$('#googleCalendarList');if(googleState.connected&&googleState.calendars?.length){box.classList.remove('hidden');box.innerHTML='<b>표시할 Google 캘린더</b>'+googleState.calendars.map(c=>`<label class="toggle-line"><input type="checkbox" data-google-cal="${esc(c.id)}" ${googleState.selected?.includes(c.id)?'checked':''}> ${esc(c.summary)}${c.primary?' (기본)':''}</label>`).join('')+'<button id="saveGooglePrefs" class="mini">선택 저장</button><button id="disconnectGoogle" class="mini">연결 해제</button>';$('#saveGooglePrefs').onclick=saveGooglePrefs;$('#disconnectGoogle').onclick=disconnectGoogle}else box.classList.add('hidden')}
async function connectGoogle(){if(!googleState.connected){const d=await googleCall('start');location.href=d.url}else $('#googleCalendarList').classList.toggle('hidden')}
async function saveGooglePrefs(){const ids=$$('[data-google-cal]:checked').map(x=>x.dataset.googleCal);await googleCall('',{method:'POST',body:{action:'preferences',calendar_ids:ids.length?ids:['primary'],enabled:$('#showGoogleCalendar').checked}});googleState.selected=ids.length?ids:['primary'];googleState.enabled=$('#showGoogleCalendar').checked;await loadGoogleEvents();toast('Google 캘린더 표시 설정을 저장했습니다.')}
async function disconnectGoogle(){await googleCall('',{method:'POST',body:{action:'disconnect'}});googleState={connected:false,enabled:false,selected:[],calendars:[],events:[],email:null};renderCalendar();toast('Google Calendar 연결을 해제했습니다.')}
async function importGoogleEvent(id){const e=googleState.events.find(x=>x.id===id);if(!e)return;await api('/rest/v1/app_events',{method:'POST',body:{workspace_id:workspace.id,title:e.title,description:'Google Calendar에서 가져온 일정',event_type:'other',start_at:new Date(e.start).toISOString(),end_at:e.end?new Date(e.end).toISOString():null,location:e.location||null,created_by:user.id}});await reload(['events']);toast('팀 일정으로 가져왔습니다.')}
function switchView(view){if(window.KPTURouter?.go){window.KPTURouter.go(view,{source:'team'});return}$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view-panel').forEach(v=>v.classList.add('hidden'));$('#'+view+'View')?.classList.remove('hidden');if(view==='calendar'&&googleState.connected)loadGoogleEvents()}
function openEventModal(){['eventTitle','eventLocation','eventDescription','eventStart','eventEnd'].forEach(id=>{if($('#'+id))$('#'+id).value=''});$$('#eventAttendees input').forEach(x=>x.checked=false);$('#eventProject').innerHTML=projectOptions(true);openModal('eventModal')}
function openTaskModal(){['taskTitle','taskDescription','taskDue'].forEach(id=>{if($('#'+id))$('#'+id).value=''});$('#taskAssignee').innerHTML=memberOptions(true);$('#taskProject').innerHTML=projectOptions(true);openModal('taskModal')}
function openDocumentModal(){['docTitle','docCategory','docSource','docDate','docTags','docUrl','docDescription'].forEach(id=>{if($('#'+id))$('#'+id).value=''});$('#docProject').innerHTML=projectOptions(true);openModal('documentModal')}
function openMeetingModal(){['meetingTitle','meetingAt','meetingNotes','meetingDecisions','meetingTaskTitle','meetingTaskDue'].forEach(id=>{if($('#'+id))$('#'+id).value=''});$('#meetingProject').innerHTML=projectOptions(true);$('#meetingTaskAssignee').innerHTML=memberOptions(true);openModal('meetingModal')}
function bind(){
 $$('[data-auth-tab]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.authTab));
 $('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),pw=$('#authPassword').value,name=$('#authDisplayName').value.trim();setStatus($('#authStatus'),'처리 중…');try{if(authMode==='signup'){if(pw!==$('#authPasswordConfirm').value)throw new Error('비밀번호 확인이 일치하지 않습니다.');const active=await signUp(email,pw,name);if(!active){setStatus($('#authStatus'),'계정이 생성되었습니다. 이메일 인증 후 로그인해 주세요.','ok');setAuthMode('signin');return}}else await signIn(email,pw);await loadWorkspaceState()}catch(err){setStatus($('#authStatus'),err.message,'error')}};
 $('#logoutBtn').onclick=logout;
 $('#bootstrapBtn').onclick=async()=>{try{await rpc('app_claim_owner',{p_code:$('#bootstrapCode').value,p_display_name:$('#bootstrapName').value.trim()||null});await loadWorkspaceState()}catch(e){setStatus($('#bootstrapStatus'),e.message,'error')}};
 document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.project){openProject(b.dataset.project);return}if(b.dataset.editPage){openEditor(b.dataset.editPage);return}if(b.dataset.copyPage){copy(new URL('../p/?slug='+encodeURIComponent(b.dataset.copyPage),location.href).href,'페이지 링크를 복사했습니다.');return}if(b.dataset.taskToggle){const t=tasks.find(x=>x.id===b.dataset.taskToggle);if(t){await api('/rest/v1/app_tasks?id=eq.'+t.id,{method:'PATCH',body:{status:t.status==='done'?'todo':'done',completed_at:t.status==='done'?null:new Date().toISOString()}});await reload(['tasks'])}return}if(b.dataset.eventResponse){await api('/rest/v1/app_event_attendees?event_id=eq.'+b.dataset.event+'&user_id=eq.'+user.id,{method:'PATCH',body:{status:b.dataset.eventResponse,responded_at:new Date().toISOString()}});await reload(['attendees']);return}if(b.dataset.readNotif){await api('/rest/v1/app_notifications?id=eq.'+b.dataset.readNotif,{method:'PATCH',body:{read_at:new Date().toISOString()}});await reload(['notifications']);return}if(b.dataset.importGoogle){await importGoogleEvent(b.dataset.importGoogle);return}if(b.dataset.close){closeModal(b.dataset.close);return}});
 if(window.KPTURouter?.on)window.KPTURouter.on('calendar',()=>{if(googleState.connected)loadGoogleEvents()});
 $('#quickTaskBtn').onclick=openTaskModal;$('#newTaskBtn').onclick=openTaskModal;$('#homeAddEvent').onclick=openEventModal;$('#newEventBtn').onclick=openEventModal;$('#newDocumentBtn').onclick=openDocumentModal;$('#newMeetingBtn').onclick=openMeetingModal;$('#newPageBtn').onclick=()=>openEditor();$('#newProjectBtn').onclick=()=>openProjectCreate();$('#newSubprojectBtn').onclick=()=>openProjectCreate(currentProject?.id||null);
 $('#quickInviteBtn').onclick=$('#inviteBtn').onclick=()=>openModal('inviteModal');$('#createInviteBtn').onclick=createInvite;$('#newGroupBtn').onclick=()=>openModal('groupModal');$('#saveGroupBtn').onclick=saveGroup;
 $('#saveEventBtn').onclick=saveEvent;$('#saveTaskBtn').onclick=saveTask;$('#saveDocumentBtn').onclick=saveDocument;$('#saveMeetingBtn').onclick=saveMeeting;$('#saveProjectBtn').onclick=saveProject;$('#savePageBtn').onclick=savePage;$('#secureShareBtn').onclick=createSecureShare;
 $('#addProjectUpdate').onclick=addProjectUpdate;$('#addProjectCheck').onclick=addProjectCheck;$('#addProjectComment').onclick=addProjectComment;
 $('#projectChecks').addEventListener('change',async e=>{const x=e.target.closest('[data-project-check]');if(x){await api('/rest/v1/app_project_checkitems?id=eq.'+x.dataset.projectCheck,{method:'PATCH',body:{checked:x.checked}})}});
 $('#pageSearch').oninput=renderPages;$('#pageFilter').onchange=renderPages;$('#documentSearch').oninput=renderDocuments;$('#documentProject').onchange=renderDocuments;$('#taskScope').onchange=renderTasks;$('#taskStatus').onchange=renderTasks;
 $('#prevMonthBtn').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderCalendar();if(googleState.connected)loadGoogleEvents()};$('#nextMonthBtn').onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderCalendar();if(googleState.connected)loadGoogleEvents()};
 $('#showTeamCalendar').onchange=renderCalendar;$('#showGoogleCalendar').onchange=async()=>{if(!googleState.connected&&$('#showGoogleCalendar').checked){$('#showGoogleCalendar').checked=false;await connectGoogle();return}googleState.enabled=$('#showGoogleCalendar').checked;await googleCall('',{method:'POST',body:{action:'preferences',enabled:googleState.enabled}});if(googleState.enabled)await loadGoogleEvents();else{googleState.events=[];renderCalendar()}};$('#googleConnectBtn').onclick=connectGoogle;
 $('#weeklyCopyBtn').onclick=()=>copy($('#weeklyPreview').textContent,'이번 주 업무 요약을 복사했습니다.');
}
async function init(){enhanceDom();bind();setAuthMode('signin');$('#inviteNotice')?.classList.toggle('hidden',!new URLSearchParams(location.search).get('invite'));session=loadSession();if(!session){showOnly('authView');return}try{await loadWorkspaceState();loadGoogleStatus(false)}catch(e){saveSession(null);showOnly('authView');setStatus($('#authStatus'),'세션을 다시 확인해 주세요. '+e.message,'error')}}
init();