const SB='https://xmlkxfjeagycwttklxjw.supabase.co';
const KEY='sb_publishable_X-0lXJztIQUriUidBZ1PLQ_QemTRSpA';
const SESSION_KEY='kptu_collab_session_v1';
const GOOGLE_FN=SB+'/functions/v1/google-calendar';
const STATUS_LABEL={draft:'초안',review:'검토중',published:'게시',archived:'보관'};
const TASK_LABEL={todo:'할 일',doing:'진행',done:'완료',blocked:'막힘'};
let session=null,user=null,membership=null,workspace=null,authMode='signin';
let members=[],profiles=[],spaces=[],events=[],tasks=[],meetings=[],documents=[];
const teamViewFlights=new Map(),teamViewLoaded=new Set();
let monthCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let googleState={connected:null,enabled:false,selected:[],calendars:[],events:[],email:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
const dateKey=v=>{const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const todayKey=()=>dateKey(new Date());
function setStatus(el,msg,type=''){if(!el)return;el.textContent=msg||'';el.className='status'+(type?' '+type:'');if(type==='error'){el.setAttribute('role','alert');el.removeAttribute('aria-live')}else{el.setAttribute('role','status');el.setAttribute('aria-live','polite')}}
function setBusy(button,busy){if(!button)return;button.disabled=!!busy;if(busy)button.setAttribute('aria-busy','true');else button.removeAttribute('aria-busy')}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2600)}
function saveSession(s){session=s;if(window.KPTURuntime?.session){window.KPTURuntime.session.write(s);return}if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY)}
function loadSession(){if(window.KPTURuntime?.session)return window.KPTURuntime.session.read();try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function refreshSession(){if(window.KPTURuntime?.session){const next=await window.KPTURuntime.session.refresh();session=next||null;return !!next}if(!session?.refresh_token)return false;const r=await fetch(SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){saveSession(null);return false}const d=await r.json();d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d);return true}
async function ensureSession(){if(window.KPTURuntime?.session){const ok=await window.KPTURuntime.session.ensure();session=window.KPTURuntime.session.read();return ok}if(!session)return false;if((session.expires_at||0)<Math.floor(Date.now()/1000)+60)return refreshSession();return true}
async function api(path,{method='GET',body=null,auth=true,prefer=''}={}){if(auth&&!(await ensureSession()))throw new Error('로그인이 필요합니다.');const isForm=typeof FormData!=='undefined'&&body instanceof FormData;const headers={apikey:KEY};if(!isForm)headers['Content-Type']='application/json';headers.Authorization='Bearer '+(auth?session.access_token:KEY);if(prefer)headers.Prefer=prefer;const started=performance.now();let r;
try{
  r=await fetch(SB+path,{method,headers,body:body===null?null:(isForm?body:JSON.stringify(body))});
  window.__KPTU_STARTUP__?.request?.(SB+path,performance.now()-started,r.status);
}catch(e){
  window.__KPTU_STARTUP__?.request?.(SB+path,performance.now()-started,0);
  throw e;
}const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.hint||('요청 실패 '+r.status));return data}
async function rpc(name,payload={}){return api('/rest/v1/rpc/'+name,{method:'POST',body:payload})}
async function getUser(){return api('/auth/v1/user')}
function userFromSession(){
  if(session?.user?.id)return session.user;
  try{
    const token=String(session?.access_token||''),part=token.split('.')[1];
    if(!part)return null;
    const b64=part.replace(/-/g,'+').replace(/_/g,'/');
    const padded=b64+'='.repeat((4-b64.length%4)%4);
    const payload=JSON.parse(decodeURIComponent(atob(padded).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join('')));
    if(!payload?.sub)return null;
    return {id:payload.sub,email:payload.email||'',role:payload.role||'authenticated',aud:payload.aud||'authenticated',app_metadata:payload.app_metadata||{},user_metadata:payload.user_metadata||{}};
  }catch{return null}
}
function profileName(id){const p=profiles.find(x=>x.user_id===id);const m=members.find(x=>x.user_id===id);return p?.display_name||m?.email||id?.slice(0,8)||'미지정'}
function projectName(id){return spaces.find(x=>x.id===id)?.name||''}
function projectOptions(includeBlank=true){return (includeBlank?'<option value="">프로젝트 없음</option>':'')+spaces.filter(x=>x.status!=='archived').map(x=>`<option value="${x.id}">${esc(x.parent_id?'↳ ':'')}${esc(x.name)}</option>`).join('')}
function showOnly(id){document.body.classList.toggle('kptu-workspace-shell',id==='appView');['authView','bootstrapView','appView','bootView'].forEach(x=>{const el=$('#'+x);if(!el)return;const active=x===id;el.classList.toggle('hidden',!active);el.inert=!active;el.setAttribute('aria-hidden',active?'false':'true')})}
function showWorkspaceError(){const view=$('#bootView');if(!view)return;view.querySelector('h2').textContent='업무 공간을 열 수 없습니다.';view.querySelector('p').textContent='연결 상태를 확인한 뒤 다시 시도하거나 로그아웃해 주세요.';$('#bootErrorActions')?.classList.remove('hidden');showOnly('bootView')}
function setAuthMode(mode){authMode=mode;$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===mode));$('#displayNameRow')?.classList.toggle('hidden',mode!=='signup');$('#passwordConfirmRow')?.classList.toggle('hidden',mode!=='signup');if($('#authSubmit'))$('#authSubmit').textContent=mode==='signup'?'계정 만들기':'로그인';if($('#authPassword'))$('#authPassword').autocomplete=mode==='signup'?'new-password':'current-password';setStatus($('#authStatus'),'')}
function enhanceDom(){
  if(!$('#passwordConfirmRow')){const pw=$('#authPassword')?.closest('label');if(pw){const lab=document.createElement('label');lab.id='passwordConfirmRow';lab.className='hidden';lab.innerHTML='비밀번호 확인<input id="authPasswordConfirm" type="password" minlength="8" autocomplete="new-password" required>';pw.after(lab)}}
  const toolbar=$('#calendarView .calendar-toolbar');if(toolbar&&!$('#googleCalendarControls'))toolbar.insertAdjacentHTML('beforebegin',`<details id="googleCalendarPanel" class="calendar-google-panel"><summary><span>Google Calendar</span><span id="googleAccountLabel" class="updated"></span></summary><div id="googleCalendarControls" class="google-bar"><button id="googleConnectBtn" class="secondary" type="button">Google Calendar 연결</button></div><div id="googleCalendarList" class="google-cal-list hidden"></div></details>`);
}
async function signIn(email,password){const r=await fetch(SB+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'로그인에 실패했습니다.');d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d)}
async function signUp(email,password,displayName){const r=await fetch(SB+'/auth/v1/signup',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password,data:{display_name:displayName||''}})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'계정 생성에 실패했습니다.');if(d.access_token){d.expires_at=d.expires_at||Math.floor(Date.now()/1000)+(d.expires_in||3600);saveSession(d);return true}return false}
async function logout(){try{if(session)await api('/auth/v1/logout',{method:'POST'})}catch{}saveSession(null);if(!window.KPTUAuthGate)location.replace('./login/')}
window.KPTUTeamAuth={logout};
function resetPrivateState(){session=null;user=null;membership=null;workspace=null;members=[];profiles=[];spaces=[];events=[];tasks=[];meetings=[];documents=[];googleState={connected:null,enabled:false,selected:[],calendars:[],events:[],email:null};teamViewFlights.clear();teamViewLoaded.clear();window.__KPTU_BOOT_CONTEXT__=null;window.KPTURuntime?.context?.clear?.()}
window.__KPTU_RESET_PRIVATE_STATE__=resetPrivateState;
window.addEventListener('kptu:session-changed',e=>{const next=e.detail?.session?.user?.id||'';if(next&&next===user?.id)return;resetPrivateState();window.KPTUAuthGate?.lock?.()});
async function acceptInviteIfPresent(){const token=new URLSearchParams(location.search).get('invite');if(!token)return;try{await rpc('app_accept_invite',{p_token:token});history.replaceState({},'',location.pathname);toast('초대가 적용되었습니다.')}catch(e){toast('초대 링크: '+e.message)}}
async function loadWorkspaceState(){user=userFromSession()||await getUser();await acceptInviteIfPresent();const prefetched=window.__KPTU_BOOT_MEMBERSHIP_PROMISE__?await window.__KPTU_BOOT_MEMBERSHIP_PROMISE__:null;const ms=prefetched?.ok?prefetched.rows:await api('/rest/v1/app_workspace_members?user_id=eq.'+encodeURIComponent(user.id)+'&select=workspace_id,role,workspace:app_workspaces(id,slug,name)&limit=1');if(!ms?.length){showOnly('bootstrapView');$('#bootstrapName').value=user.user_metadata?.display_name||user.email?.split('@')[0]||'';return}const row=ms[0];membership={workspace_id:row.workspace_id,role:row.role};workspace=Array.isArray(row.workspace)?row.workspace[0]:row.workspace;if(!workspace){const ws=await api('/rest/v1/app_workspaces?id=eq.'+membership.workspace_id+'&select=id,slug,name&limit=1');workspace=ws[0]}if(!workspace)throw new Error('웹2를 확인할 수 없습니다.');window.__KPTU_BOOT_CONTEXT__={user,membership,workspace};window.KPTURuntime?.context?.set?.(window.__KPTU_BOOT_CONTEXT__);window.__KPTU_STARTUP__?.mark('workspaceReady');showOnly('appView');if($('#workspaceName'))$('#workspaceName').textContent='웹2';const admin=['owner','admin'].includes(membership.role);$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!admin));window.__KPTU_START_TEAM_DATA__=()=>window.__KPTU_TEAM_DATA_READY__||(window.__KPTU_TEAM_DATA_READY__=loadAll().then(()=>{renderAll();window.__KPTU_STARTUP__?.mark('teamDataReady');if(new URLSearchParams(location.search).get('google')==='connected'){history.replaceState({},'',location.pathname);return loadGoogleStatus(false)}}))}
async function loadAll(){const wid=workspace.id;[members,profiles,spaces,events,tasks,meetings,documents]=await Promise.all([
 api('/rest/v1/app_workspace_members?workspace_id=eq.'+wid+'&select=workspace_id,user_id,role,created_at'),
 api('/rest/v1/app_profiles?select=user_id,display_name,created_at,updated_at'),
 api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc'),
 api('/rest/v1/app_events?workspace_id=eq.'+wid+'&select=*&order=start_at.asc'),
 api('/rest/v1/app_tasks?workspace_id=eq.'+wid+'&select=*&order=due_at.asc.nullslast,created_at.desc'),
 api('/rest/v1/app_meetings?workspace_id=eq.'+wid+'&select=*&order=meeting_at.desc'),
 api('/rest/v1/app_documents?workspace_id=eq.'+wid+'&select=*&order=document_date.desc.nullslast,created_at.desc')
])}
async function loadForView(view){
 if(!workspace?.id)return false;
 if(teamViewLoaded.has(view))return true;
 if(teamViewFlights.has(view))return teamViewFlights.get(view);
 const wid=workspace.id;
 const flight=(async()=>{
   if(view==='calendar'){
     [spaces,events]=await Promise.all([
       api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc'),
       api('/rest/v1/app_events?workspace_id=eq.'+wid+'&select=*&order=start_at.asc')
     ]);
     fillSelects();renderCalendar();
   }else if(view==='library'){
     spaces=await api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc');
     fillSelects();
   }else if(view==='meetings'){
     [spaces,meetings,documents]=await Promise.all([
       api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc'),
       api('/rest/v1/app_meetings?workspace_id=eq.'+wid+'&select=*&order=meeting_at.desc'),
       api('/rest/v1/app_documents?workspace_id=eq.'+wid+'&select=*&order=document_date.desc.nullslast,created_at.desc')
     ]);
     fillSelects();renderMeetings();
   }
   teamViewLoaded.add(view);
   return true;
 })().finally(()=>teamViewFlights.delete(view));
 teamViewFlights.set(view,flight);
 return flight
}
window.__KPTU_START_TEAM_VIEW__=view=>loadForView(view);
window.KPTUTeamData={
  spaces:()=>spaces,
  events:()=>events,
  meetings:()=>meetings,
  documents:()=>documents
};
window.__KPTU_EVENT_PROJECT_OPTIONS__=()=>projectOptions(true);
function renderAll(){fillSelects();renderHome();renderCalendar();renderDocuments();renderMeetings();renderPages()}
function fillSelects(){const po=projectOptions(true);['eventProject','meetingProject'].forEach(id=>{if($('#'+id))$('#'+id).innerHTML=po})}
function renderHome(){}
function renderWeeklyPreview(){const now=new Date(),start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+7);const es=events.filter(e=>new Date(e.start_at)>=start&&new Date(e.start_at)<end);const ts=tasks.filter(t=>new Date(t.created_at)>=start&&new Date(t.created_at)<end);const lines=['[이번 주 업무]'];if(es.length){lines.push('◦ 일정');es.forEach(e=>lines.push(`- ${new Date(e.start_at).toLocaleDateString('ko-KR')} ${e.title}${e.location?' / '+e.location:''}`))}if(ts.length){lines.push('◦ 업무');ts.forEach(t=>lines.push(`- ${t.title} / ${profileName(t.assignee_id)} / ${TASK_LABEL[t.status]||t.status}`))}$('#weeklyPreview').textContent=lines.join('\n')}
function renderCalendar(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthTitle').textContent=`${y}년 ${m+1}월`;window.KPTUCalendarMonthView?.render?.({year:y,month:m,appEvents:events,googleEvents:googleState.events,googleState});renderGoogleControls();window.KPTUCalendarDayOverflow?.apply?.()}
window.__KPTU_RENDER_CALENDAR__=renderCalendar
function renderDocuments(){if(window.KPTULibrary?.render){window.KPTULibrary.render();return}const q=($('#documentSearch')?.value||'').trim().toLowerCase(),pid=$('#documentProject')?.value||'all';const rows=documents.filter(d=>(pid==='all'||d.project_id===pid)&&(!q||[d.title,d.source,d.category,(d.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));$('#documentList').innerHTML=rows.map(d=>`<article class="item-card"><div><div class="badges"><span class="badge">${esc(d.category)}</span>${d.project_id?`<span class="badge">${esc(projectName(d.project_id))}</span>`:''}</div><h3>${esc(d.title)}</h3><p>${esc(d.source||'출처 미기재')}${d.document_date?' · '+esc(d.document_date):''}</p>${d.description?`<small>${esc(d.description)}</small>`:''}</div>${d.drive_url?`<a class="mini" href="${esc(d.drive_url)}" target="_blank" rel="noopener">열기</a>`:''}</article>`).join('')||'<div class="empty">자료가 없습니다.</div>'}
function meetingName(m){return String(m?.series_name||m?.title||'').trim()}
function renderMeetingTypeOptions(){const select=$('#meetingTypeFilter');if(!select)return;const current=select.value||'all',types=[...new Set(meetings.map(meetingName).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));select.innerHTML='<option value="all">회의명 전체</option>'+types.map(type=>`<option value="${esc(type)}">${esc(type)}</option>`).join('')+'<option value="__none__">회의명 미지정</option>';select.value=[...select.options].some(option=>option.value===current)?current:'all'}
const MEETING_COLORS=['#358bb6','#6b7cd4','#986dd5','#c353cd','#2a9088','#2b9457','#4d922a','#8c8429'];
function meetingColor(name){if(!name)return '';let h=0x811c9dc5;for(let i=0;i<name.length;i++){h^=name.charCodeAt(i);h=Math.imul(h,0x01000193)}return MEETING_COLORS[(h>>>0)%MEETING_COLORS.length]}
function renderMeetings(){const box=$('#meetingList');if(!box)return;renderMeetingTypeOptions();const filter=$('#meetingTypeFilter')?.value||'all';const rows=meetings.filter(m=>filter==='all'||(filter==='__none__'?!meetingName(m):meetingName(m)===filter));box.innerHTML=rows.map(m=>{const related=documents.filter(d=>d.meeting_id===m.id),color=meetingColor(meetingName(m)),name=meetingName(m)||'회의명 미지정',meta=[m.round_no?`${esc(m.round_no)}차`:null,fmt(m.meeting_at),related.length?`자료 ${related.length}개`:null].filter(Boolean).join(' · ');return `<article class="item-card meeting-list-row" data-mrd-meeting="${esc(m.id)}"${color?` style="--meeting-color:${color}"`:''} role="button" tabindex="0"><div class="meeting-list-main"><div class="meeting-list-title"><h3>${esc(name)}</h3></div><p>${esc(meta)}</p></div></article>`}).join('')||'<div class="empty">조건에 맞는 회의 결과가 없습니다.</div>'}
async function downloadMeetingDocument(id){try{const d=await api('/functions/v1/workspace-drive?action=download-token',{method:'POST',body:{document_id:id}});location.href=d.url}catch(e){toast(e.message||'회의자료를 열지 못했습니다.')}}
function renderPages(){window.KPTUWeb1Board?.render?.()}
function openModal(id,{trigger=document.activeElement,initialFocus=null,onRequestClose=null}={}){const m=$('#'+id);if(!m)return;m.classList.remove('hidden');m.setAttribute('aria-hidden','false');window.KPTUA11y?.dialog.activate(m,{trigger,initialFocus,onRequestClose:onRequestClose||(()=>closeModal(id))})}
function closeModal(id,{restoreFocus=true}={}){const m=$('#'+id);if(!m)return;m.classList.add('hidden');m.setAttribute('aria-hidden','true');window.KPTUA11y?.dialog.deactivate(m,{restoreFocus,fallbackFocus:'#appView .view-panel:not(.hidden) h2'})}
function eventCreateTimes(){const allDay=!!$('#eventAllDay')?.checked,startDate=$('#eventStartDate')?.value,endDate=$('#eventEndDate')?.value||startDate;if(!startDate)throw new Error('시작 날짜를 입력해 주세요.');if(!endDate)throw new Error('종료 날짜를 입력해 주세요.');if(allDay){const start=new Date(startDate+'T00:00:00'),end=new Date(endDate+'T00:00:00');end.setDate(end.getDate()+1);if(end<=start)throw new Error('종료 날짜를 확인해 주세요.');return{allDay,start,end}}const startTime=$('#eventStartTime')?.value,endTime=$('#eventEndTime')?.value;if(!startTime||!endTime)throw new Error('시작·종료 시간을 입력해 주세요.');const start=new Date(startDate+'T'+startTime),end=new Date(endDate+'T'+endTime);if(end<=start)throw new Error('종료시간은 시작시간보다 뒤여야 합니다.');return{allDay,start,end}}
async function saveEvent(){const title=$('#eventTitle').value.trim();if(!title)return setStatus($('#eventStatus'),'제목을 입력해 주세요.','error');if($('#eventTarget')?.value==='google')return window.KPTUCalendarPlus?.saveGoogle?.();const button=$('#saveEventBtn');setBusy(button,true);setStatus($('#eventStatus'),'저장 중…');try{const times=eventCreateTimes();const rows=await api('/rest/v1/app_events',{method:'POST',body:{workspace_id:workspace.id,project_id:$('#eventProject')?.value||null,title,description:$('#eventDescription').value.trim()||null,event_type:'other',start_at:times.start.toISOString(),end_at:times.end.toISOString(),location:$('#eventLocation').value.trim()||null,created_by:user.id,calendar_scope:'personal',color_hex:window.KPTUCalendarColors?.value?.($('#eventWeb2Color'))?.hex||'#7656a8'},prefer:'return=representation'});const ev=rows?.[0];if(!ev?.id)throw new Error('저장된 일정 정보를 확인하지 못했습니다.');await window.__KPTU_SYNC_EVENT_ORGS__?.(ev.id);closeModal('eventModal');await reload(['events']);window.dispatchEvent(new CustomEvent('kptu:calendar-changed',{detail:{event_id:ev.id}}));toast('Web2 일정을 등록했습니다.');return ev}catch(e){setStatus($('#eventStatus'),e.message,'error');return null}finally{setBusy(button,false)}}
async function saveDocument(){const title=$('#docTitle').value.trim();if(!title)return setStatus($('#documentStatus'),'자료명을 입력해 주세요.','error');const projectId=$('#docProject').value||null;try{await api('/rest/v1/app_documents',{method:'POST',body:{workspace_id:workspace.id,project_id:projectId,title,category:$('#docCategory').value.trim()||'기타',source:$('#docSource').value.trim()||null,document_date:$('#docDate').value||null,description:$('#docDescription').value.trim()||null,tags:$('#docTags').value.split(',').map(x=>x.trim()).filter(Boolean),drive_url:$('#docUrl').value.trim()||null,visibility:'private',uploaded_by:user.id},prefer:'return=representation'});closeModal('documentModal');await reload(['documents']);window.dispatchEvent(new CustomEvent('kptu:documents-changed',{detail:{project_id:projectId}}));toast('자료를 등록했습니다.')}catch(e){setStatus($('#documentStatus'),e.message,'error')}}
async function saveMeeting(){const title=$('#meetingTitle').value.trim(),meetingAt=$('#meetingAt').value,transcript=$('#meetingTranscript')?.value??'',specialNotes=$('#meetingNotes')?.value??'';if(!title)return setStatus($('#meetingStatus'),'회의명을 입력해 주세요.','error');if(!meetingAt)return setStatus($('#meetingStatus'),'일시를 입력해 주세요.','error');if(!transcript.trim())return setStatus($('#meetingStatus'),'회의 결과 원문을 입력해 주세요.','error');const projectId=$('#meetingProject').value||null,roundRaw=$('#meetingRoundNo')?.value,roundNo=roundRaw?Number(roundRaw):null,files=[...($('#meetingFiles')?.files||[])];if(files.some(file=>file.size>100*1024*1024))return setStatus($('#meetingStatus'),'회의자료는 파일당 100MB까지 첨부할 수 있습니다.','error');try{const actionRows=$$('.meeting-action-row').map(r=>({title:r.querySelector('.meeting-action-title')?.value.trim()||'',due:r.querySelector('.meeting-action-due')?.value||''})).filter(x=>x.title||x.due);if(actionRows.some(x=>!x.title))throw new Error('후속 할 일을 입력해 주세요.');const rows=await api('/rest/v1/app_meetings',{method:'POST',body:{workspace_id:workspace.id,project_id:projectId,title,series_name:title,round_no:Number.isFinite(roundNo)?roundNo:null,meeting_at:new Date(meetingAt).toISOString(),notes:specialNotes.trim()?specialNotes:'',transcript_text:transcript,result_status:'final',finalized_at:new Date().toISOString(),created_by:user.id},prefer:'return=representation'});const meeting=rows?.[0];if(!meeting)throw new Error('저장된 회의 정보를 확인하지 못했습니다.');const assignments=actionRows.map(a=>({...a,assignee_id:user.id}));if(assignments.length)await api('/rest/v1/app_tasks',{method:'POST',body:assignments.map(a=>({workspace_id:workspace.id,project_id:projectId,title:a.title,description:'회의 후속 할 일 · '+title,assignee_id:user.id,status:'todo',priority:'normal',due_at:a.due?new Date(a.due+'T18:00:00+09:00').toISOString():null,source_type:'meeting',source_id:meeting.id,created_by:user.id}))});let uploaded=0,failed=0;for(const file of files){try{const fd=new FormData();fd.append('file',file);fd.append('meeting_id',meeting.id);if(projectId)fd.append('project_id',projectId);await api('/functions/v1/meeting-files',{method:'POST',body:fd});uploaded++}catch(err){failed++;console.warn('meeting material upload failed',file.name,err)}}closeModal('meetingModal');await reload(['meetings','tasks','documents']);window.dispatchEvent(new CustomEvent('kptu:meetings-changed',{detail:{meeting_id:meeting.id}}));if(assignments.length)window.dispatchEvent(new CustomEvent('kptu:tasks-changed'));if(failed)toast(`회의 결과는 저장했습니다. 회의자료 ${uploaded}개 저장 · ${failed}개 실패`);else toast(files.length?`회의 결과와 자료 ${uploaded}개를 저장했습니다.`:'회의 결과를 저장했습니다.')}catch(e){setStatus($('#meetingStatus'),e.message,'error')}}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);toast(msg)}catch{prompt('복사',text)}}
async function reload(parts){const wid=workspace.id;for(const p of parts){if(p==='events')events=await api('/rest/v1/app_events?workspace_id=eq.'+wid+'&select=*&order=start_at.asc');if(p==='tasks')tasks=await api('/rest/v1/app_tasks?workspace_id=eq.'+wid+'&select=*&order=due_at.asc.nullslast,created_at.desc');if(p==='meetings')meetings=await api('/rest/v1/app_meetings?workspace_id=eq.'+wid+'&select=*&order=meeting_at.desc');if(p==='documents')documents=await api('/rest/v1/app_documents?workspace_id=eq.'+wid+'&select=*&order=document_date.desc.nullslast,created_at.desc');if(p==='spaces')spaces=await api('/rest/v1/app_spaces?workspace_id=eq.'+wid+'&select=*&order=sort_order.asc,created_at.asc')}renderAll()}
window.__KPTU_RELOAD_APP_EVENTS__=async()=>{if(!workspace?.id)return[];events=await api('/rest/v1/app_events?workspace_id=eq.'+workspace.id+'&select=*&order=start_at.asc');renderCalendar();renderHome();return events};
window.__KPTU_RELOAD_MEETINGS__=async()=>{if(!workspace?.id)return;[meetings,documents]=await Promise.all([api('/rest/v1/app_meetings?workspace_id=eq.'+workspace.id+'&select=*&order=meeting_at.desc'),api('/rest/v1/app_documents?workspace_id=eq.'+workspace.id+'&select=*&order=document_date.desc.nullslast,created_at.desc')]);renderMeetings()};
async function googleCall(action,opts={}){await ensureSession();const url=new URL(GOOGLE_FN);if(action)url.searchParams.set('action',action);if(opts.params)Object.entries(opts.params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const r=await fetch(url,{method:opts.method||'GET',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:opts.body?JSON.stringify(opts.body):null});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Google Calendar 요청 실패');return d}
async function loadGoogleStatus(loadEvents=false){try{const s=await googleCall('status');googleState={...googleState,...s};if(s.connected&&loadEvents)await loadGoogleEvents();renderGoogleControls()}catch(e){googleState.connected=false;renderGoogleControls();console.warn(e)}}
async function loadGoogleEvents(){return window.KPTUCalendarPersistence?.refresh?.()}
function renderGoogleControls(){if(!$('#googleConnectBtn'))return;const panel=$('#googleCalendarPanel'),connect=$('#googleConnectBtn'),box=$('#googleCalendarList');$('#googleAccountLabel').textContent=googleState.connected?(googleState.email||'연결됨'):'연결 안 됨';connect.classList.toggle('hidden',!!googleState.connected);if(panel&&!panel.dataset.initialized&&typeof googleState.connected==='boolean'){panel.open=!googleState.connected;panel.dataset.initialized='1'}if(googleState.connected&&googleState.calendars?.length){box.classList.remove('hidden');box.innerHTML='<b>표시할 Google 캘린더</b>'+googleState.calendars.map(c=>`<label class="toggle-line"><input type="checkbox" data-google-cal="${esc(c.id)}" ${googleState.selected?.includes(c.id)?'checked':''}> <span>${esc(c.summary)}${c.primary?' (기본)':''}</span></label>`).join('')+'<button id="saveGooglePrefs" class="mini" type="button">자동 저장</button><button id="disconnectGoogle" class="mini" type="button">연결 해제</button>';$('#saveGooglePrefs').onclick=saveGooglePrefs;$('#disconnectGoogle').onclick=disconnectGoogle}else box.classList.add('hidden');window.KPTUCalendarPersistence?.decorate?.()}
window.__KPTU_SYNC_GOOGLE_STATE__=next=>{googleState={...googleState,...(next||{})}};
window.__KPTU_SYNC_GOOGLE_EVENTS__=next=>{googleState.events=Array.isArray(next)?next:[];renderCalendar()};
window.__KPTU_RENDER_GOOGLE_CONTROLS__=renderGoogleControls;
async function connectGoogle(){if(googleState.connected){const panel=$('#googleCalendarPanel');if(panel)panel.open=true;return}const d=await googleCall('start');location.href=d.url}
async function saveGooglePrefs(){const ids=$('[data-google-cal]:checked').map(x=>x.dataset.googleCal);await googleCall('',{method:'POST',body:{action:'preferences',calendar_ids:ids,enabled:true}});googleState.selected=ids;googleState.enabled=true;await loadGoogleEvents();toast('Google 캘린더 표시 설정을 저장했습니다.')}
async function disconnectGoogle(){await googleCall('',{method:'POST',body:{action:'disconnect'}});window.KPTUCalendarPersistence?.disconnected?.();googleState={connected:false,enabled:false,selected:[],calendars:[],events:[],email:null};renderCalendar();toast('Google Calendar 연결을 해제했습니다.')}
async function importGoogleEvent(id){const e=googleState.events.find(x=>x.id===id);if(!e)return;await api('/rest/v1/app_events',{method:'POST',body:{workspace_id:workspace.id,title:e.title,description:'Google Calendar에서 가져온 일정',event_type:'other',start_at:new Date(e.start).toISOString(),end_at:e.end?new Date(e.end).toISOString():null,location:e.location||null,created_by:user.id,calendar_scope:'personal'}});await reload(['events']);toast('Web2 일정으로 가져왔습니다.')}
function switchView(view){if(window.KPTURouter?.go){window.KPTURouter.go(view,{source:'team'});return}$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('.view-panel').forEach(v=>v.classList.add('hidden'));$('#'+view+'View')?.classList.remove('hidden')}
function openEventModal(){['eventTitle','eventLocation','eventDescription'].forEach(id=>{if($('#'+id))$('#'+id).value=''});const now=new Date(),finish=new Date(now.getTime()+3600000),date=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,time=d=>`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;if($('#eventProject')){$('#eventProject').innerHTML=projectOptions(true);$('#eventProject').value=''}if($('#eventTarget'))$('#eventTarget').value='web2';if($('#eventAllDay'))$('#eventAllDay').checked=false;if($('#eventStartDate'))$('#eventStartDate').value=date(now);if($('#eventEndDate'))$('#eventEndDate').value=date(finish);if($('#eventStartTime'))$('#eventStartTime').value=time(now);if($('#eventEndTime'))$('#eventEndTime').value=time(finish);document.querySelectorAll('.event-time-row').forEach(x=>x.classList.remove('hidden'));$('#eventGoogleOptions')?.classList.add('hidden');$('#eventProjectRow')?.classList.remove('hidden');setStatus($('#eventStatus'),'');openModal('eventModal',{initialFocus:'#eventTitle'});window.KPTUCalendarPlus?.prepareNewEvent?.()}
function openDocumentModal(){['docTitle','docCategory','docSource','docDate','docTags','docUrl','docDescription'].forEach(id=>{if($('#'+id))$('#'+id).value=''});openModal('documentModal',{initialFocus:'#docTitle'})}
function openMeetingModal(){['meetingTitle','meetingAt','meetingNotes','meetingRoundNo','meetingTranscript'].forEach(id=>{if($('#'+id))$('#'+id).value=''});if($('#meetingFiles'))$('#meetingFiles').value='';$('#meetingProject').innerHTML=projectOptions(true);openModal('meetingModal',{initialFocus:'#meetingTitle'})}
function bind(){
 $('#bootRetryBtn').onclick=()=>location.reload();$('#bootLogoutBtn').onclick=logout;
 $$('[data-auth-tab]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.authTab));
 $('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),pw=$('#authPassword').value,name=$('#authDisplayName').value.trim();setStatus($('#authStatus'),'처리 중…');try{if(authMode==='signup'){if(pw!==$('#authPasswordConfirm').value)throw new Error('비밀번호 확인이 일치하지 않습니다.');const active=await signUp(email,pw,name);if(!active){setStatus($('#authStatus'),'계정이 생성되었습니다. 이메일 인증 후 로그인해 주세요.','ok');setAuthMode('signin');return}}else await signIn(email,pw);await loadWorkspaceState()}catch(err){setStatus($('#authStatus'),err.message,'error')}};
 $('#bootstrapBtn').onclick=async()=>{try{await rpc('app_claim_owner',{p_code:$('#bootstrapCode').value,p_display_name:$('#bootstrapName').value.trim()||null});await loadWorkspaceState()}catch(e){setStatus($('#bootstrapStatus'),e.message,'error')}};
 document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.meetingDoc){e.preventDefault();e.stopPropagation();await downloadMeetingDocument(b.dataset.meetingDoc);return}if(b.dataset.close){closeModal(b.dataset.close);return}});
 if(window.KPTURouter?.on)window.KPTURouter.on('calendar',()=>{renderCalendar();if(googleState.connected)window.KPTUCalendarPersistence?.refresh?.()});
 if($('#homeAddEvent'))$('#homeAddEvent').onclick=openEventModal;$('#newEventBtn').onclick=openEventModal;$('#newDocumentBtn').onclick=openDocumentModal;$('#newMeetingBtn').onclick=openMeetingModal;
 $('#saveEventBtn').onclick=saveEvent;$('#saveDocumentBtn').onclick=saveDocument;$('#saveMeetingBtn').onclick=saveMeeting;
 if($('#pageSearch'))$('#pageSearch').oninput=renderPages;if($('#pageFilter'))$('#pageFilter').onchange=renderPages;$('#documentSearch').oninput=renderDocuments;$('#documentProject').onchange=renderDocuments;if($('#meetingTypeFilter'))$('#meetingTypeFilter').onchange=renderMeetings;
 window.addEventListener('kptu:project-spaces-updated',e=>{const d=e.detail;if(!workspace||!user||d?.workspaceId!==workspace.id||d.userId!==user.id||!Array.isArray(d.spaces))return;spaces=d.spaces;renderAll()});
 const moveMonth=delta=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+delta,1);renderCalendar();window.KPTUCalendarPersistence?.refresh?.()};window.__KPTU_CALENDAR_MOVE_MONTH__=moveMonth;$('#prevMonthBtn').onclick=()=>moveMonth(-1);$('#nextMonthBtn').onclick=()=>moveMonth(1);window.KPTUCalendarMonthView?.setNavigate?.(moveMonth);
 $('#googleConnectBtn').onclick=connectGoogle;
 if($('#weeklyCopyBtn'))$('#weeklyCopyBtn').onclick=()=>copy($('#weeklyPreview')?.textContent||'','이번 주 업무 요약을 복사했습니다.');
}
async function init(){enhanceDom();bind();setAuthMode('signin');$('#inviteNotice')?.classList.toggle('hidden',!new URLSearchParams(location.search).get('invite'));session=window.__KPTU_AUTHENTICATED_BOOT_SESSION__||loadSession();if(!session){window.KPTUAuthGate?.redirect?.();return}try{await loadWorkspaceState()}catch(e){console.error('workspace init failed',e);if(await ensureSession()){showWorkspaceError();return 'error'}saveSession(null);window.KPTUAuthGate?.redirect?.();return 'error'}}
window.__KPTU_TEAM_READY__=init().then(result=>{const state=result==='error'?'error':!session?'auth':membership?'workspace':'bootstrap';window.__KPTU_TEAM_READY_STATE__=state;window.dispatchEvent(new CustomEvent('kptu:team-ready',{detail:{state}}));return state});
