(()=>{'use strict';if(window.KPTUWeb1Toolbar)return;
const CSS='.web1-toolbar{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin:0 0 10px}.web1-tool{appearance:none;border:1px solid #cbd5df;background:#fff;color:#344054;border-radius:9px;padding:7px 10px;font:inherit;font-size:12px;font-weight:800;line-height:1.2;text-decoration:none;cursor:pointer}.web1-tool:hover{background:#f8fafc}.web1-tool[hidden]{display:none!important}@media(max-width:650px){.web1-toolbar{gap:5px}.web1-tool{padding:7px 8px;font-size:11px}}@media print{.web1-toolbar{display:none!important}}';
function addCss(){if(document.getElementById('web1ToolbarStyle'))return;const s=document.createElement('style');s.id='web1ToolbarStyle';s.textContent=CSS;document.head.appendChild(s)}
function titleAnchor(){return document.querySelector('.hero')||document.querySelector('main h1')||document.querySelector('.wrap h1')||document.querySelector('h1')}
async function edit(cap){const existing=document.querySelector('#editPageBtn:not(#web1Edit),#areaEditAllBtn,[data-web1-edit-target]');if(cap.publicEdit){if(existing){existing.click();return}document.dispatchEvent(new CustomEvent('kptu:web1-edit',{detail:{publicEdit:true}}));return}
const auth=window.KPTUWeb1AdminAuth;if(!auth)return;if(!await auth.isAdmin()){auth.signInWithGoogle();return}if(existing){existing.click();return}document.dispatchEvent(new CustomEvent('kptu:web1-edit',{detail:{publicEdit:false,admin:true}}))}
async function mount(){if(document.getElementById('web1Toolbar'))return;addCss();const cap=window.KPTUWeb1Capabilities?.resolve(location.pathname)||{backHref:'/work/',publicEdit:false};const anchor=titleAnchor();if(!anchor)return;
const bar=document.createElement('nav');bar.id='web1Toolbar';bar.className='web1-toolbar';bar.setAttribute('aria-label','페이지 도구');
bar.innerHTML='<a id="web1Back" class="web1-tool">← 돌아가기</a><button id="web1Edit" class="web1-tool" type="button">수정</button><button id="web1Print" class="web1-tool" type="button">인쇄</button><button id="web1Logout" class="web1-tool" type="button" hidden>로그아웃</button>';
bar.querySelector('#web1Back').href=cap.backHref;if(cap.archiveReadOnly){bar.querySelector('#web1Back').textContent='← 성명·보도자료';bar.querySelector('#web1Edit').hidden=true}else{bar.querySelector('#web1Edit').onclick=()=>edit(cap)}bar.querySelector('#web1Print').onclick=()=>window.print();const logout=bar.querySelector('#web1Logout');if(await window.KPTUWeb1AdminAuth?.isAdmin()){logout.hidden=false;logout.onclick=()=>window.KPTUWeb1AdminAuth.signOut()}
anchor.parentNode.insertBefore(bar,anchor)}
window.KPTUWeb1Toolbar={mount};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();})();