import { createClient } from 'npm:@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const CALLBACK=`${SUPABASE_URL}/functions/v1/public-policy-drive/callback`;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'Content-Type':'application/json'}});
async function sha256(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function getConfig(){const {data,error}=await admin.from('public_policy_drive_config').select('google_client_id,google_client_secret').eq('id',1).single();if(error||!data?.google_client_id||!data?.google_client_secret)throw new Error('Google OAuth 설정이 없습니다.');return data}
async function getUser(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('로그인이 필요합니다.');const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw new Error('로그인 세션을 확인할 수 없습니다.');return data.user}
async function ensureAccess(userId:string){let {data:conn,error}=await admin.from('app_google_calendar_connections').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;if(!conn)throw new Error('Google Calendar가 연결되지 않았습니다.');const exp=conn.token_expires_at?new Date(conn.token_expires_at).getTime():0;if(conn.access_token&&exp>Date.now()+60000)return conn;if(!conn.refresh_token)throw new Error('Google 재인증이 필요합니다.');const cfg=await getConfig();const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:cfg.google_client_id,client_secret:cfg.google_client_secret,refresh_token:conn.refresh_token,grant_type:'refresh_token'})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.error||'Google 토큰 갱신 실패');const expires=new Date(Date.now()+(d.expires_in||3600)*1000).toISOString();const {data:updated,error:uerr}=await admin.from('app_google_calendar_connections').update({access_token:d.access_token,token_expires_at:expires,updated_at:new Date().toISOString()}).eq('user_id',userId).select('*').single();if(uerr)throw uerr;return updated}
async function googleReq(url:string,token:string,method='GET',body?:unknown){const r=await fetch(url,{method,headers:{Authorization:`Bearer ${token}`,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const msg=d.error?.message||d.error_description||'Google Calendar 요청 실패';if(r.status===403&&/insufficient|permission|scope/i.test(msg))throw new Error('Google Calendar 편집 권한이 필요합니다. Google 계정을 다시 연결해 주세요.');throw new Error(msg)}return d}
function colorMap(raw:any){const out:any={};for(const [id,v] of Object.entries(raw?.event||{}))out[id]={background:(v as any).background||'#4285f4',foreground:(v as any).foreground||'#ffffff'};return out}
function normEvent(e:any,calendarId:string,colors:any){let organizationIds:string[]=[];try{organizationIds=JSON.parse(e.extendedProperties?.private?.kptu_suborg_ids||'[]')}catch{}return {id:e.id,title:e.summary||'(제목 없음)',start:e.start?.dateTime||e.start?.date,end:e.end?.dateTime||e.end?.date,allDay:!!e.start?.date,location:e.location||'',description:e.description||'',calendarId,colorId:e.colorId||null,color:e.colorId&&colors?.[e.colorId]?.background?colors[e.colorId].background:null,htmlLink:e.htmlLink||'',organizationIds:Array.isArray(organizationIds)?organizationIds:[],source:'google'}}
function hexRgb(hex:string){const h=String(hex||'').replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(h))return null;return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}
function nearestColorId(hex:string,colors:any){const rgb=hexRgb(hex);if(!rgb)return null;let best:any=null,score=Infinity;for(const [id,v] of Object.entries(colors||{})){const c=hexRgb((v as any).background);if(!c)continue;const s=(rgb[0]-c[0])**2+(rgb[1]-c[1])**2+(rgb[2]-c[2])**2;if(s<score){score=s;best=id}}return best}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const url=new URL(req.url);try{const user=await getUser(req);const action=url.searchParams.get('action')||(req.method==='POST'?'post':'status');
if(req.method==='GET'&&action==='start'){const cfg=await getConfig();const platform=url.searchParams.get('platform')==='android'?'android':'web';const raw='calendar.'+platform+'.'+crypto.randomUUID()+crypto.randomUUID(),hash=await sha256(raw);await admin.from('app_google_oauth_states').insert({state_hash:hash,user_id:user.id,expires_at:new Date(Date.now()+10*60*1000).toISOString()});const params=new URLSearchParams({client_id:cfg.google_client_id,redirect_uri:CALLBACK,response_type:'code',scope:'openid email https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.calendarlist.readonly',access_type:'offline',prompt:'consent',state:raw,include_granted_scopes:'true'});return json({url:'https://accounts.google.com/o/oauth2/v2/auth?'+params.toString(),callback:CALLBACK})}
if(req.method==='GET'&&action==='status'){const {data:conn}=await admin.from('app_google_calendar_connections').select('user_id,enabled,calendar_ids,calendar_colors,google_email').eq('user_id',user.id).maybeSingle();if(!conn)return json({connected:false,callback:CALLBACK});const c=await ensureAccess(user.id);try{const [list,colorsRaw]=await Promise.all([googleReq('https://www.googleapis.com/calendar/v3/users/me/calendarList?minAccessRole=reader',c.access_token),googleReq('https://www.googleapis.com/calendar/v3/colors',c.access_token)]);return json({connected:true,enabled:conn.enabled,email:conn.google_email,selected:conn.calendar_ids||['primary'],colors:conn.calendar_colors||{},eventColors:colorMap(colorsRaw),calendars:(list.items||[]).map((x:any)=>({id:x.id,summary:x.summary,primary:!!x.primary,backgroundColor:x.backgroundColor||'#4285f4',accessRole:x.accessRole||'reader'}))})}catch(e){return json({connected:true,enabled:conn.enabled,email:conn.google_email,selected:conn.calendar_ids||['primary'],colors:conn.calendar_colors||{},eventColors:{},calendars:[],warning:e instanceof Error?e.message:String(e)})}}
if(req.method==='GET'&&action==='events'){const c=await ensureAccess(user.id);try{const timeMin=url.searchParams.get('timeMin')||new Date().toISOString(),timeMax=url.searchParams.get('timeMax')||new Date(Date.now()+31*86400000).toISOString(),ids=Array.isArray(c.calendar_ids)?c.calendar_ids:['primary'],out:any[]=[];const colorsRaw=await googleReq('https://www.googleapis.com/calendar/v3/colors',c.access_token);const colors=colorMap(colorsRaw);for(const id of ids){const q=new URLSearchParams({timeMin,timeMax,singleEvents:'true',orderBy:'startTime',maxResults:'250'}),d=await googleReq(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(id)}/events?${q}`,c.access_token);for(const e of d.items||[])out.push(normEvent(e,id,colors))}return json({events:out,colors:c.calendar_colors||{},eventColors:colors})}catch(e){return json({events:[],warning:e instanceof Error?e.message:String(e)})}}
if(req.method==='GET'&&action==='event'){const c=await ensureAccess(user.id);const calendarId=url.searchParams.get('calendarId')||'primary',eventId=url.searchParams.get('eventId');if(!eventId)throw new Error('일정 ID가 없습니다.');const [e,colorsRaw]=await Promise.all([googleReq(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`,c.access_token),googleReq('https://www.googleapis.com/calendar/v3/colors',c.access_token)]);const colors=colorMap(colorsRaw);return json({event:normEvent(e,calendarId,colors),eventColors:colors})}
if(req.method==='POST'){const body=await req.json().catch(()=>({}));
if(body.action==='preferences'){const patch:any={updated_at:new Date().toISOString()};if(Array.isArray(body.calendar_ids))patch.calendar_ids=body.calendar_ids;if(typeof body.enabled==='boolean')patch.enabled=body.enabled;if(body.calendar_colors&&typeof body.calendar_colors==='object')patch.calendar_colors=body.calendar_colors;const {error}=await admin.from('app_google_calendar_connections').update(patch).eq('user_id',user.id);if(error)throw error;return json({ok:true})}
if(body.action==='disconnect'){await admin.from('app_google_calendar_connections').delete().eq('user_id',user.id);return json({ok:true})}
if(body.action==='create-event'){const c=await ensureAccess(user.id);const calendarId=String(body.calendar_id||'primary');const payload:any={summary:String(body.title||'').trim()||'(제목 없음)',description:String(body.memo||''),location:String(body.location||'')};if(Array.isArray(body.organization_ids))payload.extendedProperties={private:{kptu_suborg_ids:JSON.stringify(body.organization_ids.map(String))}};if(body.all_day){if(!body.start_date||!body.end_date)throw new Error('시작일과 종료일을 입력해 주세요.');const end=new Date(String(body.end_date)+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);payload.start={date:String(body.start_date)};payload.end={date:end.toISOString().slice(0,10)}}else{if(!body.start_iso||!body.end_iso)throw new Error('시작·종료 시간을 입력해 주세요.');payload.start={dateTime:String(body.start_iso)};payload.end={dateTime:String(body.end_iso)}}if(body.color_hex){const colorsRaw=await googleReq('https://www.googleapis.com/calendar/v3/colors',c.access_token),colors=colorMap(colorsRaw),id=nearestColorId(String(body.color_hex),colors);if(id)payload.colorId=id}const created=await googleReq(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`,c.access_token,'POST',payload);return json({ok:true,event:normEvent(created,calendarId,{})})}
if(body.action==='update-event'){const c=await ensureAccess(user.id);const calendarId=String(body.calendar_id||'primary'),eventId=String(body.event_id||'');if(!eventId)throw new Error('일정 ID가 없습니다.');const patch:any={summary:String(body.title||'').trim()||'(제목 없음)',description:String(body.memo||'')};if(Array.isArray(body.organization_ids))patch.extendedProperties={private:{kptu_suborg_ids:JSON.stringify(body.organization_ids.map(String))}};if(body.all_day){if(!body.start_date||!body.end_date)throw new Error('시작일과 종료일을 입력해 주세요.');const end=new Date(String(body.end_date)+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);patch.start={date:String(body.start_date)};patch.end={date:end.toISOString().slice(0,10)}}else{if(!body.start_iso||!body.end_iso)throw new Error('시작·종료 시간을 입력해 주세요.');patch.start={dateTime:String(body.start_iso)};patch.end={dateTime:String(body.end_iso)}}if(body.color_hex){const colorsRaw=await googleReq('https://www.googleapis.com/calendar/v3/colors',c.access_token),colors=colorMap(colorsRaw),id=nearestColorId(String(body.color_hex),colors);if(id)patch.colorId=id}const updated=await googleReq(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`,c.access_token,'PATCH',patch);return json({ok:true,event:normEvent(updated,calendarId,{})})}
if(body.action==='delete-event'){const c=await ensureAccess(user.id);const calendarId=String(body.calendar_id||'primary'),eventId=String(body.event_id||'');if(!eventId)throw new Error('일정 ID가 없습니다.');await googleReq(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(eventId)}`,c.access_token,'DELETE');return json({ok:true})}}
return json({error:'Unknown action'},400)}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}});
