name = "bokdoong-router"
main = "bokdoong-router.mjs"
compatibility_date = "2026-09-20"
workers_dev = false

[[routes]]
pattern = "bokdoong.com"
custom_domain = true

[[routes]]
pattern = "work.bokdoong.com"
custom_domain = true

[[routes]]
pattern = "desk.bokdoong.com"
custom_domain = true

[[routes]]
pattern = "read.bokdoong.com"
custom_domain = true

[[routes]]
pattern = "arsenal.bokdoong.com"
custom_domain = true
