import { createClient } from 'npm:@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const CALLBACK=`${SUPABASE_URL}/functions/v1/public-policy-drive/callback`;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, PATCH, DELETE, OPTIONS'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const RECENT_COMPLETED_MS=3*24*60*60*1000;
const TASKS_CONCURRENCY=4,KST_MS=9*60*60*1000,DAY_MS=24*60*60*1000;
async function sha256(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function getConfig(){const {data,error}=await admin.from('public_policy_drive_config').select('google_client_id,google_client_secret').eq('id',1).single();if(error||!data?.google_client_id||!data?.google_client_secret)throw new Error('Google OAuth 설정이 없습니다.');return data}
async function getUser(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('로그인이 필요합니다.');const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw new Error('로그인 세션을 확인할 수 없습니다.');return data.user}
async function ensureAccess(userId:string){let {data:conn,error}=await admin.from('app_google_calendar_connections').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;if(!conn)throw new Error('Google 계정이 연결되지 않았습니다.');const exp=conn.token_expires_at?new Date(conn.token_expires_at).getTime():0;if(conn.access_token&&exp>Date.now()+60000)return conn;if(!conn.refresh_token)throw new Error('Google 재인증이 필요합니다.');const cfg=await getConfig();const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:cfg.google_client_id,client_secret:cfg.google_client_secret,refresh_token:conn.refresh_token,grant_type:'refresh_token'})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.error||'Google 토큰 갱신 실패');const expires=new Date(Date.now()+(d.expires_in||3600)*1000).toISOString();const {data:updated,error:uerr}=await admin.from('app_google_calendar_connections').update({access_token:d.access_token,token_expires_at:expires,updated_at:new Date().toISOString()}).eq('user_id',userId).select('*').single();if(uerr)throw uerr;return updated}
async function googleReq(url:string,token:string,method='GET',body?:unknown){const r=await fetch(url,{method,headers:{Authorization:`Bearer ${token}`,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const msg=d.error?.message||d.error_description||'Google Tasks 요청 실패',detail=JSON.stringify(d.error||{});if(r.status===403&&(/insufficient|permission|scope/i.test(msg)||/ACCESS_TOKEN_SCOPE_INSUFFICIENT/i.test(detail)))throw new Error('TASKS_SCOPE_REQUIRED');if(r.status===403&&(/SERVICE_DISABLED|has not been used|API.*disabled/i.test(detail+' '+msg)))throw new Error('Google Tasks API가 Google Cloud 프로젝트에서 활성화되어 있지 않습니다.');throw new Error(msg)}return d}
function normTask(t:any,list:any){return {id:t.id,title:t.title||'(제목 없음)',notes:t.notes||'',due:t.due||null,status:t.status||'needsAction',completed:t.completed||null,updated:t.updated||null,taskListId:list.id,taskListTitle:list.title||'Google Tasks',position:t.position||null,webViewLink:t.webViewLink||null,source:'google-task'}}
function dueValue(v:any){if(!v)return undefined;const raw=String(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(raw)?raw+'T00:00:00.000Z':undefined}
async function listsFor(token:string,stats?:{google:number}){if(stats)stats.google++;const d=await googleReq('https://tasks.googleapis.com/tasks/v1/users/@me/lists?maxResults=100',token);return d.items||[]}
// completedMin filters on the completion date, which pending tasks do not have, so pending and recently completed tasks are read separately.
async function tasksFor(listId:string,params:Record<string,string>,token:string,stats?:{google:number}){const items:any[]=[];let pageToken='';do{const q=new URLSearchParams({maxResults:'100',...params});if(pageToken)q.set('pageToken',pageToken);if(stats)stats.google++;const d=await googleReq(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(listId)}/tasks?${q}`,token);items.push(...(d.items||[]));pageToken=d.nextPageToken||''}while(pageToken);return items}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out:R[]=new Array(items.length);let next=0;const worker=async()=>{while(next<items.length){const i=next++;out[i]=await fn(items[i])}};await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
// Google stores a due date as midnight UTC of that date. Bounds sit between midnights, so inclusive or exclusive comparison both give today..+6 days in Korean time (the screen's 7-day window).
function kstDateKey(offset:number){return new Date(Date.now()+KST_MS+offset*DAY_MS).toISOString().slice(0,10)}
function pendingDueWindow(){return {dueMin:kstDateKey(-1)+'T23:59:59.000Z',dueMax:kstDateKey(6)+'T23:59:59.000Z'}}
async function readTasks(token:string,stats:{google:number}){const lists=await listsFor(token,stats),due=pendingDueWindow(),completedMin=new Date(Date.now()-RECENT_COMPLETED_MS).toISOString();const jobs=lists.flatMap((list:any)=>[{list,pending:true,params:{showCompleted:'false',...due}},{list,pending:false,params:{showCompleted:'true',showHidden:'true',completedMin}}]);const results=await mapLimit(jobs,TASKS_CONCURRENCY,(j:any)=>tasksFor(j.list.id,j.params,token,stats));const out:any[]=[],seen=new Set<string>();jobs.forEach((j:any,i:number)=>{for(const t of results[i]){if((t.status==='completed')===j.pending||seen.has(t.id))continue;seen.add(t.id);out.push(normTask(t,j.list))}});out.sort((a,b)=>{const ac=a.status==='completed',bc=b.status==='completed';if(ac!==bc)return ac?1:-1;const ad=a.due?new Date(a.due).getTime():Number.MAX_SAFE_INTEGER,bd=b.due?new Date(b.due).getTime():Number.MAX_SAFE_INTEGER;return ad-bd||String(a.title).localeCompare(String(b.title),'ko')});return {tasks:out,lists:lists.length}}
// Timing log: counts only, never task content or tokens.
function logLoad(action:string,started:number,stats:{google:number},lists:number){console.log(JSON.stringify({fn:'google-tasks',action,ms:Date.now()-started,lists,google_requests:stats.google}))}
async function hasWriteScope(token:string){const r=await fetch('https://oauth2.googleapis.com/tokeninfo?access_token='+encodeURIComponent(token));const d=await r.json().catch(()=>({}));return r.ok&&String(d.scope||'').split(/\s+/).includes('https://www.googleapis.com/auth/tasks')}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const url=new URL(req.url);try{const user=await getUser(req);const body=req.method==='GET'?{}:await req.json().catch(()=>({}));const action=url.searchParams.get('action')||String((body as any).action||'tasks');
if(action==='start'){const cfg=await getConfig();const platform=url.searchParams.get('platform')==='android'?'android':'web';const raw='tasks.'+platform+'.'+crypto.randomUUID()+crypto.randomUUID(),hash=await sha256(raw);await admin.from('app_google_oauth_states').insert({state_hash:hash,user_id:user.id,expires_at:new Date(Date.now()+10*60*1000).toISOString()});const params=new URLSearchParams({client_id:cfg.google_client_id,redirect_uri:CALLBACK,response_type:'code',scope:'openid email https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.calendarlist.readonly https://www.googleapis.com/auth/tasks',access_type:'offline',prompt:'consent',state:raw,include_granted_scopes:'true'});return json({url:'https://accounts.google.com/o/oauth2/v2/auth?'+params.toString(),callback:CALLBACK})}
if(action==='status'){try{const c=await ensureAccess(user.id);await googleReq('https://tasks.googleapis.com/tasks/v1/users/@me/lists?maxResults=1',c.access_token);if(!(await hasWriteScope(c.access_token)))return json({connected:true,authorized:false,needs_reconnect:true,email:c.google_email||null});return json({connected:true,authorized:true,email:c.google_email||null})}catch(e){const m=e instanceof Error?e.message:String(e);if(m==='TASKS_SCOPE_REQUIRED')return json({connected:true,authorized:false,needs_reconnect:true});if(/연결되지/.test(m))return json({connected:false,authorized:false});throw e}}
// status + tasks in one request. action=status and action=tasks stay for older app versions and rollback.
if(action==='overview'){const started=Date.now(),stats={google:0};let c:any;try{c=await ensureAccess(user.id)}catch(e){const m=e instanceof Error?e.message:String(e);if(/연결되지/.test(m))return json({connected:false,authorized:false,needs_reconnect:false,tasks:[]});throw e}const reconnect={connected:true,authorized:false,needs_reconnect:true,email:c.google_email||null,tasks:[]};try{const [scopeOk,r]=await Promise.all([hasWriteScope(c.access_token).finally(()=>{stats.google++}),readTasks(c.access_token,stats)]);logLoad('overview',started,stats,r.lists);if(!scopeOk)return json(reconnect);return json({connected:true,authorized:true,needs_reconnect:false,email:c.google_email||null,tasks:r.tasks})}catch(e){if(e instanceof Error&&e.message==='TASKS_SCOPE_REQUIRED')return json(reconnect);throw e}}
const c=await ensureAccess(user.id);
if(action==='lists'){const lists=await listsFor(c.access_token);return json({lists:lists.map((x:any)=>({id:x.id,title:x.title||'Google Tasks'}))})}
if(action==='tasks'){const started=Date.now(),stats={google:0};let r:{tasks:any[],lists:number};try{r=await readTasks(c.access_token,stats)}catch(e){if(e instanceof Error&&e.message==='TASKS_SCOPE_REQUIRED')return json({tasks:[],needs_reconnect:true,warning:'Google 할 일을 수정하려면 Google 계정을 한 번 다시 연결해 주세요.'});throw e}logLoad('tasks',started,stats,r.lists);return json({tasks:r.tasks,needs_reconnect:false})}
const listId=String((body as any).task_list_id||'');const taskId=String((body as any).task_id||'');if(!listId)throw new Error('Google Tasks 목록을 선택해 주세요.');
if(action==='create'){const payload:any={title:String((body as any).title||'').trim()||'(제목 없음)',notes:String((body as any).notes||'')};const due=dueValue((body as any).due);if(due)payload.due=due;const d=await googleReq(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(listId)}/tasks`,c.access_token,'POST',payload);return json({ok:true,task:normTask(d,{id:listId,title:String((body as any).task_list_title||'Google Tasks')})})}
if(!taskId)throw new Error('Google 할 일 ID가 없습니다.');
if(action==='update'){const patch:any={title:String((body as any).title||'').trim()||'(제목 없음)',notes:String((body as any).notes||'')};const due=dueValue((body as any).due);patch.due=due||null;const d=await googleReq(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(taskId)}`,c.access_token,'PATCH',patch);return json({ok:true,task:normTask(d,{id:listId,title:String((body as any).task_list_title||'Google Tasks')})})}
if(action==='toggle'){const completed=!!(body as any).completed;const patch:any={status:completed?'completed':'needsAction'};if(completed)patch.completed=new Date().toISOString();else patch.completed=null;const d=await googleReq(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(taskId)}`,c.access_token,'PATCH',patch);return json({ok:true,task:normTask(d,{id:listId,title:String((body as any).task_list_title||'Google Tasks')})})}
if(action==='delete'){await googleReq(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(listId)}/tasks/${encodeURIComponent(taskId)}`,c.access_token,'DELETE');return json({ok:true})}
return json({error:'Unknown action'},400)}catch(e){const m=e instanceof Error?e.message:String(e);if(m==='TASKS_SCOPE_REQUIRED')return json({error:m,needs_reconnect:true},403);return json({error:m},400)}});
