import { createClient } from 'npm:@supabase/supabase-js@2';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false}});
const CALLBACK=`${SUPABASE_URL}/functions/v1/public-policy-drive/callback`;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET, OPTIONS'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'Content-Type':'application/json'}});
async function sha256(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function getConfig(){const {data,error}=await admin.from('public_policy_drive_config').select('google_client_id,google_client_secret').eq('id',1).single();if(error||!data?.google_client_id||!data?.google_client_secret)throw new Error('Google OAuth 설정이 없습니다.');return data}
async function getUser(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('로그인이 필요합니다.');const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw new Error('로그인 세션을 확인할 수 없습니다.');return data.user}
async function ensureAccess(userId:string){let {data:conn,error}=await admin.from('app_google_calendar_connections').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;if(!conn)throw new Error('Google 계정이 연결되지 않았습니다.');const exp=conn.token_expires_at?new Date(conn.token_expires_at).getTime():0;if(conn.access_token&&exp>Date.now()+60000)return conn;if(!conn.refresh_token)throw new Error('Google 재인증이 필요합니다.');const cfg=await getConfig();const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:cfg.google_client_id,client_secret:cfg.google_client_secret,refresh_token:conn.refresh_token,grant_type:'refresh_token'})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.error||'Google 토큰 갱신 실패');const expires=new Date(Date.now()+(d.expires_in||3600)*1000).toISOString();const {data:updated,error:uerr}=await admin.from('app_google_calendar_connections').update({access_token:d.access_token,token_expires_at:expires,updated_at:new Date().toISOString()}).eq('user_id',userId).select('*').single();if(uerr)throw uerr;return updated}
async function googleReq(url:string,token:string){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok){const msg=d.error?.message||d.error_description||'Google Tasks 요청 실패',detail=JSON.stringify(d.error||{});if(r.status===403&&(/insufficient|permission|scope/i.test(msg)||/ACCESS_TOKEN_SCOPE_INSUFFICIENT/i.test(detail)))throw new Error('TASKS_SCOPE_REQUIRED');if(r.status===403&&(/SERVICE_DISABLED|has not been used|API.*disabled/i.test(detail+' '+msg)))throw new Error('Google Tasks API가 Google Cloud 프로젝트에서 활성화되어 있지 않습니다.');throw new Error(msg)}return d}
function normTask(t:any,list:any){return {id:t.id,title:t.title||'(제목 없음)',notes:t.notes||'',due:t.due||null,status:t.status||'needsAction',completed:t.completed||null,updated:t.updated||null,taskListId:list.id,taskListTitle:list.title||'Google Tasks',position:t.position||null,webViewLink:t.webViewLink||null,source:'google-task'}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const url=new URL(req.url);try{const user=await getUser(req);const action=url.searchParams.get('action')||'tasks';
if(action==='start'){const cfg=await getConfig();const platform=url.searchParams.get('platform')==='android'?'android':'web';const raw=platform+'.'+crypto.randomUUID()+crypto.randomUUID(),hash=await sha256(raw);await admin.from('app_google_oauth_states').insert({state_hash:hash,user_id:user.id,expires_at:new Date(Date.now()+10*60*1000).toISOString()});const params=new URLSearchParams({client_id:cfg.google_client_id,redirect_uri:CALLBACK,response_type:'code',scope:'openid email https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.calendarlist.readonly https://www.googleapis.com/auth/tasks.readonly',access_type:'offline',prompt:'consent',state:raw,include_granted_scopes:'true'});return json({url:'https://accounts.google.com/o/oauth2/v2/auth?'+params.toString(),callback:CALLBACK})}
if(action==='status'){try{const c=await ensureAccess(user.id);await googleReq('https://tasks.googleapis.com/tasks/v1/users/@me/lists?maxResults=1',c.access_token);return json({connected:true,authorized:true,email:c.google_email||null})}catch(e){const m=e instanceof Error?e.message:String(e);if(m==='TASKS_SCOPE_REQUIRED')return json({connected:true,authorized:false,needs_reconnect:true});if(/연결되지/.test(m))return json({connected:false,authorized:false});throw e}}
if(action==='tasks'){const c=await ensureAccess(user.id);let lists:any;try{lists=await googleReq('https://tasks.googleapis.com/tasks/v1/users/@me/lists?maxResults=100',c.access_token)}catch(e){if(e instanceof Error&&e.message==='TASKS_SCOPE_REQUIRED')return json({tasks:[],needs_reconnect:true,warning:'Google 할 일을 보려면 Google 계정을 한 번 다시 연결해 주세요.'});throw e}const out:any[]=[];for(const list of lists.items||[]){let pageToken='';do{const q=new URLSearchParams({maxResults:'100',showCompleted:'false',showHidden:'false'});if(pageToken)q.set('pageToken',pageToken);const d=await googleReq(`https://tasks.googleapis.com/tasks/v1/lists/${encodeURIComponent(list.id)}/tasks?${q}`,c.access_token);for(const t of d.items||[])out.push(normTask(t,list));pageToken=d.nextPageToken||''}while(pageToken)}out.sort((a,b)=>{const ad=a.due?new Date(a.due).getTime():Number.MAX_SAFE_INTEGER,bd=b.due?new Date(b.due).getTime():Number.MAX_SAFE_INTEGER;return ad-bd||String(a.title).localeCompare(String(b.title),'ko')});return json({tasks:out,needs_reconnect:false})}
return json({error:'Unknown action'},400)}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}});
