-- TASK-구현 PR 2: 메모 원문 표(app_notes)와 꼬리표 표(app_record_links).
-- 설계: docs/web2-task-impl-plan.md 2.1·2.2·4.3. 적용 절차: docs/web2-task-impl2-db.md.
-- 빈 표 두 개만 만든다. 기존 표·정책·데이터는 바꾸지 않는다.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '60s';

-- 메모 원문. TASK-구현에서는 빈 표로만 둔다(메모 입력은 25).
create table public.app_notes (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.app_workspaces(id) on delete cascade,
  raw_text text not null check (length(raw_text) between 1 and 20000),
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 꼬리표: 출처(Google 할 일 1건 또는 메모 1건) → 대상(프로젝트 또는 조직 1개).
create table public.app_record_links (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.app_workspaces(id) on delete cascade,
  google_task_id text,
  google_tasklist_id text,
  note_id uuid references public.app_notes(id) on delete cascade,
  project_id uuid references public.app_spaces(id) on delete cascade,
  organization_id uuid references public.app_suborganizations(id) on delete cascade,
  -- 25(개인 업무 AI)용: AI 제안/사용자 확정, 사업·조직 보고 구분
  status text not null default 'confirmed' check (status in ('suggested','confirmed')),
  report_kind text check (report_kind in ('business','organization')),
  -- 목록 개수용 Google 완료 여부 사본. 할 일 행만 채운다. 화면 표시에는 쓰지 않는다.
  task_completed boolean,
  task_checked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint app_record_links_one_source check (num_nonnulls(google_task_id, note_id) = 1),
  constraint app_record_links_task_list check ((google_task_id is null) = (google_tasklist_id is null)),
  constraint app_record_links_task_state check ((google_task_id is null) = (task_completed is null)),
  constraint app_record_links_one_target check (num_nonnulls(project_id, organization_id) = 1),
  constraint app_record_links_unique unique nulls not distinct (google_task_id, note_id, project_id, organization_id)
);
create index app_record_links_project_idx on public.app_record_links(project_id) where project_id is not null;
create index app_record_links_org_idx on public.app_record_links(organization_id) where organization_id is not null;
create index app_record_links_task_idx on public.app_record_links(google_task_id) where google_task_id is not null;
-- 프로젝트 목록 개수: 미완료 할 일 연결만 센다.
create index app_record_links_open_project_idx on public.app_record_links(project_id)
  where google_task_id is not null and task_completed = false and project_id is not null;

-- 권한: 호스팅 기본 권한(anon·authenticated ALL)을 걷어 내고 authenticated에 네 가지만 준다.
-- 행 접근은 기존 sole-owner 경계(private.app_is_workspace_owner)로만 연다.
alter table public.app_notes enable row level security;
alter table public.app_record_links enable row level security;
revoke all on table public.app_notes, public.app_record_links from public, anon, authenticated;
grant select, insert, update, delete on table public.app_notes, public.app_record_links to authenticated;

create policy notes_owner_all on public.app_notes for all to authenticated
  using (private.app_is_workspace_owner(workspace_id))
  with check (private.app_is_workspace_owner(workspace_id));

create policy record_links_owner_all on public.app_record_links for all to authenticated
  using (private.app_is_workspace_owner(workspace_id))
  with check (
    private.app_is_workspace_owner(workspace_id)
    and (project_id is null or private.app_space_in_workspace(project_id, workspace_id))
    and (organization_id is null or exists (
      select 1 from public.app_suborganizations o
      where o.id = organization_id and o.workspace_id = app_record_links.workspace_id))
  );

-- The filename/version was generated by Supabase CLI migration new.
insert into supabase_migrations.schema_migrations (version, name, statements)
values ('20260927103344', 'task_impl2_notes_record_links', array['TASK-impl PR 2: app_notes and app_record_links']);
commit;
